### ISSUE TITLE
Submit pegged orders

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1062]
## Story

As a trader
I want to submit a pegged order
So that I can submit orders pegged to mid, best bid and best ask prices

## Acceptance Criteria

- [ ] I can submit an order pegged to the market mid point
- [ ] I can submit an order pegged to the best bid price
- [ ] I can submit an order pegged to the best ask price
- [ ] I can specify how from from the reference I want my order to be pegged
- [ ] Selecting Long should change the reference to Bid
- [ ] Selecting Short should change the reference to Ask
- [ ] The "pegged toggle" should be remembered i.e. if I left the ticket in the pegged state it should still be pegged when I come back, and vice versa. 
- [ ] Review 6001-SORD-008

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] Visual Design (consider alternatives to the text under the price input fields "Peg to a reference price" and "select a price"
- [x] Team review
- [ ] Dev
- [ ] Test

## Sketch

![Image](https://user-images.githubusercontent.com/13255539/234584141-cd86e167-8b6c-4d27-8387-9b76fe73b71c.png)

## Toasts

instead of the price show the reference and distance from it.

![Image](https://user-images.githubusercontent.com/13255539/235714244-ed439589-96ef-4303-ab83-fe81ca31f106.png)

## Additional information
[Specs on pegged orders](https://github.com/vegaprotocol/specs/blob/master/protocol/0037-OPEG-pegged_orders.md) this to make it possible to submit them in Console.

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1682332699851879?thread_ts=1682078028.827429&cid=C037STCKMGC

**Comment by MadalinaRaicu** [comment]
Can we add that cool feature where you select a row from the orderbook and it populates the limit price in their deal ticket?

**Comment by campbellssource** [comment]
In a recent discussion we discussed a reduced scope for this feature that might be good to do sooner...

Instead of being able to submit a pegged order with n price levels... we could have one that simply allows you to submit a single limit order pegged to a single reference. This is be good for people who wanted to ensure they were a price market (and not pay fees)

**Comment by campbellssource** [comment]
The ticket definition has been updated with designs.

Bonus task (break into another ticket when this is implemented if not being done at the same time): 

There is a network parameter that specifies the max number of pegged orders any key can have on a market.

If the user is getting close to this limit the deal ticket could warn:

![Image](https://user-images.githubusercontent.com/13255539/235713162-ec029066-7c98-46ac-828d-dc6d5a0cf3e1.png)

**Comment by campbellssource** [comment]
See also: https://github.com/vegaprotocol/frontend-monorepo/issues/3489

**Comment by joellecharlotte** [comment]
Please see [this link](https://www.figma.com/file/wBu1KViEZz1JkwpOmhFQrO/Console-V2?node-id=2322%3A13527&t=5QuipltCfduUs41B-1) and attached for the proposed solution most preferred by the team (Slack thread [here](https://vegaprotocol.slack.com/archives/C037STCKMGC/p1683213368075829))

![01 Limit Order with Option to Peg (Long)](https://user-images.githubusercontent.com/113684458/236508008-db7ebf69-d153-425a-842f-3fde9fc8395b.png)

**Comment by JonRay15** [comment]
dont support pegged orders and no intention to
