### ISSUE TITLE
[console-lite] clean up app repo, fixes and improvements

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/frontend-monorepo#1070]
## Task
Find redundant elements and remove or refactor, clean up the application repo

## ACs
- [ ] remove  old drawer component
- [x] make market list as home page
- [ ] increase code test coverage
