### ISSUE TITLE
[console-lite] change name of the app from simple-trading-app to console-lite

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/frontend-monorepo#1113]
## Task
Remove double-naming issue simple-trading-app -> console-lite

## ACs
- [ ] change main dir of the app in monorepo
- [ ] save consistency with nx commands 
- [ ] save consistency with netlify environment (probably create a new one)
- [ ] adjust git workflow
- [ ] adjust e2e app
