### ISSUE TITLE
Add nx variables as cache inputs

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#1120]
https://github.com/nrwl/nx/issues/6891#issuecomment-1110052748

For current builds we have to use `skip-nx-cache` for builds where environment variables change. This suggestion in a related thread that @asiaznik pointed me to looks like a better workaround (for build times).

# Tasks
- [ ] Try it on `explorer`
- [ ] Roll it out to all sites if it works
- [ ] Add a README not about it if appropriate
