### ISSUE TITLE
Show rewards and fees earned (no wallet connected) - no pagination

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1230]
Dependent on summary ticket on vega core that needs to be created @dexturr 

## Story 

As a user who has not connected their wallet
I want to see a total of rewards and fees paid out
So that I can understand the financial benefits of using Vega

## Acceptance criteria 

- [x] I can see rewards and infrastructure fees paid out per epoch, per asset, per type (staking rewards, infrastructure fees, price taking rewards, price making rewards, liquidity provision rewards, market creation rewards)
- [x] I can see a total per asset 
- [x] I can see a description of each type to help me understand where they've come from on mouseover
- [x] There is a link to docs to "[Understand how rewards are calculated ↗](https://docs.vega.xyz/docs/testnet/concepts/trading-on-vega/fees-rewards#trading-rewards)"
- [x] I can see whether there is a delay on reward payout i.e. "Earn rewards and fees for trading and maintaining the network. Rewards are paid out at the end of an epoch." becomes "Earn rewards and fees for trading and maintaining the network. Rewards will be paid out from the treasury [6h] after the epoch ends." when there is a delay to payout
- [x] Epoch list should be shown in descending order with the most recent at the top

## Background / additional details 

- Staking rewards = types.AccountTypeGlobalReward
- Infrastructure fees = types.AccountTypeFeesInfrastructure
- Price taking rewards = types.AccountTypeMakerPaidFeeReward
- Price making rewards = types.AccountTypeMakerReceivedFeeReward
- Liquidity provision rewards = types.AccountTypeLPFeeReward
- Market Creation Rewards = types.AccountTypeMarketProposerReward

Mouseovers per type
 
* ( i ) Staking rewards supplement infrastructure fees in the early stages of the network, rewarding validators and those who stake them for maintaining the network. 
* ( i ) Infrastructure fees are incurred across the network during trading.  They are distributed to validators according to their share of total stake on the network, and passed onto those who stake them, proportionate to their own stake after validator commission is taken.  
* ( i ) Price taking rewards are based on the proportion of the total maker fees you paid while trading, on markets where there is a funded reward
* ( i ) Price making rewards are based on the proportion of the total maker fees you received while trading, on markets where there is a funded reward
* ( i ) Liquidity provision rewards are distributed based on how much you have earned in liquidity fees, funded by a liquidity reward pool for that market.
* ( i ) Market creation rewards are paid out to the creator of any market that exceeds a set threshold of cumulative volume in a given epoch, currently [rewards.marketCreationQuantumMultiple].

## Tasks 

- [x] Work it out 
- [x] Build 

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/205896530-fc1049db-0134-4ec2-9b42-519d60825c62.png)

**Comment by candida-d** [comment]
@ckpringle I'm having a look at the copy and have some comments. 

Staking: 
* For how long will it be true that staking rewards are funded by the treasury AND infrastructure fees? Also, I would specify infrastructure fees here, not trading fees as it's based on the infrastructure portion which is paid for trades & transfers
* "Total stake" doesn't seem to come up anywhere else in this view, so if it doesn't come up anywhere, I'd cut it. 2 parenthetical statements is 1 too many

Trading:
* This implies that a user would be rewarded for all trades in which they paid that fee, rather than only on markets where the reward is funded. 

Liquidity provision:
* This tooltip is describing the liquidity fee itself, not the reward based on how much LPs earn in liquidity fees. These rewards are not funded by the market fees but by someone funding that reward pool. 

Market creation:
* This is rewarded when the market's cumulative volume is >= rewards.marketCreationQuantumMultiple * quantum. The parameter value alone isn't enough to determine it. 
* As far as I can glean, this is checked each epoch - where did "month" come from here? 

What happened to the 'maker fees received' reward?

**Comment by ckpringle** [comment]
Currently we cannot query reward types per epoch, only the last N rewards and therefore have no way to accurately present to the user rewards grouped per epoch. 

Implementing this solution with existing API would mean we take a risk on presenting an epoch with an incomplete data set - the totals could be wrong, and it's possible we miss out whole reward types as well as individual rewards - and we'd have no way of knowing it. A first step might be adding the ability to query the existing API by epoch. 

Raised a ticket for core here - https://github.com/vegaprotocol/vega/issues/6650

**Comment by dexturr** [comment]
Blocked by: https://github.com/vegaprotocol/vega/issues/7113

**Comment by joellecharlotte** [comment]
[Figma link ↳ ](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=1946%3A12689&t=jCpUYt1L3pqDNrM8-1)

[01.1](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=1946%3A12689&t=jCpUYt1L3pqDNrM8-1) and [01.2](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=1946%3A11185&t=jCpUYt1L3pqDNrM8-1) show how, until the new API is implemented to see % of total distributed, as a user you would only see your own rewards and therefore there is no segmented control to toggle between TOTAL DISTRIBUTED and EARNED BY ME. Instead, when wallet not connected you are prompted to connect your wallet (01.1) and then you'll see your rewards (01.2) but without the % of the total in the table as well.

[02.1](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=1927%3A10257&t=jCpUYt1L3pqDNrM8-1) shows the TOTAL DISTRIBUTED state with the segmented control once the new API has been implemented.

[02.2](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=1946%3A11861&t=jCpUYt1L3pqDNrM8-1) shows EARNED BY ME with a prompt to connect wallet.

It might make sense to jump on a quick call to run through it all and clarify any questions or feedback you may have, LMK!

**Comment by dexturr** [comment]
Now blocked by: @vegaprotocol/vega#7422

**Comment by pennyandrews** [comment]
Decision to pull in everything for now and paginate later when it's available (it crashing on mainnet might push to get the pagination work done by core)
