### ISSUE TITLE
Auto Deploy Releases to IPFS

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#126]
We picked this project because it *should* be quick to get the pipeline all set up, then see how we feel about it for other internal projects.

# Tasks
- [x] Pick an IPFS pinning service
- [x] Set up the account credentials
- [x] Add Github action to pin build to IPFS
- [x] Point a new subdomain to the IPNS / CID

**Comment by edd** [comment]
Waiting for https://github.com/vegaprotocol/frontend-monorepo/pull/229 (which is very close)

**Comment by edd** [comment]
I'm closing this and creating more specific tickets for each individual project so it's more easily traceable
