### ISSUE TITLE
Identify and prioritise opportunities to improve the UX and visual design of existing features / data

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1333]
## Story

As Vega
I want to identify opportunities to improve the UX and visual design of existing features / data in Block Explorer
So that I can prioritise effectively

## Tasks

- [x] Review the current UX and sketch improvements (utilising any work that has already been done)
- [x] Review the current visual design and mock up improvements (utilising what has already been done for brand and console)
- [x] Write user stories for the backlog
- [x] Review, refine and prioritise in the backlog ready for sprint planning
