### ISSUE TITLE
Identify and prioritise opportunities add new features / data

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1337]
## Story 

As Vega
I want to identify what additional data would be valuable for users to add to Block Explorer
So that I can prioritise 

## Tasks

- [ ] See what other chains do - lightweight competitive analysis
- [ ] Gather what we already know - from previous backlogs, designs, team members, existing user research findings etc.  
- [ ] Understand what data we have available to use - work with Phil to get a clear view of the data available through APIs?
- [ ] Workshop to refine a wishlist and priorities
- [ ] Write user stories for the backlog
- [ ] Sense check priorities with ELT, Barney and Ramsey

## Primary purpose of block explorer

"If a user is confused - something has happened that I don't understand - Block Explorer is the place to go to try and understand it by telling the story of what is happening on chain"
