### ISSUE TITLE
Replace json in Genesis Parameter view

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1339]
## Story

As a user
I want to see Genesis Parameter details presented via standard UI elements
So that I don't have to be able to read json to be able to get the information I need

## Acceptance criteria 

- [ ] ...

## Tasks 

- [ ] We've reviewed what is in genesis parameters 
- [ ] We've compared against network parameters and understood how they relate to one another 
- [ ] We've identified if there are some parameters more important than others 
- [ ] Sketch out what this means to the section of the explorer

![image](https://user-images.githubusercontent.com/47143694/190442032-a53edb65-9098-41f2-9992-43909d98442f.png)
