### ISSUE TITLE
Fairground explorer is configured to point to a node that is unhappy

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#1344]
In a private window / separate browser, visit: https://explorer.fairground.wtf/

<img width="1049" alt="Screenshot 2022-09-15 at 16 49 39" src="https://user-images.githubusercontent.com/6678/190449654-9d9a9be4-315d-4b6f-8ce3-3e58697441a2.png">

The explorer will fail to connect to the node it is configured to point to, and open up the 'Connect to a node' dialog

# Tasks
- [x] Update netlify configuration to actually select `fairground` as the env for this deploy
- [x] De-deduplicate variables set in Netlify that can be set by the env file
- [ ] ~Update the configuration for fairground explorer to point to a node that is *currently* available~
- [x] Ensure that stagnet3 nodes do not appear as an optional alternative node for a Fairground explorer

**Comment by edd** [comment]
This is the current netlify configuration:
<img width="683" alt="Screenshot 2022-09-15 at 16 53 07" src="https://user-images.githubusercontent.com/6678/190450425-7b8ff279-7e85-4b50-bf03-e497ec9552a0.png">

Here is the configuration file for the environment:

https://github.com/vegaprotocol/frontend-monorepo/blob/7fb3a23a5afdbaaf641e4b5174b025e42bca9970/apps/explorer/.env.stagnet3#L1-L9
