### ISSUE TITLE
Market list

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1352]
**User Story** 
As a liquidity provider 
I want to see a list of markets with their current liquidity status 
So that I can decide if providing liquidity is right for me on vega - and see how great the returns could be 

**Acceptance Criteria**
- I can view a tabular list of market data
- I can see the market name for each market
- I can see the settlement asset for each market
- I can see the volume (24h) for each market 
- I can see the Total liquidity committed for each market
- I can see the status of each market

Sketch for reference: https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764531971937952&cot=14
![image](https://user-images.githubusercontent.com/47143694/190519250-339e579f-9e08-4ef9-b762-2a60f7c97906.png)

Visual styles can be used from this early version of a design: https://www.figma.com/file/3FxbEyG4Npw0s3YSqGpPNT/Liquidity-Provider-Dashboard?node-id=0%3A1

**Tasks**

- [x] Create new repository in github
- [x] Swat up on Vega api integration in docs
- [x] Create page skeleton
- [x] Set up new app in frontend-monorepo
- [x] Create simple page 
- [x] Find a way we can preview app (without having to merge to avoid dependencies)
- [x] Integrate market name data
- [x] Integrate settlement asset data
- [x] Integrate Volume data
- [x] Integrate additional data and calculate volume % change
- [x] Integrate committed liquidity data
- [x] Integrate status data

**Comment by pennyandrews** [comment]
Link to preview site (showing whatever is on the develop branch) https://liquidity-provision-dashboard.netlify.app/

**Comment by pennyandrews** [comment]
@malinantonsson https://explorer.near.org/nodes/validators

**Comment by pennyandrews** [comment]
@joellecharlotte please can you update the link to the figma file for Malin. Ta

**Comment by malinantonsson** [comment]
New preview link: https://deploy-preview-1529--liquidity-provision-dashboard.netlify.app/
