### ISSUE TITLE
Estimated return / APY

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1353]
## Story ##

As a liquidity provider
I want to understand the potential returns I could get from providing liquidity on each market
So that I can decide which market(s) might be right for me to provide liquidity for

## Acceptance Criteria ##

- [ ] I can see the estimated return per market
- [ ] There is suitable disclaimer / explainer / words to make it clear this is just an indicator "I really do not want any chance of someone committing liquidity because they see a number here and think they can get that return"

## Sketch ##

![image](https://user-images.githubusercontent.com/47143694/190520924-85c8155c-6e93-48bc-8336-7ce9358f17b8.png)

## Tasks ##

- [X] Get maths from David
- [x] Request answers on Slack to where the data is
- [x] Get the data
- [ ] Establish whether we are able to do calc in the frontend or not
- [ ] Kick the ticket back into the backlog
OR
- [ ] Do the work

## Maths ## 

Annual return estimate = 52 x (total LP fees + maker fees collected by LPs in a week (7 epochs))  / (sum of the maximum margin for each LP over a week + sum of maximum commitment (stake) for each LP over a week)
## Data ##

From Tan

I think the following graphql query should give you enough to get started:
I'm assuming that for each market, you need the orders, maker fees and LP fees. You'll want to tweak the filters accordingly.
Let me know if I'm missing anything and I'll see if I can dig out the appropriate query for you.

```
query {
	marketsConnection {
    edges {
      node {
        fees {
          factors {
            makerFee
            infrastructureFee
            liquidityFee
          }
        }
        liquidityProvisionsConnection {
          edges {
            node {
              fee
            }
          }
        }
        ordersConnection{
          edges {
            node {
              party {
                id
              }
              side
              size
              price
            }
          }
        }
      }
    }
  }
}
```
