### ISSUE TITLE
Other tooltips

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1358]
## Story 

As a liquidity provider 
I want to understand what we mean by each of the key types of data displayed 
So that regardless of the words we use at Vega, it's understood what we mean!

## Tasks 

- [ ] Work out a description for each header / type of information, reusing what we can from console tooltip implementation on liquidity view
- [ ] Display tooltip for each type header of information (I'd see if we can use the front end component you can see here as you mouseover data in the table on the right https://explorer.vega.xyz/, screenshot attached)

## Tooltips 

Data columns

DETAIL PAGE 
- [ ] LPs - Liquidity providers
- [ ] Duration - Time in market 
- [ ] Equity-like share - The share of the markets liquidity held - the earlier you commit liquidity the greater % fees you earn
- [ ] Committed bond -  The amount of funds allocated to provide liquidity
- [ ] 24h fees - Total fees earned by the liquidity provider in the last 24 hours
- [ ] Fee level - The market's liquidity fee, or the percentage of a trade's value which is collected from the price taker for every trade

MARKET LIST
- [ ] Market (futures) - The market name and settlement asset
- [ ] Volume (24h) - The trade volume over the last 24 hours
- [ ] Committed bond - The amount of funds allocated to provide liquidity
- [ ] Status - The current market status - those below the target stake mark are most in need of liquidity

DATA ITEMS 
- [ ] Continuous: This is the standard trading mode where trades are executed whenever orders are received
- [ ] Monitoring auction-liquidity: This market is in auction until it reaches sufficient liquidity
- [ ] Opening auction: This is a new market in an opening auction to determine a fair mid-price before starting continuous trading.

![image](https://user-images.githubusercontent.com/47143694/190523428-cf9fd623-295f-4a56-84ad-a30de9766675.png)

Dashboard sketch for reference https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764531971937952&cot=14

Could do each of these as md files that are easily editable by Vega people and maybe a way to easily show or hide the (i) based on whether there is any content for it or not?

Visual styles (only) can be used from this early version of a design https://www.figma.com/file/qgCd4r61Z1r3tUkxKehhmu/Website-Design-Updates?node-id=399%3A20530

**Comment by ciaran-** [comment]
There's a preview available at [this link](https://deploy-preview-2064--liquidity-provision-dashboard.netlify.app/markets/acff1b95980c3355e65c7162c35917388702525c0475ba753f03d0efc9c6d6a3) that's got some of these changes. I've added tooltips for the 4 columns mentioned - and the same 'i' icon we're using elsewhere.

@ckpringle I wonder if we're desperate to keep the icon? I ask because the column titles are already wide enough to be clipping at the default size on my screens, and the icon is obviously an additional thing to try and fit in. Worth saying the Tooltip component that I re-used is designed to make the _whole header for a column_ tooltip-on-hover, so that's what we've got here. The icon is just an additional nudge that it's possible.

Happy to chat - especially if anything I've said above doesn't make much sense.
