### ISSUE TITLE
Ledger entries MVP

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1387]
## Story

As a trader
I want to see any transactions that affect my accounts
So that I can understand how my accounts are being affected by open positions

## Acceptance Criteria

- [x] I can see the latest 500 ledger entries (temporary solution until dateRange input is working)
- [x] I can see the account type affected
- [x] I can see the transfer type
- [x] I can see the quantity of asset moved
- [x] I can see the market (if margin account)
- [x] I can see the formatted vega time the transfer occured

## Tasks

- [x] Add a new 'Ledger entries' tab
- [x] Add a table with columns accommodating the above ACs. Suggest: [accountType, transferType, quantity (symbol), marketId, time]
- [x] Add maps for more readable account and transfer types

## Additional details / background info

I put together a rough POC at spike/system-transactions:
![Screen Shot 2022-10-25 at 22 31 20](https://user-images.githubusercontent.com/6803987/197942882-f226e144-0bed-42ec-9f91-795c8eb84507.jpg)

The following query should get everything required for the above ACs

```
fragment LedgerEntry on AggregatedLedgerEntries {
  vegaTime
  quantity
  partyId
  assetId
  marketId
  accountType
  transferType
}

query LedgerEntries($partyId: ID!) {
  ledgerEntries(
    filter: { AccountFromFilter: { partyIds: [$partyId] } }
    groupOptions: {
      ByAccountField: [PartyId, AccountType, AssetId, MarketId]
      ByLedgerEntryField: [TransferType]
    }
    pagination: { first: 500 }
  ) {
    edges {
      node {
        ...LedgerEntry
      }
    }
  }
}
```

**Comment by pennyandrews** [comment]
Hey @gordsport I wanted to get this onto your radar as I don't believe there is an api for us to use for this, yet it was identified as critical for the FE for trading launch. Is there already a plan to do this in core?

**Comment by gordsport** [comment]
Hey Penny,
- https://github.com/vegaprotocol/vega/issues/5925
- https://github.com/vegaprotocol/vega/issues/5679

The second should provide what you need for this. @AnExsomnis is currently working on this issue in this current sprint.

**Comment by pennyandrews** [comment]
Update from Gordon in scrum or scrums - Anna is working on https://github.com/vegaprotocol/vega/issues/5679, in review so should be ready soon

**Comment by pennyandrews** [comment]
This now looks like both issues are resolved and so this should be unblocked

**Comment by pennyandrews** [comment]
This is now blocked to some extent by this core bug that @macqbat found https://github.com/vegaprotocol/vega/issues/6519 and ideally the above mentioned tickets by Gordon would be released to core before picking this up, currently only available on stagnet

**Comment by pennyandrews** [comment]
@asiaznik @mattrussell36 I have this update from Gordon:

[6519](https://github.com/vegaprotocol/vega/issues/6519) - will be in 0.59 (now in stagnet 3 for FE early access)
[5925](https://github.com/vegaprotocol/vega/issues/5925) - released in 0.56 (ledger APIs completed in 0.58 so should be in stagnet1 and testnet now)
[5679](https://github.com/vegaprotocol/vega/issues/5679) - released in 0.58 so should be in stagnet1 and testnet now

Not sure if this now unblocks this ticket?

**Comment by mattrussell36** [comment]
I've been testing this out and and everything appears to be working bar the dateRange input.

As a MVP/first pass lets just fetch the first 500.
