### ISSUE TITLE
See all the transactions a party has performed as a list

### ISSUE THREAD

**Issue by elmar-vega** [vegaprotocol/frontend-monorepo#1408]
## Story

As a user 
I want to see all the latest transactions a party has performed as a list
So that I can understand what is happening on chain and/or find a specific transaction I'm interested in

## Acceptance Criteria (proposed)

- [x] I can see the transactions listed most recent first (using block number)
- [x] I can see the transaction id
- [x] I can see the type of transaction
- [x] I can see the block id the transaction was a part of
- [x] I can click on the transaction to see the transaction details

## Tasks 

- [ ] Build
- [ ] Review
- [ ] Test

## Notes

Assuming to reuse the same table style already defined

**Comment by ckpringle** [comment]
Something like this?

![Image](https://user-images.githubusercontent.com/46783148/194286274-23380a0c-9627-4c19-bec3-0c147b19e396.png)
