### ISSUE TITLE
Console design tweaks

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#1409]
### Tasks

- [ ] Manually test and review Console from a UX perspective
- [ ] Find things that annoy me
- [ ] Fix them (in code) if I can
- [ ] Submit issues if I can't
