### ISSUE TITLE
Landing page 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1413]
## Story

As a user
I want a way to see at a glance the type of transactions and status of the Vega network 
So that I can quickly and easily find what I'm looking for 

## Acceptance Criteria

- [ ] I can see jump off points to transactions, blocks, parties and governance proposals straight away 
- [ ] I can see the key "data" of each to help me recognise the types of information contained behind each category
- [ ] There is a way to click through to the corresponding list for each i.e. a link to the list of all transactions, a link to the list of all blocks, a link to the list of all parties, a link to a list of all governance proposals
- [ ] I can see the network status, Tendermint version, up since, uptime and chain ID 
- [ ] I can see jump off points for network data - assets, genesis parameters, oracles, network parameters 
- [ ] I can see the explorer version I am running

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by JonRay15** [comment]
I dont know what this is ... we have a landing page ... is this done?

**Comment by joellecharlotte** [comment]
@JonRay15 It's possible things have changed since I worked on this but [here is an iteration from November last year](https://www.figma.com/file/CRNfp3wtC29lIr3ctcWVe9/Block-Explorer-v2?type=design&node-id=1342%3A1675&mode=design&t=2RK0124YdBoTwcDI-1) of the proposed landing page. I think it's an evolution of https://explorer.fairground.wtf, bit out the loop of the latest decisions on this...
