### ISSUE TITLE
Explorer navigation - find transaction and network data from anywhere

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1414]
## Story

As a user 
I want to quickly access a list of the transaction or network data that I am looking for from anywhere on the block explorer
So that I don't need to "go back" to the landing page every time

## Acceptance Criteria

- [ ] I can easily navigate to each list page regardless of where I am in the block explorer i.e. 

      Transactions
      Blocks
      Parties
      Governance proposals
      Validators
      Assets
      Genesis parameters
      Oracles
      Network parameters
- [ ] I can easily access search 
- [ ] I can easily get to the home page (click the logo)

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info
E.g. Explore drop down on https://explorer.near.org/

**Comment by joellecharlotte** [comment]
Attached the proposed design for the Nav + Search.

There's a simplified Nav on Mobile where everything is moved into one fullscreen modal. Search is as per the [Christies ↳](https://www.christies.com/) example where it's collapsed into an icon that exposes the field on tap. 

<img width="1800" alt="01 2 XL 1280 Dropdowns@2x" src="https://user-images.githubusercontent.com/113684458/192275772-c73162da-426c-4cd0-a2f8-365536677bd5.png">
<img width="375" alt="03 1 XSM 375 Dropdowns@2x" src="https://user-images.githubusercontent.com/113684458/192275777-15b9a7e5-6bd8-41a0-a06b-1ae52ba3f8ff.png">
<img width="375" alt="03 2 XSM 375 Search@2x" src="https://user-images.githubusercontent.com/113684458/192275779-15126838-bbf8-4cfa-86f9-7563f28647d3.png">

**Comment by ckpringle** [comment]
Feedback is that this navigation lost a couple of things @joellecharlotte  - visibility on large screens of everything that's "in there" and on mobile view, what the fields are e.g. could add "by" to label which item is the submitted by field and / or we add labels on mobile.
