### ISSUE TITLE
Transaction detail view(s)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1416]
## Story

As a user
I want to see the details of a transaction
So that I can prove the transaction occurred and show / share / evidence it

## Acceptance Criteria (needs refining)

- [x] I can see a summary of key transaction information presented in a consistent way 
- [x] I can see as a list in UI components the details of the encoded transaction 
- [x]  I can access party details of the submitter ie. click on party address to go to party detail page

## Tasks

- [x] Sense check what would be the information in the top "summary" of the - hash (transaction ID), from, block and type (order submission), timestamp e.g. https://explorer.near.org/accounts/35ef5fc055496bfcdc8d278a961c40117812fff5cdc9c8e60e1c6b47483d89e9
- [x] Find out what data is currently available for transactions and what would be valuable to show as summary and / or in list
- [x] Develop / build out a a list pattern including nesting / collapsing elements within the transaction 
- [ ] Team / stakeholder review
- [x] Refine design
- [x] Develop
- [ ] Review
- [x] Test

## Sketch 

![Image](https://user-images.githubusercontent.com/46783148/196717929-caec5bb8-dcb8-4210-a07e-4b071d668fc6.png)

Miro link for reference https://miro.com/app/board/uXjVPVRiSOM=/?moveToWidget=3458764535930678393&cot=14

## Additional details / background info

Example of collapsable list https://explorer.near.org/transactions/4wxEDcZFJQSpEEd1jPLPixcRA6pDFjuq7ZDSDcywSSE6

  - OrderSubmission: 'Order Submission',
  - OrderCancellation: 'Order Cancellation',
  - OrderAmendment: 'Order Amendment',
  - VoteSubmission: 'Vote Submission',
  - WithdrawSubmission: 'Withdraw Submission',
  - LiquidityProvisionSubmission: 'Liquidity Provision',
  - LiquidityProvisionCancellation: 'Liquidity Cancellation',
  - LiquidityProvisionAmendment: 'Liquidity Amendment',
  - ProposalSubmission: 'Governance Proposal',
  - AnnounceNode: 'Node Announcement',
  - NodeVote: 'Node Vote',
  - NodeSignature: 'Node Signature',
  - ChainEvent: 'Chain Event',
  - OracleDataSubmission: 'Oracle Data',
  - DelegateSubmission: 'Delegation',
  - UndelegateSubmission: 'Undelegation',
  - KeyRotateSubmission: 'Key Rotation',
  - StateVariableProposal: 'State Variable Proposal',
  - Transfer: 'Transfer',
  - CancelTransfer: 'Cancel Transfer',
  - ValidatorHeartbeat: 'Validator Heartbeat',

- Decision to stick with existing data for this - not adding anything new
- Raw transaction JSON can be found here: https://n13.testnet.vega.xyz/rest/transactions. Good for seeing different transaction types and getting examples
- Sketch of nested data in Miro that would be collapsable/expandable
- Elmar is going to create something and then we can refine the styles in the browser

**Comment by ckpringle** [comment]
Current transaction details

![Image](https://user-images.githubusercontent.com/46783148/192575266-8112acc2-3edc-4209-b8db-3736bcd876b6.png)

**Comment by pennyandrews** [comment]
Elmar and Neil discussed Neil's suggestion in a Miro sketch and think the conclusion was that Elmar can just go ahead and build it. Need to confirm this is the case

**Comment by neildawson** [comment]
[Slack thread where we discussed core functionality vs. extra stuff we can layer on later](https://vegaprotocol.slack.com/archives/C033K0B1N2J/p1666883811624639?thread_ts=1666859175.086649&cid=C033K0B1N2J)

**Comment by joellecharlotte** [comment]
[Here is the link to the XL and XSM designs in Figma](https://www.figma.com/file/CRNfp3wtC29lIr3ctcWVe9/Block-Explorer?node-id=1654%3A5619).
