### ISSUE TITLE
Update contract addresses for Sepolia

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#1417]
Ropsten will soon be retired. Environments that currently use Ropsten will switch over to Sepolia. While *most* apps use Network Parameters/Asset details to get the contract addresses they need, Token requires the addresses of some extra contracts.

https://github.com/vegaprotocol/frontend-monorepo/blob/832327c918a0cdec445124d49c5ce1234c1c258d/apps/token/src/config/env.ts#L20-L43

# Tasks
- [ ] Find out the new testnet (et al) contract addresses from @vegaprotocol/ops or @vegaprotocol/smartcontracts 
- [ ] Update the contract addresses
- [ ] Switch all other ropsten references to sepolia

**Comment by gordsport** [comment]
Hey @sam-keen 

Im pretty sure the info you need is in:
**Devent1**
https://github.com/vegaprotocol/networks-internal/blob/main/devnet1/templates/smart_contracts.json

**stagnet3 (the FE dev network core update every 24hrs, FE updated on each PR)**
https://github.com/vegaprotocol/networks-internal/blob/main/stagnet3/vegacapsule/smartcontracts_addresses.json

**Stagnet 1 (the new staging network release candidates will sit before moving to testnet)**
https://github.com/vegaprotocol/networks-internal/blob/main/stagnet1/templates/smart_contracts.json

**Testnet/Fairground**
https://github.com/vegaprotocol/networks-internal/blob/main/fairground/templates/smart_contracts.json

**Comment by dexturr** [comment]
@gordsport This is not what we are looking for unfortunately. @fkondej when we spoke a couple weeks ago about deploying the claim codes contract, where could I find the deploye addresses for that?
