### ISSUE TITLE
Switch all apps that interact with tokens to sepolia

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#1418]
As per #1417, except the work is easier for  every other app, because contract addresses should come from assets/ network parameters. Hopefully.

# Tasks
- [ ] Get contract addresses (see #1417)
- [ ] Switch network ids from Ropsten to sepolia
- [ ] Find any text references and do the same
