### ISSUE TITLE
Improve view of transactions on block details

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1438]
## Chore

Update the look and feel of the block details view to use new styles 

## Acceptance Criteria

- [ ] There is a page per block 
- [ ] I can see block ID, who it was mined by and when (existing functionality)
- [ ] I can see the number of transactions made
- [ ] I can see transactions summary info - type, transaction ID, status, block

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch - not a visual design!!!

![Image](https://user-images.githubusercontent.com/46783148/194286860-4f9577a7-7eab-458c-88e9-68f2c1a883ee.png)
