### ISSUE TITLE
Governance proposals list

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1448]
## Story

As a user
I want to see a list of governance proposals (before seeing the detail behind each)
So that I can quickly find what I am looking for

## Acceptance Criteria

- [ ] There is a brief explanation of what governance proposals are
- [ ] There is a link to the governance docs on making a proposal (to understand more and learn how to contribute)
- [ ] I can see a list of governance proposals 
- [ ] I can click through to see proposal details 

## Tasks

- [ ] We've reviewed what information needs to be shown in a list of governance proposals (could base off of what's on token already)
- [ ] Page sketch / design (if needed?)
- [ ] Create the view with new layout and styles
- [ ] Integrate the data
- [ ] Test?
