### ISSUE TITLE
Governance proposal details view

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1449]
## Story

As a user 
I want to see governance proposal details for an individual proposal in a UI 
So that I don't need to be a developer to recognise what I'm looking for

## Acceptance Criteria

- [ ] I can see the proposal details as UI elements (not raw JSON)
- [ ] I can click on a link to take me to the proposal on TFE where I can vote
- [ ] I can share a link to the individual proposal details i.e. [https://explorer.fairground.wtf/proposals/[ID]]

## Tasks

- [ ] We've reviewed the types of data a governance proposal has, identifying what are the summary content types at the top, and what should be listed below (including comparing to what token front end has)
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by pennyandrews** [comment]
Have a sketch ready for this to discuss with Elmar, once happy with it it can go to Joëlle to be designed
