### ISSUE TITLE
Staging environment for pre-testnet release candidates

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#1460]
## Task

Configure and set up apps for stagnet1 (testnet release candidate)

### Common Tasks
- [x] Create a release branch `release/stagnet1`

#### Token and Multisig Signer
- [x] Create .env files
- [x] Create netlify app building from release branch
- [x] Configured required Netlify env vars
- [x] Configure domain for token.stagnet1.vega.xyz

#### Block Explorer and Stats
- [x] Create .env files
- [x] Create netlify app building from release branch
- [x] Configured required Netlify env vars
- [x] Configure domain for explorer.stagnet1.vega.xyz

#### Console and Console-Lite
- [x] Create .env files
- [x] Create netlify app building from release branch
- [x] Configured required Netlify env vars
- [x] Configure domain for console.stagnet1.vega.xyz

#### Liquidity Provision Dashboard
- [x] Create .env files
- [x] Create netlify app building from release branch
- [x] Configured required Netlify env vars

Note: LP dashboard doesn't have a custom domain yet

### Additional info
Staging 3 has now been repurposed to be a 'stable development' environemnt.

The network is deployed every 24hrs and the FE apps are deployed to on every PR merge. This is a very useful environment to accelerating development and having an early feedback loop for feature testing and bug fixes. However, with these benefits we have now lost the staging environments where we can deploy a tagged release candidate (network AND FEs) in a long live environment whereby we can run any testing and incentive building/proving before moving a stable release to testnet for the community.

This issue is to implement a set of front ends configured to the network implemented in https://github.com/vegaprotocol/devops-infra/issues/1530 for this stagnet-pre-release purpose.

This process will then also give us our core / FEs tag compatibility info

**Comment by gordsport** [comment]
We now have this environment live: https://stats.vega.trading/#stag3

Smart contract info can be seen:

- https://github.com/vegaprotocol/frontend-monorepo/issues/1417

Other information you requiore *might* be able to be found here:
- https://github.com/vegaprotocol/networks-internal/tree/main/stagnet1

Please check this and if and endpoints/info you need about this network are not there for the FEs, let me know and I'll add it to this ticket.

**Comment by dexturr** [comment]
This is now done for token :+1:

**Comment by malinantonsson** [comment]
This is done for Liquidity provision dashboard: https://stagnet1-lp-dashboard.netlify.app/

**Comment by elmar-vega** [comment]
@gordsport  Done for Explorer
