### ISSUE TITLE
Update accounts and positions data providers to handle newly created entries

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1491]
Right now when a new position or account is created it doesn't get added to the data providers store via the subscription. It used to, but due to recent changes to the API, which flatten the return types of some subscriptions, we can no longer simply insert it as some fields are now missing and must be retrieved from a different data source

## Tasks

- [x] Update the positions data provider to handle newly created positions
- [x] Update the accounts data provider  to handle newly created accounts
- [x] Test it by creating a new position on a market.

## Additional details / background info
- libs/positions/src/lib/positions-data-providers.ts and libs/accounts/src/lib/accounts-data-provider.ts have a todo comment in the update function for the data provider
- You may want to look at the orders data provider which uses a derived data provider, as a similar issue was already fixed there.
