### ISSUE TITLE
workflows minor improvements, fixes and cleanup

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#1495]
## The Chore

There are few additional improvements to be made in new workflows, to make them easy to maintain in the future.

## Tasks

- [ ] Change the way env variables are assigned during the flow.
- [ ] Add shared actions where possible.
- [ ] If no projects affected, skip downloading and building binaries.
- [ ] Tests are also run after push & merge to develop/main (including PR merge) because of nx affected error. Let's fix that.
