### ISSUE TITLE
Improve party details view

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1501]
## The Chore

Now we have removed the json and are able to present party details as ui elements we want to improve the layout and look and feel  of this view 

## Acceptance Criteria

- [ ]  It should display the party id and key on top and make it easy to copy the id
- [ ]  It should display a list of assets the party owns with the balance as a list.
- [ ]  It should make it easy to copy the asset id
- [ ]  It should work in dark/light mode
- [ ]  It should be accessible and easy to navigate using a keyboard

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

## Additional details / background info

_Consider tackling this ticket if/when adding more data to the party details view as more valuable / time efficient_ [LINK TO TICKET]

<img width="1800" alt="04 XL 1280 Party Details@2x" src="https://user-images.githubusercontent.com/47143694/192501700-7e15923b-8681-463a-a472-d4287280e6ea.png">

Link to designs in Figma: https://www.figma.com/file/CRNfp3wtC29lIr3ctcWVe9/Console-V2-%26-Block-Explorer?node-id=1303%3A3253

**Comment by pennyandrews** [comment]
Discussed this and agreed to move the transaction details to the bottom as it will have infinite scroll, don't believe Elmar needs anything more from design on this
