### ISSUE TITLE
Improve transactions list view

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1502]
## The Chore

Now we re enabled the transactions list we want to improve the layout and look and feel of this view

Latest build https://deploy-preview-1625--vega-explorer-testnet.netlify.app/txs

## Acceptance Criteria

- [x] I can see transaction type (e.g. order submitted) , ID (e.g. Cnol2...), submitter (e.g. by 7B4EA...), Block (e.g. 92698) and transaction index (e.g. 30)
- [x]  It should work in dark/light mode
- [x]  It should be accessible and easy to navigate using a keyboard
- [x] More data loads as I scroll down the page (like current behaviour on blocks view)

## Tasks

- [ ] Explore initial design direction 
- [ ] Review with team 
- [ ] Detailed design 
- [ ] Implementation 
- [ ] Testing
- [ ] Etc.

## Additional details / background info

Link to designs in Figma file https://www.figma.com/file/CRNfp3wtC29lIr3ctcWVe9/Console-V2-%26-Block-Explorer?node-id=1303%3A3253

![Image](https://user-images.githubusercontent.com/46783148/192574088-b2e6d89d-c671-44d8-a827-6d381528ac44.png)

![image](https://user-images.githubusercontent.com/47143694/192506773-665c7d7a-a2ac-466d-a95f-5083c357aa8e.png)

![image](https://user-images.githubusercontent.com/47143694/192506808-b4dd0e12-3a5d-4917-9056-79d6ff486097.png)

**Comment by pennyandrews** [comment]
Need to take another run at the mobile view of the table view as you have no labels to tell you which data item it is

**Comment by joellecharlotte** [comment]
Figma file is [here](https://www.figma.com/file/CRNfp3wtC29lIr3ctcWVe9/Block-Explorer?node-id=1178%3A41).

Designs attached including a solution for mobile labels + the new colour system has been applied.

<img width="375" alt="02 1 XSM 375 Transaction List@2x" src="https://user-images.githubusercontent.com/113684458/193884328-65d0afd9-7726-425d-8012-f951ec5ef071.png">

<img width="1800" alt="01 1 XL 1280 Transaction List@2x" src="https://user-images.githubusercontent.com/113684458/193884317-612b6ebd-952d-47b6-85ee-342a0a78edf6.png">
