### ISSUE TITLE
Console Experience Review

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1507]
## The Chore

Review the latest version of Console across all epic/features to identify and prioritise any gaps that need filling and opportunities to improve the UX and visual design of existing features / data

## Tasks

- [x] Review the latest app, mapping out the current experience against the epics/features identified (@PeteWilliams )
- [x] Write / refine stories for the backlog
- [x] Workshop to review, refine and prioritise with the Console Team
- [ ] Sense check priorities with ELT, Barney and Ramsey
