### ISSUE TITLE
Set up approbation to run locally

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1534]
## The Chore

Get the script running locally so we can use it when checking AC coverage. Before attempting to include it in overnight runs
note: changes up coming in to [list categories for User-interface ACs](https://github.com/vegaprotocol/approbation/issues/48)

## Tasks

- [x] Get [approbation](https://github.com/vegaprotocol/approbation)
- [x] have the latest Specs and FEmono repo branch (or the branches you want to test)
- [x] use `./bin/approbation.js check-codes --specs="../specs/user-interface/**/*.md" --tests="../frontend-monorepo/apps/*-e2e/**/*.cy.js" --category-stats --show-branches --verbose --show-files ` to check there are no bugs (e.g. duplicate codes) in the ACs
- [x] use `./bin/approbation.js check-references --specs="../specs/user-interface/**/*.md" --tests="../frontend-monorepo/apps/*-e2e/**/*.cy.js" --category-stats --show-branches --verbose --show-files` to get the coverage output

**Comment by edd** [comment]
# Me recreating the problem
## 1. Make a new clean folder
```bash
~/src/vega took 6s 
❯ mkdir temp

~/src/vega 
❯ cd temp
```

## 2. Clone approbation to `src/vega/temp`
```
❯ gh repo clone vegaprotocol/approbation
Cloning into 'approbation'..
...
Resolving deltas: 100% (283/283), done.
```
## 3. Clone frontend-monorepo `src/vega/temp`
```
❯ gh repo clone vegaprotocol/frontend-monorepo
Cloning into 'frontend-monorepo'...
...
Resolving deltas: 100% (26452/26452), done.
```

## 4. Clone specs into`src/vega/temp`
```
❯ gh repo clone vegaprotocol/specs
Cloning into 'specs'...
...
Resolving deltas: 100% (8457/8457), done.
```

## 5. Install approbation deps
```
❯ cd approbation/
❯ npm install
```

**Comment by edd** [comment]
Fixed in https://github.com/vegaprotocol/approbation/releases/tag/v2.7.0

**Comment by campbellssource** [comment]
I'm done with this ticket.
Leaving it open for @jtsang586 @radoslaw-szpiech @AndyWhiteVega . feel free to close when you think you are good.
The right query has changed a little from the one in the ticket description
this currently works for me:
```
node ./approbation/bin/approbation.js check-codes --specs="./specs/user-interface/**/*.md" --tests="{./frontend-monorepo/apps/*-e2e/**/*.cy.{j,t}s,./vegawallet-desktop/frontend/automation/cypress/**/*.cy.js}"
```

**Comment by edd** [comment]
@campbellssource since I pushed 4.0.0, you need one extra parameter, `--categories`, which points to the JSON file containing categories. I've taken your command above and I'm adding it in:

```bash
node ./approbation/bin/approbation.js check-codes --categories="./specs/user-interface/categories.json" --specs="./specs/user-interface/**/*.md" --tests="{./frontend-monorepo/apps/*-e2e/**/*.cy.{j,t}s,./vegawallet-desktop/frontend/automation/cypress/**/*.cy.js}"
```

**Comment by pennyandrews** [comment]
Closing as I believe everyone that needs to be is set up with this + Edd has it covered nicely in the readme so doesn't make sense to keep it open in a ticket
