### ISSUE TITLE
chore: replace Order type with existing OrderSubmissionBody['orderSubission'] 

### ISSUE THREAD

**Issue by bglownia** [vegaprotocol/frontend-monorepo#1564]
## The Chore

Order type created for order submission is in naming conflict with Order from data provider. It can be replaced by OrderSubmissionBody['orderSubission']

## Tasks

- [x] replace Order type with existing OrderSubmissionBody['orderSubission'] 
- [x] rename OrderWithMarket to Order
- [x] rename TradeWithMarket to Trade
- [x] rename FillsWithMarket to Fills
