### ISSUE TITLE
chore: markets-list: move queries to .graphql, combine data in marketListProvider

### ISSUE THREAD

**Issue by bglownia** [vegaprotocol/frontend-monorepo#1566]
## The Chore

Post 0.55 migration cleanup in markets-list

## Tasks

- [x] move queries to .graphql
- [x] combine data in marketListProvider
- [x] use only necessary data sources (no market data in console-lite, no candles in trading index page ).
