### ISSUE TITLE
chore: generic data provider fixes and improvements 

### ISSUE THREAD

**Issue by bglownia** [vegaprotocol/frontend-monorepo#1568]
## The Chore

Some fixes and improvement in data provider are needed as effect of rapid changes required by migration to 0.55 version of API

## Tasks

- [ ] send isUpdate in callback payload from derived data provider even if combine delta so not exist
- [ ] sent isInsert in callback payload to support pagination
- [ ] add unit tests
