### ISSUE TITLE
Update to use global network param component

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1632]
## The Chore

There is now a network parameter component that follows the same pattern as the doc site, and is implemented on .xyz. This component allows us to embed a network parameter value in the site in a manner which shows the value is determined by a network parameter, offers an explanation on mouseover, and allows users to find the source by linking to the parameter on block explorer.

This chore is to update where and how we display network parameters on the token site.

## Tasks

- [ ] Find all the instances of network parameters on token (and add to ticket)
- [ ] Implement the network parameter component, as it exists on vega.xyz, in a modular manner so it can be embedded wherever needed.
- [ ] Replace any existing mentions of network parameters with the new component.
- [ ] Check the list of governance network parameters and consider which, if any, should also be embedded in the token site (consider both the submission and voting journeys)
- [ ] Consider linking to docs how-to guides for each type of proposal, so users can easily find explanations of network parameters.

## Additional details / background info

Example of the style for this lead by vega.xyz https://deploy-preview-230--vega.netlify.app/validators/
https://github.com/vegaprotocol/documentation/blob/main/src/components/NetworkParameter.js

- At the time of writing, the [governance propoal guides on testnet docs](https://docs.vega.xyz/docs/testnet/tutorials/proposals) have been updated to include most (if not all) network parameters, along with explanations of their meaning and how this affects the values you should use in your proposal. These will eventually be added to mainnet docs, but for now can be found in testnet docs. These are a natural thing to link to from the proposal creation process.
- At the time of writing, the network parameter component for vega.xyz is in acceptance testing phase. [Examples can be seen here](https://deploy-preview-230--vega.netlify.app/validators/). Ideally the two components will look identical, for consistency. Note that vega docs was the first touchpoint to have a network parameter component, as seen in the docs link above, but alignment should first be sought with the style and functional of the component on vega.xyz.
