### ISSUE TITLE
Deposit dialog transaction flow

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1638]
### Story
As a trader/user
I want to be more clearly guided through the deposit process
So that I can understand what transactions I am executing and start trading

**Current:**
![Image](https://user-images.githubusercontent.com/6803987/194158723-d8db46fc-f98c-4446-9d3f-970e0b38c7ae.jpg)

### ACs
- [ ] Should be able to see transaction status flow for faucet transactions within dialog
- [ ] Should be able to see transaction status flow for approval transactions within dialog
- [ ] Should be able to see transaction status flow for deposit transactions within dialog
- [ ] Should be prompted to approve deposits if you haven't already
- [ ] Transaction status styles should be consistent

## Tasks

- [ ] Review and finalise the wireframes for the flows and status https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2375%3A32241
- [ ] Develop etc.

### Additional Info
The deposit dialog clashes with the transaction status (requested, pending, complete etc) dialog and it needs to be refactored to display the transaction status within the same dialog. 

Currently we render the dialog returned by the The useEthereumTransaction hook, but it also exposes the required states to change what renders inside the dialog

Note: The ethereum libs/web3/src/lib/ethereum-transaction-dialog/ethereum-transaction-dialog.tsx has a TransactionContent component which could be used to ensure consistent transaction state UI.

**Comment by PeteWilliams** [comment]
Two issues to solve here - first, the flow of the deposit journey where approval is required first.
That can be improved by splitting the journey into steps as proposed here: https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2375%3A31983

(That page also includes a flow for the two-step withdrawal process).

The second is the issue of modals on top of modals. The above suggestion should resolve this for approval/deposits, but the issue remains for faucet transactions. We can use toasts to resolve this ([rough mockup here](https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2375%3A31983)), but they aren't available yet. If they are going to be available in the near future, I'd suggest we do something simple for the time being and revisit once toasts are available.

Some suggestions for what might be a simple short-term fix, but happy to hear others:

**One modal at a time**
When a modal triggers another modal - eg requesting faucet from the deposit page - reuse/replace the existing modal with the new one, then once the transaction is complete, go back to the original one.
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2375%3A31983

**Modals on top of modals**
Currently you can still see the original modal behind the new one. Use an overlay to hide it until the new modal is dealt with:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=3672%3A34966
