### ISSUE TITLE
Prompt to connect from deal ticket

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1641]
## Story

As a trader
When I am in the deal ticket
I want to easily connect my Vega wallet
So that I can place an order in the deal ticket

## Acceptance Criteria

- [x] I am prompted to connected my wallet within the deal ticket
- [x] I can open the connect dialog from within the deal ticket
- [x] I can still see the deal ticket

## Tasks

- [x] Identify / sketch pattern to handle this
- [ ] Add render logic to render a different button which opens the connect dialog

**Comment by PeteWilliams** [comment]
There's an existing design for this in Figma: https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=872%3A6858

![image](https://user-images.githubusercontent.com/1325606/194589954-bd605e4e-660d-4c57-aed2-06696683fae7.png)

**Comment by mattrussell36** [comment]
Lets not add the 'Get a Vega Wallet' link as you now get prompted to do that in the dialog
