### ISSUE TITLE
Differentiate between LP and pegged orders in orders table

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1642]
### Tasks
 - [ ] Show if order is a liquidity provision order in the type column
 - [ ] Show if order is a pegged order in type column with
 - [ ] Regular orders can remain untouched just showing Market/Limit
