### ISSUE TITLE
Single table for positions

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1645]
## Tasks

This task is to prepare the positions table to allow leveraging of AgGrid sorting and filtering as well as reduce surface area for bugs (such as values pushing against each other)

- [x] Render a single data grid that fills the positions panel, with all positions _not_ aggregated by asset
- [x] Add settlement asset column
- [x] Split size cell into notional and open volume columns
- [x] Split entry price and liquidation price into separate columns, progress bar can be displayed in liquidation price column
- [x] Margin allocated cell to use single actual value (not percentage)
- [x] Total value across positions gets removed
