### ISSUE TITLE
Show when a position's PnL or status has been affected by the network

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1647]
## Story

As a trader
I want to see when my PnL has been affected by the network
So that I understand why that has happened

## Acceptance Criteria

- [ ] I can see when a position has been affected by network conditions
- [ ] I can see when a position's status has been affected by network conditions
- [ ] I can inspect the resulting system transactions

## Tasks

- [ ] Tech discussion around feasibility given that the position query doesn't provide anything for this
- [ ] Visual Design
- [ ] Team review

## Additional details / background info
There is nothing in the positions API to make this easy so we probably need a spike to figure out the following:

- If something can be added to the API to make this simpler
- If there is a client side only solution, perhaps subscribing to orders and looking for system transactions for the given markets.
- Core PR https://github.com/vegaprotocol/vega/pull/7485
