### ISSUE TITLE
Market select dropdopwn snags

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1651]
### Tasks

 - [x] Add tooltip for trading mode
 - [x] Add underline to market name to indicate link to market page
 - [x] Add underline to asset to indicate click-ability
 - [x] Dont navigate to market page when asset dialog is opened

**Comment by MadalinaRaicu** [comment]
it does not navigate to another page and the dialog remains open
