### ISSUE TITLE
Remove /markets page

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1652]
## Tasks

- [ ] Remove /markets page and page specific components
- [ ] Remove any unused hooks/functions/components from libs/market-list
- [ ] If clicking the 'Trading' link and no cached market id is found, ensure the experience is the same as for the home page. IE a default market is shown and the landing dialog opens
