### ISSUE TITLE
Persist deal ticket state for each market

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1655]
## Story

As a trader
I want the deal ticket for a market to keep its state even if I navigate to other markets and pages
So that I don't have to re-input values and settings for the deal ticket every time

## Acceptance Criteria

- [x] Order type is persisted
- [x] Order direction is persisted
- [x] Order size is persisted
- [x] Order price is persisted, if no price has been stored, market mark price should be the default
- [x] Time in force is persisted
- [x] Deal ticket state is persisted _per_ market

## Tasks

- [x] Figure out most suitable method for data persistence. Local storage vs indexedDB
