### ISSUE TITLE
Show estimated order data in deal ticket

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1659]
## Story

As a trader
I want to see potential impact of my order
So that I can make sensible trading decisions

## Acceptance Criteria

- [ ] I can see the estimated closeout price
- [ ] I can see the estimated marge
- [ ] I can see the notional size
- [ ] I can see estimated fees
- [ ] I can see estimated slippage

## Tasks

- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
