### ISSUE TITLE
No markets state

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1662]
## Story

As a trader
I want to know what to do if there are no markets on the network
So that I understand that I can propose one if none exist

## Acceptance Criteria

- [x] I am shown a  'No markets' message in the landing dialog
- [x] I am shown a 'No markets' message in the select market dropdown
- [x] I am prompted to propose a market via the governance site in the landing dialog
- [x] I am prompted to propose a market in the select market dropdown.

## Tasks

- [x] Allow trading page to load in a skeleton state (tabs showing without any content) if no markets exist
- [x] Update landing dialog to render different content outlined below
  - [x] Add links specified below
  - [x] Fetch and render the latest market proposals

## Additional information
- Note that the 'view all proposed markets' link can be omitted for now as that feature doesn't exist yet

**Comment by PeteWilliams** [comment]
Initial thoughts:

On first visit, if there are no markets, instead of the 'select a market to get started' popup, show something like this:


![Image](https://user-images.githubusercontent.com/1325606/195876874-b93a354e-b742-473d-8f58-b4daf363614c.png)

https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=3600%3A34757

Probably best to show the Portfolio page by default, as they can actually do something there.
But what should happen if they do click 'Markets'? It could show the popup again, but can we show the trading view in the background in a skeleton state? So show the tabs, the ticket, a blank chart etc, but the data panels would show 'no data' or similar. It'd be nice for users to 'see' the trading app, even if they can't use it. But it'd be good to understand what development effort is involved and whether it's worth it. Thoughts @mattrussell36?

**Comment by ckpringle** [comment]
Touched on this in refinement for console, visual design requested, and question on whether there's a view all interaction / limit to the proposed market list (and if then we still need all four bullets in the bit above)

**Comment by ckpringle** [comment]
@mattrussell36 do you have any thoughts on @PeteWilliams questions above?

**Comment by joellecharlotte** [comment]
Here is the "No Markets" modal design.

[Figma link ↳](https://www.figma.com/file/deV7EBxvTF4ggdsKVVosfr/Console-V2---Design-Revisions?node-id=702%3A1807)

![01 4 No Markets](https://user-images.githubusercontent.com/113684458/200290575-d57e7c75-0365-4f51-9273-3180f019f1ab.jpg)

**Comment by asiaznik** [comment]
@mattrussell36 @joellecharlotte I gather that the proposed markets "names" should be the instrument codes of the proposed market rather than the rationale's title/description, right?

**Comment by mattrussell36** [comment]
Yup that's correct. Use code please
