### ISSUE TITLE
Spike: Investigate Ledger entries

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1670]
## The Chore

There is an existing design for Ledger Entries https://github.com/vegaprotocol/frontend-monorepo/issues/846 - this chore is to work out an approach to the technical implementation.

## Tasks

- [ ] Explore technical implementation and work out approach
- [ ] Review approach with the team
- [ ] Create resulting tickets for core and frontend teams

## Additional details / background info

We will first be adding a MVP table in https://github.com/vegaprotocol/frontend-monorepo/issues/1387 and following up with enhancements in https://github.com/vegaprotocol/frontend-monorepo/issues/846

**Comment by pennyandrews** [comment]
Spike blocked by core ticket https://github.com/vegaprotocol/vega/issues/6519

**Comment by macqbat** [comment]
After investigations and talks with API guys, they recommend using ledgerEntries api for getting data for this view. This what was done [here](https://github.com/vegaprotocol/frontend-monorepo/issues/1387), seems to cover basically all requrements, except a balance of the account after certain transaction. Colleagues suggest a resign from this requirements, because they cannot easily deliver such functionality.
