### ISSUE TITLE
Spike: Investigate loss socialisation 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1671]
## The Chore

Identify the MVP solution for loss socialisation that fulfils the need - showing the user why their position has changed or their order has been closed. 

## Tasks

- [X] Explore / identify how best to show this information e.g. in the context of your actual trades (technical approach and UX)
- [x] Look into apis and validate what data is available to present against the table design
- [x] Review with team
- [ ] Refine backlog ticket #520

**Comment by PeteWilliams** [comment]
It's probably best to think about the bigger picture, as the same question applies to other things like liquidations - how to do we make people aware of things that happen behind the scenes that effect their P+L? 

There's a couple potential options proposed in https://github.com/vegaprotocol/frontend-monorepo/issues/520 

**A log of system transactions where they can see these events**
![image](https://user-images.githubusercontent.com/1325606/194908249-a237d5a8-8b6a-4050-93c5-7ad9f87770f7.png)

**Notifications letting the user know when the event occurs**
![image](https://user-images.githubusercontent.com/1325606/194907650-d7819f31-d237-42eb-bf04-0df89ee6225c.png)


**Loss socialisation only**
If we just want to tackle loss socialisation on its own, we could look at something simple like marking it on a position row, but this wouldn't be something we could extend to liquidation etc

![image](https://user-images.githubusercontent.com/1325606/194907554-8da55c85-1824-4d13-866b-b57115516557.png)


There are other options but I think they would mean complicating existing tables like Positions which I know we're keen to avoid.

In terms of an MVP, I think a list of system transactions under portfolio would make more sense, as without building some sort of notification history, notifications would be lost when dismissed. I'm also presuming it would be easier to build that notification functionality?

The current design for the system transaction table includes things such as liquidation, fees, search levels etc, but we could start off with just liquidation and then add others in order of priority.



Happy to discuss any other ideas.
