### ISSUE TITLE
Horizontal scrolls appearing when dialog is open

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1676]
## The Chore

Whenever we have an open dialog (any dialog) the horizontal scrollbars are shown for the ag grid tables. 

~~There's also a console error being displayed which may be connected to this behaviour: `next-dev.js?36dd:24 react-remove-scroll-bar: cannot calculate scrollbar size because it is removed (overflow:hidden on body ...`~~

## Tasks

- [x] Investigate what's the root cause of the scrollbar issue.
- [x] Apply fixes if possible
- [x] Go through all ag-grids and test against horizontal scrollbars

## Additional details / background info

![Screenshot 2022-10-07 at 09 40 50](https://user-images.githubusercontent.com/1980305/194500127-3fb8e82a-1be5-4b93-82dd-ad9741fac8a6.png)
![Screenshot 2022-10-07 at 09 42 42](https://user-images.githubusercontent.com/1980305/194500139-d3e11f00-e1fa-4da4-9608-0230fcd02d89.png)
