### ISSUE TITLE
Consistent no data states

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1678]
## The Chore

Ensure UI for 'no data' states are consistent between different trade grid and portfolio grid panes. Here are some examples of inconsistencies 

![Image](https://user-images.githubusercontent.com/6803987/194446438-0338e8ae-9635-4ba2-b3e4-f34418f73ded.jpg)

![Image](https://user-images.githubusercontent.com/6803987/194447558-f703eecd-93cf-499d-8cd3-bd6542563987.jpg)

![Image](https://user-images.githubusercontent.com/6803987/194447889-e0779b8f-d9cb-4ae8-b9d9-277acd5ca51d.jpg)

## Tasks

- [x] Review all panes and fix inconsistencies
- [x] Use no `overlayNoRowsTemplate` prop where possible, so that the column headers of data grids still show
- [x] No data text for non AgGrid (eg orderbook) should be styled the same, these are likely using AsyncRenderer

**Comment by MadalinaRaicu** [comment]
I think I already approached this issue (on market/{id} tabs) in one of my PRs. I need to check again if it applies everywhere.
