### ISSUE TITLE
See reference and offset for pegged and liquidity shapes

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1716]
## Story

~~As a~~ When looking at a list of my orders (that include either pegged or liquidity shapes)
I want to see the Reference and Offset for each part of a pegged/liquidity shape order (as well as other information shown in order table)
So that I can confirm the status of my liquidity/pegged shape and decide if I wish to leave it, amend, or cancel

Language note: one summits a "pegged shape" that results in an order for each price+side combo in the shape. The submission of this whole shape is also often referred to as a pegged order (even when it results in multiple orders)

## Acceptance Criteria

See [This PR](https://github.com/vegaprotocol/specs/pull/1281) that contains working acceptance criteria. 7003-MORD-017 & 7003-MORD-016 ([readable preview of that branch](https://github.com/vegaprotocol/specs/blob/user-interface-add-MORD-manage-order-content/user-interface/7003-MORD-manage_orders.md))

- [ ] I can see the reference used for that order (e.g. bid, mid, ask)
- [ ] I can see the offset for that order (formatted with `market.quote` decimal places)
- [ ] I can see the direction of that order (long/short)

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by PeteWilliams** [comment]
Some initial thoughts for discussion here:

https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=3854%3A37007

**Comment by PeteWilliams** [comment]
Updated designs here: https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=3862%3A37354

**Comment by campbellssource** [comment]
<img width="1790" alt="Screenshot 2023-03-07 at 09 02 22" src="https://user-images.githubusercontent.com/13255539/223374846-7b32acc3-bfd3-4c2e-80d2-5a76ee0e8266.png">

But lets discuss this properly

**Comment by campbellssource** [comment]
Closing this ticket. use this ticket instead https://github.com/vegaprotocol/frontend-monorepo/issues/3373
