### ISSUE TITLE
Set up apps in new validator test network 'sandbox'

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1744]
## Task

Configure and set up apps for the new validator test network 'sandbox'

URL from Fryd https://n01.sandbox.vega.xyz/
Here is the PR they have created for the sandbox genesis https://github.com/vegaprotocol/networks-internal/pull/149

### Common Tasks
- [x] Create a release branch `release/sandbox`

#### Token
- [x] Create .env files
- [x] Create netlify app building from release branch
- [x] Configured required Netlify env vars
- [x] Configure domain for token.sandbox.vega.xyz

#### Multisig Signer
- [x] Create .env files
- [x] Create netlify app building from release branch
- [x] Configured required Netlify env vars
- [x] Configure domain for token.sandbox.vega.xyz

#### Block Explorer and Stats
- [x] Create .env files
- [x] Create netlify app building from release branch
- [x] Configured required Netlify env vars
- [x] Configure domain for explorer.sandbox.vega.xyz

#### Console and Console-Lite
- [x] Create .env files
- [x] Create netlify app building from release branch
- [x] Configured required Netlify env vars
- [x] Configure domain for console.sandbox.vega.xyz

Note: LP dashboard doesn't have a custom domain yet

**Comment by pennyandrews** [comment]
Need URLs from Fryd

**Comment by elmar-vega** [comment]
Done for BE

**Comment by pennyandrews** [comment]
Discussed and decided with Dex that LP Dashboard doesn't need to be on sandbox yet as it's not 'live' at all. Have created a ticket to do it later down the line if relevant
