### ISSUE TITLE
Mainnet console deployment

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1754]
Deploy console to IPFS for mainnet

## Tasks

- [x] Confirm URL and URL behaviour
- [x] Show interstitial page on vega.xyz to redirect
- [x] Set up pipeline to deploy to IPFS on push to main 
- [x] Set up sentry alerts and rules to create pager duty incidents
- [x] Remove unused network json files in static app (governance app will be the only app using them)
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/3853
- [x] Run E2E with mocks
- [x] Run E2E with capsule
- [x] Manual tests
- [x] Tag
- [x] Release
- [x] Manual smoke tests

## Additional details / background info

Fairground Console is already deployed from IPFS so the setup should be almost the same

**Comment by edd** [comment]
Requires #1873
