### ISSUE TITLE
Improve derivedDataProvider paginated data handling, add unit tests

### ISSUE THREAD

**Issue by bglownia** [vegaprotocol/frontend-monorepo#1765]
## The Chore

Improve derivedDataProvider paginated data handling

## Tasks

- [x] pass isInsert to callback if any dependency has isInsert
- [x] create generic paginatedCombineDelta and paginatedCombineInsertionData functon to handle updats in orders, fills and trades
- [x] add unit tests
