### ISSUE TITLE
Spike: Decide on the role of status.vega.trading and relationship with explorer

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1775]
## Chore 

Right now the landing page of block explorer includes network status information, and the landing page of status.vega.trading has the same. Status site (apart from looking odd) has no way to switch network (it could use the network switching component) and is a copy of what's on block explorer's current landing page. As a team we want to reach a conclusion on the role of these two / do we need status.vega at all or just use block explorer...

https://status.vega.trading/
https://explorer.vega.xyz/

There is also https://stats.vega.trading/ which is an internal tool (and to stay that way?). 

## Tasks 

- [x] Come up with approach / hypothesis
- [x] Validate approach with Barney (and others in the Slack thread in #project-block-explorer channel)
- [x] Sketch / decide on whether the network stats live together with the other landing page content or if it's separate (in it's own navigation)
- [x] Write tickets for whatever the resulting work is

**Comment by neildawson** [comment]
[status.vega.trading has been retired](https://vegaprotocol.slack.com/archives/C033K0B1N2J/p1666966221198319?thread_ts=1666794432.451729&cid=C033K0B1N2J)

**Comment by neildawson** [comment]
The following are excerpts from [the Miro doc](https://miro.com/app/board/uXjVPVRiSOM=/?moveToWidget=3458764537767813940&cot=14).

Proposal for updated homepage:

![Image](https://user-images.githubusercontent.com/1080322/201983162-ab6ca5e6-a8a1-4a19-9a5c-6e9edb9bb07c.png)

Proposal for new "Status" page:

![Image](https://user-images.githubusercontent.com/1080322/201983274-8522642d-7881-4c8a-8f7f-8ba233a88dd0.png)

This ticket has been de-prioritised. The above proposals have not been reviewed by any stakeholders yet. Calum suggested we show these proposals to Chris and Sunny as a strawman to get a sense of what they think community members may need.

We can pick this up when this ticket is reprioritised.

**Comment by pennyandrews** [comment]
Ticket in the backlog for this ready to refine when the time is right https://github.com/vegaprotocol/frontend-monorepo/issues/2278
