### ISSUE TITLE
Link to related forum posts from validator page and proposals from governance

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1776]
## Story 

As a vega user 
I want to easily find all the discussions available about a proposal 
So that I can find out more about the history of the proposal / take part in the conversation and inform my decision on who to stake

## Acceptance criteria 

- [ ] I can see a specific forum discussion related to this specific proposal ID and access related forum posts from a governance proposal on token front end
- [ ] I can access related forum posts from a validator profile on token front end 
- [ ] Links are relevant to fairground and mainnet

## Tasks 

- [ ] Investigate and use Forum's search API to display related discussions on the proposal page based on proposal ID
- [ ] Add to instructions to add a post (or comment?) with the proposal ID on the forum to ensure it displays on the governance site 
- [ ] Add "basic" solution to link to forum search i.e. "View related validator profile topics on the forum ↗" and "Search for topics related to this proposal on the forum ↗"

## Sketch

Example [#mainnet-validator-candidates nodes guru](https://community.vega.xyz/search?q=%23mainnet-validator-candidates%20nodes%20guru), [#governance Shiba INU market](https://community.vega.xyz/search?q=%23governance%20Shiba%20INU%20market)

![Image](https://user-images.githubusercontent.com/46783148/235727535-93e413b3-897e-4171-9c27-0a6f40a32d95.png)

<img width="1292" alt="Screenshot 2022-10-19 at 11 42 30" src="https://user-images.githubusercontent.com/46783148/196669731-a315dd75-3124-482d-9bfb-f9788ae8f626.png">

## Background 

Thoughts on implementation 

* **MVP - We link to forum search inside the category for validator profiles**
* We could take the validator name - plug into the forum search using forum API and return results on to the validator page e.g. "Related posts in the forum" - showing forum topic names linked to click through to forum posts, starting with the earliest result
* Alternatively we could find a way for a forum moderator to tag a post as a validator profile / intro and use the tag in the API response 
* Other option is having a place on something like github where someone makes a PR and says this forum URL is the validator URL for their forum post

In general bringing forum topics / surfacing them in things like this, governance is worth doing!
