### ISSUE TITLE
Show correct network uptime

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1780]
## The Chore

We need to ensure we are showing the correct network uptime

Related to and may duplicate https://github.com/vegaprotocol/frontend-monorepo/issues/1199 but I think at the very least we may need the ticket to cover status. and stats. ?

## Tasks

- [x] Identify where we need to get the correct data from
- [ ] Implement correct data on explorer
- [ ] Implement correct data on status.vega.trading
- [ ] Implement correct data on stats.vega.trading (if not already correct)

## Additional details / background info

In slack thread with Jeremy and Phil it was determined that the correct uptime data should come from gql statistics field 'Statistics.genesisTime' or directly from Tendermint if we prefer https://tm.n09.testnet.vega.xyz/genesis (genesis_time). We definitely won't get the correct information from the nodeData.
