### ISSUE TITLE
Self service user error reporting

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1783]
## Story

As a team
We want users to be able to report errors and issues in context when using our dapps
So that we might identify more issues and errors (and faster) that users are experiencing  

## Acceptance Criteria

- [ ] I can initiate an error report directly from the dapp I'm currently using
- [ ] I can automatically include details of the part of the dapp I'm trying to use? 
- [ ] I can automatically include details of my OS and browser etc.?
- [ ] If we use a third party service to do this, it's not a centralised one

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Define the process for managing these error reports and feedbacking back to users (is it just the existing feedback stuff?) 
- [ ] Team review
- [ ] Develop
- [ ] Test
- [ ] Etc.
