### ISSUE TITLE
Holding page to temporarily block features

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1784]
## Story

**As a** team
**I want to** be able to quickly implement a holding page (of some kind) that blocks certain features and provides further information about why
**So that** we can manage expectations and prevent bad things happening when we have a critical or major issue (things that could be detrimental for users to do) with features in mainnet

## Acceptance Criteria

- [ ] I can quickly configure and release a generic holding page (or equivilent)
- [ ] I can provide a small amount of additional information (text) and a link to a blog post or equivilent for users to track the issue resolution

## Tasks

- [ ] Speak to Matt + Dex to understand what and when this might be for and how they could be implementing it
  - Env var flag to trigger maintenance screen
- [ ] Explore and sketch whatever the thing is
- [ ] Team and stakeholder review
- [x] Visual Design
- [ ] Team review

## Sketch

E.g. Full (app) screen "we're doing some maintenance right now, come back later" with some nice branding. Vega logo falling over. Right font. 

![Image](https://user-images.githubusercontent.com/46783148/207391586-8acf859e-215f-492f-b9dc-893533ed70c7.png)

## Additional details / background info
Consider if there's a link to a blog post explaining what's going on, what the words need to say etc.

**Comment by joellecharlotte** [comment]
[Here's a simple page](https://www.figma.com/file/deV7EBxvTF4ggdsKVVosfr/Console-V2---Design-Revisions?node-id=972%3A5614&t=WZXqBhNMoY2VZ5yT-1) which text + option to have a link. @bigfandavid will tackle a design element that works nicely with the message.

**Comment by bigfandavid** [comment]
Suggested illustration for review:
<img width="1003" alt="Screenshot 2022-12-14 at 12 01 08" src="https://user-images.githubusercontent.com/113683891/207590268-5e0208f3-dbe6-46e6-967f-a350f79f86c5.png">

**Comment by joellecharlotte** [comment]
[Here is the design](https://www.figma.com/file/deV7EBxvTF4ggdsKVVosfr/Console-V2---Design-Revisions?node-id=972%3A5614&t=WZXqBhNMoY2VZ5yT-1).

The design shows the entire interface being blocked, including the top nav. Not sure if this would ever be the case, or if the nav would always be accessible and this is used to block sections or areas of the trading UI. Waiting confirmation from Dex / Matt and while update accordingly.
