### ISSUE TITLE
Update nodeHealth to use `x-block-height` header to check data node health

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#1791]
#2701 improved the way `NodeHealth` works, but misses one imporant part of the ticket. Data Node adds some metadata headers on every request:

```
< x-block-height: 926035
< x-block-timestamp: 1675424066275232000
< x-vega-connection: CONNECTED
< x-vega-node-id: n11.testnet.vega.xyz
```

These are interesting because they contain the data node's idea of the block height, timestamp, and whether or not it is connected to a core vega node. This is different to the `blockHeight` property in statistics, which comes directly from the  core node.

To put it another way, if you run `curl -v https://api.n11.testnet.vega.xyz/statistics`, the response header `x-block-height` could contain a different height to the body property `.statistics.blockHeight`. It this is the case, it is an indicator that the data you are being served is not up to date, which is a very important thing to flag up to the user.

<img width="413" alt="Screenshot 2023-02-03 at 12 08 41" src="https://user-images.githubusercontent.com/6678/216600230-cde4bc61-b11e-41ff-831b-7356dc479fab.png">

## Acceptance Criteria

- [ ] As a user I can clearly see that the app I am on is connected to a datanode that isn’t up to date 

## Tasks

- [ ] Update `Nodehealth` component to log `x-block-height` for the data node you are connected to
- [ ] For the data node you are connected to, compare `x-block-height` to the currently held block height value (i.e. the one read from statistics)
- [ ] Use the currently acceptable value of `BLOCK_THRESHOLD` - if `x-block-height` is more than `BLOCK_THRESHOLD` *behind* `statistics.blockHeight`, show an error indicating stale data

**Comment by edd** [comment]
The headers are not currently usable in most situations due to the headers not being passed through the HTTPS proxy

**Comment by gordsport** [comment]
Since the above linked blocking issue has been resolved its been identified that there is still some reminaing work to unblock this issue. This work is captured here:

- https://github.com/vegaprotocol/vega/issues/6701

**Comment by pennyandrews** [comment]
@dexturr to touch base with @edd to see if there is anything to do here for Governance team

**Comment by MadalinaRaicu** [comment]
is this blocked by https://github.com/vegaprotocol/vega/issues/6913 ?

**Comment by edd** [comment]
I have reworded the ticket. While #2701 improve this behaviour, it does not use `x-block-height` which is the point of the ticket.
