### ISSUE TITLE
connect wallet button in deal ticket improvements

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/frontend-monorepo#1792]
## The Chore

Add small improvements to the implementation

## Tasks

- [x] less words in the button
- [x] no additional css on the button
- [x] remove get wallet link
