### ISSUE TITLE
Change data shown in "volume" column in market switcher

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#1794]
## The Chore
![image](https://user-images.githubusercontent.com/13255539/196881790-798ae6b4-60d3-4f93-92ff-506f9262db75.png)

The column above is using indicative uncrossing volume. It shouldn't. id doesn't makes sense in this context and wouldn't have any data to show if markets are not in auction.

Instead I suggest the column becomes "24 hour traded volume", and moves between 24 low and trading mode.

here is what some other exchanges do
<img width="1368" alt="Screenshot 2022-10-20 at 08 20 46" src="https://user-images.githubusercontent.com/13255539/196883108-e8744d3b-edd6-4dd0-92fe-1d5dba2baefa.png">
<img width="1719" alt="Screenshot 2022-10-20 at 08 23 35" src="https://user-images.githubusercontent.com/13255539/196883121-1f8e8f45-d132-437e-95f3-0ab8cb5cbf29.png">
<img width="1198" alt="Screenshot 2022-10-20 at 08 26 15" src="https://user-images.githubusercontent.com/13255539/196883729-0531ced8-24d8-4d31-8ca7-4b3a0fe37e3e.png">
<img width="1427" alt="Screenshot 2022-10-20 at 08 27 45" src="https://user-images.githubusercontent.com/13255539/196884927-63bdc95f-81fd-48db-887f-d7cd64a2b540.png">

## Tasks

- [ ] move the column
- [ ] change what data it displays to 24 hour traded volume.
- [ ] Consider adding a tooltip to explain what this is (not part of this ticket as this overview doesn't have any tool tips yet. but should as part of future work maybe?
- [ ] Consider adding 24h vol to the header of the market trading screen as per examples above, raise ticket to do so or do as part of this

## Additional details / background info

The period the where the traded volume is counted should be the same as the 24 hour high/low and change calculations.
