### ISSUE TITLE
Update order rejection reason mappings

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1808]
Two rejection reasons have been renamed and we need to update the mappings to translations

## Tasks

- [x] Review PR https://github.com/vegaprotocol/vega/pull/6132/files#diff-be016f833f94c6069e96beb4873414c55bdfb7af1924c9c1b90eb709304ff90e
- [x] Regen types with stagnet3 schema
- [x] Update order rejection reason map in global-types-mappings.ts
- [x] Update usage of `Account` type to `AccountBalance`
