### ISSUE TITLE
Update docs links to ensure they go to the right places (and use the new URL structure)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1825]
## Chore

Replace the links to docs to the right places (as things have changed)

Docusaurus (the framework for docs.vega.xyz) no longer requires that we have /docs/ in the URL for it to work as a documentation site. This means we can slim down the docs URLs i.e. 

docs.vega.xyz/docs/testnet/api/rest/overview

becomes

docs.vega.xyz/testnet/api/rest/overview

Edd will be setting up a batch redirect to prevent (most/all) external broken links, but ideally they should be changed across UIs/websites to the new URL structure so that the redirects can be removed.

Candida has also restructured the liquidity pages quite a bit so all the links at the top have changed. We will need to rework slightly how we approach that, currently the links are basically:

1. Background on liquidity on vega 
2. Liquidity tutorial > provide liquidity 
3. Liquidity tutorial > view liquidity orders
4. Liquidity tutorial > amend / cancel liquidity order

The way it has now been restuctured it is probably more logical to go with:

1. Learn about liquidity on Vega >> https://docs.vega.xyz/testnet/concepts/liquidity/provision
2. Learn about liquidity rewards & penalties >> https://docs.vega.xyz/testnet/concepts/liquidity/rewards-penalties
3. Tutorials on managing liquidity orders >> https://docs.vega.xyz/testnet/tutorials/committing-liquidity

## Tasks 

- [x] Find the right links (Jon)
- [ ] Find and replace all docs URLs across the app
- [ ] Test and verify everything still works

**Comment by JonRay15** [comment]
Have updated links and changed structure slightly to align better with what is now on the docs.

**Comment by JonRay15** [comment]
All of these have been replaced with a single link which is working so we're good.
