### ISSUE TITLE
Add proposal type to proposals pages

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#1835]
## Story

As a User
I want to see the type of proposal on the proposal list
So that I can more easily grok the proposals

## Acceptance Criteria

- [ ] I can see the type of the proposal on the proposals list
- [ ] I can see the type of the proposal on the proposal details page

## Tasks

- [ ] Implement 
- [ ] Review placing with Calum

**Comment by sam-keen** [comment]
As discussed as part of #2034 we'll pop this in the list item for now, and discuss a full visual update at a later time (this work will also get done in that ticket)
