### ISSUE TITLE
update Account type to AccountBalance

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/frontend-monorepo#1856]
## The Chore
Update frontend monorepo according to last schema breaking changes

## Tasks

- [ ] upgrade .graphql files
- [ ] upgrade cache policies
- [ ] check all other places
