### ISSUE TITLE
[trading] switch next router for react router

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#1873]
# Problem
Deeply nested urls (e.g. `/markets/12345`) rely on server-side routing. Netlify supports next.js, so this works fine. Fleek does not*. IPFS doesn't have something that can handle routing this to a .html file**

# Solution
Sadly, it's hash based routing. It used to be more common, back before [History.pushState](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState) was widely supported. It's... pretend routing, effectively. But given we can't rely on a server to do the redirect for us, and we don't know (for example) the market IDs in advance, it's the best tool for the job.

# Tasks
- [x] Add react router dep
- [x] Switch all navigation to [HashRouter](https://v5.reactrouter.com/web/api/HashRouter)
   - [x] `console.fairground.wtf/#/markets/1234`
   - [x] `console.fairground.wtf/#/portfolio`
   - [x] `console.fairground.wtf/`
- [x] ESLint rules to prevent usage of `next/link` or `next/router` accidentally
- [x] Update Cypress tests to navigate directly to the hash links
- [ ] Remove nextjs plugin from netlify
- [ ] Update build command to use `next export`

```
* It is on the roadmap! Date: unknown
** Actually it *does* as of September 23rd (https://github.com/ipfs/kubo/pull/8890), but the appropriate version is not widely deployed, so we are opting not to rely on it. We can roll back this change when it is.
```
