### ISSUE TITLE
Remove insignificant trailing zeroes

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1875]
addDecimalFormatNumber doesn't trim trailing zeroes in many cases we want to represent a number in the fewest characters possible to reduce noise.

## Tasks

- [ ] Add a helper function to apply decimals, format the number _and_ also remove trailing zeroes
- [ ] Apply it to the following locations
  - [ ] Landing dialog last price column
  - [ ] Market dropdown: last price, 24h high, 24h low and, 24h volume columns
  - [ ] Deal ticket: Notional value, fees, margin requirement and liquidation price

## Additional information
Example test cases
```
func = (value: string, dps: number) => string 

func(123000, 5) => 12300
func(123000, 3) => 123
func(123000, 1) => 12300
func(123001, 2) => 1230.01
func(123001000, 2) => 1230010
```
