### ISSUE TITLE
Deal ticket fees and values display

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1876]
As the values change the rows hide and show making it appear broken. Additionally with long numbers the text wraps making it hard to read

https://user-images.githubusercontent.com/6803987/198142290-2a2eb68b-c96a-48b4-8789-d139718f4e36.mov

## Tasks

- [ ] Shorten labels (Notional, Fee, Margin, Liquidation)
- [ ] Add text truncation with an ellipsis
- [ ] Add title attribute to display full values as a fallback
- [ ] Possibly reduce text to text-xs
