### ISSUE TITLE
Upgrade network proposal

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#1891]
## Story

As a User
I want to know when there is a pending, approved, rejected or unspecified protocol upgrade proposal
So that I can take actions (e.g. closing my positions)

## Acceptance Criteria

- [ ] I can see the version of the upgrade, upgrade block height and the status of the proposal
- [ ] I can see the validators that have approved this proposal 

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info

Phil added [a bit of new API](https://github.com/vegaprotocol/vega/pull/6614/files#diff-be016f833f94c6069e96beb4873414c55bdfb7af1924c9c1b90eb709304ff90e) for querying protocol upgrade proposals?

Jeremy description of what is needed: some notification to the user to be aware there is a proposed upgrade of the network. from the version N to version N+1 had been schedule for the DATE, find more information in this documentation page or in the vega blog. And this ideally should be shown on every application. that we are building.

**Comment by dexturr** [comment]
Related: https://github.com/vegaprotocol/vega/pull/6614

**Comment by pennyandrews** [comment]
Not worth doing yet because it won't show until the second upgrade of mainnet (i.e. alpha mainnet v2)

**Comment by pennyandrews** [comment]
This has been superseeded by other tickets now
