### ISSUE TITLE
Add intelligent datanode selection to all apps

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#1899]
## Story

As a user of Governance or Block Explorer
Default to a data node specified in config and allow the user to switch to a different one if they want to

Console will on first load find the node with the most advanced block height that responds the quickest and use that to fulfil decentralisation requirements. 

Token and Block Explorer already rely on centralised services and so it isn't deemed necessary to do those same node checks on start up.

For Governance and Block Explorer we use our own vega hosted node so we should know if has an issue. However we can utilise the work done in Console to check block heights of the node against other nodes to identify if the node we are using gets behind

## Acceptance Criteria
- [x] I can open any of TFE, BE, or Console and be immediately connected to a functioning datanode
- [x] I can still open the datanode selector at any time and select a specific node if I want to 
- [x] I should never be connected to a datanode that we know is broken
- [ ] I should never be connected to a datanode that we know is lagging

## Tasks
- [x] Build this into the shared network selector component (some /all of this might be covered by Matt)
- [ ] Add indicator to Governance and Explorer to notify node health (this is done in Console so might just be moving a component somewhere else)
- [x] If default node is provided, don't run startup checks
- [ ] Update start up node tests to account for lagging nodes by allowing multiple nodes to succeed and picking the one with the most advanced block height (compared to what is reported from the statistics query)

## Original story from Jon...

As a user of TFE, Block Explorer or Console

I want all of those apps to select a functioning datanode when I start them up 
So that I avoid the various issues associated with selecting a lagging or otherwise broken datanode

The node should be selected based on a simplified version of the code defined in the [Vaguer](https://github.com/vegaprotocol/vaguer) repo.  We can add some randomness to try to avoid all apps connecting to the same node every time, but we must avoid any nodes that we know are lagging.

See https://github.com/vegaprotocol/frontend-monorepo/issues/1899#issuecomment-1295070331 for output

**Comment by edd** [comment]
# Vaguer implementation
[Vaguer](https://github.com/vegaprotocol/vaguer/) is pretty basic. It's a tool for spotting nodes that have a different state from others **at the same blockheight**, and **_diagnosing the problem_**. It does this by:

## 1. Fetch a node list
For example [vegawallet-fairground.toml](https://github.com/vegaprotocol/networks-internal/blob/main/fairground/vegawallet-fairground.toml)

## 2. Run the same GraphQL query on every node
https://github.com/vegaprotocol/vaguer/blob/main/src/lib/check.js#L7-L78

This query was specifically designed to get important bits of data from various engines in the core that, if they are different, something is very wrong.

## 3. Produce a sha1 hash of each important bit of the data
Markets are hashed, assets are hashes, etc, and then finally all the hashes are hashed. It's done this way so if the final hash differs, we have a quick way to know which part of it failed - is the markets part different? 

## 4. See which is the most common hash of hashes
This lets us decide who is 'correct'. Only nodes at the same height are valid for this comparison. 

## 5. Display who was wrong, and why
Debug data shows the actual JSON taken from the GraphQL result, and also a table of all the hashes so you can easily see who was 'right', who was 'wrong', and who was at what height

# Vaguer-like in Wallet
Working with @ValentinTrinque, we realised that steps 3, 4 & 5 really don't matter for the wallet. So we ended up on this query instead:
```graphql
{
  statistics {
    appVersion
    blockHeight
    chainId
    vegaTime
  }
  nodeData {
    totalNodes
    stakedTotal
    inactiveNodes
    validatingNodes
  }
}
```

We could cut this down further. The nodeData is only selected as a proxy for 'Is the Ethereum bridge running successfully' and 'Do the nodes fundamentally see the same network'. Anyway. This query reduction is done so that we don't needlessly waste *too* much Data Node time.

# Vaguer-like on front end apps
We already have @notbot00's [Node Switcher](https://github.com/vegaprotocol/frontend-monorepo/tree/fac08bc8316d28998eee722ee6de11ca1401d323/libs/environment/src/components/node-switcher) which does some similar but more simplistic checks against nodes - and uses a default.

So the plan? Probably use the same graphql query as Vaguer-in-wallet.

**Comment by mattrussell36** [comment]
@JonRay15 

I've updated this ticket accounting for the fact that we now use headers in the node switcher. However, _we don't_ in the initial start up queries which we should as currently it could be possible to connect to a very fast responding datanode that is lagging behind in blocks.

@edd As I understand now that we have the headers we shouldn't need to hash any of the data or expand on the basic queries that we already use. Let me know if that is incorrect

**Comment by edd** [comment]
> Let me know if that is incorrect
That feels correct
