### ISSUE TITLE
Update oracle spec fields

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1905]
API fields have changed again and need updating

## Tasks

- [x] Review https://github.com/vegaprotocol/vega/pull/5980/files#diff-be016f833f94c6069e96beb4873414c55bdfb7af1924c9c1b90eb709304ff90e
- [x] Update appropriate fields and components
- [ ] Review and update transaction submission types
