### ISSUE TITLE
Validator table readability (visual) improvements

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1912]
## Story 

As a staking token holder
I want to see how existing validators are performing and measured 
So that I can decide who I want to stake

## Acceptance Criteria 

- [ ] Each heading of the table can be used to sort the content below it
- [ ] Validators are by default sorted based on stake with the largest at the top 
- [ ] I can easily scroll / see who the validator is when looking at the data in the table i.e. the validator column is "frozen"
- [ ] The first column is frozen / pinned for readability 

Mouseovers and data improvements to be made in separate tickets.

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/199042061-97c5b909-7845-4fd8-ade7-a6b607679d85.png)

## Tasks 

- [x] Sketch 
- [x] Design 
- [ ] Implement 
- [ ] etc.!
