### ISSUE TITLE
Support associating to a Vega key without being connected to that wallet

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#1926]
## Story

As a user
I want to be able to enter the vega key I want to associate to manually
So that I can stake to multilpe wallets more easily

## Acceptance Criteria

- [ ] I can use the connected key for my association, if my vega wallet is connected
- [ ] I can see a button as an escape hatch to allow me to enter my address manually
- [ ] I can associate if using manual method without connecting my vega wallet
- [ ] I can see if the address I have entered is invalid (i.e. wrong number of characters)

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info

Initially this was intended to prevent a user associating to a wallet they did not own. By requiring the wallet was connected we guaranteed that the user had access to the wallet that they wished to use. This should be the default for users that are new to vega but gets in the way of more advanced users performing things the way they wish to.

**Comment by edd** [comment]
Upvote, with some background! I have been going through the validator setup instructions in documentation, and sometimes need some aspects of the token site, but in slightly niche ways.

- I needed to stake some Sepolia Vega from a Metamask wallet (note: not the validator's own Ethereum wallet, just any old Ethereum wallet) to the validator's Vega pubkey
- I could not run a wallet on the node without setting up HTTPS - as sandbox.token is served on HTTPS, http at a remote IP counts as mixed content

So I had the Vega key I wanted to stake to, and I had a Metamask account connected to the token site with the requisite amount of Vega. But I couldn't get to the 'Approve contract' and 'Stake' form because I had to have a Vega wallet connected.

In the end I fixed it by running a local wallet, connecting it, approving the contract, then switching over to Etherscan to call the contract myself with the correct details. All possible, just.. hacky.
