### ISSUE TITLE
Improve JSON viewer readability and affordance

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#1936]
## Story

As a visitor to block explorer 
I want information stored in JSON format to be readable and accessible
So I don't have to scan and interpret JSON formatting to find what I seek

## Acceptance Criteria

- [ ] It's clear how deeply nested each group and item is
- [ ] Clear affordances for opening/closing groups:
  - [ ] I understand groups can be opened/closed
  - [ ] I understand exactly what content will shown/hidden when I open/close a group
- [ ] Where feasible, field names and values are formatted for readability

## Tasks
(Some of these may have already been implemented in https://github.com/vegaprotocol/frontend-monorepo/issues/1416, delete as appropriate)

- [ ] Consider if an indentation line is necessary for 'top level' items (when there are groups at the top level, but no fields at the top level, you see two indentation lines for one item, which looks odd)
- [ ] Open and close icons (chevrons or plus/minus icons, TBC) change depending on the state of the group
- [ ] Indent headings to the same level as their child elements
- [ ] Convert field and group names from camel case to sentence case
- [ ] Coloured indentation lines
- [ ] Format dates in a human-readable manner, consistent with date formatting elsewhere in Block Explorer
- [ ] Implement mouseover states for groups (using headings, indentation lines, and other appropriate cues to indicate exactly what will be opened/closed)
- [ ] Team review

## Sketch
[Figma design](https://www.figma.com/file/CRNfp3wtC29lIr3ctcWVe9/Block-Explorer?node-id=1654%3A5619)

## Additional details / background info
- This ticket suggests enhancements to the MVP component created in https://github.com/vegaprotocol/frontend-monorepo/issues/1416
