### ISSUE TITLE
Tidy up staking page to visually prioritise the list of validators 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1951]
## The Chore
On the staking page, you need to do a lot of reading to find the primary content - the list of validators. This chore is essentially a visual design "tidy up" on the components. 

Assumption is we don't touch the wallets on the right hand side right now. 

There is a flow to consider, connecting your wallet, associating, staking... this was a stepped flow before -> get an ethereum wallet, get ethereum, associate with a wallet, choose a validator to stake... 

## Sketch 
<img width="844" alt="Screenshot 2022-11-03 at 12 42 16" src="https://user-images.githubusercontent.com/46783148/199723305-2bfcb80c-22a0-4e45-9df7-363fe6a9c22c.png">

## Tasks

- [ ] Collapse / hide the "How does staking on Vega work" section
- [ ] Place the title "validator nodes" directly above the actual table of validator nodes 
- [ ] De-emphasise (but keep visible) the epoch run down 
- [ ] Reduce / move footer content again to give more space for the actual content
