### ISSUE TITLE
Set up LP Dashboard in new validator test network 'sandbox'

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1952]
## Task

Configure and set up apps for the new validator test network 'sandbox'

URL from Fryd https://n01.sandbox.vega.xyz/
Here is the PR they have created for the sandbox genesis https://github.com/vegaprotocol/networks-internal/pull/149

## Tasks 
- [ ] Create .env files
- [ ] Create netlify app building from release branch
- [ ] Configured required Netlify env vars
- [ ] Configure domain for console.sandbox.vega.xyz

Note: LP dashboard doesn't have a custom domain yet

**Comment by ckpringle** [comment]
Is this done @pennyandrews

**Comment by pennyandrews** [comment]
No, I do not believe it is as it doesn't have a domain and we haven't release it to anyone external and therefore it's not needed on the validator sandbox. It should be kept in the backlog but right at the bottom as a reminder we will need to do this at a point we release it, IF it ends up being released as a standalone app. If it gets swept up into the website or other app then this becomes invalid and could be deleted

**Comment by JonRay15** [comment]
I dont see why we need this.

Sandbox will probably not have markets on it for the most part.  Can be descoped.

**Comment by JonRay15** [comment]
We definitely arent doing this. Closing completely.
