### ISSUE TITLE
Check frontend apps work on Stagnet1 RC after core release

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1959]
## The Chore

There is a core release planned to Stagnet1 RC imminently. When we have confirmation that this release is complete, it will be important for each team to do a run through of their app to check that all key features are functioning as expected  

## Tasks

**Console**
- [x] Run through app to verify that all key features are functioning as expected
- [x] Create and prioritise tickets for any issues found 
- [x] Notify Gordon of the outcome in Slack

 **Block Explorer**
- [x] Run through app to verify that all key features are functioning as expected
- [x] Create and prioritise tickets for any issues found 
- [x] Notify Gordon of the outcome in Slack

 **Token Frontend**
- [x] Run through app to verify that all key features are functioning as expected
- [x] Create and prioritise tickets for any issues found 
- [x] Notify Gordon of the outcome in Slack

 **Desktop Wallet**
- [x] Run through app to verify that all key features are functioning as expected (in particular the version compatibility stuff)
- [x] Create and prioritise tickets for any issues found 
- [ ] Notify Gordon of the outcome in Slack
