### ISSUE TITLE
Overall asset totals for rewards

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#1968]
## Story

As a user 
I want to understand how much I have earned in rewards overall 
So that I have a better idea of just how profitable my activity on Vega has been 

## Acceptance Criteria 

- [ ] I can see a total of what I've earned, per asset
- [ ] I can see that this is just since the last chain reset and will eventually persist (a requirement on core)

## Tasks 

- [ ] Sketch to include how this would change once we have reward type totals...  
- [ ] Design
- [ ] Implement
- [ ] Test
- [ ] Etc.
