### ISSUE TITLE
OrderSubmission transaction

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2010]
# Tasks

- [ ] sha-256 signature to get id
- [ ] fetch order details
- [ ] render order details

Acceptance Criteria defined in the EPIC https://github.com/vegaprotocol/frontend-monorepo/issues/2082

**Comment by pennyandrews** [comment]
The blocking core ticket is now done and deployed to stagnet3 so may not be blocked anymore @edd what do you think?

**Comment by edd** [comment]
No longer blocked on any network 🥳
