### ISSUE TITLE
Block Explorer on Mainnet

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2012]
## Tasks

- [x] Get familiar with the BE APIs 
- [x] Get an understanding of what isn't working on mainnet (and why) - blocks, genesis parameters, oracles, status
- [ ] Work with Merlin to resolve issues around apis in mainnet

## Additional details / background info

Merlin is working on this https://github.com/vegaprotocol/ansible/issues/323
