### ISSUE TITLE
SPIKE: Transaction views

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2013]
## The Chore

There are ~14 different types of transactions that we ultimately need to display details for, therefore we need to get an understanding of what they are and what data is available and establish which are most important to implement 

## Tasks

- [x] Collate and prioritise the full list of transaction types
- [ ] Understand what data is available for each transaction type
- [ ] Create tickets in the backlog for the display of each transaction type in the UI

## Additional details / background info

Emil already collated the list of transaction types here https://github.com/vegaprotocol/vega/blob/develop/protos/sources/vega/commands/v1/transaction.proto#L37-L66

**Comment by edd** [comment]
Now replaced by more specific tickets
