### ISSUE TITLE
Remove apollo client fields from token

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2015]
## The Chore

We need to remove the current client fields from the apollo client in token.

## Tasks

- [x] Remove all client fields
- [x] Regenerate types
- [x] Fix typescript errors
- [x] Use format number functions instead

## Additional details / background info
 These were initially an experiment however we have handled this better with format number functions in the trading app and it is confusing to understand and read.
