### ISSUE TITLE
Focus site navigation / sign posting and language on Governance

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2033]
## The Chore

To surface the most important and interesting things we will reorient "Token site" to be a governance site. This chore is to first update the existing content / pages to reflect this change.

The interim structure would therefore be:

- Governance Proposals
- Validators & Staking [TBC: is this one or two pages]
- Rewards
- VEGA Token (token home)
- - Supply and vesting 
- - Withdraw assets 
- - Redeem vested tokens [maybe not in nav. though???]

## Acceptance Criteria 

Top level navigation contains, in order: 
- [x] Governance Proposals
- [x] Validators and Staking
- [x] Rewards
- [x] VEGA Token
- [x] Vesting (to be combined under token with https://github.com/vegaprotocol/frontend-monorepo/issues/2093
- [x] Withdraw (to be combined under token with https://github.com/vegaprotocol/frontend-monorepo/issues/2093
- [x] "Governance Proposals" links to the current governance page 
- [x] "Validators and Staking" links to the list of validators page
- [x] "Rewards" links to the current rewards page
- [x] The current token focussed homepage becomes the home page for the "VEGA Token" section
- [x] "Vesting" links to the tranches page that's currently not in the nav 
- [x] "Withdraw" links to the withdrawal page
- [x] "Redeem vested tokens" links to the redeem page [if it's in the nav...]
- [x] All pages linked from the top level nav bar have a useful and functioning version that works with no wallets connected

## Tasks

- [ ] ...

## Background 

Epic https://github.com/vegaprotocol/frontend-monorepo/issues/2070

**Comment by pennyandrews** [comment]
Latest designs https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=1666%3A11630&t=JsNrRLOSZ3Fq8ev9-0

**Comment by joellecharlotte** [comment]
Here is how we envision the navigation working across the breakpoints. On XSM ↳ MD the nav collapses into a drawer which when tapped, opens the menu. If on "Token" then the sub items are exposed by default showing the currently selected item.

There may be some slight styling tweaks to the active and inactive states of the dropdown items (colour or underline) once I review with @bigfandavid but should be minor, and I'll review with him tomorrow morning.

![Governance Navigation](https://user-images.githubusercontent.com/113684458/204790146-0a36a303-0e25-461d-9cdd-6f53952cdcc9.png)
