### ISSUE TITLE
Governance home

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2034]
## Story

As a user
I want to understand the purpose / use of the governance site and the current level of activity
So that I can immediately understand what I can do here

## Acceptance Criteria

- [ ] I can see key information / data on governance activity right now 
* Recent / active governance proposals / no. of active proposals
* Staking / delegation / validator high level info e.g. total number of validators, no. of consensus validators, no. of standby validators, no. of candidate validators 
* Summary token stats relevant to governance 
- [ ] There is an explanation of how the network is governed, that Vega is a proof stake network and how it is governed 
- [ ] I can get to the relevant docs for governance, staking from here 
- [ ] I can usefully see the content with no wallets connected

## Tasks

- [X] Explore and sketch
- [X] Team and stakeholder review
- [x] Visual Design
- [x] Team review to finalise designs and ensure they cover everything they need to
- [ ] Implementation
- [ ] Share for QA
- [ ] Etc.

**Comment by neildawson** [comment]
Homepage proposal, checked with Dex, Barney, and Calum:

![Image](https://user-images.githubusercontent.com/1080322/203749855-cc21c157-d2d3-4a37-9a6d-58c3ffdafb1b.png)

[Also on Miro](https://miro.com/app/board/uXjVPUTU6m4=/?moveToWidget=3458764539435680508&cot=14)

**Comment by pennyandrews** [comment]
Figma link for the design https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=1745%3A9847&t=taGThim6IOG1wEBC-0
