### ISSUE TITLE
Deploy frontends for validator testnet

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2066]
## Task

Configure and set up apps for validatornet (mainnet, decentralised, release candidate)

### Common Tasks
- [x] Create a release branch `release/validatornet`
- [ ] Get data node configuration for validator testnet
- [ ] Ensure that validators are running SSL enabled data nodes

#### Token
- [x] Create .env files
- [x] Create netlify app building from release branch
- [x] Configured required Netlify env vars
- [x] Configure domain for token.validatornet.vega.xyz

#### Block Explorer and 
- [x] Create .env files
- [x] Create netlify app building from release branch
- [x] Configured required Netlify env vars
- [x] Configure domain for explorer.validatornet.vega.xyz

#### Console
- [x] Create .env files
- [x] Create fleek app building from release branch
- [x] Configured required Fleek env vars
- [x] Configure domain for console.validatornet.vega.xyz

### Decide if we need

- [x] Multisig Signer - we now have one that is compatible with the validator testnet
- [X] Stats - already done
- [X] Console-Lite - not supporting any longer
- [X] Liquidity Provision Dashboard - not needed as moving into vega.xyz

Note: LP dashboard doesn't have a custom domain yet

### Additional info
We are planning on running an incentive on the validator testnet, we will need frontends for that.
