### ISSUE TITLE
EPIC: Reorient governance and token site around governance

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#2070]
## Story

- As a particpant in the Vega network or interested party I want to understand all aspects of Vega on-chain governance in one place
- As the Vega project we want to direct attention to on-chain governance proposals, the validators and decentralisation, and make these easy to discover and more prominent than the ERC20 token/asset that powers them

## Summary

To surface the most important and interesting things for most visitors, and to make it easier for new entrants to the Vega community to participate in governance, we will reorient the "Token site" (token.vega.xyz) to be a governance site. This will also change the focus from a site related to the token asset that includes other fnctons like staking and governance because they are "utilities" of the token to a site that is about the governance of the Vega network, which includes on-chain governance proposals and validator election by delegation, and also has a section about the token which powers these activities.

The new structure would therefore be [all subject to discussion]:

- Vega Governance (governance home/summary)
   - Governance Proposals 
   - Validators & Staking [TBC: is this one or two pages]
   - Rewards
   - VEGA Token (token home)
      - Supply and vesting
      - Withdraw assets [can there be a re-staking flow?]
      - Redeem vested tokens [maybe not in nav. though???]

## Acceptance Criteria

- [ ] The site is available at governance.vega.xyz https://github.com/vegaprotocol/frontend-monorepo/issues/2088
- [ ] The site at token.vega.xyz redirects to governance.vega.xyz/token https://github.com/vegaprotocol/frontend-monorepo/issues/2088
- [x] Site name is changed to "Vega Governance"
- [x] Site homepage is a page that simmarises:
  - [x] recent/active governance proposals
  - [x] staking/delegation/validator high level info
  - [x] summary token stats relevant to governance
- [x] The top level nav bar contains, in order:
   - Governance Proposals
   - Validators & Staking 
   - Rewards
   - VEGA Token
- [x] "Governance proposals" links to the current governance page
- [x] "Validators & Staking" links to the list of validators [is there one page for the list of validators and one for staking or are these combined?]
- [x] "Rewards" links to the rewards page
- [x] The current token focused homepage becomes the home page for the "VEGA Token" section
- [x] Under VEGA token is a submenu/nav with:
   - Supply and vesting
   - Withdraw assets
   - Redeem vested tokens [is this in the nav?]
- [x] "Supply and vesting" links to the tranches page that's currently not in the nav
- [x] "Withdraw assets" links to the withdrawal page
- [x] "Redeem vested tokens" links to the redeem page [if it is in the nav...]

**Comment by JonRay15** [comment]
All looks good .. only comments my side:

- Would the homepage also have high level stats on rewards similar to the page on vega.xyz or do we leave that for now?

- Validators & Staking I think would just be the validator page we're reworking now, with the click through the each validator details where you actually stake; that seems the lowest effort for now I think?

- Rewards - I think we said at some point there should be a withdrawals option here too, because you may wish to withdraw multiple asset types than just the "token", I guess the token would have similar sub-nav to withdraw specifically vega rewards, but it might not even need to if it was covered above

We should also have an AC in here about ensuring that the vega wallet connect is removed as a prerequisite to see pages everywhere (unless genuinely essential).
