### ISSUE TITLE
EPIC: Transaction detail views

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2082]
## Story

As a user
I want to see the details of my transactions
So that I can prove the transaction occurred, understand what happened and show / share / evidence it

## Acceptance Criteria

- I can see a summary of key transaction information presented in a consistent way
- I can see UI components (not json) for the details of the transaction
- I can click on links to other detail views for data that we have elsewhere on block explorer i.e. party details of the submitter 

## Stories to be completed

- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2108
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2109
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2110
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2111
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2112
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2113
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2114
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2115
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2116
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2117
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2118
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2120
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2121
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2122
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2123
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2124
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2125
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2126
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2127
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2128
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2129
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2130
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2131
- [ ] https://github.com/vegaprotocol/frontend-monorepo/issues/2119

**Comment by edd** [comment]
Closing as there is no known end date and there will always be more transactions and more changes to make to existing transactions
