### ISSUE TITLE
Show basic oracle profile info in markets

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#2086]
Depends on #3224 

## Story

As a trader interested in entering a market
I want evidence of the market oracle's reputation
So I can decide if it is trustworthy

## Acceptance Criteria

- [ ] I can see the following oracle information in market info:
  - [ ] Name
  - [ ] Status
  - [ ] Number of verified proofs
  - [ ] Number of markets participated in
  - [ ] Link to Twitter proof (if available)
  - [ ] Link to website proof (if available)
- [ ] I can click the oracle name to navigate to the oracle spec file in the `well-known` repo (note that in a future ticket this link will instead open a modal with more oracle info)
- [ ] The short oracle profile is a reusable component which can be used in other apps (Governance will be using it soon)
- [ ] I can see different states for each type of status code:
  - [ ] Unknown
  - [ ] Good
  - [ ] Negative statuses (suspicious, malicious, compromised)
  - [ ] Retired
- [ ] If there are two oracles (for settlement and termination, respectively, I can tell which is which

## Tasks

- [ ] Expand the functionality of the oracle library (created in https://github.com/vegaprotocol/frontend-monorepo/issues/3224) so it can also parse the contents of the file, and return the desired information (see acceptance criteria)
- [ ] Implement the "short" oracle profile as a component which can be reused in other apps, like Governance, including states for each possible status code
- [ ] Share deploy preview link with Joelle and Neil
- [ ] QA

## Sketch
See [Miro board](https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764536859308772&cot=14).

## Design

See [Joelle's comment](https://github.com/vegaprotocol/frontend-monorepo/issues/2086#issuecomment-1496291122)

## Additional details / background info
- This ticket is dependent on
  - the task "Visual design → Short oracle profile" from the epic: https://github.com/vegaprotocol/ux-and-visual-design/issues/79
  - https://github.com/vegaprotocol/frontend-monorepo/issues/3224
- Oracle profiles will be located in the repo here: https://github.com/vegaprotocol/well-known/tree/main/oracle-providers

**Comment by neildawson** [comment]
Thoughts on how we could break this down:

1. The smallest thing:
  - Move the oracle section up to be the third item in the market info tab
  - Add a link to the oracle spec file (if it exists) on GitHub
2. Implement the profile stub in the market info tab, to pull in the most crucial bits of info
4. Implement warning banner on markets, to draw attention to dastardly behaviour
3. Implement the full profile (in the modal)
5. Implement oracle status in market lists

Note visual design is not included in this list, as that has to happen before point 2 regardless, and all of these bits should be designed at once so they are complementary.

**Comment by neildawson** [comment]
Matt and I met and agreed there are some subtasks. In ticket 1 above we'll need to make the library to seek and parse the files from GitHub. In each subsequent stage we'll need to add functionality to that library.

Neil to make these into tickets (tag Matt particularly in item 1).

**Comment by joellecharlotte** [comment]
Please see attached the proposed designs for the Oracle in the INFO tab and the various statuses it can have. 

- Each status has a colour + icon
- We've defined some rules around how links display ie. ideally the proofs fit on one line but if the links are too long then stack them. In Console we only show the top two proofs.

[Figma link here ↳ ](https://www.figma.com/file/wBu1KViEZz1JkwpOmhFQrO/Console-V2?node-id=1841%3A11084&t=2ObJHUVylRVsagsV-1)

It might be useful for context to see the proposed Oracle Detail Pages and compare what info is exposed in the Console Accordion vs what is exposed when you (in future) are able to click to view details. 

These designs are in the Governance Figma: [Figma link](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=2502%3A14216&t=U4WmgcydlTw2i3nf-1)

<img width="2155" alt="Info Tab with Oracle" src="https://user-images.githubusercontent.com/113684458/229860297-3352e524-ce6b-4b62-bb5e-98c5af0bf11f.png">
<img width="2706" alt="Oracle Statuses" src="https://user-images.githubusercontent.com/113684458/229860314-ff86a643-2cc9-41ff-9ca9-d6b1c4ce3b28.png">
