### ISSUE TITLE
Site is moved to governance.vega.xyz (and governance.fairground.wtf .... all environments)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2088]
## The Chore

Should do this when Alpha mainnet is launched

What we need to achieve and who for

## Tasks

- [ ] Site is available at governance.vega.xyz 
- [ ] The site at token.vega redirects to governance.vega.xyz/token
- [ ] Site name is changed to "Vega Governance"
- [ ] All variations of URLs
- [ ] Redirects from token.vega.xyz URLs to the relevant governance.vega.xyz URLs 

## Additional details / background info
Epic https://github.com/vegaprotocol/frontend-monorepo/issues/2070

**Comment by pennyandrews** [comment]
Duplicates #2425
