### ISSUE TITLE
Reorganise token features into sub navigation

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2093]
## The Chore

- [ ] There is a Token Home with existing landing page content
- [ ] Under VEGA token is a submenu / nav with: 
* Supply and vesting
* Withdraw assets 
* Redeem vested tokens (not in nav though? Or?)
- [ ] "Supply and vesting" links to the tranches page that's currently not in the nav 
- [ ] "Withdraw assets" links to the withdrawal page
- [ ] "Redeem vested tokens" links to the redeem page [if it's in the nav...]
- [ ] There is a useful and functioning version that works with no wallets connected

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by joellecharlotte** [comment]
A little bit of repetition with ticket [2033](https://github.com/vegaprotocol/frontend-monorepo/issues/2033) :)

On XSM ↳ MD the nav collapses into a drawer.
Any sub-items are exposed by default with the current page nav item set as active

There may be some slight styling tweaks to the active and inactive states of the dropdown items (colour or underline) once I review with @bigfandavid but should be minor, and I'll review them with him tomorrow morning.

[Figma link here ↳](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=1712%3A8401&t=wnPgBNeph7GCiYbt-1)

![Token Sub Nav](https://user-images.githubusercontent.com/113684458/204791201-757e56ee-a2ed-4b92-8ce0-a2d98c2d5fe5.png)
