### ISSUE TITLE
Spike: Collapse "the wallets" into a connect wallets interaction like uniswap

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2094]
To investigate collapsing the wallets that currently take up a lot of the screen into an interaction so that the main focus - the governance proposal list, the validator list - is on the content, but that you always have the ability to connect your wallets to see your associated balance / associate more tokens.

E.g. https://app.uniswap.org/#/vote

## Tasks

- [x] Show how the wallet drawer could remain pinned open, like a toggle, at very large viewport widths
- [x] Design pending transaction animation (spinny or glowy or something!)
- [x] Mockup in Light Mode
- [x] Align tabs used to tabs used in Console (and dApp wide)

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/202184106-466a2d97-9920-48ba-9db6-b83fa63c9673.png)

We would likely want to expand the wallet automatically when you initiate some flows
Might need to link to things like associate in other ways / places if we are collapsing / hiding the wallet stuff to ensure all the sign posting is still there and good

**Comment by bigfandavid** [comment]
Perhaps the two options should somehow be visually separated (exactly how TBC)


![Image](https://user-images.githubusercontent.com/113683891/203276101-b11d3167-18e1-4586-a86d-f8886700b51d.png)

**Comment by joellecharlotte** [comment]
@neildawson 

[Here is the exploration](https://www.figma.com/file/DUHzxECUu0Pe1TyRI4wL4C/dApp-Navigation?node-id=1948%3A2440&t=DTZyW03fxrp9HmJd-1) I did around these questions: 

- Can we fit an extra bit of info (e.g. balance, or public key) in a wallet button in the nav bar
- How do we signal pending transactions in the wallets when it’s just an icon
- Can we signal none/some/all wallets are connected via the icon
- How does the drawer look when it has tabs inside it for the two wallets

When we're back - let's go through it all together. Pasting it here for my 2023 brain and will tidy up this task once we have a more complete direction.

**Comment by neildawson** [comment]
@joellecharlotte I just added a couple of things as tasks to this ticket so it was written down somewhere. I think those are the last things we'd need before we could start building.

**Comment by joellecharlotte** [comment]
Thanks @neildawson 

This is done, would love to run through this with you when you're back.
