### ISSUE TITLE
JSON component styling corrections

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#2096]
## The Chore

The new component for displaying JSON data (as seen on transaction details pages) needs some changes to match the Figma designs

## Tasks

- [ ] The heading “Transaction CnoI2...YjZiNGQyM2” is 48pts, should be 56pt. In the Design System, this is the “Heading L” style.
- [ ] The grey container behind the copy icon is different to the Figma. Design has been updated to use #404040 / $dark-200. Also needs a 5px rounded corner.
- [ ] The heading: “Order submission…” is 36pts, should be 40pts. In the Design System, this is the “Heading M” style.
- [ ] The expanding headings should be UPPERCASE and 24pt (not 20pts). In the Design System, this is the “Heading S” style.
- [ ] The spacing below the expanding headings and the related values feels a bit tight, it should be 24px (currently ~19px)
- [ ] Remove the object and array tags
- [ ] The “All Transactions” back link should be “All transactions” i.e. Sentence case, not Title Case (though this is something we should agree on globally and define somewhere)
- [ ] The line-height of the values seems a bit high, but when I inspect the css it seems correct ie. it’s 16px font size with 24px line-height. Is there additional spacing being added between each line or does each line have a hard return (new paragraph return) rather than a soft return (new line return) perhaps?

## Additional details / background info
- Tasks pulled from [this Slack thread](https://vegaprotocol.slack.com/archives/C0473D9HN05/p1668603443603739?thread_ts=1668594327.579759&cid=C0473D9HN05)

**Comment by edd** [comment]
Bumping out of the sprint because this ticket is lower priority than adding transaction views
