### ISSUE TITLE
ChainEvent transaction (validator)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2124]
Like transaction views, Chain Event views are a rabbit hole. Like transaction views, an exciting rabbit hole!

Chain Events (see: https://docs.vega.xyz/testnet/api/rest/explorer/block-explorer-get-transaction)

# Tasks: Build a details view for each of
- **builtin** object
  - [x] deposit object
  - [x] withdrawal object
- **erc20** 
  - [x] assetDelist object
  - [x] assetLimitsUpdated object
  - [x] assetList object
  - [ ] bridgeResumed Bridge operations has been resumed
  - [ ] bridgeStopped Bridge operations has been stopped
  - [x] deposit object
  - [x] withdrawal object
- **erc20Multisig**
  - [x] signerAdded object
  - [x] signerRemoved object
  - [x] thresholdSet object
- **stakingEvent** 
  - [x] stakeDeposited object
  - [x] stakeRemoved object
  - [x] totalSupply object

# Extra
- [ ] Custom label for each of the above in tx list
- [ ] Custom label for each of the above in block details
