### ISSUE TITLE
Create Oracle repo

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2135]
## Story

As a oracle provider
I want to submit my oracle to Vega with my proofs
So that users of the oracle can see how trustworthy it is

## Acceptance Criteria

- [ ] There is a way to provide a public key for the oracle(s)
- [ ] There is a way to provide proofs of ownership links i.e. a link to a tweet
- [ ] There is a way to provide a name for the oracle and description with markdown text 
- [ ] I can find instructions as to what goes in this repo

## Tasks

- [x] Agree if each Oracle have its own file? 
- [x] Agree a naming convention i.e. what is the file name - the public key?
- [x] Create a repo for "Oracles" (and decide where it needs to be)
- [x] Create a readme with what needs to be in the file - the instructions 

## Additional details / background info

Dependent on https://github.com/vegaprotocol/ux-and-visual-design/issues/79

**Comment by JonRay15** [comment]
Repo has been created here 

https://github.com/vegaprotocol/well-known

Needs review and needs readme to be built out

**Comment by neildawson** [comment]
Draft readme has been reviewed with Jon and Barney and can be found in [the "readme" branch of the repo](https://github.com/vegaprotocol/well-known/tree/readme).

**Comment by pennyandrews** [comment]
@ckpringle @neildawson @JonRay15 I think this one is done too, no? Can we close it?
