### ISSUE TITLE
Oracle verification process

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2136]
## Story

As a voter on new markets
I want to know if an oracle's identity has been verified
So I can decide if it is trustworthy

## Acceptance Criteria

- [ ] The community is in control of adding and removing verified status(es) from oracles
- [ ] The oracle verification process is (as) secure (as is feasible) against tampering and bad actors

## Tasks

- [x] Explore the process of approving changes to an oracle's status
  - [x] Who approves changes to oracle status?
  - [ ] Does GitHub support a robust process for managing this status?
  - [x] How and where will the statuses will be stored and managed? Is it in the same file as the oracle profile and proofs? will there be a separate file?
- [ ] Team and stakeholder review

## Additional details / background info
- Dependent on
  - https://github.com/vegaprotocol/ux-and-visual-design/issues/79
  - https://github.com/vegaprotocol/frontend-monorepo/issues/2135

**Comment by pennyandrews** [comment]
Neil has created a straw man [here in miro](https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764540284994519&cot=14) (and [shared in Slack](https://vegaprotocol.slack.com/archives/C03DA0K9YUW/p1670954357865049)) and we need to get heads together to flesh it out and agree the process

**Comment by neildawson** [comment]
Reviewed the process diagram today with @barnabee and Jon Ray. Made some small changes, but broadly agreed on the flow for now. The flow may change when console and governance teams come to work on the tickets and feed back on the feasibility of the system.

**Comment by pennyandrews** [comment]
@ckpringle @JonRay15 @neildawson is this now done? Can we close it?

**Comment by barnabee** [comment]
Closing as I agree with @pennyandrews. Reopen if needed.
