### ISSUE TITLE
Party accounts should have a type & market label

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2138]
The party accounts view is not very informative. 2 extra bits of information would make it much more useful

# Tasks
- [x] Update query to fetch market Id
- [x] Link to market if account related to a market
- [x] Render type of account in the account row

**Comment by edd** [comment]
This was partially done in #2244, but without the market link this ticket isn't realy *closed*
