### ISSUE TITLE
[Explorer] Footer should be at the bottom of the page

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2141]
The footer on explorer should always be at the bottom of the screen height, even if the content within the explorer is not tall enough to fill the screen. This is already true on console and token - just not explorer, which leads to things like this:

![Screenshot 2022-11-17 at 11-10-37 Explorer](https://user-images.githubusercontent.com/6678/202431636-ee355d3d-fb59-4552-aac0-d1bd773faa87.png)

# Tasks
- [ ] Make main container full height
- [ ] Ensure footer is anchored to the bottom
- [ ] No cheating that would make the footer hover over content on long pages

Similar to, but not the same as, #1787
