### ISSUE TITLE
Add intro to landing dialog

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2146]
## Chore
This is to add a title and proposition statement of console to the market popup on first landing. 

E.g. 

> Console
> Trade cash settled futures on the fully decentralised Vega network.

## Acceptance Criteria

- [ ] There is an intro to what console is on the market popup on first opening console
- [ ] There is a variation for Fairground to make it clear you are on the testnet / a safe place to try trading... 

## Tasks

- [ ] Agree words + design (are we using a sylised "console" or VEGA | Console? "web client" doesn't sound great?)
- [ ] Implementation 
- [x] UX to sketch how this would look in the 3 different states/scenarios 
- [ ] Merge risk, landing and no market state dialogues into a single landing dialogue with 3 different states (as part of this work)

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/206685577-8700a8e5-f52c-47fa-a4ee-c58e710b0dc0.png)

See Miro for logic / flow: https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764540864776438&cot=14

## Additional details / background info

It makes sense to do this ticket at the same time as this ticket also in the sprint https://github.com/vegaprotocol/frontend-monorepo/issues/2147

**Comment by pennyandrews** [comment]
Take a look at the words

**Comment by bigfandavid** [comment]
Here's a first pass...

- Table styling informed by most recent work done on Console;
- Noticed some competitors have icons for markets - is this relevant for us? I've designed it in for reference, but can remove easily;

I can design other variations, but please send through and thoughts/comments/revisions :)

![Image](https://user-images.githubusercontent.com/113683891/206706346-6489884c-43f0-46d8-8fde-3ee99fecf6af.png)
