### ISSUE TITLE
Pre populate market change and new market proposals with existing data

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2160]
## Story

As a User
I want to pre populate market change and new market proposals with existing data
So that it is easier for me to create these types of proposals

### Market change

- [ ] I can select market from a list of existing markets for a market change proposal.
- [ ] I can see that after selecting the JSON is pre-popualted with the existing values
- [ ] I can see an error message if I have not changed anything
- [ ] I can submit the proposal and it will be accepted by the network 

### New market

- [ ] I can select market from a list of existing markets for a market change proposal.
- [ ] I can see that after selecting the JSON is pre-popualted with the existing values
- [ ] I can submit the proposal and it will be accepted by the network 

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info

Consider the following script: 

https://github.com/vegaprotocol/documentation/blob/main/scripts/generate_proposals.js produces https://github.com/vegaprotocol/documentation/tree/main/docs/tutorials/proposals/_generated-proposals
