### ISSUE TITLE
Use new graphql types

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2161]
## The Chore

We in the middle of migrating away from the previous code geenration tool to a newer one. We should migrate all token queries to use the new format.

## Tasks

- [x] Find all old queries
- [x] Replace with new file format
- [x] Run generate
- [ ] Fix all type errors
- [ ] Change `__generated___` to `__generated__`

## Remaining

- [ ] Proposals list query
- [ ] Proposal details query
