### ISSUE TITLE
[console]: Update ledger entries columns

### ISSUE THREAD

**Issue by asiaznik** [vegaprotocol/frontend-monorepo#2170]
The ledger entry API is changing

## Tasks

- [ ] Update ledger entry table columns to accommodate renamed query fields
- [ ] Update filter arguments to accommodate renamed inputs
- [ ] Adjust table. 
  - [ ] Add Sender and Receiver columns
  - [ ] Conditionally render truncated partyId or market code (with block explorer links) along with account type in each cell. EG `0x123...345 General`, `TSLA.QM21 Margin`

## Additional information

See backend PR: https://github.com/vegaprotocol/vega/pull/6834
