### ISSUE TITLE
Generate types from swagger

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2176]
Yeah the types in this PR are a little bit lame as they're manually written. I'm going to switch to types generated from the swagger file (https://raw.githubusercontent.com/vegaprotocol/documentation/main/specs/v0.62.1/blockexplorer.openapi.json) - I'll make a ticket for that ⌛

_Originally posted by @edd in https://github.com/vegaprotocol/frontend-monorepo/pull/2152#discussion_r1026545673_
      

# Tasks
- [x] Add a project level script to run https://www.npmjs.com/package/openapi-typescript and use the generated types to replace the hand written ones - done in https://github.com/vegaprotocol/frontend-monorepo/pull/2194
- [ ] Try out Orval in comparison to openapi-typescript
  - [ ] Switch if required

**Comment by notbot00** [comment]
i have a lib for this which is extremely nice to use: https://orval.dev/
check it out, if you like it. it uses react-query, so the generated result's semantics will be super similar to the hooks generated by the graphql codegen, it allows you to be able to just use endpoint specific hooks for requests, all typed.
