### ISSUE TITLE
[explorer] mainnet should use old chain API, not the new one

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2183]
# Task
- [x] Work out how
- [x] For TX details view, fall back to old API if new api fails
- [ ] For Transaction list....?
   - [x] We need a block explorer api fix

Ref: https://github.com/vegaprotocol/vega/issues/6870

**Comment by edd** [comment]
Fixed by redeployment of BE. No dev work needs to happen on explorer.
