### ISSUE TITLE
[console] NotFound error handling

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2200]
Core has made API changes where not found resources return an error object (with type `NotFound`). Our error handling is often crudely just checking for the presence of an error object when we should also be checking the error type and handling it differently.

## Tasks

- [x] Update AsyncRenderer to handle NotFound errors
- [x] Review usage of errors returned from data providers, useQuery hooks, and useGeneratedQuery hooks and update error handling accordingly
- [x] Update apollo client error link to not report not found errors
