### ISSUE TITLE
Spike: How to integrate into website

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2207]
It has been decided that the LP Dashboard should become part of the vega.xyz website rather than a stand alone application.

The dashboard has been built as a React app within the frontend-monorepo and utilises some shared libraries that are currently within that repo and not currently published for use as a dependency outside of it. 

This spike needs to explore the different options available to us to achieve this desired integration, the relative 'costs'/benefits (or impact v effort) of each and make a decision on how to proceed. **(as website project lead, Rebecca will be looking for the quickest, cheapest way forward without compromising what we are trying to achieve and should be part of the 'approval process')**

At the different ends of the scale we are looking at:

Full integration - rip the code out of the frontend-monorepo, put it in the vega.xyz repo and do everything we need to do to make it work as a genuine part of the website likely including needing to publish shared libraries in the frontend monorepo etc.)

Smoke and Mirrors - we could leave the app where it is and somehow embed / link to the page replicating headers and footers etc. to give the impression of it being part of the site when it's actually not

But there are likely in between options and variations of the above.

# Tasks

- [ ] Facilitate a call with Ciaran, Matt, Dex, Edd and Oli to flesh out and assess the options
- [ ] Share conclusions in Slack for other frontend leads and stakeholders to feedback / input / approve
- [ ] Make a final decision on the tech approach
- [ ] Write/refine a ticket(s) that capture the approach and work needed ready for sprint planning
