### ISSUE TITLE
Allow downloading of proposals on proposal forms

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2211]
## Story

As a User 
I want to be able to download the JSON of a proposal
So that I can post it on the forum and itterate on it

## Acceptance Criteria

- [ ] I can see a download button
- [ ] I can create a proposal without a wallet connected
- [ ] I can see the submit button is disabled if I am not connected to my Vega wallet

## Tasks

- [ ] Add button
- [ ] Ensure works without being connected to a vega wallet

## Additional details / background info

- #2205
