### ISSUE TITLE
Really simple example API integration examples

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2222]
## The Chore

As a market maker / trader / liquidity provider looking to implement a strategy via API
I want to see examples of API integrations in use 
So that I can check that I've set my environment up successfully 

## Acceptance Criteria 

There is a code sample of an API integration demonstrating how to connect to data node and read part of the APIs - get Vega time or see a list of current markets for example, and another example that sends an order for a given wallet and reads it back, in prioritised languages e.g.
- [ ] Golang
- [ ] Java
- [ ] Javascript 
- [ ] Python
- [ ] C#
- [ ] Rust
- [ ] Others?

## Tasks 
- [ ] Refine shortlist of languages required 
- [ ] Agree who can do what
- [ ] Create code samples
- [ ] and then what?
- [ ] Etc.

## Additional details / background info
Had previously talked about other candidates... specifically including how you might stream the order book, sign and submit transactions and read the result, and submit a query to get your position

**Comment by dexturr** [comment]
@ckpringle This doesn't seem like an FE ticket, probably should be tracked in x-func planning rather than here?

**Comment by pennyandrews** [comment]
Scratch that, @edd says Lewis, Tom, Charlie or Witold have been working on API stuff for market makers and LPs, more along the lines of writing libraries to make their lives easier so would be more familiar with those APIs

**Comment by JonRay15** [comment]
I just dont think this is going to happen ,...... I'm closing it
