### ISSUE TITLE
Add distressed amount to liquidity view

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2224]
## Story

As a potential liquidity provider
I want to see how distressed the existing liquidity providers are 
So that I can assess whether there might be an opportunity to provide liquidity here

## Acceptance Criteria

- [ ] I can see a distressed amount per liquidity provider when they have dipped into their bond to meet their liquidity commitment (an LP is distressed when their bond amount minus committed liquidity returns a negative number)
- [ ] There is a visual indicator that the LP is distressed e.g. colour / flag / minus symbol 
- [ ] There is an explanation for this distressed status "The amount the LP has dipped into their bond to meet their liquidity commitment"

## Tasks

- [ ] Decide on how to display this information - is it a column of its own in which case, what do we call it / how do we display the figure when it's not distressed, or do we combine with another field / status icon etc.
- [ ] Implement 
- [ ] Test
- [ ] ...

## Additional details / background info
Originally came up in the work on the liquidity dashboard.

**Comment by pennyandrews** [comment]
We will be reviewing the value, details and priority of this ticket, and others, to do with surfacing Liquidity data with Jon and Lewis next week to decide if / how to move forward on it.

**Comment by pennyandrews** [comment]
Lewis doesn't think this data is massively valuable to existing LPs, but for traders that are doing a LOT of trading on a market, knowing that the LP is distressed might make them want to provide liquidity (undercutting the fee) in order to ensure the market stays active and they can continue to make money. 

Not sure how to calculate (will need help from David / Barney for this), but showing some kind of percentage that shows how over committed an LP is would be useful.
