### ISSUE TITLE
Restaking journey

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2240]
## Story

As a user who has already staked validators
I want to easily stake to the same validator and / or a different one
So that I can continue to support who I want to validate transactions on the network

## Acceptance Criteria

- [ ] When I associate tokens with my Vega wallet, there is an easy way to use those to stake the same validator as I have already
- [ ] When I associate tokens with my Vega wallet, I can easily choose a different validator to stake with my newly associated tokens 
- [ ] I can easily increase my stake for existing nominated validators

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info

Currently, if you already have $VEGA tokens nominated to validators, your newly associated tokens will automatically be nominated to the same validators, in the same proportion.
