### ISSUE TITLE
Retire usage of old chain explorer

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2241]
`NX_CHAIN_EXPLORER_URL=https://explorer.vega.trading/.netlify/functions/chain-explorer-api`

This API is used in one place. It's not actually required any more now that we have the block explorer API, but is still in use.

# Tasks
- [ ] Remove usage of this API in `txs-per-block` component
- [ ] Remove env vars from all configs
- [ ] Remove flag variable
- [ ] For @gordsport: As part of this issue would you be able to advise on the changes required to the vega capsule[ front end config](https://github.com/vegaprotocol/vegacapsule/blob/main/net_confs/config_frontends.hcl#L111).
  - [ ] Work out if both .hcl files are require or if the one in 
  - [ ] Rationalise the env vars in both
  - [ ] Remove NX_ for the old chain explorer
- [ ] Fix `tx-order-type` to only have one `Command` type

# Follow up tasks
- [ ] Back port fix to mainnet
- [ ] Re-archive github.com/vegaprotocol/explorer
- [ ] Remove associated netlify app

**Comment by gordsport** [comment]
Hey @edd 
As part of this issue would you be able to advise on the changes required to the vega capsule[ front end config](https://github.com/vegaprotocol/vegacapsule/blob/main/net_confs/config_frontends.hcl#L111).

**Comment by edd** [comment]
Unblocked - stagnet3 has the signatures field, so I can proceed
