### ISSUE TITLE
Remove request and get permission calls to Vega wallet

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2249]
The client.get_permissions and client.request_permissions methods are being removed from the wallet json rpc api

## Tasks

- [x] Remove usage of `client.get_permissions`
- [x] Remove usage of `client.request_permissions`
- [x] Ensure the 'requesting permissions' UI is displayed at the appropriate moment which is now when calling `client.list_keys`

## Additional details / background info

Related vega wallet PR:
https://github.com/vegaprotocol/vega/pull/6954
