### ISSUE TITLE
Publishing frontends for Vega Capsule

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2252]
## Story

As a Vega Capsule user
I want to have access to all of the frontend docker containers
So that I am able to specify my required version in the Vega Capsule frontend configuration file 

## Acceptance Criteria

- [ ] Docker containers are generated on the CI when tagging a new version of the app for release

## Tasks

- [ ] Update github action to new tag format
- [ ] Ensure all 3 app containers are generated
- [ ] Find out what we need to do to make Capsule pick up the version tag

## Additional details / background info

Vega capsule allows the user to bootstrap a network using any version of the core, we need to have access to the correct frontend docker containers in order to allow users to choose the correct versions when using the below configuration file:
https://github.com/vegaprotocol/vegacapsule/blob/main/net_confs/config_frontends.hcl

As part of the release process when tagging a new core version Gordon will capture the frontend versions that are compatible with this core version - this will be captured in the release ticket and then Gordon and Candida are working on a process going forward to capture the release matrix to help people work out what version they want to grab to spin up the network they want. 

Use cases:

- Mainnet is on core 63 and I want to create a Vega Capsule network using the associated / compatible frontend, regardless of how much more feature development has happened.
- I want to grab the latest version of the core and the latest version of the frontends

**Comment by gordsport** [comment]
Hey @dexturr 
I think this maybe warrants a new issue, however, since now being able to connect to the correct verison of the token dApp with the vegacapsule using the [frontends config](https://github.com/vegaprotocol/vegacapsule/blob/main/net_confs/config_frontends.hcl)

I change the URL that its pointing to to get the data from stagnet3 to:

http://127.0.0.1:3028/query

This then presents me with the following error:

`This app only works on chain ID: 1440`


It does however seem to work as expected on BE and console (however I have yet to propose a market etc..)
