### ISSUE TITLE
Fail CI if a query is missing a mock

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#2254]
## The Chore

Add check for missing query mocks and fail before e2e test run

## Tasks

- [ ] Add some kind of linting or code analysis tool to detect if queries are missing mocks for tests
- [ ] Add a github action to fail if missing mocks are found
- [ ] Ensure the action runs _before_ the e2e test run so we can fail early
