### ISSUE TITLE
Reorganise mocks

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#2256]
## The Chore

Reorganise mocks to make things clearer

## Tasks

- [x] Propose how we should organise the mocks
- [x] Share with the team for feedback 
- [x] Refine and finalise
- [ ] Implement
