### ISSUE TITLE
Define options to get to true end to end tests

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#2258]
## The Chore

DETAILS TO BE DEFINED.

## Tasks

- [ ] Define and propose options for how to do this
- [ ] Share with the team for feedback 
- [ ] Select / refine and finalise approach
- [ ] Create ticket(s) for the work required to implement the approach
