### ISSUE TITLE
Make a proposal to the team for how to provide cover / be more responsive to the requests that come in to slack from incentives, market sims and other channels

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#2259]
## The Chore

We would like to be more responsive to the requests that come in to slack from incentives, market sims and other channels and ensure the resulting work is captured and prioritised / actioned quickly and effectively. 

## Tasks

- [x] Propose an approach to how we organise ourselves to provide cover and responsiveness 
- [x] Share with the team for feedback 
- [ ] Refine and finalise
- [ ] Create schedule?
- [x] Share the approach in Slack for the wider team's information
- [ ] Start

**Comment by MadalinaRaicu** [comment]
It would be great if we all try to cover in shifts chat activity and support in #project-console-v2 and #incentives or #mainnet-sims channels.   We can either: 

Option 1.  Have one person covering at a time as the primary job is to understand what's being talked about, create a ticket if one hasn't been created by the reporter and establish how critical it is.  As it doesn't have to be that same person that fixes the bug if it's not within their knowledge or skillset, they could ask someone else to pick it up or pair with them. 


Option 2. Split in 3 rotas of two people within the console team to reply and investigate if issues appear. The suggestion is that there are at least two people to cover chat activity, with the hope that this helps with taking decisions like deploying something, review and approve.
We can divide based on timezone and to accommodate personal plans. Being responsive does not mean firefighting alone. Means providing support and perhaps easy solutions for different issues that appear. 
Rota: 
* Perhaps two people from the polish crew in the morning 
* anyone and anyone in the afternoon
* UK and US-based people during UK evening time (because in Poland that is too late)


Also, we reached to a level where kind of everyone is specialized on pieces of functionality across console. So, if someone from that specific rota doesn’t know how to easily fix it, they should know at least a person from the team who perhaps can fix it sooner. So, they should feel comfortable tagging/dm in chat as soon as possible, and then try to figure out the bug. **Don’t debug in silence!**  

My initial proposal was to get at least two people because even if you know how to fix it, you need to have someone to approve and review it quite quickly to get it merged. Or even pair-program. Also, it increases the chances to get that issue sorted and it increases responsiveness in the chat overall.
But, somehow, we need to find a way to balance that with the amount of productive time it takes away from the team as a whole, bearing in mind not all issues that come up need to be jumped on straight away. Also, this should not erode focused coding time.

**Comment by mattrussell36** [comment]
We need to align with Jon Ray on the pager duty setup
