### ISSUE TITLE
Close position toast

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2270]
Depends on https://github.com/vegaprotocol/frontend-monorepo/issues/1679

## Story

**As a** User
**I want** to be notified by toast when closing positions
**So that** I can continue to use the application while waiting for transactions to complete

## Acceptance Criteria

- [ ] I am shown a batch market instruction (close position) pending toast once the tx is sent
- [ ] I am shown a failed to close position toast if the tx fails
- [ ] I am shown a position closed toast if the tx succeeds
- [ ] I am prompted to complete the transaction by dialog
- [ ] I am notified via dialog if the order was rejected immediately by the wallet
- [ ] Toasts are only used to confirm transactions once approved by the wallet, dialog still used for user confirmations
- [ ] The layout of content in the toasts has been considered in line with the design and to fit the new format

## Tasks

- [ ] Get toast working for order submission, edit and cancellation
- [ ] Review the content and layout of the toasts with someone from UX/Design and/or as a team
