### ISSUE TITLE
Order submission, edit and cancellation toasts

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2271]
Depends on https://github.com/vegaprotocol/frontend-monorepo/issues/1679

## Story

**As a** user
**I want** to be notified of order updates by toast
**So that** I can continue to use the app whilst waiting for transactions

## Acceptance Criteria

- [ ] I am shown an order pending toast once an order tx is placed
- [ ] I am shown an order rejection toast if the tx fails
- [ ] I am shown an order success toast if the tx was successful and the order was created
- [ ] I am prompted to complete the transaction by dialog
- [ ] I am notified via dialog if the order was rejected immediately by the wallet
- [ ] Toasts are only used to confirm transactions once approved by the wallet, dialog still used for user confirmations
- [ ] The layout of content in the toasts has been considered in line with the design and to fit the new format

## Tasks

- [ ] Get toast working for order submission, edit and cancellation
- [ ] Review the content and layout of the toasts with someone from UX/Design and/or as a team

**Comment by asiaznik** [comment]
@mattrussell36 I think some of those ☝  ACs are incompatible with what we've actually did - we do not mix dialogs with toasts
