### ISSUE TITLE
Positions view for trading page

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2274]
## Story

**As a** user
**I want** to see a singled detailed position breakdown for the currently viewed market
**So that** I can take more actions and and get more information

## Acceptance Criteria

- [ ] I can see the same information that is available in the current table (notional size, open volume, mark price, asset, liquidation price estimation, leverage, margin allocated, realised/unrealised pnl, timestamp)
- [ ] I can see additional information such as all margin levels (with visualization?)
- [ ] I can perform actions such as
  - close position without closing orders
  - close position with closing orders
- [ ] I can see more information about how my position was affected by market state (loss socialization)

## Tasks

- [ ] Sketch potential solution
- [ ] Discuss and agree with team
- [ ] Socialise the idea with Barney and other key stakeholders
- [ ] Refine and write tickets based on feedback etc.

**Comment by neildawson** [comment]
@mattrussell36 I've added you to this ticket as I think you had a few other use cases or calls to action in mind, and we thought it would be best to consider them all from the outset
