### ISSUE TITLE
Make liquidity provision table more prominent 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2307]
## Story

As a potential liquidity provider 
I want to be able to quickly find the liquidity level on a market and details of the liquidity providers
So that I can more easily find / identify / understand the markets liquidity status (than navigating into market info - liquidity - liquidity provision table) and when navigating from the liquidity dashboard, I can more easily navigate to the market details

## Acceptance Criteria

- [ ] We've added a tab for liquidity beside candles and depth
- [ ] I can always see the target stake and supplied stake for the market 
- [ ] When I select to view the liquidity provision for the market, I can still see active and inactive commitments

## Tasks

- [ ] Answer whether the nested tabs (active and inactive) need to be swapped out for a different pattern e.g. filter drop down (feels wrong but could be a visual designthing)
- [ ] Build
- [ ] Test

## Sketch

<img width="2190" alt="Screenshot 2022-12-02 at 14 21 27" src="https://user-images.githubusercontent.com/46783148/205313864-7a0b1b97-9b34-4b45-81cd-0ccbd5e3eccd.png">

**Comment by pennyandrews** [comment]
Would need to create a new ticket to do first before this to make it possible to link to a specific tab on a page (i.e. in URL params) rather than a page because we link to this page from other places i.e. Liquidity Dashboard
