### ISSUE TITLE
Show rewards and fees earned (wallet connected)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2318]
Implement initially without pagination to avoid being dependent on https://github.com/vegaprotocol/vega/issues/6650

## Story 

As a user who _has_ connected their wallet
I want to see what I have earned in comparison to the total of rewards and fees paid out 
So that I can understand the financial benefits of using Vega

## Acceptance criteria 

- [ ] There is a way to connect my wallet to see rewards earned
- [ ] I can see rewards and infrastructure fees (totals) paid out per epoch, per asset, per type (staking rewards, infrastructure fees, price taking rewards, price making rewards, liquidity provision rewards, market creation rewards)
- [ ] I can see a total per asset 
- [ ] I can see what I have earned myself of each (number and % of total), in a way that is visually differentiated from the overall totals e.g. in a toggle

## Background / additional details 

- Staking rewards = types.AccountTypeGlobalReward
- Infrastructure fees = types.AccountTypeFeesInfrastructure
- Price taking rewards = types.AccountTypeMakerPaidFeeReward
- Price making rewards = types.AccountTypeMakerReceivedFeeReward
- Liquidity provision rewards = types.AccountTypeLPFeeReward
- Market Creation Rewards = types.AccountTypeMarketProposerReward

Ensure precision is considered i.e. the 0% issue here - https://github.com/vegaprotocol/frontend-monorepo/issues/2771

## Tasks 

- [ ] ...

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/205896628-4a4755bc-dfd0-4cdb-93f1-edc4384f1724.png)

**Comment by joellecharlotte** [comment]
[03.1](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=1946%3A10238&t=jCpUYt1L3pqDNrM8-1) shows how once you have connected your wallet you see your rewards and the % of total distributed.

I'm proposing to truncate any values in the table at 4 decimal points and then expose the full value via a tooltip + explain what the % value actually is with the words _(X% of total distributed)_. Screenshot attached of Coinbase and my tezos rewards which truncated in the list view but on click you view a popup with the full long number with many decimal points.

<img width="1041" alt="Screenshot 2022-12-16 at 09 55 21" src="https://user-images.githubusercontent.com/113684458/208072846-551a68cd-1d79-4a77-9983-5c1d80bd1b9f.png">

[04](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=1933%3A14464&t=jCpUYt1L3pqDNrM8-1) is an alternative design exploring styling the table values as links with a dashed underline to indicate a tooltip and moving % of total distributed into the tooltip. The table headings are also styled as links and remove the info icon... not sure I'm sold on this approach.

Might make sense to run through these before you get started for feedback etc.!

**Comment by pennyandrews** [comment]
Decision to pull in everything for now and paginate later when it's available (it crashing on mainnet might push to get the pagination work done by core)
