### ISSUE TITLE
Export CSV file for all Ledger Entries

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2320]
## Story

As a user
I want to be able to export a csv file that includes all ledger entries
So that I can see everything I have earned whilst trading on Vega and analyse the data for myself 

Example use case: to help me complete my accounting / tax returns etc. 

## Acceptance Criteria

- [x] I can export ledger entry data in csv format
- [x] If I click to export all ledger entries when my wallet is connected, the csv file contains all ledger entries for the key that I am currently connected with
- [ ] If I click to export all ledger entries when my wallet isn't connected, there is a way to choose which key(s) I want to export data for
- [x] The file downloads within a 'reasonable time' 

## Tasks

- [ ] Evaluate the API performance of the export (when there is a significant volume of data)
- [ ] If it isn't sufficient to provide a good experience, create core ticket to improve and maybe tickets for how we could improve the experience i.e. I get notified when it's ready OR I restrict the period of data I can export etc.
- [ ] If it is sufficient to provide a good experience then implement it
- [ ] Test it 
- [ ] Release it

## Additional details / background info

There is an API for a csv download https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-export-ledger-entries#export-ledger-entries-records-ledger-entries-to-a-csv-file

Was dependent on https://github.com/vegaprotocol/vega/issues/6754 which is now complete

**Comment by pennyandrews** [comment]
We will need someone with more trader knowledge to do this, maybe Lewis

**Comment by pennyandrews** [comment]
We are blocked by this core ticket https://github.com/vegaprotocol/vega/issues/7859 as the API doesn't currently spit out csv it is spitting out JSON. @pennyandrews  is going to chat to @gordsport about getting this prioritised ASAP

**Comment by pennyandrews** [comment]
@Maciek Gordon confirmed this morning that the core ticket to unblock our CSV export of Ledger Entries is complete and deployed to Stag3 last night so we should be able to get this work over the line now https://vegaprotocol.slack.com/archives/C02MV2GQ20Y/p1682388664264399

**Comment by macqbat** [comment]
As rest endpoint for getting downloadable file (/`api/v2/ledgerentry/export`) requires also assetId as a mandatory parameter, we CAN'T get all ledger entries at once. We CAN request now for each asset separately only.
