### ISSUE TITLE
Move vega & vegacapsule to docker

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#2334]
## The Chore

Move vegacapsule & vega binaries to  github-runner docker image.

## Tasks

- [ ] Install vegacapsule & vega binaries in docker image
- [ ] Update k8s with new version of docker image
- [ ] Remove vegacapsule & vega installation from workflows.

## Additional details / background info

This should speed up PR checks.
