### ISSUE TITLE
Use quantum formatting for collateral table

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2340]
Depends on: https://github.com/vegaprotocol/frontend-monorepo/issues/3952

## Story

**As a** user
**I want** to see values in the collateral table that are more meaningful
**So that** I can better understand the true value of my collateral

## Acceptance Criteria

- [x] Numeric values in the collateral table are formatted using asset.quantum
- [x] Values in the collateral breakdown are formatted using asset.quantum
- [ ] ~~I can interact with a column header to change the formatting to show the raw full value for that column~~ Waiting for pane context menu, which will provide a place for the formatting type switch to exist
- [x] There is a way to see the full number if I want to know the fully accurate number (e.g. with a tooltip)
- [ ] There is a way to find a definition of quantum, how it is calculated and why we use it in Console (i.e. [link to docs](https://github.com/vegaprotocol/documentation/issues/640))

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [x] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

Created from: https://github.com/vegaprotocol/frontend-monorepo/issues/2132

**Comment by JonRay15** [comment]
For this ticket I think the AC about explanation is more worthwhile.  

I think AC "I can interact with a column header to change the formatting to show the raw full value for that column" should be changed to "I can interact with a tick box somewhere on screen to toggle showing the amount to full precision". 

The below is a pretty standard pattern for exchanges, and then when the user clicks on the Hide / Show Balances button or hovers over it we can display the explanation.  

<img width="260" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/7c6007e3-b535-45a3-a183-2b1ce9a6a752">

Or maybe in our case it would be "Show Full Amounts" and would be unticked by default?

Then the explanation just needs to say "By default Console uses the `quantum` for each asset to show a number of decimal places that are roughly equivalent to 0.01 USD.  For more information on `quantum` see the docs."

**Comment by mattrussell36** [comment]
@JonRay15 I've been taking a look at this today.

I think we should wait for the [pane context menu](https://github.com/vegaprotocol/frontend-monorepo/issues/3114) to allow switching between full/formatted values. This will give us a nice consistent UI pattern for changing pane settings. For the time being all values will be formatted with quantum, with the full value being available via a tooltip on the cell

I'm going to update the ACs accordingly but lmk if you disagree.
