### ISSUE TITLE
 Use quantum formatting for liquidity provisions table

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2341]
## Story

**As a** user
**I want** to see values in the liquidity provisions table that are more meaningful
**So that** I can better understand the real value of the numbers in the LP table

## Acceptance Criteria

- [ ] Numeric values in the LP table are formatted using asset.quantum
- [ ] I can interact with a column header to change the formatting to show the full raw number for that column
- [ ] There is a way to see the full number if I want to know the fully accurate number (e.g. with a tooltip)
- [ ] There is a way to find a definition of quantum, how it is calculated and why we use it in Console (i.e. [link to docs](https://github.com/vegaprotocol/documentation/issues/640))

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

Created from: https://github.com/vegaprotocol/frontend-monorepo/issues/2132
