### ISSUE TITLE
Liquidity info in market header

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2367]
## Story

As a user
I want to see liquidity data in the header
So that I can make a decision how risky it may be to trade on that market

## Acceptance Criteria

- [ ] I can see supplied liquidity
- [ ] I can see target liquidity
- [ ] I can be linked through to the liquidity page

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch
<img width="1237" alt="Screenshot 2022-12-08 at 16 49 51" src="https://user-images.githubusercontent.com/46783148/206514185-dbe1837c-3f25-476a-b9e3-ebebbbdf1687.png">
