### ISSUE TITLE
Market switching pattern (LHS panel)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2394]
## Story

As a user
I want to more easily switch from one market to another
So that I can jump between the markets I'm most interested in 

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Review data items needed for market switching 
- [ ] Identify if / how we might highlight markets you have a position in 
- [ ] Look at efficiencies using visual patterns to condense data e.g. trading mode icons / colours / states rather than showing "a bunch of zeros", making sense of the market code (what it's derived from) 
- [ ] Sketch 
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info

* Looking at other DEX's it's a common pattern to have a scrollable left hand side panel for market switching in the market view
* Currently our pop over solution fills the screen, has a lot of information in it and hasn't been looked at from a design point of view i.e. how can we display this dense information in a more palatable way 
*
