### ISSUE TITLE
View all validators I have staked to (including ex-validators and pre-validators)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2404]
## Story

As a user with Vega staked to a validator(s)
I want to be able to easily see and remove stake from ex validators (those that are stopping being validators)
So that I have visibility of everything I have staked and can still unstake etc. to avoid losing money etc.

## Acceptance Criteria

- [ ] I can see if the validator I have staked is inactive with a way to remove stake from my wallet staking list
- [ ] When I go to remove stake from an inactive validator I can see an explanation of why e.g. "It is inadvisable to maintain your stake as this validator has not staked themselves. It is possible that this validator is new or leaving, look at their info URL for more details." and can remove stake
- [ ] It is not possible to add stake to a validator with 0 self stake
- [ ] If I have not staked any tokens, When I click to view `staked by me` I am informed that I have not staked any tokens (not shown a blank page) and am prompted to do so (or connect my wallet if not connected)

## Tasks

- [ ] Detailed sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/214835745-b43805bc-0c94-47aa-b828-e62c3be5b8e4.jpg)

Screenshot taken from Figma designs in [#2734](https://github.com/vegaprotocol/frontend-monorepo/issues/2734)
![Screenshot 2023-03-28 at 16 41 32](https://user-images.githubusercontent.com/30622993/228292681-af71267e-8135-4ed0-a8eb-8b3ce4b831a6.png)

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/075fe3aa-0d6d-4d5c-8e57-249059d1a344)

## Notes

**Comment by pennyandrews** [comment]
Need to do this before we do anything with the collapsing wallet (as the wallet is the only other place you can see what you have staked)

**Comment by JonRay15** [comment]
Note there is a hacky list we created a while ago to hide Nala etc.

When this enhancement is built that list and code should be killed off and replaced with this better functionality.

Even if a validator is in this list the self-stake should show them.

export const LEAVING_VALIDATORS = [
  'efbdf943443bd7595e83b0d7e88f37b7932d487d1b94aab3d004997273bb43fc',
  '5db9794f44c85b4b259907a00c8ea2383ad688dfef6ffb72c8743b6ae3eaefd4',
  'f3022974212780ea1196af08fd2e8a9c0d784d0be8e97637bd5e763ac4c219bd',
  '8d33c6e06207ed5735c8b5b6c0c6234f44eb381b242a25a538ed3315369d2203',
];
