### ISSUE TITLE
SPIKE: handling non-existent or leaving validators

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2405]
## The Spike

Investigate how to handle non-existent or leaving validators on the Governance app that is a better experience than just a disabled button

## Questions to answer

- [x] How to see where a user has stake on a validator that is no longer validating e.g. in the UI, a notification (grafana monitoring)
- [x] How we establish a validator "is no longer validating" e.g. self-stake = 0? Is there an edge case where someone switches off their node but actually doesnt remove their own self-stake? Performance score is 0 for X epochs or similar?
- [x] How to stop people adding stake to any validator that is dead
- [x] How to unstake from dead validators

## Outcome 
- #2404 
- #2728 
- #2727 
- #2734

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/214831386-4bfa649e-bf13-4b6f-ba23-d534033f620d.jpg)

## Tasks 

- [ ] Get answers to the questions 
- [x] Sketch flow / improvements
- [x] We've created any tickets needed

**Comment by JonRay15** [comment]
Things to consider:

- Need to be able to see where user has stake on a validator that is no longer validating 
- How to decide someone "is no longer validating"? Could rely on self-stake = 0 ... is there an edge case where someone switches off their node but actually doesnt remove their own self-stake? Then what?
- I believe there is something in Core that if a validator is completely dead for a number of epochs something happens ... like if their performance score is 0 for X epochs or similar ... worth checking that, not sure what we do then 
- Do we need any additional statuses from Core on top of Consensus / Standby / Pending (Candidate)?
- This might be a good time to ask whether Pending / Candidate should be two seperate statuses... Candida has thoughts on this.  Because there's a difference between a node that has submitted its heartbeat transactions but just doesnt have enough stake to become a standby validator vs one that hasnt done that basic step yet ... currently I believe both are Pending? Maybe not though
- Certainly we need to stop people adding stake to any validator that is dead 
- Certainly we need to be able to unstake from dead validators 
- Note we expect to have grafana monitoring that will notify when a validator leaves / dies / is demoted ... so that could be part of the process, users could subscribe to alerts potentially

**Comment by barnabee** [comment]
A few thoughts on this:

- Given that self-staking is the way you say "I wanna be a validator", we probably can't tell the diference between someone who has decided to try and be a validator and someone who's given up and not un-self-staked. I think this is fine. Most people will focus on validators who are standby validators or already consensus validators, as those receive rewards.
- Pending (Candidate) seems confusing to me: I would have thought pending meant a standby validator who would be a consensus validator next epoch and candidate is a validator who wants to be a standby validator but doesn't have the stake/score or hasn't set up their node correctly. If that's not the case and pending + candidate are the same, what do we call a standby that will be a consensus validator soon? How do we show that and also the inverse (a consensus validator that is about to be demoted to standby or candidate)?
- For undelegating this can currently already be done from the Vega wallet panel on the right hand side of the screen, so there's no reason we'd need to keep them in the main validator list just to enable undelegating if they're otherwise out of that list.
- We might want to think about highlighting or something for connected users if some of their delegations might possibly be to dead / wrong / invalid validators.

**Comment by JonRay15** [comment]
1. Agree
2. Yes this is confusing ... In terms of the API / Core we only have 3 statuses: Consensus, Standby and Pending to describe any validator that is not in one of those states.  We (Candida, Calum and I) have used "Candidate / Pending" interchanegably in docs and website because pending never made sense to me. IMO we should review the validator statuses with Core and see if we want more as part of this task.  I would think one for "no longer validating" would be useful if possible, as would one for non-validator, one for a node which has not done the necessary tasks (network heartbeat etc... Candida is better versed here) to become a validator, and one for someone that has done all the tasks but simply doesnt have enough stake would be useful.  To my knowledge we do not (and cannot?) have a status for one that will move up "soon" because we dont know with absolute certainty until the end of the epoch that a validator WILL move up, after which it has already moved.
3. Agreed
4. I have been wondering if we could have grafana alerts for various validator related things which people could subscribe to? I could imagine it would be good to have alerts if a validator you stake to unstakes, their performance reduces, they get penalised, etc etc

**Comment by JonRay15** [comment]
Just seen the below in the latest docs which is a good summary of what goes into "Candidate / Pending" status, and is the part I said Candida was better versed in than me.

**Candidate validators**
Any other nodes on the network are known as candidate (pending) validators. Nodes could be in this status for three reasons:
1. The node has not sent the necessary transaction to announce itself to the network
2. The node has sent the transaction, but does not have enough total stake to make become a standby or consensus validator
3. The node has not yet seen and then reported on enough Ethereum bridge transactions

To me at least ... it feels like 2 is a materially different status to 1 and 3. 2 is a node that has done everything it needs to but is just lacking stake.  1 and 3 are nodes that have admin they need to complete - or completed that admin very recently - before they can be considered for Standby status.
