### ISSUE TITLE
Trading data grid snags

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2408]
## The Chore

Improve visual consistency of data tables that use ag grid

## Tasks

- [x] Ensure row heights are consistent
- [x] Remove use of Button within cells and use ButtonLink
- [x] Replace custom market name cell in positions table with instrument.code and render single line text
- [ ] Remove cell focus globally
- [ ] Use pinned row for deposit/withdraw button (outside of the table)
- [x] TBD: Investigate ledger entry table and how we can compact the data so we have single rows

**Comment by bglownia** [comment]
Pinned row for single button is bad idea. I removed this approach in orders and "Cancel all" button.
It requires to add row with empty data and handle different rendering in every column. It also affects column with.
