### ISSUE TITLE
Refactor theme provider to use zustand

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2412]
## The Chore

It would be good to do a small refactor to use zustand. Benefits being
- align with other local state management
- no need to wrap apps with the theme provider
- can remove theme.js
- less passing of props

## Tasks

- [ ] Refactor using zustand
- [ ] Ensure default state is taken from local storage
- [ ] Remove theme.js
