### ISSUE TITLE
Repoint DNS to governance.vega.xyz for mainnet

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2425]
## The Chore

Repoint DNS to governance.vega.xyz for mainnet

## Acceptance Criteria

- [x] Site is available at governance.vega.xyz 
- [x] Navigating to URL token.vega.xyz redirects to governance.vega.xyz/token (and all other URL variations)
- [x] Site name is changed to "Vega Governance" (including Title that show in browser tab) - this needs to be changed for testnet version too, not just mainnet
- [ ] Review and correct all page titles for testnet and mainnet
- [x] Redirects from all other token.vega.xyz/xxx URLs to the relevant governance.vega.xyz/xxx URLs 

## Tasks

- [x] Repoint DNS
- [x] Set up redirections

**Comment by pennyandrews** [comment]
There are a few Page titles that don't seem quite right and need sorting...

Token page title should be Token, not Home

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/8108ceca-54c0-4b26-b517-fa6e6e6f9a3f)
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/6af41da4-51f4-490a-97f5-e14b4613d963)

Associate page title should be Associate, not Vesting

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/deca4b24-350e-4343-b102-aa70c338a82e)
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/6e91a213-80a8-4695-b2f0-74b85467bdb5)

Disassociate page title should be Disassociate, not Vesting

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/e110eddd-415c-4b6f-b7b7-f22c6e2eaf62)
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/a95e9607-6249-45f6-a043-ac48bd6e8a74)

**Comment by pennyandrews** [comment]
And the landing page should just be Vega Governance, or Vega Governance | Home not Vega Governance | Token

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/4f5baebf-34de-406a-bb9d-b0b7afb52dd4)
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/c1a5f62c-d06e-4b84-b7d3-2fedfd44943e)
