### ISSUE TITLE
Improve governance proposal card component

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#2428]
## Story

As a voter
I want to understand the type and status of each proposal at a glance
So that I can easily browse proposals

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Ask Michael to dig out earlier work from the Figma design system
- [ ] Look at acceptance criteria for governance
- [ ] Identify all states and variants
- [ ] Sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review

## Additional details / background info
- As part of [the new governance homepage](https://stagnet3.token.vega.xyz/token) Sam has added the proposal type to the current card, and added rounded corners for : 
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/1080322/208127352-ab3c8864-fbf1-42f8-b54d-bbca5bb17300.png">
- We identified a need to update this component to match the update style of the latest designs and reflect all the possible states and variations, e.g.
  - Proposal type
  - Fields unique to each proposal type
  - Participation
  - Expected outcome
  - State (e.g. enacted)

**Comment by pennyandrews** [comment]
Need to consult with Michael about all the edge cases on this one

**Comment by dexturr** [comment]
Related to #2637

**Comment by pennyandrews** [comment]
This has been superseeded now by other tickets
