### ISSUE TITLE
Custom rewards empty state dependent on user journey progress

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2463]
## Story

As a user
Given I have staked but not yet recived any rewards
I want a message to tell me that on the rewards page
So that I know that my rewards are coming

As a user
Given I have not staked
I want a message to tell me that on the rewards page
So that I know that to earn rewards I need to stake

## Acceptance Criteria

- [ ] I can see a message telling me to go stake if I have not staked yet
- [ ] I can see a message telling me to associate if I have not yet
- [ ] I can see a message telling me I have staked if I have both staked and assocaited

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
