### ISSUE TITLE
Make chart indicators and overlays more on brand

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2466]
## The Chore

The colors used for the overlays and studies could be more on brand

## Tasks

- [ ] Decide on colors
- [ ] Add new colors to palette if required
- [ ] Code changes were requried in frontend-monorepo/pennant

**Comment by joellecharlotte** [comment]
There are three suggested routes we can go for the colours in the charts, with one recommended route. Waiting on final input from Barney.
