### ISSUE TITLE
Frontend vegacapsule config should start up a block explorer API

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2494]
## Description

https://github.com/vegaprotocol/frontend-monorepo/pull/2492 had failing tests due to the explorer-e2e .env files not containing a `NX_BLOCK_EXPLORER` variable. This raised the point that so far no e2e tests have relied on the existence of a [block explorer](https://github.com/vegaprotocol/vega/tree/develop/blockexplorer) API, which explorer is now dependent on. Checking `/vegacapsule/config.hcl` confirms that no block explorer API is started.

# Tasks
- [ ] Update vegacapsule config to start a block explorer API instance
- [ ] Update explorer-e2e .env with the appropriate port for the block explorer API service
- [ ] Re-enable `Previous button disabled on first block` test in explorer-e2e
