### ISSUE TITLE
Investigate profiling and tracking of long running queries on TFE

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2508]
## The Chore

Investigate Sentrys' existing performance functionality and see if we are able to leverage this in order alert on things like LCP and FCP. It appears at the time of writing we are getting some information on some projects, we should see what is required to get all this information (SDK upgrade?).

## Tasks

- [ ] Investigate performance functionality
- [ ] Diagnose issue
- [ ] Fix issue
- [ ] Investigate what we can do for long running queries
- [ ] Investigate what we can do in terms of alerting
