### ISSUE TITLE
Remove `markets` JSON views

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2534]
# Option 1
## The Chore

The markets index is a giant list of JSON fields, which is of very little use. Let's remove the index page, and add a `/markets/:id` route that shows the same JSON thing, but just for one market

## Tasks

- [ ] Remove `/markets/`
- [ ] Remove sidebar entry
- [ ] Add `/markets/:id`
- [ ] Optional: Add a nicer Market view (can be moved out to a separate ticket)

# Option 2
Like has been done with the new Assets view, replace the index page with a table, and rather than add market by id, address the modal
