### ISSUE TITLE
Re-enable Oracles page

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2550]
## Description

Console currently links to the Oracles page, which ~is disabled through environment variables in most environments~ was deleted. 

## Tasks
- [x] Ensure Oracle empty state is reasonable
- [x] Recover it from git history
- [x] Turn it back on in all environments
- [x] Improve it

# Related
See https://github.com/vegaprotocol/vega/issues/7286, https://github.com/vegaprotocol/vega/issues/7283, https://github.com/vegaprotocol/vega/issues/7281

**Comment by edd** [comment]
The basic `JSON` view x 12 (6 markets, 2 per market) made a page that was not useful, so I switched over to this and have got this far: a few more fields and it'll be at least _functional_.

<img width="942" alt="Screenshot 2023-01-09 at 17 45 29" src="https://user-images.githubusercontent.com/6678/211373504-f871653a-58b9-4ee8-8a54-c932f0996cfb.png">
