### ISSUE TITLE
Rich asset details dropdown

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2557]
## Story

As a trader
I want to see more asset details in the asset dropdown
So that I can more easily select an asset for deposit or withdrawal

## Acceptance Criteria

- [ ] I can see the asset symbol
- [ ] I can see the asset name
- [ ] I can see the asset contract address or type (eg BuiltIn)

## Tasks

- [ ] Implement
- [ ] Touch base with design on the built thing
-
## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1673267954910889

**Comment by pennyandrews** [comment]
We did something similar to this in console lite
