### ISSUE TITLE
Trading test refactor

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#2593]
## The Chore

We have highly increased Trading app test coverage, and that will continue in the nearest future. There are also new capsule tests for trading. We need to clean up a little for better performance and to ease possible parallelisation. 

## Tasks

- [x] Analyse existing test scenarios and improve their structure. There are tests, that execute multiple validations in single `it` block, which 1. decrease visibility, 2. prevent validations to be done if one of them is failed. We need to rework it into `describe`s with many `it`s, where possible.
- [x] Minimise situations where app is refreshed, as it takes much time to reload the app. If it's possible to perform many tests without refreshing, let's do that instead.
- [x] We have bigger and bigget test files with many contexts and describes. Break it down to multiple spec files, where possible, which increase readability and allow such tests to be run in parallel in the future.
