### ISSUE TITLE
As a liquidity provider I want to see the price range for the market so I know where my orders need to be in to count towards my commitment

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#2599]
## Story

As a liquidity provider
I want see the `market.liquidity.priceRange` (in GQL `market.lpPriceRange`)
So that I know where I need to place my orders to count towards my obligation.

## Acceptance Criteria

- [x] I can see the value for the price range
- [x] the value is correctly formatted as a percentage with the decimal in the correct place
- [x] I can see a tool tip as an explanation of the value

(not the ACs for liquidity providers have not yet been created, this should be included)

## Tasks

- [x] Explore and sketch
- [ ] Team and stakeholder review
- [x] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

![image](https://user-images.githubusercontent.com/13255539/212061329-919ff003-491b-4d09-924e-2a1663952c90.png)

under market value proxy

tool tip: (taken from docs)
> the maximum distance from the mid price that a liquidity providers orders need to be to count towards their commitment

## Additional details / background info

Background on concept: https://docs.vega.xyz/testnet/concepts/liquidity/provision#price-range-for-liquidity-orders

Requested by @davidsiska-vega

**Comment by MadalinaRaicu** [comment]
Need to get some feedback on the tooltip wording and check if this needs to be formatted with asset dp too.
