### ISSUE TITLE
Collapsing wallet

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#2614]
## Story

As a Vega tokenholder
I want wallets to be moved from a sidebar into a drawer
So I have lots of space to look at my lovely big validators table

## Acceptance Criteria

- [ ] I can see how to connect a wallet
- [ ] I can see which wallets are connected without opening the wallet drawer
- [ ] I can tell when a pending transaction is happening without opening the wallet drawer, and trace it back to the wallet it belongs to
- [ ] Clicking anywhere on the wallet button opens the wallet drawer
- [ ] Clicking a wallet name/icon in the wallets button opens the wallet drawer with the corresponding wallet tab selected
- [ ] Clicking a link to a wallet in the main body content of the website opens the wallet drawer with the corresponding wallet tab selected (see #2605 for applications of this)
- [ ] On very large breakpoints (where the viewport width is at least the max width of the page content + the max width of the wallet drawer) the wallet button behaves like a toggle to open and close the wallet, and clicking outside of the wallet does not close it.

## Tasks

- [ ] Implement
- [ ] QA across device types and sizes

## Sketch
- [Design in Figma](https://www.figma.com/file/DUHzxECUu0Pe1TyRI4wL4C/dApp-Navigation?node-id=2033%3A3993&t=1vIaqievGpv2yBjg-1)

## Additional details / background info
- Dependent on #2094 
- Should ideally be merged after (or simultaneously with) #2605
