### ISSUE TITLE
Key to key transfers

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2615]
## Story

As a user
I want to be able to transfer collateral from key to key
So that so that I can better control risk

## Acceptance Criteria

- [ ] I can transfer from the current selected key
- [ ] I can transfer to one of my other keys in the wallet OR enter a pubkey manually
- [ ] I can select the asset to transfer
- [ ] I can only transfer from and to general accounts
- [ ] I can choose an amount to transfer
- [ ] I am shown the transfer fee calculated by `amount * networkParameter(transfer.fee.factor)`
- [ ] I can transfer
- [ ] I am prompted to confirm the tx via toast
- [ ] I am notified of transaction success or failure by toast

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] Visual Design
- [ ] Dev
- [ ] Test

## Sketch

![Console - Key to key transfers](https://user-images.githubusercontent.com/46783148/213701153-acd177ab-3cb5-46e9-9435-9f3ef466be4f.jpg)

https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764543771230897&cot=14

**Comment by jeremyletang** [comment]
@ckpringle @mattrussell36 Only general account type transfers should be considered for now.
Basically the only transfers the UI should offer are transfer from an asset A to any other general account for the same asset A, for any pubkeys of the same user or others.

**Comment by jeremyletang** [comment]
For info the fee is calculated like so:
```
amount * networkParameter(transfer.fee.factor)
```
