### ISSUE TITLE
Improve Explorer oracles query

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2632]
## The Chore

The new oracles page requests every oracle, and all its data. This is tolerable when markets are low and a small amount of data is sent, but would quickly get huge with active oracles or lots of markets

## Tasks

- [x] Only request one thing on the Data Connection by default
- [x] Set page limit on oracles to fetch
- [ ] 0possibly a follow up ticket: make an oracle by ID page that can use a heavyweight query, and a simpler listing page. Or when the markets page is better, remove the oracles index (after checking with console) and require a user to come in via markets
