### ISSUE TITLE
View as ethereum user

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2636]
## Story

As a user
I want to be able to input an ethereum key and see the site from their point of view
So that I can easily inspect data

## Acceptance Criteria

- [ ] I can input an eth key and see all the data on that site as if I was that eth addres
- [ ] I cannot place a transaction and I am informed about why this is the case
- [ ] I can disconnect the key i am viewing
- [ ] I can see an indication on the site that I am in some kind of view only mode

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
