### ISSUE TITLE
ELS vote not reflected on Proposal cards

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2637]
## Story

As a user
When I am looking at a market update proposal
I want to see Equity Like Share (ELS) vote on the proposal cards when applicable
So that I can evaluate quickly how likely the vote is to pass

## Acceptance Criteria

- [ ] I can see ELS vote, when there is one,  on market update proposal
 
## Tasks

- [x] Find / understand and document in the ticket, the answers to the below questions (including [reading the spec](https://github.com/vegaprotocol/specs/blob/master/protocol/0028-GOVE-governance.md#outcome))
- [x] Sketch out the solution (and confirm whether or not we need any visual design, we assume probably not)
- [x] Implement
- [ ] QA Test

## The questions that we need to answer

- [x] What do we need show?
- [x] What scenarios do we need to show this in?
- [x] What are the requirements for an ELS vote to pass i.e. is it network parameter dependent?
- [x] Does the ELS vote require a threshold?
See sketch

## Sketch

<img width="759" alt="Screenshot 2023-03-03 at 15 30 13" src="https://user-images.githubusercontent.com/13255539/222760469-42138a77-7c86-4bf5-9c03-67003934c356.png">

If the more VEGA has voted than the required participation it determines the outcome. show we show pass/fail by token vote.
if there hasn't been enough VEGA voting it is up to the LPs

In addition I noticed that their LP participation threshold is not shown on the details page in the same way that token participation is. It should be added

- [ ] add detail on LP participation, it does not need to show a count in the same way token vote does. just a %
<img width="967" alt="Screenshot 2023-03-03 at 15 32 50" src="https://user-images.githubusercontent.com/13255539/222761289-e0bc1a99-9a13-45f9-956b-746c092479d8.png">

note a lot of logic appears to already exist here:
<img width="973" alt="Screenshot 2023-03-03 at 16 20 15" src="https://user-images.githubusercontent.com/13255539/222772920-022a6b67-ea17-4ae8-abdd-0ee1ad42741f.png">

**Comment by campbellssource** [comment]
FYI: https://github.com/vegaprotocol/specs/blob/master/user-interface/3001-VOTE-vote.md
I'm trying to dig out a copy of the designs that had this in, I think they've been deleted from figma

**Comment by campbellssource** [comment]
Updated ticket description with sketch.

**Comment by campbellssource** [comment]
note: here are some some old designs for the proposal details page (originally created for https://github.com/vegaprotocol/frontend-monorepo/issues/801 ), shown here just for reference. We may want to do something different with the new design system. Or just do the simplest change

<img width="984" alt="Screenshot 2023-03-08 at 10 15 40" src="https://user-images.githubusercontent.com/13255539/223686059-81ae39be-6700-46aa-8be3-6195446a7f19.png">
<img width="1749" alt="Screenshot 2023-03-08 at 10 16 21" src="https://user-images.githubusercontent.com/13255539/223686210-72929161-9c86-4503-bfa3-c35727ecca84.png">
