### ISSUE TITLE
Add validator penalties to the validator details page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#2647]
## Story

As a user 
I want to be able to see details of the penalties (overstaking and performance) applied to each validator 
So that I can make rational decisions about where to allocate my stake to earn the best bang for my buck on rewards

## Acceptance Criteria

- [ ] I can see the overstaked amount on the validator details page  
- [ ] I can see any additional higher penalty applied on the validator detail page 
- [ ] I can see the optimal stake and total stake somewhere on the validator page

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info
The changes to support this on the Core side are [here](https://github.com/vegaprotocol/vega/issues/7351).
