### ISSUE TITLE
Add block height to node status indicator

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2681]
## Story

As a user
I want to see the block height against the node I'm connected to 
So that I can see it tick over, and if a market is inactive (no trades happening) I can see I'm still connected and things are working

## Acceptance Criteria

- [ ] I can see the block height count up dynamically alongside node / node status

## Sketch 

<img width="1179" alt="Screenshot 2023-01-19 at 17 26 35" src="https://user-images.githubusercontent.com/46783148/213516681-dbd415e2-3294-4ef8-93b0-6b8b454fd423.png">

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] Visual Design
- [ ] Dev
- [ ] Test
