### ISSUE TITLE
Post-mobile review ensure any known issues are highlighted to users

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#2684]
## Story

As a user visiting Vega dapps on a mobile device or from an unsupported browser or platform
I would like to be informed about any limitations and how to avoid them (e.g. by moving to desktop, using different browsers/tools, downloading an app, whatever…) when I first arrive at a dapp that either doesn't work at all, is unsupported, or requires a Vega wallet or other software/features that aren't available on mobile
So that I can decide whether or not to continue my journey on the mobile device and avoid wasting time

## Acceptance Criteria

- [ ] I am informed of limitations on each dapp that users a Vega wallet or isn't supported by my configuration immediately or soon after visited
- [ ] I am informed if the dapp is untested on mobile or the UI is not designed for small screens and likely to be difficult or impossible to use
- [ ] The information includes or links to accurate and easy to follow instructions to work around the limitations and/or about other ways to access the dapp that aren't limited
- [ ] The information include details of things that are still possible on mobile

## Tasks

- [ ] Determine exactly what you cannot do on mobile (possibly deposit and withdraw)
- [ ] Sync with wallet team on mobile support progress
- [ ] Define and agree what browsers we support
- [ ] Add callout to welcome dialog explaining the above
- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by dexturr** [comment]
Based on the browser list:

```
last 1 Chrome version
last 1 Firefox version
last 2 Edge major versions
last 2 Safari major version
last 2 iOS major versions
Firefox ESR
not IE 9-11 # For IE 9-11 support, remove 'not'.
```

**Comment by JonRay15** [comment]
This should be included as part of the mobile review
