### ISSUE TITLE
Warn users on mobile  and unsupported browsers/systems when they try to connect a wallet

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#2685]
## Story

As a user visiting Vega dapps on a mobile device
I would like to be informed about the state of support for wallets on mobile or other unsupported platforms (Chromebook, iPad/tablets, browsers that can't connect to wallet with their default configuration, etc.)
So that I don't try fruitlessly to find a way to use the dapp and get frustrated and can use a different device etc. to access the dapp

## Acceptance Criteria

- [ ] I am informed at the start of the connection process if my device or browser or system may not be supported
- [ ] The information includes or links to instructions for how to access the dapp successfully

## Tasks

- [ ] Define and agree what browsers we support
