### ISSUE TITLE
Highlight mainnet sims on frontend applications

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2714]
## Background / context

The blog announcing the mainnet sim’s is going out today (24th Jan), and the first sim is due to start next Tuesday (31st Jan).

## The Chore

We would like to have something on our frontend applications to highlight the sims, either a new ‘banner’ at the top (we will be doing something similiar for vega.xyz shown in screengrabs below) or we could re-use a relevant existing common component i.e. the pop-up that has been built as the ‘warning message’ for console.

I would expect that we would do this for console, governance and block explorer (not wallet or docs) but this is TBC. 

## Tasks

- [x] Decide what component to use
- [ ] Design and content (as needed)
- [ ] Implement
- [ ] Test
- [ ] Launch (need to decide whether we would launch it before or on the 31st)

## Additional information

vega.xyz will be using the existing banner (top) and pop up (bottom right) components 

Rebecca & Nissa will be providing 2-3 word main heading, short secondary sentence and CTA for us to use

![image](https://user-images.githubusercontent.com/47143694/214333202-71bc6de0-6e70-4209-aa49-fc11bf794a2f.png)
