### ISSUE TITLE
Add Alpha Lyrae to Console

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2723]
## The Chore

Switch to using Alpha Lyrae everywhere without the glitch effect only. `font-alpha liga-0-calt-0` should do the trick

## Tasks

- [x] Add `font-alpha liga-0-calt-0` to the body so that the font is applied without ligatures or contextual alternatives
- [x] Review and apply any fixes all views to ensure line heights and alignment is all okay
- [x] Add typography section to storybook to close https://github.com/vegaprotocol/frontend-monorepo/issues/176
