### ISSUE TITLE
Associate tokens with "view only" pubkey

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2724]
## Story

As a user
I want to understand that I am associating tokens with a "view as" pubkey and therefore won't be able to use them to delegate or vote
So that I better understand what I am doing

## Acceptance Criteria

- [ ] I can see that I am associating to a view only pubkey rather than a connected pubkey
- [ ] I can see an explanation of the implication i.e. "The key you are associating to is not part of your connected wallet. You will not be able to delegate these tokens or vote on governance proposals without connecting the wallet containing this key."
- [ ] There is a way to exit the "view as" mode to go connect my wallet

## Sketch
<img width="1271" alt="Screenshot 2023-01-25 at 11 18 35" src="https://user-images.githubusercontent.com/46783148/214550100-5b2ee93a-f1de-4545-b711-05999764474c.png">

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
