### ISSUE TITLE
Tighten up the flow for "view as vega user"

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2725]
## Chore
Catching a couple of things to make the "View as vega user" more easily understandable. 

## Tasks
On wallet connect popup
- [ ] Separate "View as vega user" from the wallet connect options with "OR"

<img width="1112" alt="Screenshot 2023-01-25 at 11 21 31" src="https://user-images.githubusercontent.com/46783148/214550671-d175159f-57d5-4bbc-b7a6-11ff6263d8ee.png">

On View as Vega user state / page
- [ ] Add explanation of what you are doing by viewing as a vega user "Browse from the perspective of another Vega user in read-only mode"
- [ ] Add title "View as Vega user"
- [ ] Update CTA to "Browse network"
- [ ] Add navigation to go back

<img width="1167" alt="Screenshot 2023-01-25 at 11 24 17" src="https://user-images.githubusercontent.com/46783148/214551245-65c1ddc3-d2f3-43be-9e59-b2af09cfb8ca.png">
