### ISSUE TITLE
Add `signer` column to Open Oracle price table

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2726]
Removing signer, will add it back in a follow up ticket

_Originally posted by @edd in https://github.com/vegaprotocol/frontend-monorepo/issues/2698#issuecomment-1403521795_
            

This column was removed, as the implementation to derive the `signer` from the message & signature is hacky & incorrect.

# Tasks
- [ ] Fix address recovery function `getAddressFromMessageAndSigner`
- [ ] Enable column again
- [ ] Re-enable disabled tests
