### ISSUE TITLE
Automated notifications for change in validator status

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2728]
## Story

As a user
I want to be notified when a validator changes status 
So that I don't need to "go look" and find out

## Acceptance Criteria

- [ ] There is an automated way to be notified of a change e.g. to list of consensus validators, change to ersatz list, validator inactive in Discord or something to subscribe to as part of staking 
- [ ]...

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
