### ISSUE TITLE
See only my staked validators grouped together

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2734]
## Story

As a user
I want to easily see a list of who I have staked
So that I can manage / see my stake in one place

## Acceptance Criteria

- [ ] There is a way to handle empty / when you haven't staked - i.e. just not show the toggle?
- [ ] There is a way to see my staked validators together
- [ ] I can still see my stake in the context of the long list of validators

## Initial sketch 
<img width="1281" alt="Screenshot 2023-01-25 at 16 12 42" src="https://user-images.githubusercontent.com/46783148/214615793-53292af2-1095-4109-a794-1c9690dce11d.png">

## Tasks

- [x] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by pennyandrews** [comment]
@sam-keen this is ready for you now

**Comment by pennyandrews** [comment]
@joellecharlotte please add Figma link to the designs for this ticket

**Comment by joellecharlotte** [comment]
Here is the [Figma link ↳](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=2416%3A14341&t=0FvJIcFq4cDyCrNG-1) 

Note that the STAKE button becomes MY STAKE when the Validator row item is one you're staking. Equally, your fees. rewards etc. are highlighted in green to make a visual connection to the green YOUR STAKE button.

The idea is that when toggled to view _All validators_ you have a visual identifier for your staked validators and scan the list and see which are yours.

LMK if this requires a quick call.

**Comment by sam-keen** [comment]
Discussion about the new features lead to discussion about the staking section on the validator details page. It makes sense to move the staking data to the top of the page, as it makes the 'stake'/'my stake' button's action clearer. 



![Image](https://user-images.githubusercontent.com/2410498/225082894-35b3863a-5342-47ff-9fa2-21801745c238.png)
