### ISSUE TITLE
Color config update

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2736]
## The Chore

Update color config as per [latest design here](https://www.figma.com/file/8lCQ6iNK3dbw42bIKwGCRk/Foundations?node-id=3750%3A77046&t=oURrtiMmaUHOy3Ka-1)

## Tasks

- [x] Joëlle to add missing colour styles for Yellow and Purple into Figma for completeness
- [x] Update config so color values and names match
- [x] Update component classes to use new names
