### ISSUE TITLE
Deposit flow from deal ticket

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#2762]
## Story

As a new user of vega
I want to immediately see how to make a deposit and start trading from the UI
So that I can get started without having to find the right place to go

## Acceptance Criteria

- [ ] There is a call to action to deposit collateral when you have not connected your vega wallet e.g."deposit collateral" when there is no wallet connected , on the collateral tab, with intro copy e.g. "Deposit funds & start trading."
- [ ] This is visible when you first come to console

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] Visual Design
- [ ] Dev
- [ ] Test

### Ticket tab
[Miro source](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764542528012197&cot=14)

<img width="244" alt="image" src="https://user-images.githubusercontent.com/1080322/215144752-3d5251bd-2bae-4e40-87d3-9692c535962c.png">

## Additional details / background info
- This task was split from https://github.com/vegaprotocol/frontend-monorepo/issues/2145. This ticket only concerns the entry points to the deposit form. The other ticket focuses on the experience _in_ the deposit form.
