### ISSUE TITLE
Deploy token for validator testnet

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#2772]
## The Chore

Setup validator testnet

## Tasks

- [ ] Get validator testnet data nodes
- [ ] Create release/validator-testnet from main
- [ ] Create new environment config based on: https://github.com/vegaprotocol/frontend-monorepo/pull/1774 on main branch
- [ ] Add new Environment name to config
- [ ] Fix all type errors
- [ ] Create network.json
- [ ] Create tranches.json
- [ ] Cherrypick or otherwise port this commit onto develop (separate PR)
- [ ] Create netlify site based on mainnet mirror config
