### ISSUE TITLE
Collateral tab doesnt sort by column

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#2799]
## The Chore

The collateral tab in Console currently doesnt sort based on columns.

You can click the column header and it acts as if it is trying to sort ... but doesnt. We need to fix this so we can sort on any column.

Ideally we should also have some sort of default sorting.

## Tasks

- [x] Fix sorting on the collateral tab
- [x] Decide if we want a default sort and if so, what is it?
- [x] Apply the default sort if applicable

**Comment by macqbat** [comment]
if we have there so-called "infinite scroll", the only one reasonable possibility of doing column sorting is to do it on server side. This was already reported to core team. Each other way of implementation this feature in front end will bring more or less lame solution. 
I can create an issue for core team and temporary hide controls for sorting on the table.

**Comment by mattrussell36** [comment]
@macqbat I don't think we should use infinite scrolling here, the list of assets isn't likely to be long enough to require pagination (at least in the short/mid term), so I'd say the need for filtering and sorting is greater. Can we change it to not use the infinite row model to allow filtering and sorting, client side only

**Comment by macqbat** [comment]
Default sorting of ag-grid is the first column ascending
