### ISSUE TITLE
Feedback, help, docs - signposting and links

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2804]
Blocked by #2840 

## Chore

There are several links we need to add to console to help tie up different user journeys 

* Docs 
* Provide feedback 
* [Link to mainnet incident reports#2764](https://github.com/vegaprotocol/frontend-monorepo/issues/2764)

This chore is to find / design a place to hold these, and implement. 

## Acceptance Criteria

- [ ] I can get to the docs site
- [ ] I can get to the feedback site

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] Visual Design
- [x] Dev
- [ ] Test

## Additional details / background info / ideas

DYDX 

![Image](https://user-images.githubusercontent.com/46783148/218719915-ed65cef7-cc0a-4393-aa4d-57bcc255ed8a.png)

GMX

![Image](https://user-images.githubusercontent.com/46783148/218720072-d164e8c0-86fe-4a45-8972-36df52295665.png)

Perp

![Image](https://user-images.githubusercontent.com/46783148/218720244-b353d87e-f708-4d3c-af92-b78690359006.png)
![Image](https://user-images.githubusercontent.com/46783148/218720245-d8fa1124-1037-4e3a-a9b3-2c9f018a0e83.png)

GTrade

![Image](https://user-images.githubusercontent.com/46783148/218720367-11840c62-7254-485e-8875-2ff13ceac1f4.png)

OKX 

![Image](https://user-images.githubusercontent.com/46783148/218720619-6431f670-c214-4b06-a39a-543c0983a1ef.png)

Binance

![Image](https://user-images.githubusercontent.com/46783148/218720738-cc4ea2d0-3eb1-4ef6-98e5-a3638d02be15.png)

**Comment by joellecharlotte** [comment]
Proposed solution is a new nav item, possibly labeled "Resources" that can house Docs and Feedback and possibly other items in future. Explorer needs a different solution for the Side Nav Dropdown / Expanding Sub Nav unless we can reduce the items down but based on [an earlier test](https://www.figma.com/file/CRNfp3wtC29lIr3ctcWVe9/Block-Explorer?node-id=2108%3A12079&t=KYhbEJ6fonlla277-1) doubt this is possible.

[Figma ↳](https://www.figma.com/file/DUHzxECUu0Pe1TyRI4wL4C/dApp-Navigation?node-id=2289%3A7223&t=BpicgD86wbaQQudQ-1)

![Feedback, Help, Docs](https://user-images.githubusercontent.com/113684458/219497774-6d3173d9-b194-4d82-b79c-171f09c9625f.jpg)
