### ISSUE TITLE
Define and agree what browsers we support

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2805]
## The Chore

There are two tickets requested by Barney that in order to do we need to define and agree what browsers we support

https://github.com/vegaprotocol/frontend-monorepo/issues/2684
https://github.com/vegaprotocol/frontend-monorepo/issues/2685

Primary question is do we (no / maybe) / should we (yes) support Brave and if so how much do we care / should we be testing for it 

## Tasks

- [ ] Decide where it should go (notion page / readme) etc.
- [ ] Draft something
- [ ] Review it with the wider team - Mandatory Project Leads, Optional (with a set deadline / cut off point) for everyone else
- [ ] Once decided, make browser list rc agree with the spec (or make a ticket)

**Comment by edd** [comment]
The browser support matrix for every app is defined separately. But no app has changed from the default! So 
- [Token](https://github.com/vegaprotocol/frontend-monorepo/blob/develop/apps/token/.browserslistrc)
- [Explorer](https://github.com/vegaprotocol/frontend-monorepo/blob/develop/apps/explorer/.browserslistrc)
- [Trading](https://github.com/vegaprotocol/frontend-monorepo/blob/develop/apps/trading/.browserslistrc)
- [LP](https://github.com/vegaprotocol/frontend-monorepo/blob/develop/apps/liquidity-provision-dashboard/.browserslistrc)

All declare support for:

> last 1 Chrome version
> last 1 Firefox version
> last 2 Edge major versions
> last 2 Safari major version
> last 2 iOS major versions
> Firefox ESR
> not IE 9-11 # For IE 9-11 support, remove 'not'.

# Brave support: Partial
Brave can use the dapps, but cannot connect to a Vega Wallet running locally, due to [brave/brave-browser#27346](https://github.com/brave/brave-browser/issues/27346). This blocks our connection to the wallet. CORS is properly supported, and is not the issue.

*Mitigation*: Turning down the 'Shields Up' setting for the site may work
*Proper fix*: When the [Vega Wallet browser extension](https://github.com/vegaprotocol/vegawallet-browser) is published, this will work in Brave, and our support will be upgraded to Full.

# Safari support (MacOS): Partial
Safari can use all the dapps, but cannot connect to a Vega Wallet running locally due to a misconfiguration of the server on https://console.fairground.wtf. Specifically `upgrade-insecure-requests` is set to true, which makes Safari (MacOS) try to connect to *https://localhost...* which does not work.

*Mitigation:* Access Console on IPFS: https://console-fairground-wtf.ipns.dweb.link/
*Proper fix:*: Ensure Console (HTTPS) is not served with the `upgrade-insecure-requests`
