### ISSUE TITLE
Update layout and implement design

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2815]
## Story

As a team
We want to tighten up the displayed data and how it is presented 
So that it's most visible at a glance and fits with the Vega website design

## Acceptance Criteria

- [ ] Remove "(Futures)" from "Market" column heading 
- [ ] List market name, market code and settlement asset under "Market" column heading e.g.

```
**Market**
UNIDAI Monthly (Dec 2022)
UNIDAI.MF21
tDAI
```

- [ ] Remove settlement asset e.g. "tDAI" from "Last price", "Target Stake" and "Total staked by LPs" (should only see numbers in those columns)
- [ ] Wrap volume change % onto a new line e.g. 

```
**Volume (24hr)**
2.54254
(-3.074%)
```
- [ ] Change "Total staked by LPs" column heading to "Liquidity supplied"

```
**Liquidity supplied** 
1,210,009.15718
```

- [ ] Remove "% Target stake met" column, adding the data to "Liquidity supplied" a new line (see below)
- [ ] Add colour dot from liquidity status to "liquidity supplied" data (this is as per console, but with the % on a new line):

```
**Liquidity supplied** 
🟢  1,210,009.15718
(20%)
```

- [ ] Rename "fee levels" to "Liquidity fee"
- [ ] Combine status label and health bar, under "Trading mode" i.e. 

<img width="267" alt="Screenshot 2023-02-01 at 12 50 10" src="https://user-images.githubusercontent.com/46783148/216047771-c5be80a6-81a9-4521-9128-2b5606145491.png">

Becomes

![Image](https://user-images.githubusercontent.com/46783148/217512878-c401fc50-a46f-47c6-98ee-ac995e41ae55.png)

- [ ] Rename "Closing time" "Expiry", and push the time onto a new line i.e. 

```
**Expiry**
11/11/2022
16:28:25
```

- [ ] Data columns come in this order: 

```
1. Market 
2. Last price 
3. Change (24hr)
4. Volume (24hr)
5. Target stake
6. Liquidity supplied 
7. Liquidity fee
8. Trading mode
9. Age
10. Expiry
```

- [ ] We've implemented the table styling as per design
- [ ] There is a way to see all markets or markets for specific settlement assets 

<img width="657" alt="Screenshot 2023-02-01 at 12 53 38" src="https://user-images.githubusercontent.com/46783148/216048520-0c67bf85-e770-41c1-ab2c-b21792ea68cd.png">

## Design
![XL](https://user-images.githubusercontent.com/46783148/216048924-1b2f6bb0-f459-4336-888e-f686f471598d.jpg)

Figma link: https://www.figma.com/file/ZQrh7fiFciTQ9GWD4Pp1Am/LP-Dashboard?node-id=1536%3A13160&t=Dsq7EfBwxNBx5J1s-0

## Tasks

- [ ] Implementation
- [ ] Testing 
- [ ] Etc.
