### ISSUE TITLE
Enhance rich asset select with typeahead 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/frontend-monorepo#2820]
## Story

As a user
I want to be able to quickly find the asset I want to deposit
So that I can deposit and start trading quickly

## Acceptance Criteria

- [ ] I can start typing an asset name or symbol to filter the asset select options
- [ ] I am shown if there are no assets matching my search term
- [ ] I can easily select my chosen asset by mouse or keyboard

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Dev
- [ ] Test

### Original ticket

On testnet, when you try to deposit you currently get a mammoth list of every asset ever created on testnet, which looks a bit rubbish and confusing.  

Potential solutions are to add some new enhancements would avoid hacky / setupy type fixes... namely:
* On deposit flow by default check in the user's ETH wallet and only show assets that they have, include a "show all" button to access the entire list
* On withdrawal flow by default check in the user's Vega wallet and only show assets they have, include a "show all" button to access the entire list

Raised by @JonRay15

**Comment by mattrussell36** [comment]
@candida-d @JonRay15 I've update this ticket to be a more targeted task that should help with asset selection for deposits and withdrawals.

Note:

- We already filter the asset list for withdrawals based on what accounts you have
- Doing the same for deposits is possible, but involves several requests to get the required data and wouldn't be a robust solution (we'd have to pull all asset listed evens on the bridge and then fetch each balance individually)

**Comment by JonRay15** [comment]
Loads of work now done on guided deposit that addresses this
