### ISSUE TITLE
Show collateral for current market

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2824]
## Story

As a user
I want to see my collateral for a given market more prominently
So that I can monitor my position and make decisions around trading

## Acceptance Criteria

- [ ] I can see my available collateral in the deal ticket or somewhere else not hidden by default
- [ ] The value subscribes to any changes

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [ ] Visual Design
- [ ] Dev
- [ ] Test

### PREFERRED OPTION: Style the collateral table row for this market
Apply a style, like a background colour, to the settlement asset for the market you're viewing.

![image](https://user-images.githubusercontent.com/1080322/225038124-58168c50-50f0-4c4b-beb0-8b3baf0d8101.png)

### Alternative option: Pin the collateral table row for this market
Pin the asset for this market to the top of the table so it's easy to find. However, this might interfere with sorting.

![image](https://user-images.githubusercontent.com/1080322/225038603-94daf377-79ff-46c3-89ed-f2ff72b578a0.png)

## Additional details / background info
https://vegaprotocol.slack.com/archives/C037STCKMGC/p1675181550764529?thread_ts=1675181200.687929&cid=C037STCKMGC

**Comment by MadalinaRaicu** [comment]
What about showing it in the trade header?

**Comment by mattrussell36** [comment]
@neildawson @MadalinaRaicu 

I'd prefer to go with the pinned row option, even if that means (for now) the row is duplicated below.

This allows the asset for the market to always at the top and super visible and you can still filter and sort and see how it compares to other assets.

In future we can iterate to enhance this by adding logic to set/unset the pinned row when filters are applied, or allow the user to manually unpin it

@barnabee chime in if you have strong opinions on this
