### ISSUE TITLE
Show margin maintenance level in console

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#2834]
## Story

As a user placing an order
I want to understand how my margin use will change when I place this order
So I can avoid getting too close to my maintenance level and being liquidated

## Acceptance Criteria

- [x] I can see how much margin I have my account for this market now, and an estimate of how much I'll have after I place this order
- [ ] I can see my maintenance level now, and an estimate of the level after I place this order
- [ ] I can see a visualisation of the above which helps me understand how much buffer I have between the two figures
- [ ] I am given an explicit warning if my new margin balance is likely to fall below the initial level
- [ ] I am told if my order will flip the position

## Tasks

- [x] Refine with Michael 
- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] Neil or Calum to brief Joelle
- [x] Create visualizations in deal ticket: https://github.com/vegaprotocol/frontend-monorepo/issues/3767
- [x] Create margin health dialog https://github.com/vegaprotocol/frontend-monorepo/issues/3769
- [ ] ~~Show if order will flip position~~
- [ ] ~~Show estimated margin levels in margin health dialog from deal ticket~~
- [x] Update deal ticket value and tooltips

## Sketch

![image](https://user-images.githubusercontent.com/1080322/229076436-60140101-73f8-4fc9-85e1-b0d009fa935c.png)

- From [the Miro board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764546934193057&cot=14)
- Note: the "total margin available", "deduction from collateral", and "deduction from margin" fields will be implemented as part of a separate ticket: https://github.com/vegaprotocol/frontend-monorepo/issues/3215

## Background 
- Dependent on https://github.com/vegaprotocol/frontend-monorepo/issues/3216

**Comment by mattrussell36** [comment]
Closing as we agreed the visualization will exist in the collateral table
