### ISSUE TITLE
Deposit flow from collateral window

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2864]
## Story

As a new user of vega
I want to immediately see how to make a deposit and start trading from the UI
So that I can get started without having to find the right place to go

## Acceptance Criteria

- [ ] There is a call to action to deposit collateral when you have not connected your vega wallet e.g."deposit collateral" when there is no wallet connected , on the collateral tab, with intro copy e.g. "Deposit funds & start trading."
- [ ] This is visible when you first come to console

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [ ] Visual Design
- [ ] Dev
- [ ] Test

### Collateral tab and its sibling tabs
[Miro source](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764542524313091&cot=14)

<img width="966" alt="image" src="https://user-images.githubusercontent.com/1080322/215145072-ec9489f0-52e5-4e79-86f1-6bdae5fea70e.png">

## Additional details / background info
- This task was split from https://github.com/vegaprotocol/frontend-monorepo/issues/2145. This ticket only concerns the entry points to the deposit form. The other ticket focuses on the experience _in_ the deposit form.

**Comment by mattrussell36** [comment]
@MadalinaRaicu lets go with option two, we should be able to update the collateral table to accept an asset id to pin that assets row to the top
