### ISSUE TITLE
Clarify collateral and breakdown tables

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2871]
## The Chore

We need to make better sense of the way we display collateral, used margin, total margin available so that people understand 
* How much they have left 
* What is using the most margin of the markets they hold positions in 

## Tasks
- [x] Get to grips with what we currently have and where the issues are (session with Michael, Matt?) 
- [x] Look at how this is handled most commonly by the biggest players - DYDX and Binance
- [x] Sketch out an information architecture that addresses the main needs coming from the manual testing remembering to consider how this impacts what we call collateral / assets in the wallet side panel on governance 
- [x] Agree improvements to be made 
- [ ] Implement 
- [ ] Test 

#### In collateral table
- [ ] Rename 'Total' column to 'General'
- [ ] Add a 'Total margin' column and display the sum of all margin accounts for that asset
- [ ] Remove 'Used' column
- [ ] Add 'Fees earned' column and display the sum of all fee accounts (infrastructure, maker, liquidity) for that asset
- [ ] Add 'Bond' column and display the bond account type balance

#### In breakdown table
- [ ] Show full list of un-aggregated accounts for asset
- [ ] Show columns for type, market (if margin account), balance

## Sketch

From [the Miro artboard](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764547506685987&cot=14)

### Collateral table
![Image](https://user-images.githubusercontent.com/1080322/223385033-3fd61945-89fe-4c0f-849e-7ed6ed81ac1c.png)

"Used" tooltip:
> Currently allocated to a market as margin or bond. Check the breakdown for details.

"Available" tooltip:
> Deposited on the network, but not allocated to a market. Free for use in new markets or orders.

"Total" tooltip:
> The full amount associated with this key. Total of used and available collateral.

### Breakdown modal
![Image](https://user-images.githubusercontent.com/1080322/223382325-7bc14a2d-1790-48ae-9ab9-d4cbc969cd82.png)

## Additional details / background info

https://vegaprotocol.slack.com/archives/CFXA4EGN7/p1675417313628039

**Comment by campbellssource** [comment]
![image](https://user-images.githubusercontent.com/13255539/221929306-ea61eebe-5377-461c-b673-302a77f36c6f.png)
e.g. this is the breakdown where there is more than ~one~ two accounts in one settlement asset
