### ISSUE TITLE
URL and title tweaks on Supply and Redeem pages

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#2880]
## The Chore

When we implemented the new navigation for Governance dApp, we updated the page titles and URLs, too. There are a few instances we still need to update.

## Tasks

https://token.fairground.wtf/token/tranches
- [ ] Change page title to Supply & Vesting (to match the navigation label)
- [ ] Change URL to /token/supply

https://token.fairground.wtf/token/redeem
  - [ ] Change page title to "Redeem vested tokens"

## Additional details / background info
- [Miro board with outline of all changes to URLs, titles, and nav labels](https://miro.com/app/board/uXjVPUTU6m4=/?moveToWidget=3458764539286377363&cot=14)
