### ISSUE TITLE
FELT ACTION: Formalise and roll out Community Feedback Process

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2910]
## The Chore

We are starting to receive more feedback from the community via the mainnet sims, and expect this to just increase as trading is launched etc. so need to make sure there is a robust process in place for receiving, triaging, prioritising and feeding back / tracking progress on issues that come from external sources. 

And... we need to make sure that everyone at Vega knows what this process is and what part they play in executing it. 

And... that we provide visibility to the community of what this process looks like from their perspective

https://docs.google.com/document/d/1lxn6kQS-khmNhJEW3hiALzVEr23zH65SI8lYfJVnr3w/edit?usp=sharing

## Tasks

- [x] Write up current process - @JonRay15 
- [x] Identify areas that need more details / fleshing out - @JonRay15 
- [x] Define who the stakeholders are for this work (who needs to agree with the process) - @JonRay15 
- [x] Share with the stakeholder group and agree on the process and areas for refinement - @JonRay15 
- [x] Get everyone that needs to be, up to speed on the process and their role
- [x] Set up schedule for monitoring / triage etc?
- [x] Review and create tickets to improve signposting to providing feedback (UX) (Candida created a BE ticket that we might re-use)
- [ ] Create view of all issues with the feedback label in FE project view (and see how we can leverage it) AND/OR reflect community feedback on a roadmap view in some way @pennyandrews 
- [x] Include as agenda item on Dan's weekly meeting
- [x] Frontend leads to review doc and make sure happy with it (and everyone else in frontend is aware)

## Additional details / background info

Current Process

- Someone puts an issue in the repo
- Candidate reviews and gathers information / gets clarity
- Give an answer i.e. how to solve their problem OR Transfer the discussion item into an issue on the relevant github repository and board (and tell people in the relevant slack channel) - tickets linked and labelled feedback
- Tickets get prioritised and done / not done by Project Lead
