### ISSUE TITLE
Prevent closing a position during auction

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2920]
## Story

As a user
I want to know that I can't close my position during auction
So that I am not confused about the state of my position

## Acceptance Criteria

- [ ] I can not close my position during auction
- [ ] I am shown why I can't close my position

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Dev
- [ ] Test

## Additional details / background info
https://vegaprotocol.slack.com/archives/C037STCKMGC/p1676474796680919

**Comment by macqbat** [comment]
I see we have now such a error message presented to the user:
![image](https://user-images.githubusercontent.com/338931/225957542-22d93c3e-94fc-4972-b3e6-8a9bfec1c501.png)
May be this fair enough for handle this case?

**Comment by macqbat** [comment]
@mattrussell36 do we have any new conclusion here?
