### ISSUE TITLE
Handle users connection being lost

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#2922]
## Story

As a user
I want to be notified if my browsers loses connection
So that I am not waiting for updates or confused if the app is unresponsive

## Acceptance Criteria

- [ ] I am notified if the users connection is lost
- [ ] I can still see application data

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Dev
- [ ] Test

## Sketch
https://www.figma.com/file/wBu1KViEZz1JkwpOmhFQrO/Console-V2?node-id=1559%3A10993&t=DfjPopWHB7x5BlmW-1

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1676481459834409

**Comment by joellecharlotte** [comment]
[Here is a solution](https://www.figma.com/file/wBu1KViEZz1JkwpOmhFQrO/Console-V2?node-id=1559%3A10993&t=OcmrtgTQdfA0IPD4-1) utilising the bottom left status indicator combined with a toast message.
