### ISSUE TITLE
Update proposal table to use set filter component

### ISSUE THREAD

**Issue by asiaznik** [vegaprotocol/frontend-monorepo#2939]
**question (non-blocking)**:  Is it possible to prefill the filter selection on this? I think it's currently treating it like a string, where really it's an enumb of (something like) `[Enacted, Open]`. On the network I'm looking at, all proposals are `Enacted` and that gives me no clue what the alternatives would be if I wanted to filter to just the Active ones.

<img width="300" alt="Screenshot 2023-02-17 at 09 58 16" src="https://user-images.githubusercontent.com/6678/219613415-42f744b7-afbe-4a9c-8075-0eff2e03d85d.png">

_Originally posted by @edd in https://github.com/vegaprotocol/frontend-monorepo/pull/2925#discussion_r1109552732_
            

# Tasks
- [ ] Determine roughly what is simple and quick: https://www.ag-grid.com/javascript-data-grid/filter-api/#example-filter-api-readonly
- [ ] Decide a rough estimate for how long the big fancy version would take: https://www.ag-grid.com/javascript-data-grid/filter-api/#example-filter-model 
- [ ] Agree on the thing that will get us Transasction Type filtering within a reasonable amount of time
- [ ] Do that

**Comment by bglownia** [comment]
We already have se filter which should work in that case 

```
import { SetFilter } from '@vegaprotocol/datagrid';

<AgGridColumn
    filter={SetFilter}
    filterParams={{
      set: Schema.OrderStatusMapping,
    }}
```
