### ISSUE TITLE
Add support for IssueSignatures TX

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2947]
The next release (https://github.com/vegaprotocol/vega/blob/v0.68.0-pre3/CHANGELOG.md#0680) contains a 'new' tx - `IssueSignatures`. It's not *actually* new, but is not yet supported because it used to be a validator only TX

# Tasks
- [x] Look at an `IssueSignatures` TX
- [x] Decide what should go in the view that isn't already in the default view
- [x] Make it so
