### ISSUE TITLE
Improve date picker in ag-grid column filters

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/frontend-monorepo#2948]
## The Chore

Currently we date pickering in ag-grid is done by native picker of the browsers. Despite few advantages of such solution (easy handling of the mobile view, easy maintenance) it provides more potential problems: 
- native date picker looks differently in each browser
- no easy possibility of potential enhancement - no place for error messages, tooltips etc.
- view not consistent with selected theme
- small sizes of buttons are more difficult for  the user to use
-  "popup in popup" solutions imply hard usability

It is to be considered, if better solution would be to use external library for date picker, like ie [react-datepicker](https://www.npmjs.com/package/react-datepicker). Despite the overhead of the amount of code it offers quite good features: flexible api, possibility of get exactly what we need. We could get unified view of UI.

So instead current solution:
![Screenshot 2023-02-21 at 09 41 30](https://user-images.githubusercontent.com/338931/220293664-2d010378-b599-4e0f-af74-7c2641615ab6.png)

we could get IMHO better one:

![image](https://user-images.githubusercontent.com/338931/220293485-ce856967-c634-4360-b377-d8a581cab01d.png)

## Tasks

- [ ] Design UX use-case
- [ ] Implementation in [date-range-filter](https://github.com/vegaprotocol/frontend-monorepo/blob/bdc917306f6fdc09f0da3ed5cbcda2ca654f049e/libs/react-helpers/src/lib/grid/date-range-filter.tsx) and other possibly places
- [ ] add use-case to the UI-toolkit library

**Comment by macqbat** [comment]
The other weaknesses of native date pickers are:
- not supportitng time picker in safari and firefox
- undeterministic behaviour of displaying empty value :-(
