### ISSUE TITLE
Convert Governance tests to typescript

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#2950]
## The Chore

In keeping with a lot of the other tests. The Governance tests should be changed to typescript for a bit more robustness

## Tasks

- [x] Refactor existing staking and association tests - there's a lot of repeated code in those tests that can be refactored. 
- [ ] Move test files to typescript and resolve any errors
- [ ] Change Cypress commands which are not in libs to functions
