### ISSUE TITLE
See rewards for a specific / range of Epochs

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2952]
## Story

As a user
I want to see what rewards I earned between specific epochs
So that I can use this information to account / track my earnings 

## Acceptance Criteria

- [ ] There is a way to see a specific Epoch's reward earnings
- [ ] There is a way to see a reward earnings in a range of epochs e.g. I want to see rewards between epoch 50 and 57 

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by ckpringle** [comment]
Also consider if we do #4024
