### ISSUE TITLE
Make it easier to understand valid liquidity price range

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#2955]
For an order to count towards a liquidity providers commitment it needs to within a reasonable range of the current mid price.

## The Chore

There are two useful fields (to help an LP place valid orders) in the market info tab that have a misleading label 🟢  and incorrect Unit 🔴 .
It is also worth double checking they are using the correct decimal places 🟦 .
I would also expect these values to change as the mid prices change.

<img width="325" alt="Screenshot 2023-02-21 at 14 11 34" src="https://user-images.githubusercontent.com/13255539/220379594-4ecdf5b6-09d8-42ee-98d0-512323b1f4ba.png">

The intention of this field is to tell the user what the Liquidity price range (50%) means in terms of a price on the market.
LP need to place their orders within 50% (in this case) of the mid price. the filed say the lowest and highest prices these need to be within. 

## Tasks

The data type of this information is [Quote](https://github.com/vegaprotocol/specs/blob/master/user-interface/9001-DATA-data_display.md#quote-price). So...

- [ ] Change the labels from `LP Volume Min` and `LP Volume Max` to something else that better describes (e.g. "Lowest price" or "highest price" see sketches below) 
- [ ] Change the unit to use `market.quoteName` rather than "settlement asset"
- [ ] Check that the number of decimal places is coming from the right place. i.e. [Quote](https://github.com/vegaprotocol/specs/blob/master/user-interface/9001-DATA-data_display.md#quote-price). This number should not be truncated and displayed to the full precision as the quote
- [ ] Ensure the min/max fields update as the mid price moves
- [ ] Quotes should be right aligned where possible

## Sketches

Options for label names
- Lowest/Highest price
- Lowest/Highest price within liquidity range
- Lowest/Highest valid price
- LP valid Price Min/Max
- LP Price Min/Max

e.g.
<img width="927" alt="Screenshot 2023-02-21 at 14 56 48" src="https://user-images.githubusercontent.com/13255539/220379539-8fca638e-83c1-4d11-9839-4461a3640209.png">

Note: Some of these labels may be misleading if the Price monitoring bounds are in fact tighter...

- [ ] Consider re-jigging further so price monitoring and liquidity bounds are displayed together...

In this example

<img width="1010" alt="Screenshot 2023-02-21 at 16 04 33" src="https://user-images.githubusercontent.com/13255539/220397340-6e08b4ac-4903-4105-8e32-9b8d34346c96.png">

## Additional details / background info

https://vegaprotocol.slack.com/archives/CFXA4EGN7/p1676977474367579

[Broader thinking about liquidity provision](https://www.figma.com/file/Vnf1XhB4p6Dlg9AnxbdE32/Untitled?node-id=0%3A1&t=G0y1BN0lpZ0xPoQO-1) as part of https://github.com/vegaprotocol/frontend-monorepo/issues/1716

**Comment by MadalinaRaicu** [comment]
checked and they are using market decimal places and that should be correct

**Comment by MadalinaRaicu** [comment]
also, there might be **multiple** price monitoring triggers, it might not be just one to be brought together with LP price range
