### ISSUE TITLE
Staking how-to content 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2980]
## Story

As a user
I want to understand what I need to do to stake 
So that I feel confident staking without having to read docs

## Background 

On mainnet token we have this: 
<img width="849" alt="Screenshot 2023-02-23 at 15 40 19" src="https://user-images.githubusercontent.com/46783148/220956378-700a9b72-e861-4cb5-8feb-b573d9e04b5f.png">

It was removed / tidied as part of the page redesign 
<img width="1048" alt="Screenshot 2023-02-23 at 15 42 56" src="https://user-images.githubusercontent.com/46783148/220957115-d3ab7439-c86e-4e44-a83f-f7a657e53d3d.png">

https://vegaprotocol.slack.com/archives/C038EB6V2RE/p1677143185480449

Ideally we'd have some real user research with the new version to see how people understand and are able to stake etc. (Barney's dad could do it)

## Acceptance Criteria

- [ ] There is a way to understand the steps to stake e.g. they could be described up front, or they could be described in what happens when you press the "stake" button or both

## Tasks

- [ ] Review the stepped list against what we have in the latest validators page design 
- [ ] Agree what to bring back / keep / add to make it clear the steps to nominate a validator 
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by campbellssource** [comment]
The biggest thing that is weird is that VEGA is on Ethereum and you have to associate to a Vega key. we have to break any pre-ideas people might have about how it works. As well as make it clear to people with less staking experience
