### ISSUE TITLE
SPIKE: Validator upgrade readiness (part 1)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2991]
## User

As a governance dapp user
When a protocol upgrade proposal has been passed
I want to know what tasks validators need to do to be 'ready' for the upgrade and which validators are ready and which aren't 
So that I can get a general idea of validator performance, assess how this might impact me and decide if I need to take action i.e. if a validator I am delegating to isn't ready for an upcoming upgrade I might choose to move my stake to one that is so that I can continue to earn rewards  

Relevant slack thread https://vegaprotocol.slack.com/archives/C01P24880JY/p1675164514569819

## Questions

- [x] How do we know, currently, what tasks are involved in an upgrade preparation and when validators are ready to upgrade?
- [x] What data do we already have access to that can tell us this?

## Tasks

- [x] Read specs / speak to the relevant people to find the answers to our questions
- [x] Document the findings in the ticket
