### ISSUE TITLE
SPIKE: Reporting (and explaining) protocol governance state (part 1)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2993]
Decided with Barney that we would tackle the known states as they come up rather than do the investigation to try and pre-empt them all. This includes multisig contract state, network upgrades etc. that are all ticketed individually

## User story we are trying to satisfy

As a governance dapp user
I want to understand the current governance state of the protocol - in particular when the protocol is in an 'undesirable' state, understand why this is the case and what action needs to be taken, by whom, to resolve it
So that I have visibility of what is happening with the network, can assess how it impacts me and decide whether I need to act
AND so that I am reassured in many cases that the protocol is not broken, that the opposite is true, it's doing what it has been designed to do to protect users and their assets  

Example: If the multisig bridge is configured with the wrong validators, rewards will not be paid and you can't get your money out of the protocol

## Tasks

- [ ] Get a list from Klaus of all the states and scenarios
- [ ] Figure out the different technical ways we could identify / show this for each state / scenario
- [ ] Document the findings in the ticket 

## Background Info

- Klaus and others can give us info on the different states / scenarios that need to be covered
- Consider 'global' network (effects everyone) as well as key specific (effects just some people)
- If there aren't suitable APIs for it then we need to request them to see the statuses etc.
