### ISSUE TITLE
Remove graph on tranches page

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#2994]
We have a graph on the tranches page that might not be accurate 

## Tasks

- [x] Verify if / how inaccurate the data being displayed on the graph is (in terms of as of today as well as future estimates) 
- [x] Establish and document in the ticket our options for removing, replacing or updating the graph (with an idea of relative effort)
- [x] Review and decide on the option to go ahead with with team and Barney and Lewis
- [x] Write ticket(s) for the resulting work

**Comment by dexturr** [comment]
We are going to remove this for now: https://docs.google.com/spreadsheets/d/1-AK-G1CSdzzTJ6r3QgaqykkX2SucXAKA/edit#gid=426530149

**Comment by dexturr** [comment]
We are going to remove the graph for now
