### ISSUE TITLE
Proposal rationale can be markdown formatted

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2998]
## The Chore
Current proposals tend not to be, so this has gone unnoticed. If usage of markdown picks up, Token and Block Explorer should correctly render the proposal rationale as markdown

## Tasks

- [x] Pick a markdown library
- [x] Add it as a dependency
- [ ] Update Governance site > Proposal Details to render description as markdown
- [x] Update Explorer > Transactions > Proposal Summary to render description as markdown

# Why did this go straight in the backlog
Only one markdown formatted proposal exists on any of the networks running currently. Adding a reasonably sized dependency just for this doesn't seem like the right move right now.
