### ISSUE TITLE
Quicker deposits using built in assets on Fairground

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3016]
## Story

As a potential console user
I want to be able to quickly try out trading on the platform 
So that I can make a decision on whether to invest my time in learning more about Vega

## Acceptance Criteria

- [ ] There is a faster way to get funds into Console and trade on Fairground e.g. using built in assets via API inspired by DYDX's approach

## Background 

DYDX has made it possible to "trade" on testnet without having to have the test assets available in your ETH wallet. This makes it a lot faster to "try out" the trading functionality. 

<img width="299" alt="Screenshot 2023-02-27 at 17 15 02" src="https://user-images.githubusercontent.com/46783148/221637037-fec38ee2-5a9d-4cdf-bf55-6d3bf4a885b4.png">

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by pennyandrews** [comment]
Lower priority as we wouldn't use this in sims or incentives so more maybe useful for later
