### ISSUE TITLE
More details on proposals with signature bundles

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#3065]
## The Chore

#2111 adds a Proposal view, which contains a view of the signature bundle. It's currently pretty basic:

<img width="552" alt="Screenshot 2023-03-01 at 17 25 15" src="https://user-images.githubusercontent.com/6678/222430122-747aed55-db3d-400f-9617-b309060704eb.png">

From that signature bundle we could be pulling:
* Which validators contributed to the bundle

Which is interesting data.

## Tasks

- [ ] Wait for the `vega` CLI to support bundle decoding
- [ ] Reimplement the logic with Ethers
- [ ] Update bundle view to decode signature bundle
- [ ] Update bundle view to link to signing validators
