### ISSUE TITLE
Filter orders by default on trading page

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3072]
## Story

As a user
I want the order list to be filtered when on the trading page
So that I only see relevant orders

## Acceptance Criteria

- [x] I only see active and parked orders by default when viewing orders on the trading page
- [x] I can filter the list
- [x] I can understand that I am looking at a filtered view of orders (not all orders) (ideally using existing AG Grid elements)
- [x] Orders are shown for all markets
- [x] Infinite scroll is removed
- [ ] Sorting and filtering is applied client side only
- [x] The initial request for orders should fetch the latest ~~1000~~ 5000 orders
- [x] Subsequent data is fetched by using the date filter and using the selected dates as the DateRange for the query
- [x] Orders arriving via subscription are immediately applied to the grid
- [ ] Apply a default sort order on type column to group LP orders to the bottom

## Tasks

- [x] Check with Lewis on liquidity pegged orders and whether they should be shown (and if so, at the bottom?)
- [ ] Dev
- [ ] Test

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1677749496425519

**Comment by bglownia** [comment]
@mattrussell36 since orders table use pagination (infinite scroll) sorting need to be done on backend. To move LP pegged orders to the bottom backend need to return it on very bottom. 
Even if this will be done on backend  I don't think it has a lot of sense. User will need to scroll through all pages of "normal" orders to get to LP pegged orders. IMHO it will be better to have filter to hide pegged orders or show only pegged orders

**Comment by barnabee** [comment]
> @mattrussell36 since orders table use pagination (infinite scroll) sorting need to be done on backend. To move LP pegged orders to the bottom backend need to return it on very bottom. Even if this will be done on backend I don't think it has a lot of sense. User will need to scroll through all pages of "normal" orders to get to LP pegged orders. IMHO it will be better to have filter to hide pegged orders or show only pegged orders

Some design choices here we should at least take a critical look at in future iterations.

I'm not sure infinite scroll makes sense here (nor in many places on a trading app, to be honest). I'd expect Console to always **load all orders** into the active orders view, unless there are literally thousands and be able to filter, sort, and group them in many more ways than would be supported by DN APIs. This seems to me like something that ought to live on the client.

I'm open to the idea that my intuition here is wrong, but I get the sense we might be doing this just because it's become kind of a default for websites, not because it's necessarily the right approach for the application we are building.

**Comment by mattrussell36** [comment]
@bglownia @barnabee 

Allowing infinite scroll for the order list was a requirement that came from me, which may or may not be wrong from a purely a user experience point of view. 

However, implementing it that way absolutely had a technical knock on affect of making filtering and sorting much more difficult to manage, which IMO provides way more value.

In other tables we've already made changes to handle more on the client. I'd suggest we do the same for orders. What that would like is the following:

- Mount the grid with whatever default filters we deem necessary
- Fetch the latest N orders on page load
- We use the date range filter to refetch a new payload on change
- We could also create a more classic pagination ui in future as well
- Incoming orders via the subscription can be applied to the grid (AgGrid will filter according to the filter critieria)
