### ISSUE TITLE
Check all deployments link to all other deployments in the network switcher

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#3076]
## Description

A user noticed that the mainnet explorer says 'Fairground testnet (not available)' in the network switcher. They were trying to check on why the network was behaving badly (see #3074 - it was down). Block explorer is a tool that's useful for diagnosing that.

# Tasks
- [ ] Check that explorer.vega.xyz links to testnet and other networks
- [ ] Check that explorer.fairground.wtf links to testnet and other networks
- [ ] Same for devnet, stagnet1 & 3, mirror and vtestnet
