### ISSUE TITLE
When trying to connect a wallet to a dapp I'd like to be reminded of common reasons I can't connect to wallet

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3089]
## Story

~~As a~~ When connecting a dApp to a wallet
I want to be ~~reminded~~ told about common reasons that I can't connect to my wallet 
So that I can quickly fix an issue and get connected

Connecting a Vega wallet to a dApp is a significant moment in the first use of Vega, it is already full of tension, and we can expect (from experience and due to known issues) that lots of users will struggle at this moment

<img width="841" alt="Screenshot 2023-03-06 at 10 26 17" src="https://user-images.githubusercontent.com/13255539/223084130-5a4f4faa-ad9e-4bdf-83d1-6a11d74b4f36.png">

Issues:
- The message says "no wallet application running" (but the user can see the Vega wallet is open)
- The message says "no wallet application running" (but it actually means the "service", but even then)
<img width="1346" alt="Screenshot 2023-03-06 at 10 45 18" src="https://user-images.githubusercontent.com/13255539/223088658-6e893aff-8f39-45b7-b37c-8b48cf37df2d.png">
- The link to [Having trouble?](https://docs.vega.xyz/testnet/concepts/vega-wallet) don't feel attached to the error I'm seeing so users don't tend to follow
- The page doesn't address common issues, and is too generically about wallets and Get a Vega wallet. Consider using this link instead https://docs.vega.xyz/testnet/tools/vega-wallet/desktop-app/latest/getting-started#troubleshooting

## Background
~~Some~~ Many browsers (on some operating systems with default or common settings) Will block attempts from a website to https://localhost This is to prevent potentially malicious software. When this happens it is often silent meaning there is no message shown to the user. This is a specific CORS policy implimented differently by browser vendors

**The following list is only based on my quick test with an uptodate Mac.**

### Brave with "shields up"
<img width="842" alt="Screenshot 2023-03-06 at 10 32 00" src="https://user-images.githubusercontent.com/13255539/223085472-e604d416-b95a-449f-b0aa-c28d2e98c160.png">

The recommendation here might be to Suggest the user "lowered the shields" for this site.

The can either
- Lower shields with this simple switch
<img width="539" alt="Screenshot 2023-03-06 at 10 40 19" src="https://user-images.githubusercontent.com/13255539/223087479-6bd71271-0064-42ac-8cac-007ebf83e348.png">

- or in advanced controls allow all trackers and adds
<img width="478" alt="Screenshot 2023-03-06 at 10 39 22" src="https://user-images.githubusercontent.com/13255539/223087261-9d5af089-72c1-49a0-b6eb-82b6d1b3c927.png">

### Safari
<img width="1681" alt="Screenshot 2023-03-06 at 10 33 56" src="https://user-images.githubusercontent.com/13255539/223085961-9ac9f283-89e7-4df7-9fb6-953290bd7d8d.png">

Safari will never work. In this case we should advise using a different browser (Firefox)

### Firefox

Current Firefox doesn't appear to have any issues

### Chrome

Current Chrome doesn't appear to have issues (older ones do)

### Other browsers with issues
I recommend showing some options:
- You could try using another browser (e.g. Firefox)
- Check the wallet "service" is running on https://localhost:1789 (where your Vega wallet should be), The desktop Wallet shows the service status in the footer.
- Try changing the settings on your browser so that it can connect to localhost, this might be in CORS or tracking settlings
- If your wallet is running at another location (enter it here)(link to modal with URL input)

## Acceptance Criteria

https://github.com/vegaprotocol/specs/blob/master/user-interface/0002-WCON-connect_vega_wallet.md

## Tasks

- [ ] Consider researching what all common browsers (os) do
- [ ] Agree an approach to testing this
- [ ] Update the specs repo with reference ACs (there is a high level bullet point already, but no code or detail)
- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by ValentinTrinque** [comment]
@vegaprotocol/frontend @barnabee ideas could help addressing these issues.

https://github.com/vegaprotocol/vega/issues/7771#issuecomment-1456474848

**Comment by barnabee** [comment]
I'd be in favour of explicitly detecting the browser and config combo and most likely cause of errors to display an appropriate customised message to users, either:
- the workaround for Brave / use a different browser
- explain that an ad blocker or similar might be blocking things if not working on Firefox or Chrome (also Edge??)
- not supported and link to a different browser for Safari
- not supported on mobile yet, suggest view as user for read only on any mobile browser
- etc.

We should link to the browsers that work / Firefox, and always remind users the wallet needs to be open and the service running.

Desktop wallet probably ought to display a warning bar all the time / until dismissed if it can't bind to the port.

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.
