### ISSUE TITLE
Fetch network configs from networks repos

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3101]
## The Chore

Currently we fetch a list of nodes from json files deployed to static.vega.xyz. These need to be fetched directly from the networks repo

## Tasks

- [ ] Work with dev ops to add a CI check on the validity of the .toml files
- [x] Update start up logic to fetch network configs directly from https://github.com/vegaprotocol/networks and https://github.com/vegaprotocol/networks-internal
- [x] Parse .toml result
- [x] Ensure that we properly handle the experience if github is down
- [ ] Delete old config files
- [x] Update env vars to point to the relevant .toml files
