### ISSUE TITLE
Improve UX surrounding deposit balances, allowances and limits

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3102]
## Story

As a user
I want to understand the various balances, allowances and thresholds applicable to depositing
So that I can more easily deposit

## Acceptance Criteria

- [ ] Before I approve an asset, I am not shown the table of thresholds etc. about the asset
- [ ] After I approve the asset:
  - [ ] I can see the balance of the selected asset in my Ethereum wallet
  - [ ] I can see the current allowance (approved amount)
  - [ ] I can see when the deposit has a life time deposit cap, and how much I have used

## Tasks

Figures in [square brackets] should show the appropriate value dynamically

- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] ~~Visual Design~~ Unnecessary
- [ ] Implement
  - [ ] Hide the table of thresholds (balance, lifetime deposit limit, etc.) if the selected asset is not approved
  - [ ] Remove "lifetime deposit allowance" and "deposited" fields
  - [ ] Relabel "remaining" as "Remaining deposit allowance" and give it a tooltip:
    > VEGA has a lifetime deposit limit of [10,000.0000] [TDAI] per address. This can be changed through governance. [NEW PARAGRAPH] To date, [9000.00000] [TDAI] has been deposited from this Ethereum address, so you can deposit up to [1000.00000] [TDAI] more.
  - [ ] Relabel "Approved" as "Ethereum deposit cap" and add a tooltip:
    > The deposit cap is set when you approve an asset for use with this app. To increase this cap, approve TDAI again and choose a higher cap. Check the documentation for your Ethereum wallet app for details.
  - [ ] Change the inline notification shown when you successfully approve an asset to:
    > You approved deposits of up to [9,768] [tDAI].
  - [ ] Change the error when you exceed your approved amount to:
    > You can't deposit more than your approved deposit amount, [100] [TDAI]
  - [ ] Change the error when you exceed the lifetime deposit limit to:
    > You can't deposit more than your remaining deposit allowance, [1000] [TDAI]
  - [ ] Change the error when you exceed your balance to:
    > You can't deposit more than you have in your Ethereum wallet, [9,768.31147] [TDAI]
- [ ] Test

### Changes to the order of form fields, table, and labels

![image](https://user-images.githubusercontent.com/1080322/230036766-bb0550f7-e438-4e84-9223-f94159e92672.png)

### Improved error messages

![image](https://user-images.githubusercontent.com/1080322/230036234-ec09d082-f5be-4629-8bc2-6d637a6580c4.png)

## Details

We would ideally like to incorporate Michael's recent findings in this (if we can keep it small)
