### ISSUE TITLE
Pane/Tab context menu

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3114]
## The Chore

We need a method of allowing users to execute actions from within a pane, where those actions are specific to the content of the pane itself.

Some examples of these 'actions' could be:

- Changing the view to display a settings area for that data grid or chart
- Executing transactions such as cancelling all orders or depositing
- Changing chart overlays and studies
- Changing deal ticket types
- Changing number precisions

## Tasks

- [x] Design
- [x] Review
- [ ] Dev (ui-toolkit)
  - [ ] Adjust tabs component to allow for rendering buttons/dropdowns/anything in the right hand section
  - [ ] Add way of passing actions/state from the tab bars to the rendered view below
  - [ ] Implement for chart overlays and studies

## Additional details / background info

- Open to any ideas here but my initial thoughts here are that this is one or more contextual (the context being the current selected tab) menus (possibly similar to our Dropdown component) from the top right of each tab bar. Alternatively this menu could exist within the tab itself.
- [Some examples gathered on Miro](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764548123344271&cot=14)

**Comment by joellecharlotte** [comment]
Started looking at this as part of Console v3. See Cancel all, Settings icon + Expand Icon in the _Positions_ tab (is incorrectly functionality but just to show what a button + icons could look like.

<img width="1728" alt="Pane-Context-Menus@2x" src="https://github.com/vegaprotocol/frontend-monorepo/assets/113684458/b2e21c2c-ffed-4f62-b51b-d90f905d2c8a">
