### ISSUE TITLE
feat: Show positions for all connected keys

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3115]
There is a decision to make whether we do this sooner by looping through multiple connections key by key or building an abstraction layer until the APIs we need are there and then replacing earlier OR we hold off and do it when the APIs are available

Start with positions and assess each data grid on a case by case basis

In the deal ticket (and maybe others) we would need the user to be able select a key to use

Make sure we consider the understanding of the user, especially if we are implementing in one place and not others
Consider and make people aware/ note the issues of the implications of the fact that the wallet currently doesn't allow you to select only certain keys to give access to 

REFINE BASED ON THIS 

Barney: this would be particularly valuable across collateral
Could be that we do this only at a positions level, market remains key specific, to include positions and collateral
If we have risk and leverage control it could be less of an issue for our retail users 

## Story

As a user
I want to see positions across all my wallets keys
So that I can monitor all positions at once

## Acceptance Criteria

- [ ] I can see positions for every key in my connected wallet
- [ ] I can see what key a position was created by
- [ ] I can filter by pubkey

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Team review
- [ ] Dev
- [ ] Test

## Additional details / background info

The `party.positionsConnection` query has been deprecated in favor of the top level `positions` query which now takes a filter argument that can be used to pass multiple pubkeys as variables to the query

**Comment by mattrussell36** [comment]
Note that currently we only have the required query filters for positions. It might be a little weird to only implement this ticket for positions and not also orders/fills/accounts etc.

Any thoughts on this @barnabee @neildawson @campbellssource

**Comment by asiaznik** [comment]
We need to drop the `party` -> `positionsConnection` query and use top-level `positions` which accepts a list of keys. We'd need to refactor the provider a bit but it's doable.

```
query poss {
  positions(filter:{ partyIds:["1703ea1fa68cf19452d8484af96c09629e0e3601c5354454dec0f39a5d8e1ca8", "6817af32e94bb998ed4a39da1f44fbb42eba026cf11d93a8f3973884e92eb605"]}) {
    edges {
      node {
        market {
          id
        }
        openVolume
        realisedPNL
        unrealisedPNL
        lossSocializationAmount
        positionStatus
        marginsConnection {
          edges {
            node {
              maintenanceLevel
              timestamp
              initialLevel
              collateralReleaseLevel
              searchLevel
              asset {
                id
                symbol
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by mattrussell36** [comment]
Suggestion we make a simplified version of this to avoid the data joining for accounts, margin levels markets etc.

Perhaps a new tab 'All positions', which only uses the positions query and subscription (and perhaps the markets query to obtain decimal places/market code) and displays only the top level data in those queries.

CC @barnabee
