### ISSUE TITLE
Separate orders/fills and positions/collateral in bottom pane

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3116]
## The Story

As a Trader
I want to see more data related to the market I am looking at in a single view 
So that I can avoid having constantly click between tabs

Separate bottom pane into two. Orders (default) and Fills on the left. Positions (default) and Collateral on the right.

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Explore and sketch solution (including refining A/Cs)
- [ ] Team and stakeholder review
- [ ] Visual design
- [ ] Team review
- [ ] Implement
- [ ] QA Check (A/Cs met, code quality and adherence to design)
