### ISSUE TITLE
Store current tab selections

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3117]
## The Chore

When you reload the page your tab selections are lost

## Tasks

- [ ] Store tab selections for the trading page
- [ ] Store tab selections for the portfolio page
- [ ] Store tab selections for the liquidity page
- [ ] Store tab sleections for markets page
