### ISSUE TITLE
Establish naming conventions - and maintain in glossary

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3119]
## Story

As a Vega user
I want things to be named consistently across all touchpoints
So I can recognise familiar concepts, and don't have to learn exceptions

## Acceptance Criteria

- [ ] I cannot find an example of one concept with two or more names 

## Tasks
- [ ] Collate list of terms which differ
- [ ] Cross reference with backend field titles and descriptions
- [ ] Propose a list of "correct" terms
- [ ] Designate a central place where terms are logged, so we have an agreed source of truth
- [ ] Team and stakeholder review
- [ ] Write tickets for any changes that need to be implemented in our UIs
- [ ] Make changes to the existing glossary 

## Terms for consideration
These terms are often used interchangeably:
- "Assets" (Vega wallet on token site) / "Collateral" (console) / Balances (?)
- Margin "Used" (console orders breakdown modal) / "Margin Allocated" (console positions tab) / Allocated Margin / Margin Allocation
- "Available" margin (console assets pane)
- Lifetime limit (asset details modal in console, and maybe block explorer) / Maximum total deposit amount (deposit form)
- Party (block explorer) / public key (see https://github.com/vegaprotocol/frontend-monorepo/issues/3140)
- Pane / window / tab (all console)

## Additional details / background info

https://github.com/vegaprotocol/specs/tree/master/glossaries - might want a console specific section
How this aligns with core specs also

**Comment by pennyandrews** [comment]
There is a glossary already that might be useful as part of this ticket
