### ISSUE TITLE
Notify users of incomplete withdrawals

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3120]
## Story

As a user who made a withdrawal
I want to be notified if I haven't completed
So that I don't lose funds when the network resets

## Questions
- Can we automate the withdrawal? Is there any way to "pre-approve" the second transaction, so it happens automatically?

## Acceptance Criteria

- [ ] The app automatically completes the withdrawal
OR
- [ ] The app proactively draws my attention to the incomplete withdrawal(s)

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Implement
- [ ] QA
- [ ] UX and design QA

## Additional details / background info
- When withdrawing, first there is a transaction to unlock funds for withdrawal, then there is a seconds transaction to actually withdraw. When the first is complete, [the user is prompted to initiate the second](https://miro.com/app/board/uXjVPUTU6m4=/?moveToWidget=3458764541274784808&cot=14). However, if the user has closed the modal or left the app, they miss this prompt.
- Visiting the withdrawal page after this time will show a list of incomplete withdrawals and allow you to complete. But there is no indication anywhere else on the app. With no prompt to return to the withdrawal page, this could easily be overlooked. Ideally the app would clearly signal this to the user to avoid potential loss of funds.
- I think there are scenarios where there's an enforced delay between unlocking and completing
  <img width="345" alt="image" src="https://user-images.githubusercontent.com/1080322/223699978-bd652feb-19e2-4b1a-8b91-6cd2682a29db.png">
