### ISSUE TITLE
UI toolkit dependencies need to be reviewed

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#3124]
Timebox this task to half a day and do as much as we can

## The Chore

Graph below but:

- Apollo client should not be a dep
- Ethers should not be a dep
- Graphql should not be a dep

We should consider:

- Paneling is not generally going to be used by anything other than console. Suggest moving into its' own package
- Grids are big and not always needed, consider moving to its' own package

```
info Direct dependencies
└─ @vegaprotocol/ui-toolkit@0.7.0
info All dependencies
├─ @apollo/client@3.7.10
├─ @blueprintjs/icons@3.33.0
├─ @ethersproject/abi@5.7.0
├─ @ethersproject/contracts@5.7.0
├─ @ethersproject/json-wallets@5.7.0
├─ @ethersproject/providers@5.7.2
├─ @ethersproject/solidity@5.7.0
├─ @ethersproject/units@5.7.0
├─ @ethersproject/wallet@5.7.0
├─ @graphql-typed-document-node/core@3.1.2
├─ @juggle/resize-observer@3.4.0
├─ @radix-ui/react-popover@1.0.4
├─ @radix-ui/react-select@1.2.0
├─ @radix-ui/react-slider@1.1.0
├─ @radix-ui/react-tabs@1.0.2
├─ @vegaprotocol/i18n@0.0.1
├─ @vegaprotocol/react-helpers@0.0.1
├─ @vegaprotocol/types@0.0.1
├─ @vegaprotocol/ui-toolkit@0.7.0
├─ @vegaprotocol/utils@0.0.1
├─ @wry/equality@0.5.3
├─ aes-js@3.0.0
├─ ag-grid-react@27.3.0
├─ allotment@1.18.1
├─ bech32@1.1.4
├─ bignumber.js@9.1.1
├─ date-fns@2.29.3
├─ ethers@5.7.2
├─ fault@1.0.4
├─ format@0.2.2
├─ graphql-tag@2.12.6
├─ graphql@15.8.0
├─ highlight.js@10.7.3
├─ js-sha3@0.8.0
├─ lodash.clamp@4.0.3
├─ lodash.isequal@4.5.0
├─ lowlight@1.20.0
├─ optimism@0.16.2
├─ prismjs@1.29.0
├─ react-syntax-highlighter@15.5.0
├─ refractor@3.6.0
├─ response-iterator@0.2.6
├─ scrypt-js@3.0.1
├─ symbol-observable@4.0.0
├─ ts-invariant@0.10.3
├─ use-resize-observer@9.1.0
├─ use-sync-external-store@1.2.0
├─ zen-observable-ts@1.2.5
└─ zen-observable@0.8.15
```

## Tasks

- [x] Review list and decide which dependencies should be removed
- [x] Remove the dependencies
  - [x] @apollo/client https://github.com/vegaprotocol/frontend-monorepo/pull/3626
  - [ ] ~~bignumber~~ leaving bignumber for now
  - [x] ethers https://github.com/vegaprotocol/frontend-monorepo/pull/3627
  - [x] @etheresproject/* https://github.com/vegaprotocol/frontend-monorepo/pull/3627
  - [x] graphql-tag https://github.com/vegaprotocol/frontend-monorepo/pull/3626
  - [x] graphql https://github.com/vegaprotocol/frontend-monorepo/pull/3626
  - [x] ag-grid-react
- [x] Add eslint restrict import rules

**Comment by asiaznik** [comment]
From what I've checked here's a list of the deps used in ui-toolkit:

@blueprintjs/icons
@radix-ui/react-accordion
@radix-ui/react-checkbox
@radix-ui/react-dialog
@radix-ui/react-dropdown-menu
@radix-ui/react-navigation-menu
@radix-ui/react-popover
@radix-ui/react-portal
@radix-ui/react-radio-group
@radix-ui/react-select
@radix-ui/react-slider
@radix-ui/react-tabs
@radix-ui/react-tooltip
@storybook/addon-docs/blocks
@storybook/addons
@storybook/react
@testing-library/react
@testing-library/user-event
@vegaprotocol/i18n
@vegaprotocol/react-helpers
@vegaprotocol/tailwindcss-config
@vegaprotocol/utils
ag-grid-community
allotment
bignumbejs
classnames
d3-array
d3-scale
d3-shape
lodash/isEqual
lodash/isEqual
lodash/omit
lodash/random
lodash/sample
lodash/uniqueId
react
react-copy-to-clipboard
react-dom/test-utils
react-router-dom
react-syntax-highlighter
resize-observer-polyfill
tailwindcss/colors
zustand
zustand/middleware/immer

**Comment by asiaznik** [comment]
I think that we can loose the dep of `allotment` as it's only being used in Console and the code in ui toolkit just renames the component.

The ag-grid* deps are:
* ag-grid-progress-bar - this I believe can be moved to the grid lib
* tooltip - TooltipCellComponent - this could be also move to the grid lib

**Comment by mattrussell36** [comment]
That list of deps are the direct dependencies, installing ui-toolkit will also pull in ethers, apollo and lots of other unwated stuff
