### ISSUE TITLE
Competitor Review

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3125]
## The Chore

In the mid term prioritisation with ELT, we agreed it would be beneficial to conduct a competitor review / gap analysis to identify experiences / features / functionality / approaches that we might want to introduce to Console, and consider whether we should prioritise any of them as more important to do over the things we have already prioritised for the next 3-6 months.

## Tasks

- [ ] Decide on how many, and which competitors to include in the review (based on the competitive analysis done in the target audience work)
- [ ] Conduct a benchmarking exercise comparing Console to our top n competitors
- [ ] Discuss findings as a team and shortlist the opportunities we want to consider for prioritisation
- [ ] Come up with a proposal for how we would prioritise the opportunities relative to our mid term plan
- [ ] Discuss and refine/agree with ELT
- [ ] Create tickets in the backlog for the opportunities
