### ISSUE TITLE
Sense check mid term priorities against Barney's wish list

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3126]
## The Chore

Barney has previously shared a long list of features / fixes he would like to cover in Console. Although we think we have probably either already implemented or have in the backlog all those things, we would like to review it just to make sure we've not missed anything that we need to consider in the context of mid term planning.

## Tasks

- [ ] Find and drop into the ticket the slack thread with the list from Barney
- [ ] Review the list adding anything missing onto the prioritisation board in Miro and github backlog
- [ ] Share updated priority list with ELT and refine / finalise based on feedback
- [ ] Share finalised mid term prioritisation in Console slack channel

**Comment by pennyandrews** [comment]
A bit more time needed to iterate the strategy before it's ready to share
