### ISSUE TITLE
Show multiple data panels in one view

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3127]
## Story

As a Trader
I want to see more data related to the market I am looking at in a single view 
So that I can avoid having constantly click between tabs

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Explore and sketch solution (including refining A/Cs)
- [ ] Team and stakeholder review
- [ ] Visual design
- [ ] Team review
- [ ] Implement
- [ ] QA Check (A/Cs met, code quality and adherence to design) 

## Additional details / background info

For example, we could show positions and collateral in one view, or positions and active orders etc.
