### ISSUE TITLE
Persist existing configurability

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3130]
## Story

As a user
I want Console to remember how I have configured it to my preferences
So that I don't have to re do my configurations if I reload Console or leave and come back later

MAY NEED TO BE BROKEN DOWN INTO MULTIPLE TICKETS?

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Identify all current configurations and write A/Cs to cover them
- [ ] Implement persistence of each configuration
- [ ] Quality testing (A/Cs met, code quality)
