### ISSUE TITLE
Tweaks and improvements of floating bottom buttons in table panels

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/frontend-monorepo#3134]
## The Chore

Quick fixes and improvements to issues in bottom floating buttons detected after merging

## Tasks

- [ ] Set the same alignment for buttons in all tables (right-3)
- [ ] use bool prop in collateral tab, instead useParams to conditionally hide/show buttons  
- [ ] add placeholder row for fills tab (since footer covers last rows)
- [ ] add placeholder row for position tab (as well)

## Additional details / background info
-
