### ISSUE TITLE
Token Frontend migration rough edges and issues

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#315]
# Token frontend migration

## Questions:
* Are claim codes being used?
    * Twitter DM problem?

## Test cases from notion:
	* notion.so/vegaprotocol/Test-cases-fc43837bcf964581b7ee79a3ea61b49e

## Tasks

- [x] A bunch of generic regressions
- [x] Removing blueprint
- [x] Table of what is needed for each step
- [x] Sentry, ensure that we are pointing to the correct sentry project (Env vars need updating after deploy)
- [x] Callouts need to accept any react element
    * No loading elements in some of the callouts
- [x] Prepend and append elements in UI toolkit (lozenges with currency)
- [x] ~~Confirmation in transaction callouts~~
    * ~~Should we add Vega scan transactions in~~ Lets do this in this ticket https://github.com/vegaprotocol/frontend-monorepo/issues/534
- [x] Staking is broken investigate why?

## Adding deployments for all envs

- [ ] Stagnet1
- [ ] Stagnet2
- [ ] Devnet
- [ ] Testnet
- [ ] Mainnet

## Regression testing:

Key flows:
* Association
    * Wallet
    * Associate more
    * Vesting contract
    * Amounts credited correctly
    * Desktop wallets/Local wallets
    * Token input
        * Balances
        * Disabled stated
        * Use maximum
        * Approval
* Disassociation
    * Token input
        * Balances
        * Disabled stated
        * Use maximum
* Nominating
    * Remove
        * Remove now
        * Remove at end of epoch
    * Add
    * Click through into a validator
    * Token input
        * Balances
        * Disabled stated
        * Use maximum
    * Remove by dissassociation 
* Claiming
    * Targeted
    * Untargeted
* Governance
    * Empty state
    * Voting
    * Viewing proposals
    * Changing votes
* Rewards
    * Check that epochs are ending properly
    * Will need to do a transfer for this (May require developer to do this, possible core help)
* Withdrawals
    * Token input
        * Balances
        * Disabled stated
        * Use maximum
* Redeeming
* Locked/unlocked
* Tranches pages
* Balance formatting consistency
* Unconnected states
    * Vega only
    * Eth only
    * Both connected
    * Neither connected
    * Add to feature files in TFE that exist
* Pending transaction modals
* Meta mask state changing
    * Chain
    * Account
* Home page
* Mobile across all states
    * Drawer

**Comment by candida-d** [comment]
Fonts here, and possibly the spacing/borders, aren't right
<img width="898" alt="Screenshot 2022-04-26 at 15 55 04" src="https://user-images.githubusercontent.com/62548908/165532537-d9ab50dc-d34b-4dd7-a2a9-9fca15cb70c6.png">

**Comment by jtsang586** [comment]
Minor one but the white border for eth wallet address on withdrawals page is overlapping the address field. I feel like the border isn't needed?
![Screenshot 2022-04-27 at 14 46 27](https://user-images.githubusercontent.com/30622993/165533740-48bb8b5f-edec-425b-adb3-145a52211e90.png)

**Comment by edd** [comment]
- Remove old deployments
- Ensure all deployments are configured to the correct networks and assets
