### ISSUE TITLE
Clarify the differences between rewards and make tool tip text more accurate

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3164]
## The Chore

Participants were expecting to see a staking reward on this table. They were confused why they could not see one.

<img width="1048" alt="Screenshot 2023-03-13 at 11 22 49" src="https://user-images.githubusercontent.com/13255539/224687966-7fa98618-de15-46e3-89b1-3d5d0895bda0.png">

Instead they saw "Infra fees", some were unsure what this was. It could even be interpreted as a deduction on your "rewards".

Hovering over this tool tip, they only read the "Validators" and didn't catch that it also goes to " those who stake them"

<img width="1045" alt="Screenshot 2023-03-13 at 11 24 48" src="https://user-images.githubusercontent.com/13255539/224688405-e34c71ed-f904-40fb-a73e-052ee70a046c.png">

<img width="1044" alt="Screenshot 2023-03-13 at 11 24 32" src="https://user-images.githubusercontent.com/13255539/224688335-df6a0a31-a50e-4bfc-b1fc-c9d82c9d4db0.png">

## Tasks

- [ ] Consider alternate headings, perhaps the difference between organic and supplementary rewards is useful?
- [ ] consider grouping infra and staking columns?
- [ ] Consider alternate copy for tool tips
- [ ] Do it
