### ISSUE TITLE
Update graphql endpoint env vars

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3179]
## The Chore

Graphql endpoints for all environments are changing

## Tasks

- [x] Update VEGA_URL for governance app
  - [x] devnet
  - [x] stagnet1
  - [x] stagnet3
  - [x] mirror
  - [x] testnet
  - [x] validator-testnet
  - [x] mainnet
- [x] Update VEGA_URL for explorer app
  - [x] devnet
  - [x] stagnet1
  - [x] stagnet3
  - [x] mirror
  - [x] testnet
  - [x] validator-testnet
  - [x] mainnet
- [ ] Update network json files in static app (note this might be superseeded by https://github.com/vegaprotocol/frontend-monorepo/pull/3145)
  - [x] devnet
  - [x] stagnet1
  - [x] stagnet3
  - [x] mirror
  - [x] testnet
  - [x] validator-testnet
  - [x] mainnet

Console does not require .env var update is it will read a node from the json files in apps/static

## Additional details / background info

https://vegaprotocol.slack.com/archives/CD4AKTFQT/p1678719711923099
