### ISSUE TITLE
CMD+Click to open a market in another tab

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3188]
## The Chore

Make it so I can CMD+Click (or whatever the windows equivalent is) on a market name and have that market open in another browser tab, just like a normal link would. 

(Right click and open in new tab does appear to work). 

Multi monitors and watching many markets at once is such a common use case that we should support the way the browser normally works.

## Tasks

- [ ] Makes in the the positions, orders etc panels
- [x] Markets in the market switcher
- [x] Markets in the markets list

**Comment by mattrussell36** [comment]
Not sure why default browser behavior is being overridden, but where possible lets ensure we are using native functionality
