### ISSUE TITLE
Find rewards for a specific epoch

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3198]
## User Story

As a Governance dapp user
I want to be able to find rewards for a specific epoch I'm interested in 
So that I can avoid having to browse page by page through all rewards by epoch to find the one I'm interested in

## Acceptance Criteria

- There is a way to find rewards data for a specific epoch I'm interested in without having to browse page by page

## Tasks
- [ ] Define/design the interaction patterns (utilising common patterns where possible) 
- [ ] Implement (utilising existing libraries if at all possible)
- [ ] QA Test (including adherence to design, verify a/c are met and no bugs/defects/regressions have been introduced) 
- [ ] Release

**Comment by pennyandrews** [comment]
Duplications #2952
