### ISSUE TITLE
Improve Account History chart

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#3200]
## Task 

- [ ] Discuss with Jon and David to understand the desired behaviour
- [ ] Explore different options and socialise to see what makes most sense for people
- [ ] Decide what we want to do to make it better
- [ ] Implement changes
- [ ] etc.

For example we might want to aggregate the data into the right intervals, and then fill the gaps in order to make a more useful view 

Review the set of intervals and queries in `account-history-container.tsx`

Maciek has done something similar with candles, drawing horizontal lines when there is a gap between candles, that we could leverage

## Bug (originally reported by David)

x axis seems to always be 8h

> I have more than 24h of history but the day / week etc. buttons don’t seem to do much:

> And the x-axis seems to be always like 8 hours, maybe 9? Is this known or a bug and issue to be filed

![Image](https://user-images.githubusercontent.com/16125548/225289124-4314e9e5-27f4-4b37-b189-21738698e4ab.png)

but the bahviour described isn't actually what happens

**Comment by JonRay15** [comment]
We've killed this
