### ISSUE TITLE
Refine default approval amount for deposits

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3212]
## User Story

As a Console user
I want an approval amount (comparable to other exchanges I'm familiar with) pre-populated when making deposits, that I can then edit to adjust if I need to
So that I can minimise the amount of decisions I have to make, fields I have to complete if I'm happy with what is set by default

## Acceptance Criteria

-  The default approval amount is updated accordingly

## Tasks

- [ ] Review the amounts our competitors use and propose a new default for Vega based on this (see background / additional details below)
- [ ] Share and agree with team and key stakeholders
- [ ] Implement
- [ ] QA Test (verify a/c are met and no bugs/defects/regressions have been introduced functionally or visually) 
- [ ] Release

## Background / additional details

This came up in discussion with Barney during sprint planning on Wednesday 8th March where he directed that we should review what our competitors use as default approval amounts i.e. DYDX and uniswap and do the same as them - what is the common / avg amount they use.

There was also a slack thread related to this a good while back https://vegaprotocol.slack.com/archives/CFXA4EGN7/p1657733387359709

**Comment by mattrussell36** [comment]
Looks like at least some platforms use `MaxUint256` from `@ethersproject`
