### ISSUE TITLE
Datagrid row actions

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3213]
## Story

As a user
I want more space in datagrids
So that I can see more information at any given time and not have repeated button text

## Acceptance Criteria

- [ ] I can perform already existing row actions
  - [ ] Order list: edit, cancel 
  - [ ] Positions: close
  - [ ] Collateral: deposit, withdraw
- [ ] Datagrids with multiple actions are combined into a single UI pattern

## Tasks

- [x] Explore and sketch
- [x] Visual Design
  - [ ] Create icons for available actions: deposit, withdraw, edit, cancel, close, breakdown (use info icon), transfer
- [ ] Ui toolkit development
  - [ ] Adjust styles to match designs
  - [ ] Allow dropdown placement to be set via props, (row dropdown should render to the left of the kebab button)

## Additional details / background info

Currently in some tables we end up with a lot of repeated button text, it already takes up lots of space and if we continue with this pattern we'll lose even more (what if a table row as 5/6 plus actions?).

Current example:
![Screenshot 2023-03-15 at 18 41 49](https://user-images.githubusercontent.com/6803987/225487886-6ca56c7b-e090-4237-8ead-e7c2fe80900e.jpg)

**Comment by joellecharlotte** [comment]
Some [in context designs](https://www.figma.com/file/wBu1KViEZz1JkwpOmhFQrO/Console-V2?node-id=1933%3A12656&t=Utvq54zOetjLsJhQ-1) using the COLLATERAL tab as the example.

[Figma Documentation](https://www.figma.com/file/EaFndX7sV9CgZOdsE2Ilqp/dAPP-Components?node-id=1321%3A11744&t=ZthbMopnX1hTOwFr-1)

For light mode, just swap the dark token colours with the light token colours (but an example of light mode is also in the link above)

A note that I kept this dropdown consistent with other dropdowns / tooltips currently designed or in use across dApps. Some examples below of the Top Nav Dropdown 

![01 1 Dark Action Button Hover](https://user-images.githubusercontent.com/113684458/232977698-9c43f4fc-7fde-4e0e-ad90-e3160d4176bc.png)
![01 2 Dark Action Button Clicked](https://user-images.githubusercontent.com/113684458/232977703-9d5961cc-2624-4489-877d-ea6b67ff05cd.png)
![02 Light Action Button Clicked](https://user-images.githubusercontent.com/113684458/232977705-40e98b16-6f4b-4903-aea2-724f33a89e7c.png)
![04 Documentation](https://user-images.githubusercontent.com/113684458/232977707-ce58f662-28a9-41be-9001-5808a987d7dd.png)
![05 Dropdowns and Tooltips](https://user-images.githubusercontent.com/113684458/232978128-cafe7bc0-3920-438b-a3c9-993016f06acb.png)

**Comment by campbellssource** [comment]
I think it's important that "Cancel" for orders and "close" for positions are not hidden within this menu. At least not until there is another really visible and easy alternative

**Comment by mattrussell36** [comment]
Okay happy to keep those exposed. Perhaps secondary actions can be behind the drop-down. In this case we might want links to BE, copy row ID etc

**Comment by joellecharlotte** [comment]
Noted, have attached the (current) list of possible actions with their respective icons.

<img width="379" alt="Possible Actions   Icons" src="https://user-images.githubusercontent.com/113684458/233052440-bb47558b-efcc-4acb-827c-0a7be97ee9c5.png">
