### ISSUE TITLE
Show total margin available for an order, and where it will come from

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3215]
## Story

As a user placing an order
I want to know how much collateral I can use, and which account(s) it will come from
So I understand how my assets will be used

## Acceptance Criteria

- [ ] I can see the maximum amount of margin I could commit to this order
- [ ] I can find an explanation of how that maximum is calculated
- [ ] I can see where that margin will come from (general account, market margin account, or both)

## Tasks

- [ ] Write tooltips for "deduction from collateral" and "deduction from margin" fields
- [ ] Double check if you can use margin down to the maintenance level, or only down to search level. If it's the latter, update the tooltip for the "Total margin available" field to say so.
- [ ] Implement "Total margin available" field in deal ticket
- [ ] Implement "Deduction from collateral" field in deal ticket
- [ ] ~~Implement "Deduction from margin" field in deal ticket~~ (Barney, Bart, and Neil agreed to remove this on 30th March 2023, see comments for Slack link)
- [ ] Dev and design QA

## Sketch

These fields should be shown underneath the "Margin required" field currently in the deal ticket.

It would be useful if the total margin available, deduction from collateral, and deduction from margin fields were indented a little bit, to show they are all related. However this is not necessary. The ticket https://github.com/vegaprotocol/frontend-monorepo/issues/2834 will add an expanding/collapsing area to collect this extra detail.

![image](https://user-images.githubusercontent.com/1080322/225659294-4ceb4b3d-42de-4aa6-9f73-a64f02b1e186.png)

Tooltip for "Total margin available" field:
> Total margin available = general account balance (166 tDAI) + margin balance (32 tDAI) - maintenance level (10.00 tDAI).

### Calculating available margin
Redrawn from a sketch by Barney. The grey area might actually start at maintenance level, not search level, we need to check this.

![Image](https://user-images.githubusercontent.com/1080322/223423905-bb27252e-ef59-44cf-ae2c-b3ac21a35139.png)

## Additional details / background info
- This task was split out from https://github.com/vegaprotocol/frontend-monorepo/issues/2834

**Comment by bglownia** [comment]
Values calculated as fallow:
Margin required = estimatedTotalInitialMargin - marginAccountBalance
Total margin available = generalAccountBalance + marginAccountBalance -  currentMaintenanceMarginLevel
Deduction from collateral = estimatedTotalInitialMargin - marginAccountBalance
Deduction from margin = (deductionFromCollateral > 0 ? marginAccountBalance : estimatedTotalInitialMargin) - currentInitialMargin

Both deduction values are displayed as 0 if they are lower than 0
