### ISSUE TITLE
Hook up new `estimatePosition` and `estimateFees` queries

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3216]
## The Chore

Once the `EstimateOrder` API method has been refactored (see https://github.com/vegaprotocol/vega/issues/7847) we need to ensure console is using this new logic in the estimations on the deal ticket.

## Tasks

- [ ] Hook up new EstimateOrder API method
- [ ] Restore the "estimated liquidation price" field
- [ ] Compare the accuracy of the new estimations with the old method
- [ ] Check against #3531 

## Additional details / background info
- Dependent on https://github.com/vegaprotocol/vega/issues/7847
