### ISSUE TITLE
View balance changes over time

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#3217]
## Story

As a Trader
I want to see the sum of all my account balances for a given asset (and a way to get a breakdown of each)
So that I can get a picture of my account status over time and analyse what has impacted the changes

## Acceptance Criteria

- [ ] I can see how my total balance across all accounts has changed over time
- [ ] I can see how the total balance breaks down by account (type)
- [ ] I can filter the data by date range
- [ ] I can filter the data by market
- [ ] I can filter the data by asset (?)
- [ ] I can filter the data by account (i.e. general, margin, bond etc.)
- [ ] I can see a breakdown of how money has moved to achieve the balance (driven by ledger entries and aggregated by type)

## Tasks

- [ ] UX
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
There are other tickets for this sort of thing
