### ISSUE TITLE
Link to oracle files from market info

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3224]
## Story

As a trader interested in entering a market
I want evidence of the market oracle's reputation
So I can decide if it is trustworthy

## Acceptance Criteria

- [ ] I can find a link to oracle profile information

## Tasks

- [x] Scaffold oracles lib with NX
- [x] Add a github action to compile proofs in the [the well-known repo](https://github.com/vegaprotocol/well-known/tree/main/oracle-providers) into a single requestable json file
- [x] Add initial logic to look for a file in [the well-known repo](https://github.com/vegaprotocol/well-known/tree/main/oracle-providers) with a filename which matches the key of the oracle for a given market
  - [x] leave scope to expand the library to fetch and parse the contents of the file in future
- [ ] If an oracle spec file is present in the repo, add a link (titled "Oracle profile") to it in the existing oracle section of the market info accordion (if there is no oracle file, do not show the link)
- [ ] Move the oracle info up to the third slot in the market info accordion, after "Key details" and "Instrument"
- [ ] QA

## Sketch
![image](https://user-images.githubusercontent.com/1080322/225942306-ca02cbb4-d509-401d-8605-f2fbeb8eaeaf.png)

## Additional details / background info
- Epic: https://github.com/vegaprotocol/ux-and-visual-design/issues/79
- Oracle profiles will be located in the repo here: https://github.com/vegaprotocol/well-known/tree/main/oracle-providers. The oracle key will be used as the filename.
