### ISSUE TITLE
Show full oracle profile info in markets

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3227]
## Story

As a trader interested in entering a market
I want evidence of the market oracle's reputation
So I can decide if it is trustworthy

## Acceptance Criteria

- [x] I can open the long oracle profile modal from the short oracle profile
- [x] I can find links to all proofs provided for this oracle
- [x] I can see which other markets (if any) are configured to use this key as an oracle, along with links and details for those markets
- [x] The long profile reflects all oracle statuses

## Tasks

- [x] Implement long oracle profile as a component which can be reused in other apps, like governance
- [x] Pull data from github wellknown repo
- [x] Share a deploy preview link with Neil & Joelle
- [ ] QA

## Sketch

See [the Miro board](https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764536859308772&cot=14) for sketches

## Design

designs are in the Governance Figma: [Figma link](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=2502%3A14216&t=U4WmgcydlTw2i3nf-1)

### Showing oracle status in the info pane

![image](https://user-images.githubusercontent.com/113684458/231186735-639b74f7-b451-460d-92e4-6274ad15bc0e.png)

### Showing full oracle profile in a modal

See Figma for the other status states for this modal

![image](https://user-images.githubusercontent.com/1080322/231191738-18ef834e-900c-40f1-8bd1-88fc8c25b484.png)

## Additional details / background info

- This ticket is dependent on:
  - the task "Visual design → Long oracle profile" from the epic: https://github.com/vegaprotocol/ux-and-visual-design/issues/79
  - https://github.com/vegaprotocol/frontend-monorepo/issues/2086
- Oracle profiles will be located in the repo here: https://github.com/vegaprotocol/well-known/tree/main/oracle-providers

**Comment by joellecharlotte** [comment]
Please see the designs below + the [corresponding Figma link](https://www.figma.com/file/wBu1KViEZz1JkwpOmhFQrO/Console-V2?node-id=1841%3A11084&t=VGxjMNmMiMJBsYs4-1).

**An example of an Oracle in the context of the Console UI / Info Tab**

<img width="2155" alt="Info-Tab-with-Oracle" src="https://user-images.githubusercontent.com/113684458/231186454-7e1eb78c-de42-489b-9055-778c0cca42f6.png">

- Each status has a colour + icon
- We've defined some rules around how links display ie. Ideally the proofs fit on one line but if the links are too long then stack them. In Console, we only show the top two proofs.

**The various Oracle statuses**

<img width="2706" alt="Oracle-Statuses" src="https://user-images.githubusercontent.com/113684458/231186735-639b74f7-b451-460d-92e4-6274ad15bc0e.png">

---

It might be useful for context to see the proposed Oracle Detail Pages and compare what info is exposed in the Console Accordion vs what is exposed when you (in future) are able to click to view details.

These designs are in the Governance Figma: [Figma link](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=2502%3A14216&t=U4WmgcydlTw2i3nf-1)
