### ISSUE TITLE
FELT ACTION: Setting a QA Strategy

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3231]
## The Chore

With two new hires in the FE QA team joining soon, we had a discussion on whether we needed to have a Lead for the team. The conclusion was that we didn't, at least not right now...

Instead we want the QA team to form a Community of Practice and work together to define and propose to the FE Leads a QA Strategy

## Tasks

- [ ] Write up and flesh out the list of questions we would like the QA team to consider and propose answers to
- [ ] Collate some guidelines for them to constrain their thinking - i.e. Dex is allergic to cucumber
- [ ] Communicate interim initiatives across frontend teams
 
## Interim initiatives in frontend

 - To prevent the coverage gap getting wider, devs across all apps should be writing end to end tests for the fixes and enhancements they are working on - to allow QA to focus on proactively increasing baseline coverage (Console & Wallet starting now, Governance plan to do this once we reach the 'end' of the work prioritised in the mid term plan, Block Explorer will start when Edd starts back)
 - All teams to focus time in refinement to create testing tickets to ensure we focus on the highest value / priority areas of the products to increase coverage
 
## Questions that need to be answered

- What test stack should we use (for what apps - if it's might not be a one size fits all)
- What do we want to do in terms of Vega capsule usage and development of tools to utilise vega capsule?
- Should we be aiming for more of a test first approach - get QA more closely involved in the design process and involved in writing A/Cs rather than just testing what has been implemented
- How can we best work with A/Cs and specs etc. (we have a hypothesis on this we are trialling with the Wallet team)
- What are the responsibilities of the Devs v QAs when it comes to testing
- What should the role of QA be in our release cycles/workflow (testnet and mainnet - assuming they may be different)
- What are the different types of testing we want to be doing? And on the automated side of things, what should be feature tests v system tests, e2e etc.
- How do we want to distribute QA resource across our different app teams in terms of numbers? 
- Are there specific skills / experience / preferences etc. that make QAs more suitable for one team/app over another or even personality fit considerations etc. 
- What testing is required for a feature to be done (including all types of testing, not just the bits that QA actually do)?
- What is our definition of done and definition of ready?
- How can we best support / enforce the above with our workflow - i.e. ceremonies, collaboration approaches, columns in github, automated actions and workflows etc. 

## Background / additional information

![image](https://user-images.githubusercontent.com/47143694/228357799-27d4c76c-ad69-464c-81c0-8b036023a578.png)
