### ISSUE TITLE
Add post only and reduce only order options to deal ticket

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3238]
## Story

As a trader
I want to be able to place post only and reduce only orders (aka execution flags or order conditions)
So that can minimize risk and maximise profit

## Acceptance Criteria

- [ ] I can place a post only order
- [ ] I can place a reduce only order

more detailed ACs here: https://github.com/vegaprotocol/specs/pull/1640

## Tasks

- [x] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Dev
- [ ] Test

### Changes to deal ticket

![](https://user-images.githubusercontent.com/13255539/228012302-02e4ef31-1838-4d0a-8eb9-674f1bd4dcc0.png)

- Add two check boxes to the deal ticket: one for post only one for reduce only
- Add logic so that only one of these can be selected at the same time. (Radio buttons were considered instead but Checkboxes are more appropriate)
- Possibly a later ticket: add tool tips on hover of each with an explanation of what they mean

Suggested draft content

> Selecting Post only will ensure the order is not filled immediately but is placed on the book as a passive order. When the order is processed it is either be stopped (if it would be filled immediately) Or placed in the book as a passive order until and price taker matches with it

> Selecting Reduce only will ensure that this order will not increase the size of an open position. When the order is matched it will only trade enough volume to bring your open volume towards 0 but never change the direction of your position. If applied to a limit order that is not instantly filled the order will be stopped.

- Link to documentation from these tool tips: https://github.com/vegaprotocol/documentation/pull/544

![](https://user-images.githubusercontent.com/13255539/228012240-40fcc9f0-4b00-4aa1-bb35-b3ae8e2c34ae.png)

- When the TIF is FOC or IOC the Post only check box should be unchecked and disabled 
-The tool tip when hovering over the disabled check box should tell you that this can not be used for the selected TIF

> "Post only" can not be used on "Fill or Kill" or "Immediate-or-canceled" orders

- The selected state of the Execution flags should be remembered as part of the general deal ticket state (size value etc). This includes the change to state that happen when the box is unchecked automatically.

### Changes to Orders table

![Image](https://user-images.githubusercontent.com/13255539/228215293-23eaa093-99b7-420f-98bd-2c63938f15ee.png)

- Add any selected execution flag to the TIF column. Simply append the flag to the end of the time in force text. e.g. "Good til' close. Reduce only" or "Good til` time" if no execution flag is applied.
- ensure that the "[reason](https://docs.vega.xyz/mainnet/api/graphql/enums/order-rejection-reason)" is being displayed in the status if there is one. I know this is the case for rejected orders but not sure if it has been implemented for Stopped orders too. background:  "...it is instead immediately Stopped with a reason informing the trader that the order was stopped to avoid a trade occurring" [source](https://github.com/vegaprotocol/specs/blob/master/protocol/0014-ORDT-order_types.md#execution-flags).

### Changes to toast

none

### 

## Additional details / background info

![](https://user-images.githubusercontent.com/13255539/228014331-5b088805-607a-4827-9a13-a37100083cd0.png)

Specs PR: https://github.com/vegaprotocol/specs/pull/1625
Related core issue: https://github.com/vegaprotocol/vega/issues/7851
Related core pull request: https://github.com/vegaprotocol/vega/pull/7852

**Comment by campbellssource** [comment]
<img width="1665" alt="Screenshot 2023-03-27 at 18 05 05" src="https://user-images.githubusercontent.com/13255539/228014331-5b088805-607a-4827-9a13-a37100083cd0.png">

Changes to deal ticket:

<img width="944" alt="Screenshot 2023-03-27 at 17 57 38" src="https://user-images.githubusercontent.com/13255539/228012302-02e4ef31-1838-4d0a-8eb9-674f1bd4dcc0.png">

<img width="2275" alt="Screenshot 2023-03-27 at 17 57 06" src="https://user-images.githubusercontent.com/13255539/228012240-40fcc9f0-4b00-4aa1-bb35-b3ae8e2c34ae.png">

Changes to order table:

<img width="1842" alt="Screenshot 2023-03-27 at 18 03 29" src="https://user-images.githubusercontent.com/13255539/228013547-aeab2263-9375-4462-b19e-83de366e8342.png">

Adding a new column doesn't feel worth the space. I suggest it is combined with the TIF to be space efficient. This does break the sorting or grouping by "Execution flags" however I don't think there is a good enough use case for this to justify the space. My preferred solution would be to have an extra column that could be turned on but is off by default.

- [ ] Check that the [reason](https://docs.vega.xyz/mainnet/api/graphql/enums/order-rejection-reason) is shown if there is one in the same way that rejected reasons are shown on rejected orders.

>  it is instead immediately Stopped with a reason informing the trader that the order was stopped to avoid a trade occurring

https://github.com/vegaprotocol/specs/blob/master/protocol/0014-ORDT-order_types.md#execution-flags

Changes to toasts:

<img width="1421" alt="Screenshot 2023-03-27 at 18 07 26" src="https://user-images.githubusercontent.com/13255539/228014876-e61cfc1a-5f20-403b-a62d-a2901f94ae33.png">

Changes to positions table: 

covered in https://github.com/vegaprotocol/frontend-monorepo/issues/3240

-----

[discussion](https://vegaprotocol.slack.com/archives/C037STCKMGC/p1679927314918539)
