### ISSUE TITLE
Include fees in transfer amount

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3248]
## Story

As a user
I want to be able to include fees in my transfer amount
So that I can more easily transfer everything to a new key

## Acceptance Criteria

- [ ] I can easily transfer all funds in an account to a different account
- [ ] I can include fees in my transfer amount

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Dev
- [ ] Test

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1679415847321469

**Comment by MadalinaRaicu** [comment]
Would this do? 
@neildawson  @mattrussell36 


![Image](https://user-images.githubusercontent.com/16125548/229495535-f83cc4e5-2c24-4fc9-87d9-482994a7c5a2.png)



![Image](https://user-images.githubusercontent.com/16125548/229495640-62822405-680d-42e6-9c99-c1845b5549e6.png)
