### ISSUE TITLE
Highlight network upgrade proposals

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3257]
## Story

As a governance dapp user
I want to know when a validator has proposed a network upgrade  
So that I have visibility of what's happening with the network, can assess how it might effect me and decide whether I need to take any action

## Acceptance Criteria

- [ ] I can understand that network update proposals are made by validators (and not Vega) 
- [ ] Network upgrade proposals are highlighted on the governance dapp landing page
- [ ] Network upgrade proposals are highlighted on the governance dapp landing page 

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by sam-keen** [comment]
Note: there's no closed date available for the proposals currently, and no way to map block height to a timestamp. So for now, closed proposals will sit at the top of the closed proposals list. @pennyandrews @ckpringle
