### ISSUE TITLE
Announce scheduled network upgrade

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3259]
**_This work has been done by Console team and just needs to be hooked up in Governance app_**

## Story

As a governance dapp user
I want to know when a validator's network upgrade proposal has been passed and an upgrade is now scheduled
So that I have visibility of what's happening with the network, can assess how it might effect me and decide whether I need to take any action

## Acceptance Criteria

- [ ] I can see the network upgrade announcement from anywhere on the governance dapp
- [ ] I can see 'what' version of the protocol the network is planned to be upgraded to 
- [ ] I can see what block height the upgrade will run at
- [ ] I can see the current block height
- [ ] I can understand the impact(s) of the upgrade i.e. how long the network might be offline etc.
- [ ] I can see an up to date estimate of / countdown to 'when' the planned upgrade is estimated to take place
- [ ] There is a way to see all the details of the upgrade proposal (dependent on this ticket is done https://github.com/vegaprotocol/frontend-monorepo/issues/3260)

## Tasks

- [x] Finalise copy
- [x] Visual design
- [ ] Implement the global network upgrade announcement banner (consider whether it makes sense to utilise, or build on, the work Botond has done to [make the sims announcement banner a common component ](https://github.com/vegaprotocol/frontend-monorepo/issues/3244))
- [ ] Hook up the banner to automatically display when there is a scheduled network upgrade
- [ ] QA test (Verify meets acceptance criteria, exploratory testing for bugs, check adherence to visual design, add automated regression tests for the A/Cs)
- [ ] Release

## Sketch

![Image](https://user-images.githubusercontent.com/47143694/230053189-311853c4-b2c1-4831-8861-91ca1734af62.png)

## Additional details / background info

Details of what data is available from the API to facilitate this story can be found in this spike https://github.com/vegaprotocol/frontend-monorepo/issues/2992

Considering a variation in words for console... 

<img width="1032" alt="Screenshot 2023-03-29 at 16 10 20" src="https://user-images.githubusercontent.com/46783148/228584257-4c741e03-4bc8-4255-9f10-e658e136f58a.png">

**Comment by pennyandrews** [comment]
I believe we are now going to get this ticket for free from the work Art is doing for this related ticket on Console https://github.com/vegaprotocol/frontend-monorepo/issues/3316. When he's done I will confirm we have everything we need and it can go into QA and A/Cs added and test written for Governance etc.

**Comment by pennyandrews** [comment]
@asiaznik @sam-keen did this ever get 'hooked up' for Governance now that it's done for Console? Would be great to wrap this up!
