### ISSUE TITLE
Basic network upgrade proposal details page

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3260]
## Story

As a governance dapp user
I want to know the full details of a proposed network upgrade
So that I have visibility of what's happening, can monitor it as it progresses through the validator approval process and can assess how it might effect me

## Acceptance Criteria

- [ ] I can access the network upgrade proposal details page from the [highlight component on the landing page](https://github.com/vegaprotocol/frontend-monorepo/issues/3257)
- [ ] I can access the network upgrade proposal details page from the [relevant list item on the proposals page](https://github.com/vegaprotocol/frontend-monorepo/issues/3257) 
- [ ] I can access the network upgrade proposal details page from the [network upgrade announcement banner](https://github.com/vegaprotocol/frontend-monorepo/issues/3259)
- [ ] I can see 'what' release version of the protocol the network is planned to be upgraded to 
- [ ] I can see what block height the upgrade will run at
- [ ] I can see the current block height
- [ ] I can see the status of the proposal (approved / rejected / pending / unspecified)
- [ ] I can see who has approved it already 
- [ ] I can see the validators who approved it already against the total number of validators required to pass the proposal
- [ ] I can understand the current likelihood of the proposal passing

## Tasks

- [ ] Sketch page and finalise copy
- [ ] Implement the new page view
- [ ] Hook up the data from the api endpoints
- [ ] QA test (Verify meets acceptance criteria, exploratory testing for bugs, check adherence to visual design, add automated regression tests for the A/Cs)
- [ ] Release

## Additional details / background info

Can't find 
- I can see which validator proposed the network upgrade

Details of what data is available from the API to facilitate this story can be found in this spike https://github.com/vegaprotocol/frontend-monorepo/issues/2992

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/230149685-ed18b689-ef70-418f-bc15-fa1cf5a188b8.png)
