### ISSUE TITLE
Opt in telemetry

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3285]
## Story

As a user
I want telemetry to be opt in only
So that user data is not captured without consent

## Acceptance Criteria

- [x] Telemetry is off by default, until user has opted in
- [x] I can opt in/out of telemetry at any time
- [x] I am prompted to opt in to telemetry the first time I use the app
- [x] There is a way to go and change my preferences at a later date
- [x] I can visit the settings page by clicking the link in the main navigation

## Tasks

- [x] Explore and sketch
- [x] Visual Design
- [ ] Implement
- [ ] QA Test
- [ ] Release

## Sketch

[See Miro board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764551429657666&cot=14) for competitor examples and exploration

### Prompt to opt-in

![image](https://user-images.githubusercontent.com/1080322/233092165-f2eb6680-dee8-49c0-8055-4f645fd15bff.png)

## Visual design

See [Joelle's comment below](https://github.com/vegaprotocol/frontend-monorepo/issues/3285#issuecomment-1514723724) for Figma link

![image](https://user-images.githubusercontent.com/113684458/233087246-d72e6c32-65cf-4b04-9a21-f5d3458ac557.png)

## Additional details / background info

Incorporated into the onboarding flow

We don't need to manually configure sentry sessions
Change to their browser based solution
Just check local storage, has user opted in, if they have we call sentry, if not we don't
