### ISSUE TITLE
Update announcement banner: Mainnet SIMS #4 coming soon

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3296]
## The Chore

We would like to update the announcement banner to let people know that Mainnet SIMS #4 is coming soon... 

MAINNET SIMS #4 IS COMING SOON! [LEARN MORE](https://fairground.wtf/)

The update is currently live on vega.xyz for reference
<img width="807" alt="Screenshot 2023-03-28 at 17 19 17" src="https://user-images.githubusercontent.com/47143694/228304652-0bfc18e2-1aba-4714-99b6-62dde7af46c5.png">

## Tasks

- [ ] Update Console banner
- [ ] Update Governance banner
- [ ] Update Block Explorer banner

## Additional details / background info

@notbot00 did some work recently to make it possible to do a single update that shows on all frontend apps that are using the announcements library https://github.com/vegaprotocol/frontend-monorepo/issues/3244 Not sure if this is in a state to be used (quickly) for this or not, but worth checking

**Comment by notbot00** [comment]
@pennyandrews made the update, and the code part was merged in https://github.com/vegaprotocol/frontend-monorepo/pull/3252
