### ISSUE TITLE
Link to liquidity provision docs

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3300]
## Story

As a user
I want to find out how to provide liquidity for a market
So that I can 

## Acceptance Criteria

- [ ] I can easily find my way to the liquidity provision docs that describe how to submit a liquidity provision

## Tasks

- [ ] Explore and sketch (including where in docs is best to link to)
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Implement
- [ ] QA Test

## Additional details / background info

https://vegaprotocol.slack.com/archives/C02KUFHDYAC/p1679998338792499?thread_ts=1679996159.434839&cid=C02KUFHDYAC
