### ISSUE TITLE
Notify of network upgrade proposal

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3306]
## Story

As a console dapp user
I want to know when a validator has proposed a network upgrade  
So that I have visibility of what's happening with the network, can assess how it might effect me 

## Acceptance Criteria

- [x] I can understand that network upgrade proposals are made by validators (and not Vega) 
- [x] Network upgrade proposals are highlighted to me from anywhere in Console (i.e. in a toast with status 'pending')
- [ ] If there are more than one open network upgrade proposal they are all highlighted to me from anywhere in Console (i.e. in toasts with status 'pending') 
- [x] There is a way to see all the details of the release that will be upgraded to on github (until this ticket is done https://github.com/vegaprotocol/frontend-monorepo/issues/3260 at which point it should go to the proposal details page on governance dapp instead)
- [x] I can dismiss the toast (and I won't be shown it again)

## Tasks

- [x] Finalise UX and copy
- [x] Visual design
- [x] Implement network proposals toasts
- [x] QA test (Verify meets acceptance criteria, exploratory testing for bugs, check adherence to visual design, add automated regression tests for the A/Cs)
- [x] Release

## Sketch

<img width="351" alt="Screenshot 2023-03-30 at 06 52 21" src="https://user-images.githubusercontent.com/47143694/228741987-8f352ea1-d98e-4710-9d3a-e553a281b2de.png">

## Additional details / background info

Details of what data is available from the API to facilitate this story can be found in this spike #2992

**Comment by asiaznik** [comment]
Of course it's possible to show a toast for the proposal but what's the value of that? Is reporting about the proposal status really needed here? I believe that what we've already have - notification about upcoming upgrade and upgrade in progress - covers the main AC which is the visibility what happens about the network.

**Comment by bwallacee** [comment]
Currently market-sim doesn't have the capability in order for us to E2E test this. I have created a [ticket](https://github.com/vegaprotocol/vega-market-sim/issues/487) in the repo, and we can look to add an E2E test once it has been implemented
