### ISSUE TITLE
Closed markets

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3312]
## Story

As a user
I want to easily see all closed markets (terminated/settled/closed)
So that I can review market history

## Acceptance Criteria

- [ ] I can see a closed markets tab
- [ ] When on the closed markets tab only `STATE_CLOSED/STATE_TRADING_TERMINATED/STATE_SETTLED` markets are shown
- [ ] The closed markets table shows the most pertinent information for closed markets, which may differ from open and proposed markets

## Tasks

- [ ] Explore and sketch
- [ ] Agree what information is most important to know for terminated and settled markets
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Dev
- [ ] Test

## Sketch

[Miro exploration](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764548499363099&cot=14)

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1679068209890369
