### ISSUE TITLE
Show available balance in asset selector when withdrawing

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3313]
## Story

As a user
I want to see balances when using the asset selector for withdrawals
So that I can more easily find the asset I'm looking for

## Acceptance Criteria

- [ ] I can see the balance of the general account next to each asset

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Dev
- [ ] test

## Sketch

See exploration in [the Miro board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764551321026434&cot=14)

![Image](https://user-images.githubusercontent.com/1080322/231782202-8756781e-af16-4a52-8410-93e7a394b64c.png)

![image](https://user-images.githubusercontent.com/1080322/231783368-30692fb7-201d-4916-9a7d-d82060c90f44.png)

## Additional details / background info

- Slack conversations:
  - https://vegaprotocol.slack.com/archives/C037STCKMGC/p1680102585845039
  - https://vegaprotocol.slack.com/archives/C037STCKMGC/p1680187258874979
- Related to #3314

**Comment by mattrussell36** [comment]
> Assuming the ID is mostly used for differentiating assets with the same name, could we only show the ID when there are two assets with the same name?

I'd say it would be more useful to show the contract address (at least for now whilst we only deal with ERC20), but I wouldn't want to ever show _only_ the contract address. Some combination of symbol (or name) with contract address (or truncated contracted address) would be best

**Comment by neildawson** [comment]
@joellecharlotte, me and @mattrussell36 just met and agreed to go with concept H (embedded above) which preserves the contract address

Could you please work up a design for this?

**Comment by joellecharlotte** [comment]
Here are the designs + [the Figma link ↳ ](https://www.figma.com/file/wBu1KViEZz1JkwpOmhFQrO/Console-V2?node-id=1943%3A13281&t=YNwkal1noyp4D6pR-1)

These use DEPOSITS as the example but the pattern is the same for WITHDRAWELS.

![01 1 Asset Selected](https://user-images.githubusercontent.com/113684458/233316977-0f0bd8b7-933f-427a-9d8c-066207f6a24f.png)
![01 2 Asset Dropdown Expanded](https://user-images.githubusercontent.com/113684458/233316987-c899c0d3-bcdd-4047-a012-8287de09befd.png)
