### ISSUE TITLE
Show available balance in asset selector when depositing

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3314]
```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```
## Story

As a user
I want to see balances when using the asset selector for deposits
So that I can more easily find the asset I'm looking for

## Acceptance Criteria

- [ ] I can see the balance of the asset in my Ethereum wallet next to each asset

## Tasks

- [x] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Dev
- [ ] test

## Sketch

See exploration in [the Miro board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764551321026434&cot=14)

![Image](https://user-images.githubusercontent.com/1080322/231782202-8756781e-af16-4a52-8410-93e7a394b64c.png)

![image](https://user-images.githubusercontent.com/1080322/231783368-30692fb7-201d-4916-9a7d-d82060c90f44.png)

## Additional details / background info

- Slack conversations:
  - https://vegaprotocol.slack.com/archives/C037STCKMGC/p1680102585845039
  - https://vegaprotocol.slack.com/archives/C037STCKMGC/p1680187258874979
- Related to #3313 

## Ideas
- Could have a skeleton view load in with a spinner whilst we collate the balance data to display
- We'll need to do the following to show balances in the user's Ethereum wallet
  - Get all enabled, active and allow listed assets for Vega (to avoid unnecessary network requests)
  - For each asset call balanceOf on the tokens contract `tokenContract.balanceOf(ethAddress)`
- For now I think it will be safe to call balanceOf for every asset, but as a stretch task we might want to look at virtualizing the list so that the requests are only made for assets that are visible (with some amount of px buffer)

**Comment by joellecharlotte** [comment]
Here are the designs + [the Figma link ↳ ](https://www.figma.com/file/wBu1KViEZz1JkwpOmhFQrO/Console-V2?node-id=1943%3A13281&t=YNwkal1noyp4D6pR-1)

These use DEPOSITS as the example but the pattern is the same for WITHDRAWELS.

![01 1 Asset Selected](https://user-images.githubusercontent.com/113684458/233316977-0f0bd8b7-933f-427a-9d8c-066207f6a24f.png)
![01 2 Asset Dropdown Expanded](https://user-images.githubusercontent.com/113684458/233316987-c899c0d3-bcdd-4047-a012-8287de09befd.png)
