### ISSUE TITLE
SPIKE: Notification history

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3315]
## Spike Tasks

- [ ] Look into options for implementation to achieve the below
- [ ] Update #3535 / Create additional tickets as required

Some of the questions that need to be answered: 

- Do we show the history of every toast considering one action may have triggered multiple toasts showing how the status changes?
- How does the notification history relate / overlap with the ledger entry table, feels like there is some overlap
- When someone opens console after being away for a while, do we notify them in some way of the things that happened whilst they were away? Show the toasts or a red dot on a notification bell type icon to get them to open the history and see everything there?
- Does the history include all notifications for all network proposals / changes or just the most recent of each type etc. and how far back in 'time' can we / is useful to store
- Is this notification history the solution to handling toasts that probably shouldn't dismiss - like complete withdrawal
- Could we / should we have some kind of retry functionality that prompts you to go to the history to act on stuff you missed as a toast?
 
 
## Story

As a console dapp user
I want to be able to see a history of the notifications (toasts) I have received 
So that I can refer back to them in case I missed something or want to find more details i.e. a transaction or network upgrade proposal

## Acceptance Criteria

- [ ] I can access a history of notifications from anywhere on console
- [ ] I can filter by notifications triggered by me and those triggered by the network
- [ ] I can see the most recent notifications at the top of the list
- [ ] I can scroll the list to see older transactions
- [ ] I can see the latest status of the notification
- [ ] There is a way to see the details of the thing I was notified about (i.e. link to the transaction details on block explorer or the network upgrade proposal on governance)

## Tasks

- [ ] Finalise UX and copy
- [ ] Visual design
- [ ] Implement network proposals toasts
- [ ] QA test (Verify meets acceptance criteria, exploratory testing for bugs, check adherence to visual design, add automated regression tests for the A/Cs)
- [ ] Release

## Sketch

<img width="422" alt="Screenshot 2023-03-30 at 06 59 07" src="https://user-images.githubusercontent.com/47143694/228743139-e6d83e4f-3d60-48d4-b4af-e61c8d5c752e.png">

## Additional details / background info

Some related feedback from Jon: 

Just had a toast pop up on Console telling me about a spam pow proposal.

Which was very nice, and I enjoyed it, but it did then drop off a few seconds later, and Barney loaded console and he doesnt see it.  What is the logic for when they come up?  It feels like it just came up at the exact moment the proposal was made (13:40) and then dropped off.

Then the more complex bit is I think ideally Console would show you any proposals that have occurred since you were last here.  You shouldnt need to be actively using Console at the time of proposal to get notified.

Alternatively I guess you could just always bring up toasts for any active proposals on each load and let the user dismiss them, although depending on how many proposals we see that might get painful.

Depends a bit on how many proposals we think will ever be open at one time.  Network params probably not many, but I guess once we're live there might be a number of market proposals open ALL THE TIME ... at least if we're vaguely successful. 

Maybe grouped notifications is an option.  Probably needs a bit of thought and design.
