### ISSUE TITLE
Announce scheduled network upgrade

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3316]
There are two tickets created for this Governance sprint related to this ticket to solve the problems around the linking to the [github release](https://github.com/vegaprotocol/frontend-monorepo/issues/3376) and [estimating / counting down a time to the upgrade](https://github.com/vegaprotocol/frontend-monorepo/issues/3377). We might want to decide to do these tickets ourselves in order to be able to complete this announcement ticket to the full. 

## Story

As a console user
I want to know when a validator's network upgrade proposal has been passed and an upgrade is now scheduled
So that I have visibility of what's happening with the network, when, and can assess how it might effect me and decide whether I need to take any action

## Acceptance Criteria

- [ ] I can see the network upgrade announcement from anywhere on the console dapp
- [ ] I can see 'what' version of the protocol the network is planned to be upgraded to 
- [ ] I can see what block height the upgrade will run at
- [ ] I can see the current block height
- [ ] I can see 'when' the upgrade is estimated to take place (based on the current and planned block height - instructions to calculate time in the future are here https://docs.vega.xyz/testnet/node-operators/how-to/upgrade-network)
- [ ] I can understand the impact(s) of the upgrade i.e. how long the network might be offline etc.
- [ ] There is a way to see all the details of the release that will be upgraded to on github https://github.com/vegaprotocol/vega/tags (until this ticket is done https://github.com/vegaprotocol/frontend-monorepo/issues/3260 in which case it should link to the upgrade proposal details page)
- [ ] I can close the banner (to free up space on my screen when I'm trading)
- [ ] When I have closed the banner there is a way for me to still see that there is a network upgrade planned  
- [ ] When I have closed the banner there is a way for me to re-open the banner to see the details of the planned upgrade
- [ ] Whether the banner is open or not, I can see a count down to the planned network upgrade  
- [ ] The above criteria are true for the Governance app
- [ ] The above criteria are true for Block Explorer

## Tasks

- [ ] Finalise UX and copy
- [ ] Visual design
- [ ] Implement the global network upgrade announcement banner (consider whether it makes sense to utilise, or build on, the work Botond has done to [make the sims announcement banner a common component ](https://github.com/vegaprotocol/frontend-monorepo/issues/3244))
- [ ] Hook up the banner to automatically display when there is a scheduled network upgrade
- [ ] Make it work across all three apps in the frontend mono-repo
- [ ] QA test (Verify meets acceptance criteria, exploratory testing for bugs, check adherence to visual design, add automated regression tests for the A/Cs)
- [ ] Release

## Sketch

<img width="1136" alt="Screenshot 2023-03-30 at 07 12 47" src="https://user-images.githubusercontent.com/47143694/228745617-d0366177-c86e-4ca2-8f9b-3a9521bac146.png">

<img width="1102" alt="Screenshot 2023-03-30 at 07 13 14" src="https://user-images.githubusercontent.com/47143694/228745724-f3bbb0d0-d41b-4ebc-9230-3c3a5f674a08.png">

## Additional details / background info

Details of what data is available from the API to facilitate this story can be found in this spike https://github.com/vegaprotocol/frontend-monorepo/issues/2992
