### ISSUE TITLE
SPIKE: Network upgrade in progress now, or happened recently

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3319]
We need to understand more about what we can get from the API and what we need to gather from other places

For example: if I come to console, there was an upgrade scheduled to have taken place recently, but nothing is happening... is the upgrade in progress still or is there another problem happening. 

What if I'm connected to a node that hasn't come back up so blocks haven't progressed, but others have.
Could be simple things "upgrade scheduled for x, visit block explorer to find out what's happening"

Define the scenarios and define what we can do to help people for each

## Story

As a console user
I want to know when a network upgrade is taking place
So that I have visibility of what's happening with the network, am reassured that nothing bad is happening, and am provided with information to help me decide what action I need to take

## Acceptance Criteria

- [ ] I can see that a network upgrade is taking place
- [x] I can see 'what' version of the protocol the network is planned to be upgraded to 
- [x] I can see what block height the upgrade will run at
- [x] I can see the current block height
- [x] I can see 'when' the upgrade is estimated to take place (based on the current and planned block height - instructions to calculate time in the future are here https://docs.vega.xyz/testnet/node-operators/how-to/upgrade-network)
- [ ] I can understand the impact(s) of the upgrade i.e. how long the network might be offline etc.
- [x] There is a way to see all the details of the release that will be upgraded to on github https://github.com/vegaprotocol/vega/tags (until this ticket is done https://github.com/vegaprotocol/frontend-monorepo/issues/3260 in which case it should link to the upgrade proposal details page)
- [x] I can close the banner (to free up space on my screen when I'm trading)
- [x] When I have closed the banner there is a way for me to still see that there is a network upgrade planned  
- [ ] When I have closed the banner there is a way for me to re-open the banner to see the details of the planned upgrade
- [x] Whether the banner is open or not, I can see a count down to the planned network upgrade  

## Tasks

- [ ] Consider whether it makes sense to utilise the work done to create a [Holding page to temporarily block features](https://github.com/vegaprotocol/frontend-monorepo/issues/1784) or not
- [ ] Finalise UX and copy
- [ ] Visual design
- [ ] Implement
- [ ] QA test (Verify meets acceptance criteria, exploratory testing for bugs, check adherence to visual design, add automated regression tests for the A/Cs)
- [ ] Release

## Sketch

<img width="559" alt="Screenshot 2023-03-30 at 10 36 02" src="https://user-images.githubusercontent.com/47143694/228794849-f06cb19e-206d-4ee5-8b52-7b7caadc10b5.png">

## Additional details / background info

Details of what data is available from the API to facilitate this story can be found in this spike https://github.com/vegaprotocol/frontend-monorepo/issues/2992

**Comment by JonRay15** [comment]
One the upgrade has concluded we also need a solution for what to show on console for the period it was out.

Currently we just show a gap.

![image](https://user-images.githubusercontent.com/89918817/231804568-90ffd067-8dba-49bc-a0c7-bb6caaec1983.png)

**Comment by JonRay15** [comment]
Consensus seems to be we should show a line for "forward fill" and take the last close price as the open, close, high and low. for all intervals until we have data again.  Same thing we should do for any interval that doesnt have any volume. 

Kucoin example

![image](https://user-images.githubusercontent.com/89918817/231811729-d8e5d32b-4c02-42e1-be63-d5dc0773689b.png)

**Comment by JonRay15** [comment]
Note that in te above, if the next trade was at a diff price you will still get a vertical jump like we see about 3/4 across on the above, but you should never have a horizontal gap.
