### ISSUE TITLE
SPIKE: Define target experience for improved market list

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3327]
## The Spike

We have a 'should do' item in our mid term prioritisation to improve the markets list (& information) in console so need to explore and define a target experience for the market list that we want to aim for and break it down into prioritised tickets to deliver that experience incrementally

To a large extent the improvements might be visual, for example, Barney really likes Kraken's new experience market list design as it uses icons and other elements that create visual interest. 

However there are some potential new features we could also implement to make the markets list more valuable / usable, for example 

- Making it searchable
- Adding useful filters based on things like tags, settlement asset, product etc.

We should consider all 3 market lists as part of this spike, considering whether we actually need these different lists? And if so what information should be on each, how they should be presented and what features / functionality should be available to help people find and get to a market they are looking for / interested in 

AND we should consider how the addition of new product types like spot and perpetuals would be presented / effect what we do with the markets list 

## Tasks

- [ ] Sketch a target experience
- [ ] Review and refine with team (and stakeholders)
- [ ] Breakdown and write stories as github issues
- [ ] Review and prioritise issues into the backlog with the team

## Additional details / background info

Barney and Jon recently defined a market list they want to add to the website landing page, this might give some insight also in to the sort of visuals we might be able to achieve as well as the sorts of data we might want to consider displaying

<img width="1795" alt="Screenshot 2023-03-30 at 16 35 26" src="https://user-images.githubusercontent.com/47143694/228889358-522ae6d0-ac25-4ad9-837a-dff6b0e50909.png">
<img width="1782" alt="Screenshot 2023-03-30 at 16 35 35" src="https://user-images.githubusercontent.com/47143694/228889332-98925c34-3182-4ae4-aef6-b4c07e2edf31.png">

Kraken market lists for reference:

<img width="2219" alt="Screenshot 2023-03-30 at 16 32 00" src="https://user-images.githubusercontent.com/47143694/228888020-598c3453-5b86-4378-a830-1de7f5916ae4.png">
<img width="904" alt="Screenshot 2023-03-30 at 16 31 48" src="https://user-images.githubusercontent.com/47143694/228888024-0080cc55-5bac-4d37-aeed-a84ffc484a4f.png">
<img width="893" alt="Screenshot 2023-03-30 at 16 31 29" src="https://user-images.githubusercontent.com/47143694/228888028-ce824ea5-3cd5-44f7-b636-7df864ba58d6.png">
