### ISSUE TITLE
Make volume cells in orderbook update the deal ticket

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#3330]
## Story

As a trader looking to make some easy orders
I want to click on the 'cumulative volume' cell in the order book
So that I don't need to type in a 'size' for my order

## Acceptance Criteria

- [x] I can click on a 'price' cell in an orderbook row to update the deal ticket with the that price
- [ ] I can can click on the 'cumulative volume' cell in any row to update the deal ticket
- [ ] Changing the size by clicking on any volume cell should set the size to the size that I click on. It should not do any maths to add that to the currently entered size
- [ ] Value entered into size field on click should be the same as the value clicked in the book.
- [ ] Add tooltip to indicate that clicking will update size field

## Tasks

- [ ] Make 'cumulative volume' cells clickable
- [ ] Verify that clicking the volume/cumulative volume cell should strictly enter the size that you click on, even if that size is above the current trader's balance. This would make the order form display an error. 

## Video of using the 'price' cell (which currently works)

https://user-images.githubusercontent.com/6678/229073753-c148d181-1d5f-48eb-98b0-3f1f200c8db3.mov
