### ISSUE TITLE
Spike: Close position button for more extreme scenarios (use persistent orders or make it clear the close failed)

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3341]
## Story

~~As~~ a When using the close button on the positions panel
I want the position to be closed asap. even if market conditions meaning if can't be fully closed right away
So that I end up with a 0 open volume 

<img width="1323" alt="Screenshot 2023-03-31 at 16 20 17" src="https://user-images.githubusercontent.com/13255539/229162084-6aad3c11-0dc1-4c8a-a20b-8dd636ba9648.png">

## Background

The exiting close button will 2 two things: cancel all existing orders on that market & submit a `Market order`, `IOC` with `Reduce only = true` and a `size that matches your existing open vol`. This was done in https://github.com/vegaprotocol/frontend-monorepo/issues/3240

This is good, but it does leave scenarios where the users position will not be fully closed. This ticket is to find + implement something that Is less likely to fail.

## Scenarios
- The market goes into an auction just as you hit submit (or your order a causes the auction). The order fails because auctions don't support Market orders* (*Vega doesn't have Persistent Market orders yet I.e a market order with a TIF other than IOC or FOK)
-  There isn't sufficient liquidity on the book to close your order. In this case the IOC will reduce your exposure as much as it can but the rest of your open volume will remain open with no orders to close it.

### Possible approach

One [proposed solution](https://vegaprotocol.slack.com/archives/C037STCKMGC/p1679926333956819?thread_ts=1679925280.948239&cid=C037STCKMGC) is to use a persistent limit order instead.

> You could argue it ought to place a v high/low priced persistent limit order (we don't support persistent market orders yet) now that we have reduce only? :thinking_face:

Closing positions that are long would send a SELL GTC with a price of 0.

- [ ] Task: decide how to set the price for a closing Short position

- $largest_allowable ?
- Mark_price * 10 ?

## Alternative approach 1

> Keep the close button as is and have a clear (non-toast) message after the order is process so they know they have open vol

> 3,440 of 10,000 closed, 6,560 remains open

## Alternative approach 2

> use the market simulating limit order and ALSO check how much executes on entry then if it doesn't all trade, have a message like:

```
   3,000 of 10,000 closed, pseudo-market (?) order to close 7,000 remains on the book.

[ Edit limit price for close order ]    [ Cancel closing remainder of position ]    [ OK ] 
```

## Alternative approach 4

> The alternative re:slippage of course is to have a "max close-order slippage" setting that we default to say 2% or 5% and let people configure in the settings tab, and actually calculate a limit price (whether IOC, FOK, or persistent order) for these closes, then we can report back that we only closed some or didn't close any (if we choose FOK) because the slippage would be too high, and you need to do it manually in that case.

## Alternative approach 5

Ask users to choose what it does

> tbh in settings I would probably have:
Close position with [ default = FOK | IOC | GTC ]
Max close position slippages [ default = 2% or whatev ]

## Acceptance Criteria

- [ ] Make it easier for users to get a full close in extreme conditions
- [ ] Consider using a size that is larger than the open volume (incase your exposure increased as order was submitted)
- [ ] TBD

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
