### ISSUE TITLE
Re-enable SRI for stats

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#335]
#334 disables SRI. My guess is that the hashes generated aren't right? Or are served incorrectly? I am not sure. Either way:

# Tasks
- [x] Actually read up on what enabling SRI in webpack entails
- [x] Ensure hashes are generated correctly for CSS & JS bundles
- [ ] Ensure hashes are written in to HTML
- [ ] Turn it on again
