### ISSUE TITLE
Block Explorer Batch Cancels should show what they cancel instead of -

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#3359]
## The Chore

<img width="902" alt="Screenshot 2023-04-04 at 12 29 10" src="https://user-images.githubusercontent.com/6678/229778337-50b8d80e-b6e7-43f8-b68e-6e747f340db6.png">

The cancel in these screenshots cancel all orders in the market. I *thought* this had been addressed, but it's still happening on validator testnet, so here's a new ticket

## Tasks

- [x] Batch order > Cancel with market ID > show 'Cancel all in market: '
- [x] Batch Order > Cancel with order id > Show the order it cancels
- [ ] Batch Order > Cancel with no id > Show 'Cancel all orders'
- [ ] Single order > Cancel with market ID > show 'Cancel all in market '
- [x] Single Order > Cancel with order id > Show the order it cancels
- [ ] Single Order > Cancel with no id > Show 'Cancel all orders'
