### ISSUE TITLE
Support improved error coding for batch orders

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#3360]
## The Chore

https://github.com/vegaprotocol/vega/pull/8063 added new, improved error reporting for batches that gives us more information

## Tasks

- [ ] In transaction lists, only show an ❌ for a batch that fails 100%
- [ ] Decide how to represent a batch with a mix of success and failure. Either ✅ or something else to imply mixed results
- [ ] Update status code display in shared header to correctly report a mixed result
- [ ] Add a ❌ or ✅ for each row in batch view

71 is partial failure. 70 is complete failure.
