### ISSUE TITLE
Improve messaging around withdrawal delays

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3364]
## Story

As a user withdrawing an asset
I want it to be very obvious that my withdrawal has been delayed
So that I know to come back and complete later

## Acceptance Criteria

- [ ] After releasing funds, if there is _NO_ withdrawal delay, it is clear I need to perform another action to complete (see sketch A1)
- After releasing funds, if there _IS_ a withdrawal delay… (see sketch A2)
  - [ ] …I am told that my withdrawal is incomplete, and I must return to complete it
  - [ ] …I am told exactly when I will be able to complete the withdrawal
  - [ ] …I am given some indication of how/where I will complete the withdrawal after the delay has passed
- [ ] If I try to complete a withdrawal that is still delayed, it is clear I need to come back after the delay has passed, because the withdrawal will not be completed automatically. (see sketch A3)
- [ ] If I try to complete a withdrawal with no wallet connected, I am prompted to complete the correct wallet (see toast 6 in the flow diagram)
- [ ] NONE of the toasts in the flow chart below should time out, all should remain on screen until dismissed by the user

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [ ] Team review
- [ ] Implementation
- [ ] QA

### Flow diagram

Logic for when each toast should be shown.

Note toasts 3 and 4 could also be implemented in https://github.com/vegaprotocol/frontend-monorepo/issues/3459.

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/7fc3bb41-4e97-41ae-b993-c948173d095e)

### Old vs. new

Comparing the existing toasts with the new toasts proposed in this ticket.

![image](https://user-images.githubusercontent.com/1080322/229820849-99bfedc3-dd66-4fb4-b1ee-48258ab74a14.png)

## Additional details / background info
- Related: https://github.com/vegaprotocol/frontend-monorepo/issues/3366
- Spin off ticket from https://github.com/vegaprotocol/frontend-monorepo/issues/3103
