### ISSUE TITLE
Simple Trading App Features Draft

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#337]
This ticket is to start thinking about the list of initial features we need for the simple trading app. You can think of this as an MVP. The below shows a summary of the stories and they should be converted to individual user stories.

## Setup
- [x] #377 
- [x] #378 

## Wallet
- [x] #339
- [ ] #340

## Trading Information 
- [x] #338
- [x] #341
- [x] #342

## Making a Trade
- [ ] #343
- [x] #344
- [x] #345
- [x] #346
- [ ] #347
- [x] #348
- [x] #352
- [x] #353

### Later
- [ ] **As a user I would like to select the type of trade at market or limit (Market/Limit)**
- [ ] **As a user I would like to select the Time in Force under advanced settings for a trade (button with cog icon)**

## Trading Portfolio
- [x] #354
- [x] #355

## Markets
- [x] #356
- [x] #358
- [ ] #359

### Later

- [ ] **As a user I would like to filter by derivative type (“Futures”, “Options”)**
- [ ] **As a user I would like to see the charts for different markets (maybe v2)**

## Liquidity

- [x] #360
- [x] #361
- [x] #362
- [x] #363
- [x] #364
- [ ] #365
- [x] #366

**Comment by pennyandrews** [comment]
Closing this as Console-lite is on hold indefinitely
