### ISSUE TITLE
Show pegged shape for liquidity provision

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3373]
## Story

As a liquidity provider and trader
I want to see the pegged shape of a liquidity provision
So that I can better under stand the market and liquidity

## Acceptance Criteria

- [ ] I can see the full pegged shape of the liquidity provision
- [ ] I can see liquidity order for the buy side
- [ ] I can see the liquidity order for the sell side

https://github.com/vegaprotocol/specs/blob/e6750a3b954caeadd10aa74c0b88ed78f30b6e80/user-interface/7003-MORD-manage_orders.md#7003-MORD-017

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Dev
- [ ] Test

## Sketch

Transferred from #1716 

<img width="1790" alt="lp-from-order-sketh" src="https://user-images.githubusercontent.com/6803987/229978297-18df7bae-d12a-4989-94e5-164fa801bf3b.png">

## Additional details / background info

This issue has been broken out from #1716
