### ISSUE TITLE
Link to release in github from network upgrade proposal details

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3376]
## Story

As a Governance user
I want to be able to easily find the details of the software release version i.e. release notes etc.
So that I can understand the changes the upgrade includes and can assess how it might effect me and my open / planning ed trading and governance activity

## Acceptance Criteria

- [x] I can get to the details of the release that the network is proposed to be upgraded to on github i.e. https://github.com/vegaprotocol/vega/tags 

## Tasks

- [x] Work out the logic needed to identify which repo the release has been tagged in so we can display the correct link for the proposal being viewed
- [ ] Implement
- [ ] QA test (Verify meets acceptance criteria, exploratory testing for bugs, check adherence to visual design, add automated regression tests for the A/Cs)
- [ ] Release

## Additional details / background info

Currently, releases could sit under https://github.com/vegaprotocol/vega-dev-releases/releases or https://github.com/vegaprotocol/vega/releases and there isn't any obvious way to know which for any given release / network upgrade proposal - so we will need to create some logic to check both links and display the one that doesn't return a 404 (or something) 

## Sketch

Just the bit of the sketch in the blue square is relevant for this ticket:
<img width="1178" alt="Screenshot 2023-04-05 at 10 58 52" src="https://user-images.githubusercontent.com/47143694/230048142-9c43cae0-a52f-41e4-bca5-ea7a9e8f266d.png">
