### ISSUE TITLE
Estimate time to network upgrade

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3377]
## Story

As a Governance user
I want to understand roughly when I can expect an approved network upgrade to take place 
So that I can decide if and when I need to take any action

## Acceptance Criteria

- [ ] I can see an up to date estimate of / countdown to 'when' the proposed / planned upgrade is estimated to take place from the proposal details page

## Tasks

- [ ] Investigate with stakeholders what data is available / logic is needed to be able to communicate a valuable enough estimate / countdown of 'time' / 'progress' towards upgrade (Barney, Jeremy, David, Edd???)
- [ ] Finalise UX and copy
- [ ] Visual design
- [ ] Implement the estimate / countdown in the proposal details view
- [ ] Implement the estimate / countdown in the announcement banner
- [ ] Implement the estimate / countdown in the persistent notification in the dapp header
- [ ] QA test (Verify meets acceptance criteria, exploratory testing for bugs, check adherence to visual design, add automated regression tests for the A/Cs)
- [ ] Release

## Additional details / background info

Estimated upgrade time is based on the current and planned block height - instructions to calculate time in the future are here https://docs.vega.xyz/testnet/node-operators/how-to/upgrade-network

## Sketch

![Image](https://user-images.githubusercontent.com/47143694/230068631-7a3afb61-082a-4f6b-84e3-6f402f143dda.png)
