### ISSUE TITLE
Network upgrade likelihood to pass 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3386]
## The Chore

What we need to achieve and who for

## Acceptance Criteria 
- [ ]  I can see the validators who approved it already against the total number of validators required to pass the proposal
- [ ]  I can understand the current likelihood of the proposal passing

## Tasks

- [ ] What do we need to do first
- [ ] and then what?
- [ ] Etc.

**Comment by ckpringle** [comment]
https://github.com/vegaprotocol/frontend-monorepo/issues/3260
