### ISSUE TITLE
Connect my Vega wallet

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#339]
## Task
As a user I would like to connect my Vega wallet

### Notes:
Some work has been done in the PoC, this is going to need tests writing

## AC

- [ ] Provide simple explanation on how to create a vegawallet network using the desktop app or cli
- [ ] Provide simple explanation on how to deposit money into the wallet
- [x] The user can use multiple keys in their wallet

**Comment by elmar-vega** [comment]
<img width="644" alt="Screenshot 2022-05-05 at 14 45 37" src="https://user-images.githubusercontent.com/102954831/167457828-150b139a-a227-4001-aa8d-55ad20dc8519.png">
