### ISSUE TITLE
Persist pane sizes

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3392]
## Story

As a user
When I have adjusted the pane sizes to my preferences
I want pane sizes to be persisted when I refresh my browser
So that I don't have to resize to my desired layout every time

## Acceptance Criteria

- [x] I can resize panes
- [x] When I switch to view another market, I can see the pane sizes I specified are preserved
- [x] When I refresh the page I am looking at, I can see the pane sizes I specified are preserved
- [x] When I switch between light and dark themes, I can see the pane sizes I specified are preserved
- [x] All markets use the same pane sizes
- [x] Panes are also persisted for the Portfolio page

## Tasks

- [x] Implementation
- [ ] Write tests (unit and e2e) 
- [ ] Code review
- [ ] Verify acceptance criteria met
- [ ] Exploratory testing to find bugs and edge cases
- [ ] Write automated regression tests for the A/Cs and add to spec doc (expanding on A/Cs where possible)

## Notes

- We need to consider the breakpoint that splits the bottom pane in two
- We need to store pane sizes as percentages so that it doesn't matter if I've changed my browser size in between
