### ISSUE TITLE
Persist data grid column sizes (per pane)

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3393]
## Story

As a user
When I have adjusted the table layout to my preferences
I want column sizes to be persisted (per pane) when I refresh my browser
So that I don't have to resize to my desired table layout every time

## Acceptance Criteria

- [x] I can resize columns
- [x] When I switch to view another market, I can see the table column sizes I specified are preserved
- [x] When I refresh the page I am looking at, I can see the table column sizes I specified are preserved
- [x] When I switch between light and dark themes, I can still see the table column sizes I specified are preserved
- [x] All markets use the same column sizes
- [x] This same behaviour is true for every table in console where I can adjust column sizes
- [ ] There is a way to reset to the default column sizes (and potentially other things that are configurable by the user)

## Tasks

- [ ] Determine whether this should be applied per pane or per component (class or instance)
- [ ] Explore and sketch how / where the user would reset column sizes (and how this effects the other things we are persisting)
- [ ] Set up versioning in local storage to handle user configurable settings that might no longer work i.e. a different number of columns
- [ ] Implementation
- [ ] Write tests (unit and e2e) 
- [ ] Code review
- [ ] Verify acceptance criteria met
- [ ] Exploratory testing to find bugs and edge cases
- [ ] Write automated regression tests for the A/Cs and add to spec doc (expanding on A/Cs where possible)
