### ISSUE TITLE
Persist table filters

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3396]
## Story

As a user
When I have set filters on data tables to my preferences
I want those filters to be persisted when I refresh my browser
So that I don't have to reset filters to my preferences every time

## Acceptance Criteria

- [ ] I can apply filters to data tables
- [ ] When I switch to view another market, the filters I applied are preserved
- [ ] When I refresh the page I am looking at, I can see the filters I applied are preserved
- [ ] When I switch between light and dark themes, I can see the filters I applied are preserved
- [ ] All markets use the same filters
- [ ] This same behaviour is true for every table in console where I can apply filters

## Tasks

- [ ] Implementation
- [ ] Write tests (unit and e2e) 
- [ ] Code review
- [ ] Verify acceptance criteria met
- [ ] Exploratory testing to find bugs and edge cases
- [ ] Write automated regression tests for the A/Cs and add to spec doc (expanding on A/Cs where possible)

**Comment by candida-d** [comment]
This was also raised by an integrator as an issue they observed while using Console.
