### ISSUE TITLE
Persist table sorting

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3397]
## Story

As a user
When I have sort data in tables to my preferences
I want that sorting to be persisted when I refresh my browser
So that I don't have to sort to my preferences every time

## Acceptance Criteria

- [ ] I can sort data in tables
- [ ] When I switch to view another market, the sorting I applied is preserved
- [ ] When I refresh the page I am looking at, I can see the sorting I applied is preserved
- [ ] When I switch between light and dark themes, I can see the sorting I applied is preserved
- [ ] All markets use the same sorting
- [ ] This same behaviour is true for every table in console where I can apply sorting

## Tasks

- [ ] Implementation
- [ ] Write tests (unit and e2e) 
- [ ] Code review
- [ ] Verify acceptance criteria met
- [ ] Exploratory testing to find bugs and edge cases
- [ ] Write automated regression tests for the A/Cs and add to spec doc (expanding on A/Cs where possible)
