### ISSUE TITLE
Make query for assets list lighter - fix "ResourceExhausted" errors

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/frontend-monorepo#3415]
## The Chore

API claims to heavy and complicated query by returning "ResourceExhausted" in assets provider. Probably we need to remove some unneeded nodes elements from asset list query like `infrastructureFeeAccount`, `globalRewardPoolAccount`, `takerFeeRewardAccount` since we need them only on detail views (or only explorer need it)

## Tasks

- [ ] make new tiny assetList query
- [ ] check carefully compatibility with existing views 
- [ ] adjust tests and mocks
