### ISSUE TITLE
Add documentation for library usage in mono repo

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3419]
## The Chore

We need clearer documentation on how we manage libs in the monorepo so we can avoid having complicated dependency trees which can result in some packages depending on packages they shouldn't, or circular dependencies. For example current ui-toolkit depends on @apollo/client.

## Tasks

- [ ] Make sure READMEs for library's include information on how the library is intended to be used
- [ ] Update the root README (and possibly add a CONTRIBUTING.md) to outline how packages should be added, and what sort of code they should contain
- [ ] Add any supporting notion pages to provide additional internal context

## Additional details / background info

https://github.com/vegaprotocol/frontend-monorepo/issues/2796#issuecomment-1503686427
