### ISSUE TITLE
Multisig incorrect warning on Governance app

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3423]
## User Story

As a Governance user (particularly Validators and Delegators)
I want to know when the Ethereum Multisig Contract is configured incorrectly 
So that I can understand the reason for penalties and/or delays to rewards payouts and how I can resolve it  

## Acceptance Criteria

When one or more validators have a multisig score of 0...
- [ ] I can see a warning on the **Validators** page of the Governance site when the Multisig Contract signers list is configured incorrectly
- [ ] I can see a warning on the **Rewards** page of the Governance site when the Multisig Contract signers list is configured incorrectly
- [ ] The current info panel about when rewards will be paid is blue (not orange) and is replaced by this Multisig warning
- [ ] I can see a link to the Multisig Contract on Ethereum relevant to the network I am currently on (i.e. https://sepolia.etherscan.io/address/0x36276F313D2428f9893dD628593589802c3382de for Fairground)
- [ ] I can understand the impact of the Multisig Contract being configured incorrectly (i.e. validator penalties)
- [ ] I can see how to get to the right part of the docs site to learn more about [Validator Scores and Rewards](https://docs.vega.xyz/testnet/concepts/vega-chain/validator-scores-and-rewards) 
~~I can see a link to the Multisig Signer Management Tool to resolve the issue~~
- [ ] On the Validators page, when the Multisig Contract is correctly configured I can no longer see the Multisig warning
- [ ] On the Rewards page, when the Multisig Contract is correctly configured the Multisig warning is replaced with the blue info panel about when rewards will be paid out

## Sketch

![Image](https://user-images.githubusercontent.com/47143694/234880335-1f332a73-7a34-4193-b6ab-e5641c6cd621.png)

## Tasks

- [ ] Detailed sketch and finalise copy
- [ ] Visual design
- [ ] Implement
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Resole bugs and new edge cases (as applicable)
- [ ] Write automated regression tests against the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to Governance spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Notes

When the multisig is configured incorrectly ALL Validators and delegators will receive penalties and may not receive rewards until it is resolved.

**Comment by JonRay15** [comment]
OK this is now updated with all the relevant technical detail to change the derivation of the necessary scores.  Unnassigning myself.
