### ISSUE TITLE
Visual indication in deal ticket when updated externally

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3436]
## Story

As a user
I want visual indication that a field has changed in the deal ticket
So that its easier to verify

## Acceptance Criteria

- [ ] Fields flash or has some other visual indication when its updated externally
  - [ ] Type
  - [ ] Side
  - [ ] Size
  - [ ] Price
  - [ ] Time in force
  - [ ] Expiry
  - [ ] Post only
  - [ ] Reduce only

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Dev
- [ ] Test

## Additional details / background info

When you click a price in the book (and in future volumes) the deal ticket updates. We want to add extra visual indication when the field changes so that the user is more easily shown the link between clicking the price and the change in the ticket
