### ISSUE TITLE
Add creation of signature bundle to Multisig Add/Remove Signer Tool

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3438]
## User Story

As a Vega Validator (or project team)
I want to be able to create a valid signature bundle on the vega datanode api as part of the workflow to add or remove signers from the Ethereum Multisig Contract
So that I can complete the whole process quickly in one place, avoiding having to do some parts manually via the API and others via the [Multisig Add/Remove Signer Tool](https://validator-testnet.tools.vega.xyz/)

### When landing on the Multisig Add/Remove Signer Tool:
- [ ] I can see the Ethereum Multisig Contract address (relevant to the network I am on)
- [ ] I can see the current valid signer count on the Ethereum Multisig Contract
- [ ] I can see the update form to make changes to the signers on the Multisig Contract

### When using the form to make an update:
- [ ] I can an update choosing to add a signer to OR remove a signer from the Multisig Contract 
- [ ] If not already connected, I am prompted to connect my Ethereum wallet so that my wallet / key ID can be used to update to the multisig contract
- [ ] I can connect my Ethereum wallet
- [ ] I can change which Ethereum wallet / key to use in Metamask
- [ ] I can NOT edit the Ethereum wallet / key ID directly in the Multisig Add/Remove Signer Tool 
- [ ] If not already connected, I am prompted to connect my Vega wallet so that my wallet / key ID can be used to create the signature bundle on the Vega network datanode api
- [ ] I can connect my Vega Wallet
- [ ] I can change which Vega wallet / key to use in my Vega wallet
- [ ] I can NOT edit the Vega wallet / key ID directly in the Multisig Add/Remove Signer Tool 
- [ ] I can click a link to the Governance app validator page to find the node ID (relevant to the network I am on) 
- [ ] I can enter the node ID for the signer(s) I want to add / remove
- [ ] The button to submit my request to add / remove signer is disabled until Ethereum wallet / key, Vega wallet / key and Node ID have been entered
- [ ] I can submit my update request to the Ethereum Multisig Contract

### When I have submitted an update:
- [ ] I can no longer edit the form and am shown an 'in progress' view
- [ ] If there is a already a valid signature bundle on the datanode API, that signature bundle is submitted 
- [ ] If there is not already a valid signature bundle on the datanode API, an IssueSignatures transaction is submitted to the vega network and Vega wallet prompts me to approve the transaction 
- [ ] When I have approved the transaction, a valid signature bundle is created on the datanode API
- [ ] When there is a valid signature bundle on the datanode API, a signer update request is submitted to the Multisig contract
- [ ] When the update request is submitted to the multisig contract, Metamask prompts me to approve the transaction 
- [ ] When the request has completed, I am given feedback on the success / failure of my update

### When my update fails
- [ ] I am given some feedback on the reason for the failure:
    - Invalid ethereum wallet / key
    - Invalid vega wallet / key
    - Invalid node ID
    - Signature bundle couldn't be created
    - Signature bundle invalid
    - Transaction to update signer to the Ethereum mutlisig contract failed
- [ ] I can click 'try again' and be returned to the update form

### When my update succeeds
- [ ] The details of my update are confirmed and I can click 'done' and be returned to the update form
- [ ] The page updates to show the updated valid signer count on the Ethereum Multisig Contract

## Tasks

- [ ] Detailed sketch and finalise copy
- [ ] Visual design
- [ ] Implement (including using useForm as can then benefit from some out of the box client side validation)
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Resole bugs and new edge cases (as applicable)
- [ ] Write automated regression tests against the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to Governance spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch

![image](https://user-images.githubusercontent.com/47143694/234665580-cf8bea9b-99b8-4e50-b4b7-6fd040375350.png)

## Notes

For the multisig contract to be correct and valid, the signers on the contract have to be exactly the same as the set of consensus validators currently on the network.

- Each update to the multisig contract requires a valid signature bundle
- Each add / removal of a signer constitutes an update - so if I want to add two and remove one, that is 3 updates and requires 3 signature bundles
- To create a signature bundle you need to create an [IssueSignatures transaction](https://docs.vega.xyz/testnet/api/grpc/vega/commands/v1/commands.proto#issuesignatures) - this transaction requires:
    - submitter (ethereum address submitting the signatures to the smart contract)
    - kind (kind of signatures to generate - whether a signer is being **added** or **removed**)
    - validator_node_id (ID of the node that will be signed added or removed from the smart contract)
