### ISSUE TITLE
Switch to use wagmi

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3441]
## The Chore

We should switch to using wagmi instead of web3-react
- its more widely used
- has better documentation
- better type safety
- often get Ethereum account errors in the console

## Tasks

- [ ] Switch to Wagmi
- [ ] Test all Ethereum wallet connection options
- [ ] Test all Ethereum contract interactions
