### ISSUE TITLE
Select a market to make a trade

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#345]
## Task
As a user I would like to select a market

## ACs
- [x] It should allow you to select the market by searching for a name
- [x] Once you start typing it should filter the markets by text in real-time (filter client side)
- [x] It should display automatically a list of markets underneath search box (is this most recent searches, 1st 10 or all?)
- [x] It should show the market description/text
- [x] It should show the market name once you select it and click next
- [x] It should work on dark/light mode
- [x] It should match the design for both desktop and mobile
- [x] It should be A11Y friendly
- [x] It should automatically select a Time in Force set to IOC as default
- [x] It should automatically select the type of trade as Market
- [x] It should only the markets that are set to active

**Comment by gordsport** [comment]
Note: Need to figure out what Time in Force to have selected as default

**Comment by elmar-vega** [comment]
Question: What happens on desktop search/selection? Display as dropdown?
