### ISSUE TITLE
EPIC: i18n

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3451]
## Story

As a user
I want to be able to switch to using an app in my language
So that I can more easily use Vega

## Acceptance Criteria

- [x] I can switch to a different language
- [x] Language is changed after selection
- [x] Translations should be fetched and loaded on request
- [x] Selected language is stored in localStorage so that its persisted through a reload
- [ ] Ensure common phrases and labels are centralized in the same place

## Tasks

- [ ] Figure out best approach for i18n with libs
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/4718
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/4719
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/4720
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5223
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5224
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5225
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5226
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5227
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5228
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5229
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5230
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5231
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5232
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5233
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5234
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5235
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/5236

## Additional details / background info

VEGA XYZ: https://vegaprotocol.notion.site/The-Ultimate-Guide-For-Translating-vega-xyz-488e28e90cba400cabf8da36f98c1ef8

**Comment by JonRay15** [comment]
Need to confirm with Ramsey & Rebecca on the dates for which they need this.  Assume it will be after the October release, and also ensure you build in time for translations themselves.

**Comment by JonRay15** [comment]
Ramsey / Rebecca have said mid-Nov is when we will need full Asia language support, so need to get started thinking about this. 

Need to bear in mind the potential UI / layout impact given the very different nature of the characters. 

We should be able to gather up all the labels that we have and run them through a basic translator to tr to see what the visual impact of these changes will be and determine if there are any wider layout changes we need to factor in time for.

**Comment by bwallacee** [comment]
#5371 Ticket for issues found with i18n
