### ISSUE TITLE
When monitoring my orders I want to jump to see what is active, get feedback on what has "failed" or changed, as well as All orders

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3452]
## Story

~~As a~~ when monitoring the positions I have in Vega,
I want to know what orders have have active, see feedback on orders that have changed status or failed as well as see all orders (and apply bespoke filters
So that I don't have to re-apply filters each time

![image](https://user-images.githubusercontent.com/13255539/232725050-6d5af3b5-dd8a-437f-8430-eac5d0698842.png)

Proposal part 1: A tab for each order status (or order status group)
- `Active` + `Parked`. aka **Open**
- `Canceled` + `Expired` + `filled` + `Partially filled` + `stopped` - aka **Closed**
- `Rejected` - aka **Rejected**
- All

When the viewport is wide enough for two tables:

<img width="2489" alt="Screenshot 2023-04-18 at 09 59 48" src="https://user-images.githubusercontent.com/13255539/232727636-366358ac-c0a5-4bd6-bc85-089108937d25.png">

On the narrow viewport I (Michael) suggest showing all tabs (existing behaviour)

Barney suggests a single "Orders" tab, perhaps with the same default as implemented.

<img width="451" alt="Screenshot 2023-04-18 at 10 01 34" src="https://user-images.githubusercontent.com/13255539/232728112-216a7f3e-9c36-4500-bc4c-7b45fedaa1e1.png">

Proposal part 2: Show a badge / count on each tab

- Open shows a badge with a count of all the "open" orders (parked and active)
- Badge could flash or light up each time this changes
- Canceled shows a badge (not a count) to show that this has changed since the last time the user looked at it (on this device). 
  - However it may not be necessary to update this badge if the change happended due to a user action in console e.g... they hit the cancel order button (although it probably should happen if they place a market order that gets part filled) Lets play with this on a deploy preview and decide.
- Rejected has badge that is reset each time the user views the tab

[Slack discussion](https://vegaprotocol.slack.com/archives/C037STCKMGC/p1680862379891279)

## Acceptance Criteria

- [ ] See above and [existing ACs](https://github.com/vegaprotocol/specs/blob/master/user-interface/7003-MORD-manage_orders.md#manage-orders).

## Tasks

- [x] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

See above

**Comment by mattrussell36** [comment]
Created a couple tickets to split this work up

- https://github.com/vegaprotocol/frontend-monorepo/issues/3462
- https://github.com/vegaprotocol/frontend-monorepo/issues/3461
