### ISSUE TITLE
View important information and a link to see more for the market I have selected

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#346]
## Task
As a user I would like to see important information and a link to see more for the market I have selected

## ACs
- [ ] It should show the expiration date with a tooltip with more info
- [ ] It should show the Settlement Amount with a tooltip with more info
- [ ] It should show Estimated Margin with a tooltip with more info
- [ ] It should show a link to get more info

**Comment by gordsport** [comment]
Note: We need to define where the link for `more info` take the user
