### ISSUE TITLE
Rejected/Closed orders indcators

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3462]
## Story

As a user
I want to be notified if orders have been closed or rejected
So that I am aware of my orders and their state on the book

## Acceptance Criteria

- [ ] Rejected tab indicator shows when new rejected orders are received
- [ ] Viewing rejected orders clears the indicator
- [ ] Cancelled tab indicator shows when new cancelled orders are received
- [ ] Viewing the cancelled tab clears the indicator

## Tasks

- [ ] Dev
- [ ] Test

## Sketch

https://user-images.githubusercontent.com/13255539/232725050-6d5af3b5-dd8a-437f-8430-eac5d0698842.png
