### ISSUE TITLE
Show delay countdown in withdrawal tab

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3463]
Depends on https://github.com/vegaprotocol/frontend-monorepo/issues/3578

## The Chore

When looking at an incomplete withdrawal, I should be able to see how long is left before I can complete it.

## Tasks

- [ ] Determine colours (or any other necessary visual devices) to highlight withdrawals that are ready to complete
- [ ] Add a status for a delayed withdrawal that shows **how long** til the delay ends
  - [ ] Add a tooltip to this status, showing **the exact time** the delay ends
- [ ] Add a status for incomplete withdrawals which are ready to complete
- [ ] Share a deploy preview link with Neil and Joelle
- [ ] QA

## Sketches

![image](https://user-images.githubusercontent.com/1080322/232853075-704fe98d-770b-4496-90a0-65f366e3b5d6.png)

![image](https://user-images.githubusercontent.com/1080322/232853121-004d6024-8442-43ae-9253-43a656a90021.png)

## Additional details / background info
- Epic: https://github.com/vegaprotocol/frontend-monorepo/issues/3366
- We might want to repurpose the "Pending" transaction
