### ISSUE TITLE
Tab badges

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3464]
## Story

As a console user often navigating between tabs
I want a breadcrumb trail to new activity in closed tabs
So I can tell when something needs my attention, and what has changed since I last looked

## Acceptance Criteria

- [ ] I can see a visual indicator of new activity in a closed tab
- [ ] The indicator tells me how many things are new (it includes a number)
- [ ] There is a way for the component within the tab to update the tab indcator

Note: This is not to connect any real data for any of our tabs, just set up the functionality

## Tasks

- [ ] Visual Design
- [ ] Team and stakeholder review
- [ ] Implementation
- [ ] QA

## Additional details / background info
- Also necessary for https://github.com/vegaprotocol/frontend-monorepo/issues/3452
- Related to https://github.com/vegaprotocol/frontend-monorepo/issues/3366
- Note. This ticket is for the tab indicator _only_ (not highlighting individual rows)
