### ISSUE TITLE
Select the direction of trade (Long/Short)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#347]
## Task
As a user I would like to select the direction of trade (Long/Short)

## AC
- [x] It should show text with information on what it means to go short or long
- [x] It should allow you to select long/short
- [x] It should work on dark/light mode
- [x] It should be A11Y friendly
