### ISSUE TITLE
Graphical input to choose a corner for toasts

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3479]
Blocked by: https://github.com/vegaprotocol/frontend-monorepo/issues/3232

## The Chore

Create a graphical UI for selecting which corner toasts should be seen, instead of using standard form fields

## Tasks

- [ ] Sketch exploration
- [ ] Review current implementation
- [ ] Replace icons with Vega versions
- [ ] Visual design
- [ ] Team and stakeholder review
- [ ] Implementation
- [ ] QA

## Sketch

One idea from [the Miro board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764551457168595&cot=14):

![image](https://user-images.githubusercontent.com/1080322/233341965-cf1b68b7-3c09-43db-86ee-8e439edcab82.png)

## Additional details / background info
- A mvp for this was already produced. But it does not use Vega icons
- We may also support showing the toast in the top-centre or bottom-centre
- Dependent on https://github.com/vegaprotocol/frontend-monorepo/issues/3232
