### ISSUE TITLE
Select the size for the trade

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#348]
## Task
As a user I would like to select the size for the trade

## ACs
- [x] It should allow me to select the amount using a slider that has the leverage percentage applied to my total balance for the settlement asset
	- [x] It should have a minimum amount set for this type of trade
	- [x] It should have the maximum amount set to the leveraged balance  
- [x] It should show the amount selected by the slider below with label “Size ([Currency, e.g. USDC])” and a tooltip with more info
- [x] It should show the current estimated price with label “Est. Price” and a tooltip with more info
- [x] It should show the estimated close out price with label “Est. Close Out” and a tooltip with more info
- [x] It should match the design
- [x] It should be A11Y friendly
- [x] It should work in dark/light mode

**Comment by elmar-vega** [comment]
Question: what goes into the tooltip
