### ISSUE TITLE
Spike: Explore including oracle info in the market list

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3480]
## Story

As a console user browsing markets
I may want to see, search, filter, or sort markets by some attributes of their oracles
So that I can find markets with reliable oracles

## Acceptance Criteria

TBD

## Tasks

- [ ] Determine which, if any, attributes of oracles might be valuable when browsing the market list
- [ ] Determine what use cases would necessitate the presence of oracle info in the market list
- [ ] Write acceptance criteria
- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info
- Suggested by Michael

**Comment by mattrussell36** [comment]
@barnabee how important do you think this is? I could see users trusting certain oracles and wanting to filter lists to only see markets that use those oracles?

**Comment by barnabee** [comment]
There won't be enough choice of markets/oracles early on to make a filter particularly useful for a while I suspect.
