### ISSUE TITLE
Show reference, offset and current price for pegged orders

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3489]
Block explorer currently uses what looks like a Limit order view for pegged orders. this results in a few issues...

## Story

~~As a~~ When checking a transaction with a pegged order, 
I want to see the reference and offset that was used (as well as the current price)
So that I can verify Vega has processed my order as I intended (i.e. that the ref and offset I entered match what was received, and I've got the number of digits after the decimal right).

Here is what it currently looks like: [e.g.](https://explorer.fairground.wtf/txs/98795E58C492F943ECD3E4AAC6C41D211D76D8EECAD1CC06FC86593B74AC0FA9)

<img width="889" alt="Screenshot 2023-04-21 at 12 04 14" src="https://user-images.githubusercontent.com/13255539/233620748-89a3eb84-5c71-4295-8ae9-bf2aabaa844a.png">

Note that a pegged order doesn't have a price, it has an offset from a reference price. The price changes as the reference moves.

I would expect to see these offset and reference as primary, and maybe the current price (subscription) as secondary. 

## Acceptance Criteria

- [ ] the pegged order view shows the reference that was used
- [ ] the pegged order view shows the offset that was used

## Tasks

- [x] Explore and sketch

GTC Buy 10.01 @ +0.01 from Mid. (currently priced 1,915.86 USD) 

or

GTC Sell 20.01 @ 1.01 from Mid. (Filled at 1,915.86 USD) 

but it could get filled a multiple prices... So maybe it should not show a price. or list all fill prices

GTC Sell 1.01 @ 0.01 from Best Bid. 
Filled at 0.50 * 1,915.86 USD
Filled at 0.50 * 1,915.87 USD
Open 0.01 * 1,915.88 USD

however:  this live data could be left out until https://github.com/vegaprotocol/frontend-monorepo/issues/2401

GTC Sell 1.01 @ 0.01 from Best Bid

- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
