### ISSUE TITLE
Network upgrade in progress

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3534]
Dependent on this #3319 

## Story

As a console user
I want to know when a network upgrade is taking place
So that I have visibility of what's happening with the network, am reassured that nothing bad is happening, and am provided with information to help me decide what action I need to take

## Acceptance Criteria

- [ ] I can see that a network upgrade is taking place
- [ ] I can see 'what' version of the protocol the network is planned to be upgraded to 
- [ ] I can see what block height the upgrade will run at
- [ ] I can see the current block height
- [ ] I can see 'when' the upgrade is estimated to take place (based on the current and planned block height - instructions to calculate time in the future are here https://docs.vega.xyz/testnet/node-operators/how-to/upgrade-network)
- [ ] I can understand the impact(s) of the upgrade i.e. how long the network might be offline etc.
- [ ] There is a way to see all the details of the release that will be upgraded to on github https://github.com/vegaprotocol/vega/tags (until this ticket is done https://github.com/vegaprotocol/frontend-monorepo/issues/3260 in which case it should link to the upgrade proposal details page)
- [ ] I can close the banner (to free up space on my screen when I'm trading)
- [ ] When I have closed the banner there is a way for me to still see that there is a network upgrade planned  
- [ ] When I have closed the banner there is a way for me to re-open the banner to see the details of the planned upgrade
- [ ] Whether the banner is open or not, I can see a count down to the planned network upgrade  

## Tasks

- [ ] Consider whether it makes sense to utilise the work done to create a [Holding page to temporarily block features](https://github.com/vegaprotocol/frontend-monorepo/issues/1784) or not
- [ ] Finalise UX and copy
- [ ] Visual design
- [ ] Implement
- [ ] QA test (Verify meets acceptance criteria, exploratory testing for bugs, check adherence to visual design, add automated regression tests for the A/Cs)
- [ ] Release

## Sketch

<img width="559" alt="Screenshot 2023-03-30 at 10 36 02" src="https://user-images.githubusercontent.com/47143694/228794849-f06cb19e-206d-4ee5-8b52-7b7caadc10b5.png">

## Additional details / background info

Details of what data is available from the API to facilitate this story can be found in this spike https://github.com/vegaprotocol/frontend-monorepo/issues/2992

**Comment by bwallacee** [comment]
Currently market-sim doesn't have the capability in order for us to E2E test this. I have created a [ticket](https://github.com/vegaprotocol/vega-market-sim/issues/487) in the repo, and we can look to add an E2E test once it has been implemented
