### ISSUE TITLE
Notification history

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3535]
Dependent on spike #3315 

## Story

As a console dapp user
I want to be able to see a history of the notifications (toasts) I have received 
So that I can refer back to them in case I missed something or want to find more details i.e. a transaction or network upgrade proposal

## Acceptance Criteria

- [ ] I can access a history of notifications from anywhere on console
- [ ] I can filter by notifications triggered by me and those triggered by the network
- [ ] I can see the most recent notifications at the top of the list
- [ ] I can scroll the list to see older transactions
- [ ] I can see the latest status of the notification
- [ ] There is a way to see the details of the thing I was notified about (i.e. link to the transaction details on block explorer or the network upgrade proposal on governance)

## Tasks

- [ ] Finalise UX and copy
- [ ] Visual design
- [ ] Implement
- [ ] QA test (Verify meets acceptance criteria, exploratory testing for bugs, check adherence to visual design, add automated regression tests for the A/Cs)
- [ ] Release

## Sketch

<img width="422" alt="Screenshot 2023-03-30 at 06 59 07" src="https://user-images.githubusercontent.com/47143694/228743139-e6d83e4f-3d60-48d4-b4af-e61c8d5c752e.png">

## Additional details / background info
