### ISSUE TITLE
Proposal details page quick win improvements

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3538]
## Chore

We need to tidy and prioritise the content on the proposal details page so that users can immediately see how to vote and what this proposal is, rather than sift through lots of data.

## Acceptance Criteria 
- [x] I can still see the proposal title 
- [x] I can still see the proposal type (Freeform, New market, Network parameter etc. exists already in label)
- [x] I can see the state of the proposal (unspecified, failed, open, passed, rejected, declined, enacted, waiting for node vote) (definitions [here](https://docs.vega.xyz/mainnet/api/rest/data-v1/trading-data-service-get-proposals))
- [x] Open proposals i.e. open for voting are visually differentiated from other states
- [x] I can see the proposal description, clearly labeled, in a way that scales i.e. can handle longer descriptions 
- [x] I can still see proposal ID, closing date, proposer and proposed on fields 
- [x] We've removed the duplication of type "Freeform" and proposal ID so that each are displayed once
- [x] I can still see the token vote status / details of the proposal 

<img width="733" alt="Screenshot 2023-05-02 at 17 32 38" src="https://user-images.githubusercontent.com/46783148/235728274-8f541fc1-819c-4bb3-b049-a30f6effa01a.png">

- [x] There is a clear way for me to connect my wallet in order to vote 
- [x] When I'm connected, I can see clear buttons to vote for or vote against 
- [x] When I'm connected, but don't have any associated vega, vote for and vote against are disabled
- [x] When a vote is submitted, I can still see the "Casting vote" status 
- [x] When I have successfully voted, I can still see my vote i.e. "You voted: For 02 May 2023."
- [x] There is a way to access the vote breakdown data and proposal terms 

## Sketch 
<img width="1130" alt="Screenshot 2023-05-02 at 17 35 42" src="https://user-images.githubusercontent.com/46783148/235729000-dbee537c-6a76-4430-b10c-4cf28301e71d.png">

![Image](https://user-images.githubusercontent.com/46783148/235911251-fb4b9b09-7ce5-4ace-a149-ac6517a294a2.png)

## Tasks
- [ ] Visual design 
- [ ] Implementation 
- [ ] Test 
- [ ] Etc. 

## Additional details / background info
Miro board https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764552880066763&cot=14

**Comment by sam-keen** [comment]
Note: ticket for adding blog link is separated due to not being ready. See https://github.com/vegaprotocol/frontend-monorepo/issues/3623

**Comment by sam-keen** [comment]
Change requests to mainnet have come in over the weekend: https://github.com/vegaprotocol/frontend-monorepo/issues/3631. Need to reassess this ticket in light of these @ckpringle
