### ISSUE TITLE
Expose signature bundle for withdrawals

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3546]
## Story

As a user
I want to get my signature bundle for a withdrawal after I create it
So that I can still complete my withdrawal if console or the datanode is down

## Acceptance Criteria

- [ ] I can view my signature bundle after withdrawal creation
- [ ] I can copy my signature bundle
- [ ] I am told why it might be a good idea to note down your signature bundle

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Dev
- [ ] Test

## Additional details / background info

https://vegaprotocol.slack.com/archives/CD4AKTFQT/p1682435722367239

**Comment by barnabee** [comment]
I agree this would be good.

Does the signature bundle contain enough information to identify, using just an Ethereum RPC node whether it has been completed?

If so we could potentially store it in localstorage (it’s public data, this shouldn’t be dangerous) and not only continue to show it in the event it’s no longer available from the data node, but even prompt a user to recover and note down the bundle/complete their withdrawal in that scenario.

**Comment by barnabee** [comment]
NB: @JonRay15 was also going to create a ticket to close the hole whereby uncompleted withdrawals can be lost if not backed up before a checkpoint restart.

**Comment by JonRay15** [comment]
The suggestion was that Jeremy had subsequntly changed his mind about putting them in the checkpont hence Matt had raised that ticket to cover us.  There was also a suggestion that even if we did have it in a checkpoint it is good to basically say during the withdrawal "these funds are now leaving Vega and cannot be recovered, keep these signatures safe since they will allow you to withdraw via ethereum directly if required due to network outage". 

I would point out though that fairgroud just got checkpoint restarted and I can safely say as a user that had made multiple withdrawals over the last two weeks this screen is jarring.

![image](https://user-images.githubusercontent.com/89918817/234540142-8f5b71ce-5bb6-4013-8485-c8bfc7d3903e.png)

**Comment by JonRay15** [comment]
Mentioned on the [PR ](https://github.com/vegaprotocol/frontend-monorepo/pull/3701)for this....

I think the wording on this needs to be stronger.

Nothing about that green toast says to me "If you dont copy this and you dont complete your withdrawal you may lose your funds"

Think it needs like a big exclamation mark and something more like "WARNING: Your funds have now left the Vega network and cannot be returned. Please copy this signature so you can still retrive your funds directly from ethereum in the event of a network restart"

**Comment by JonRay15** [comment]
OK ... those look better. 

Can we make sure when we do this we also check the toast MUST be physically closed by the user?  I dont know the exact current behaviour but certainly a while ago it dropped off-screen after 5s or something.  IMO it shouldnt go away until you complete your withdrawal or explicitly close it.

**Comment by neildawson** [comment]
@JonRay15 I added sketches to the ticket for clarity, and added an acceptance criterion for removing the timeout on the toast
