### ISSUE TITLE
Ensure the data node urls in the monorepo are valid

### ISSUE THREAD

**Issue by sam-keen** [vegaprotocol/frontend-monorepo#3548]
## The Chore

Fairground has recently been redeployed with a reduced list of data nodes. The three that are left are n00, n06 and n07.

## Tasks

- [ ] Check the env vars for the monorepo apps
- [ ] Check any other locations, such as installation instructions
- [ ] Replace any that are invalid with a remaining valid one
