### ISSUE TITLE
See reference and offset (as well as price) for pegged orders

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3551]
## Story

~~As a~~ When I have a pegged order
I want to see the reference and offset (as well as the price)
So that I can confirm that the order is when I expect it to be

## Acceptance Criteria

- [ ] I can see the Reference (bid, ask or mid)
- [ ] I can see the offset (e.g. + 0.001 for a Sell, or -1231.023 for a Buy)
- [ ] I can also see the current price (if unfilled), the last price it had (if it was filled canceled etc) or the rejected/stopped reason if there is one (note this is already implemented but I mention it because it is still required

## Tasks

- [x] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

![image](https://user-images.githubusercontent.com/13255539/234581261-7d08cf04-0a3e-4fb0-810e-87fb04462fa9.png)

One could argue that the word limit is not needed as that is all it could be, but in the future it could be possible to peg stop orders

**Comment by campbellssource** [comment]
FYI: to submit pegged orders: https://github.com/vegaprotocol/frontend-monorepo/issues/1062
