### ISSUE TITLE
Multisig incorrect warning on Multisig Add/Remove Signer Tool

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3554]
## User Story

As a Validator (or Vega team member) 
I want to know when the Ethereum Multisig Contract is configured incorrectly and how 
So that I can understand the reason for delays to my rewards payouts and understand what updates need to be made to resolve it  

## Acceptance Criteria

- [ ] I can see a warning on the Multisig Add/Remove Signer Tool when the Multisig Contract signers list differs from the current consensus validators list on the Vega datanode API
- [ ] I can see a link to the Multisig Contract on Ethereum relevant to the network I am currently on (i.e. https://sepolia.etherscan.io/address/0x36276F313D2428f9893dD628593589802c3382de for Fairground)
- [ ] I can see information about what the differences are:
    - [ ] multisig contract contains n additional validator(s) that aren't currently consensus validators on the vega network AND/OR
    - [ ] multisig contract is missing n validator(s) that are currently consensus validators on the vega network
- [ ] I can understand the impact of the Multisig Contract being configured incorrectly (i.e. delay to rewards payouts)
- [ ] I can see how to get to the right part of the docs site to learn more about [Validator Scores and Rewards](https://docs.vega.xyz/testnet/concepts/vega-chain/validator-scores-and-rewards) 
- [ ] When updates have been made that resolve the differences I can no longer see the Multisig warning

## Sketch

![image](https://user-images.githubusercontent.com/47143694/234668251-246e8389-4612-4726-933a-d1b6618def20.png)

## Tasks

- [ ] Detailed sketch and finalise copy
- [ ] Visual design
- [ ] Implement UI
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Resole bugs and new edge cases (as applicable)
- [ ] Write automated regression tests against the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to Governance spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by wwestgarth** [comment]
Just a note on how you might go about working out the nodeIDs of the validators who need to be added/removed from the multisig contract.

Using the `/api/v2/epoch`, you would need to first iterate backwards through all the epochs to the first one where all validators have a rewardScore.multisigScore of 1. This will be the last time the multisig contract was correct. Then you need to look at that epoch's ranking score and look for:
- A nodes `rankingScore.previousStatus != VALIDATOR_NODE_STATUS_TENDERMINT && rankingScore.status == VALIDATOR_NODE_STATUS_TENDERMINT`. This means they need to be added to the contract
- A nodes `rankingScore.previousStatus == VALIDATOR_NODE_STATUS_TENDERMINT && rankingScore.status != VALIDATOR_NODE_STATUS_TENDERMINT`. This means that node needs to be removed

Then iterate forward through the epochs again doing the same and collecting all the other add/remove validators that might have occurred during the time that it has been out of sync.

I would think that almost all of the time when the multisig needs updating in mainnet you would probably only have to look back a couple of epochs and there would only be one person to add and one to remove. This is because people will actually care a little bit more than on the validator-testnet because actually money is being withheld on mainnet when its out of sync.

Also note that if a checkpoint restore happens while the multisig contract is out of date then this won't work because we'd lose the data from before the checkpoint and not be able to find the last time everything was correct.
