### ISSUE TITLE
Highlight ready to complete withdrawals in withdrawal table

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3578]
## Story

As a user
I want to see which withdrawals in the withdrawal table are now ready to complete
So that I am prompted to withdraw

## Acceptance Criteria

- [ ] Withdrawals that are pending completion due to withdrawal delays and then become available to complete during the users session are highlighted.

Note: This ticket does not include the indicator in the tab

## Tasks

- [x] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Dev
- [ ] Test

## Sketch

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/1080322/232855995-3454a9c5-9b4b-4ec7-a943-5b885745cb6d.png">

## Additional details / background info
- The available to complete timestamp can be calculated by using the created time stamp plus the delay timestamp.
- If current time surpasses the 'available to complete' timestamp we can change the cell state to highlight it

**Comment by asiaznik** [comment]
We should also improve error message for a case when a user clicks on "Complete withdrawal" but it's not connected to any etc wallet - now it only tells "You're on the wrong network" which is true, because no network is wrong network but 🤣
