### ISSUE TITLE
Error handling for vote submission

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3583]
```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```
## Story

As a user
I want to understand what went wrong and what I can do about it if my vote was not seen by the network
So that I can solve the problem and know what to do next

## Acceptance Criteria

- [ ] I can see an error message specific to what has occurred explaining what has happened, the impact it has had on my vote, and what I can do about it
- [ ] There is a way to resolve the problem where possible e.g. try again - placing my vote 

## Tasks

- [ ] Investigate what we are / can get back about the error to be more useful
- [ ] Improve the UX of the error message generally to make sure it is visible and we help the user know what to do next
- [ ] Improve the content of the error (if we can)
- [ ] Design best fit approach based on what we know about each error type
- [ ] Write a user facing explanation, impact and the action they can take e.g. try again or refresh? 
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Additional details / background info

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/2f9c7f5e-bfb7-4c6b-a127-495470ba1fbe)
