### ISSUE TITLE
Edit a pegged order

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#3585]
## Story

~~As a~~ When I have a pegged order 
I want to change its reference and offset 
So that it has a new reference and offset (e.g. so It is closer or further away from the rice) 

## Acceptance Criteria

- [ ] I can click a link in the orders table that opens an edit order window
- [ ] I can change the reference 
- [ ] I can change the offset
- [ ] The remaining size is visible (and should update if the filled/remain amounts change)
- [ ] I can submit the order amendment and see feedback on the success or failure of the amendment

## Tasks

- [x] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

![image](https://user-images.githubusercontent.com/13255539/235769788-4ab4790e-ab34-4452-aa5c-a141d3362129.png)

**Comment by JonRay15** [comment]
Dont support pegged orders and no intention to
