### ISSUE TITLE
Stop Orders tab showing “No orders” in the background

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/frontend-monorepo#3589]
In the orders tab, there is “No orders” in the background getting in the way, can we remove it please?

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/2043502e-9509-458a-a3a4-5f81a4abe478)

Observed in validator_testnet

## Notes

- Change to use AsyncRender only to handle error states for tables
- Use no overlay rows component for no data in AG Grid

## Tasks

- [ ] Use default AgGrid no rows template prop for empty state
- [ ] Remove any infinite scroll logic
- [ ] TBD: Modify AsyncRenderer to handle error state
