### ISSUE TITLE
Ability to filter markets by their status (active, suspended)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#359]
## Task
As a user I would like to filter markets by their status (active, suspended)

## ACs
- [x] It should persist the filtered state via the url, so I can share the link?
- [x] By default it should show only active markets
- [x] It should match the designs
- [x] It should work for dark/light mode
- [x] It should be A11Y friendly for screen readers

**Comment by elmar-vega** [comment]
Question: On the design it doesn't show what happens when you click this active button? Also the arrow next to it makes it look less like a filter and more like a sorting (confusing).
