### ISSUE TITLE
Set default environments to stagnet1, remove stagnet3

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#3603]
## The Chore

Stagnet3 is no more. @mattrussell36 already removed the frontend deploys for those environments. THere is more tidy up to do.

## Tasks

1. [x] Explorer
    1. [x] Set `.env` to point to stagnet1, not `stagnet3`
    2. [x] Remove `.env.stagnet3`
    3. [x] Remove e2e `.env.stagnet3`
1. [x] Governance
    1. [x] Set `.env` to point to stagnet1, not `stagnet3`
    2. [x] Remove `.env.stagnet3`
    3. [x] Remove e2e `.env.stagnet3`
1. [ ] Trading
    1. [ ] Set `.env` to point to stagnet1, not `stagnet3`
    2. [ ] Remove `.env.stagnet3`
    3. [ ] Remove e2e `.env.stagnet3`
1. [ ] LP Dashboard
    1. [ ] Remove `.env.stagnet3`
    2. [ ] Remove e2e `.env.stagnet3`
1. [x] Multisig signer
    1. [x] Set `.env` to point to stagnet1, not `stagnet3`
    2. [x] Remove `.env.stagnet3`
1. [x] Static assets
    1. [x] Remove networks file `stagnet3`
 1. [x] libs
     1. [x] `libs/environment/src/components/network-switcher/network-switcher.tsx`
