### ISSUE TITLE
Select the size of capital to deploy

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#363]
## Tasks
As a user I would like to select the size of capital to deploy

## ACs

- [ ] It should show an explanation of it works (slider?)
- [ ] It should allow me to type in the amount for the bond that is less or equal to my balance in the settlement asset
- [ ] It should allow me to input the fee as a percentage
