### ISSUE TITLE
Description formatting improvements

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3631]
## Story

As a user 
I want nicely formatted proposal descriptions
So that I can read them

Impacts areas below

1. Go to [governance homepage](https://governance.fairground.wtf/), it needs formatting  
2. Look at the main [proposals](https://governance.fairground.wtf/proposals) screen, it needs formatting
3. Click through to a [proposal details](https://governance.fairground.wtf/proposals/aed3ded4f5f90c494be216bb1530958c5e2cb3eb5bd08b703649bed320f85c05) screen, it needs formatting

## Acceptance Criteria

**Proposal Details View**
- [ ] Description should be removed from where it currently is since the text can be long 
- [ ] Instead display a type specific text string, in a few cases this is currently shown below, move it up instead 
>> Network Param: "Change" `network_param` to `new_value` 
>> New Asset:  Symbol: `symbol`. ERC20 Contract Address `contract_address` (This is basically already like this)
>> Update Asset: `Asset_Name` (`asset_id`)
>> New Market: This is already fine, it shows something like "Code: AAVEDAI.MF21. tDAI settled future."
>> Update Market: `Market_Name`. Market ID: `market_id` (small addition)
>> Freeform... dont know or care! 

- [ ] Description should appear as its own section under the heading "Description" above the block with the IDs etc 
- [ ] It should follow markdown formatting and we will put together a template for this

Proposals View & Homepage View
- [ ]Apply short summary logic as above 
- [ ] Remove the description

## Tasks

- [ ] Agree
- [ ] Build

**Comment by sam-keen** [comment]
@JonRay15 no ability to get the asset name for the update asset data from the proposals query at the minute. I'll raise a ticket with core as I don't want to get this data in a separate query.

**Comment by JonRay15** [comment]
Understood. Anything else useful we can get from the proposal?

**Comment by sam-keen** [comment]
@JonRay15 no, we get everything we currently can. Core ticket here: https://github.com/vegaprotocol/vega/issues/8275

**Comment by sam-keen** [comment]
@JonRay15 Same for update market. Added to the core ticket
