### ISSUE TITLE
Prompt user to switch to latest version

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3641]
## Story

As a user
I want to know when there is a newer version of console
So that I can use the latest features

## Acceptance Criteria

- [ ] I am notified if a newer version is available
- [ ] There is a link to the newer version

## Tasks

- [ ] Sync with @edd on how this should work
- [x] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Dev
- [ ] Test

## Sketch

Sense checked this with Matt and Calum. From [the Miro Board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764554784129447&cot=14).

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/fc37978e-a6de-4a2e-8f1c-b0f7019d6d40)

**Comment by mattrussell36** [comment]
We also want to consider how we keep users settings in sync between upgrades to new versions
