### ISSUE TITLE
"Hide" make proposal journey and link to docs instead

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3652]
## The Chore

- Right now we have a "new proposal" button in the governance dapp that takes you to a form to fill in that is not part of the governance process, and may encourage submitting proposals without going through the forum process or following the guidance in the docs.
- As a short term solution, we'd like to redirect the button to go to the docs page, then have the docs send you to the forms on the token site.
- Rather than having a submit button at the end of each form, it would be a "download JSON" and instruct to go to the forum to paste and discuss.
- We'd repurpose the submit raw JSON section for proposal submission i.e. paste from forum.

## Tasks

- [ ] Change button to point to "Make a proposal ↗" linking to https://docs.vega.xyz/mainnet/tutorials/proposals 
- [ ] Add heading "Submit an agreed proposal from the forum" to "New proposal" page 
- [ ] Re-label "Let me choose (raw proposal)" to "Submit agreed raw proposal" on the new proposal page 
- [ ] Re-label "What type of proposal would you like to make" to "Create proposal and download JSON to share"
- [ ] Add link to the forum in the header links "Share proposals on [the forum] (https://community.vega.xyz/c/governance/25)↗" 
- [ ] Remove button to submit proposal from every proposal type EXCEPT for raw proposal 
- [ ] Add heading "Download and share" and description "Share the JSON of your proposal on the forum (link) for feedback before submitting on each (except for raw proposal)
- [ ] Link to the forum should be https://community.vega.xyz/c/governance/network-parameter-proposals/30 for network params, [https://community.vega.xyz/c/governance/network-parameter-proposals/30](https://community.vega.xyz/c/governance/market-proposals/28) for market (new and update), https://community.vega.xyz/c/governance/asset-proposals/29 for assets and https://community.vega.xyz/c/governance/free-form-proposals/31 for freeform proposals 
- [ ] Submit an agreed raw proposal from the forum no longer has "download proposal as JSON" call to action but DOES have submit / connect vega wallet to submit button 
- [ ] 

## Sketches

![Governance (  Token Utility) - Sketches](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/d498e590-aea1-4d02-ab0f-e81652e8081e)

**Comment by ckpringle** [comment]
Just moved back to review as there's a couple of things to capture in separate ticket / do / are missing
