### ISSUE TITLE
Review and submit my liquidity commitment

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#366]
## Task
As a user I would like to review and submit my liquidity commitment

## ACs

- [ ] It should display the bond with label “Bond”
- [ ] It should display the fee with label “Fee”
- [ ] It should have a button to submit
- [ ] It should have a checkbox for terms and conditions or a simple statement what it means when the user clicks submit?
