### ISSUE TITLE
Make 'cancel all' cancel  everything for all markets

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3684]
## The Chore

The cancel all button should cancel all orders, regardless of the current market

## Tasks

- [ ] Verify if we need a confirmation dialog to warn about closing all
- [ ] Remove marketId from the cancel all orders transaction so that all orders are called
- [ ] Remove cancel all button from closed, rejected and all order tabs. We only need cancel all on the active orders list.
