### ISSUE TITLE
Acceptance criterea for seeing governance proposals

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3705]
## Story

As a user
I want to see governance proposals on the Vega protocol that are awaiting votes and those from the past
So that I can see how active governance is and take part myself

## Acceptance Criteria

- [ ] I can see the title of the proposal (rationale: title)
- [ ] I can see what type of proposal it is (Freeform, New market, Update market, Network parameter, New asset, Update asset)
- [ ] I can see the change introduced by the proposal summarised specific to each proposal type: 

-  Network parameter: `[network param name] to [change]`
-  Update asset: `asset ID`
-  Market change: ID

- [ ] I can see the description of the proposal (rationale: description)
- [ ] I can see the state of the proposal (unspecified, failed, open, passed, rejected, declined, enacted, waiting for node vote)

- [ ] There is a way to find the proposal ID
- [ ] I can understand when the proposal was made
- [ ] I can understand when the vote will close
- [ ] I can understand when the proposal will be enacted if it is successful
- [ ] I can see who the proposer is (e.g. their public address)
- [ ] There is a way to see the proposal's terms in JSON
-

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
