### ISSUE TITLE
Acceptance criteria for understanding vote status

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3714]
## Story

As a governance participant 
I want to understand the current status in votes of a proposal 
So that I can understand whether a vote is for or against

## Acceptance Criteria

- [ ] When understanding the vote status of a proposal 
- I can understand the number of token votes for and against a proposal
- I can understand what proportion of the votes are for vs. against e.g. there is a percentage, a visual cue
- There is a way to understand whether majority has been reached for either "for" or "against"
 - I can understand whether this proposal has reached the required level of participation 
-  I can see whether the proposal is currently expected to fail or the result be enacted
 - I can understand how long is left to vote
- When the proposal is an update market proposal and has gone to a liquidity vote (when the token vote has not reached the participation required within time), there is visible separate section of liquidity vote results 
- There is a way to understand that the result in the end may differ (as the outcome of the vote is based on the number of tokens held by the voters at time of vote close)

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
