### ISSUE TITLE
Add a proposal preview to the raw proposal JSON page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3728]
## Story

As a proposer
I want to see a fully formatted version of my JSON proposal before i submit it 
So that I can make sure it is valid JSON and that it will render nicely in the front end once submitted

## Acceptance Criteria

- [ ] I can paste my JSON into the [New Raw Proposal](https://governance.vega.xyz/proposals/propose/raw) page as usual 
- [ ] I can either see a live fully formatted preview of the proposal
- [ ] Preview should include full formatting of the markdown in the rationale fields
- [ ] I can get feedback on whether my JSON is valid (think it does this already to be fair, but better debug might be nice - if quick and easy!) 

## Tasks

- [ ] Investigate, hopefully we are just reusing components from the proposal detail page?!
- [ ] Agree approach 
- [ ] Build

## Sketch

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/26f5f870-c752-4885-99e5-e837735f1b43)

**Comment by JonRay15** [comment]
Equally it would work to have just the preview button initiially...which generates the preview on another page, and then from that page you submit.  Either / or.

**Comment by sam-keen** [comment]
Unfortunately the difference between the data submitted by Governance compared to the data we receive when getting data from the api is too great, it will not be possible to hand-craft a way to mutate the data comprehensively by the 22nd.
