### ISSUE TITLE
Small update to text on network param and freeform proposal

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3729]
## The Chore

We have now changed the forms for [freeform proposal](https://governance.fairground.wtf/proposals/propose/freeform) and [network parameter](https://governance.fairground.wtf/proposals/propose/network-parameter) change to not allow you to submit, only to download JSON.

This is good, but we shoud just massage the wording a bit at the bottom.

## Tasks

Network Parameter 
- [ ] Add text before the download JSON button that says "Use the button below to generate the JSON for your proposal and share on the [governance forums](https://community.vega.xyz/c/governance/network-parameter-proposals/30)."
- [ ] Add text after the download JSON button that says "Once your JSON is reviewed and agreed on the proposals submit it [here](https://governance.fairground.wtf/proposals/propose/raw)."

Freeform Proposal
- [ ] Add text before the download JSON button that says "Use the button below to generate the JSON for your proposal and share on the [governance forums](https://community.vega.xyz/c/governance/free-form-proposals/31)."
- [ ] Add text after the download JSON button that says "Once your JSON is reviewed and agreed on the proposals submit it [here](https://governance.fairground.wtf/proposals/propose/raw)."

**Comment by JonRay15** [comment]
Not for now because until the others have full form entry they're too hard to use so the plan is to hide them from the main user flow.
