### ISSUE TITLE
Table row action icons

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3764]
## The Chore

- [x] Replace edit text button with edit icon button
- [x] Replace cancel text button with cross icon button
- [x] Replace close text button (in positions) with cross icon button

## Tasks

- [x] Design icons for each
- [x] Replace current text
