### ISSUE TITLE
Show margin level visualisation in asset breakdown modal

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3767]
## Ticket history
- This issue was originally titled _Show margin level estimations in deal ticket_
- Bart prototyped this behaviour, and we identified [some issues with the approach](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764555798516476&cot=14)
- Bart and Neil spoke to Witold, Barney, and Lewis to seek feedback, resolving to:
  - Not visualise estimated margin in the order form
  - Instead show the margin health stacked bar chart in the asset breakdown modal
  - Visualise leverage or margin usage in the order form (to be added as a new GitHub issue)

## Story

~~As a user placing an order
I want to understand how my margin use will change when I place this order
So I can avoid getting too close to my maintenance level and being liquidated~~

As a user assessing my position in a market
I want to understand when my margin will be released, topped up, or confiscated
So I can take steps to avoid liquidation

## Acceptance Criteria

- [x] I can see my current margin levels
- [ ] I can see worst case margin levels
- [ ] I can see best base margin levels
- [x] I can understand what each section of the stack chart means
- [x] I can see a stack chart visualizing the levels.
  - [x] Each section maps to a margin level. 
    - Everything below maintenance is red
    - maintenance → search is amber
    - search → half way to initial is yellow
    - the rest to release level is green
  - [ ] Range of values in stack charts must be normalized
  - [x] Must be shown current margin balance on the stack chart (for projected margin levels, this is just the initial level)

## Tasks

- [ ] Visual design
  - [ ] Collapsing area in deal ticket
  - [ ] Asset breakdown modal, including margin health chart
- [x] Build margin level stack chart component
- [ ] Add collapsible area to deal ticket for margin level estimations
- [x] Add margin level stack charts for
  - [x] Current
  - [ ] ~~Worst case estimation~~
  - [ ] ~~Best case estimation~~

## Sketches

From [the Miro Board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764555797108848&cot=14)

### Link to asset breakdown from the deal ticket

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/932ea91d-532e-4f85-8ac1-e5c7a468aea3)

### Margin levels in asset breakdown

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/10b44732-769f-4d84-8ae2-be3e8550bd18)

### Mouseover on the stacked bar chart

[See Miro board for link URLs](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764556126595095&cot=14)

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/45bb22bd-a967-4b28-aea1-0f3dc0acc6bc)

## Additional details / background info

Miro board:
https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764546934193057&cot=14

Split off from: https://github.com/vegaprotocol/frontend-monorepo/issues/2834

There is an already built maring visualization component here:
https://github.com/vegaprotocol/console/blob/develop/src/components/vega-ag-grid/margin-cell/margin-zone-visualization.tsx
