### ISSUE TITLE
Margin health dialog

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3769]
## Story

As a user viewing positions
I want to understand what my current margin levels are
So I can avoid getting too close to my maintenance level and being liquidated

## Acceptance Criteria

- [ ] I can open a dialog to show current margin levels breakdown
- [ ] I can open the dialog from the margin allocation column in positions.
- [ ] I can see a short explanation of margin levels.
- [x] I can see stack charts showing margin levels as outlined here: https://github.com/vegaprotocol/frontend-monorepo/issues/3767
- [ ] There are visible labels for each section of the the stack chart, with tooltips for additional information, tooltip content is in miro
- [ ] I can see my current margin balance
- [ ] There is a link to the docs on margins (link here: https://docs.vega.xyz/testnet/concepts/trading-on-vega/positions-margin)

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] Visual Design
- [x] Dev
- [ ] Test

## Additional details / background info

Miro board:
https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764546934193057&cot=14

**Comment by mattrussell36** [comment]
It has been decided that we are using the visualization only in the collateral table
