### ISSUE TITLE
Setup and Boilerplate

### ISSUE THREAD

**Issue by elmar-vega** [vegaprotocol/frontend-monorepo#377]
## Task
This issue is created to track any project setup related tasks

## ACs
- [x] Create new NX project
- [x] Add capabilities for testing
- [ ] Deploy app to Netlify
- [ ] Cypress related setup

**Comment by gordsport** [comment]
Speak to the wider FE team to align across teams
