### ISSUE TITLE
Properly render market proposal data

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3778]
## Story

As a user 
I want to understand the key attributes of a new market proposal at a glance without digging into JSON 
So that I can understand the most important information quickly and easily

## Acceptance Criteria

- [ ] I can view the key details from market proposal on screen 
- [ ] I can see this in a section called "Proposal Details" that would appear below the Voting section
- [ ] I can **ideally** see this broken into subheadings similar to what we have on the [validator details screen](https://governance.vega.xyz/validators/43697a3e911d8b70c0ce672adde17a5c38ca8f6a0486bf85ed0546e1b9a82887)

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

Something a bit like this ... but maybe not exactly this 

<img width="562" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/dff0d65f-cb4a-43cb-84b2-dbc2d3742c80">

## Additional details / background info
We should make sure asset and market proposals properly surface all the important proposal details without the user having to expand sections or look at the JSON. Especially market proposals.
