### ISSUE TITLE
Improve asset proposal details view

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3781]
## Story

As a governance user
When I am considering voting on an asset proposal
I want to be able to see the full details of the proposal in a human readable way 
So that I can review them without having to decipher the proposal JSON

This is building on the work done for #3808 

## Acceptance Criteria

- [ ] I can view full asset proposal details in human readable format (UI components, not raw json)
    - [ ] I can view the ERC20 contract address
    - [ ] I can view the Name
    - [ ] I can view the Symbol
    - [ ] I can view the Decimals
    - [ ] I can view the Quantum 
    - [ ] I can view the Lifetime deposit limit
    - [ ] I can view the Withdrawal delay threshold
- [ ] There is a way to find more information on what all of these fields mean (e.g. mouseovers / click through)

## Tasks

- [x] Detailed sketch
- [ ] Work out what can be re-used from the console implementation of this data
- [ ] Implement UI
- [ ] Integrate with backend
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release

## Sketch

<img width="1235" alt="Screenshot 2023-06-22 at 10 11 06" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/67f12ba9-8f0a-4332-b7ac-7ffa92780055">
