### ISSUE TITLE
Improve page titles

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3798]
## The Chore

Some page titles (those seen in the browser tab, not visible on the page itself) are inaccurate and could be improved.

## Tasks

- [ ] https://validator-testnet.governance.vega.xyz/token – title is “Home”, change to “$VEGA Token”
- [ ] https://validator-testnet.governance.vega.xyz/token/associate – has no title, change to “Associate tokens”
- [ ] https://validator-testnet.governance.vega.xyz/token/redeem – title is “Vesting”, change to “Redeem vested tokens” (the title on the page itself should also be changed match)
- [ ] https://validator-testnet.governance.vega.xyz/token/disassociate – has no title, change to “Disassociate tokens”

## Additional details / background info
- [Slack thread discussing page titles](https://vegaprotocol.slack.com/archives/C038EB6V2RE/p1683189517551839?thread_ts=1683189207.796239&cid=C038EB6V2RE)
- Note [Barney's Slack message](https://vegaprotocol.slack.com/archives/C038EB6V2RE/p1683189207796239) and https://github.com/vegaprotocol/frontend-monorepo/issues/2425 also asks for general page title improvements, these could be handled simultaneously
