### ISSUE TITLE
Improve page metadata and link unfurls

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3799]
We think this would require major re-architecting and take weeks to implement and therefore questioning the value / urgency right now

## The Chore

Page metadata seems to be identical for all pages.

In this example, Slack unfurled links to [Token](https://validator-testnet.governance.vega.xyz/token), [Associate](https://validator-testnet.governance.vega.xyz/token/associate), [Redeem](https://validator-testnet.governance.vega.xyz/token/redeem), and [Disassociate](https://validator-testnet.governance.vega.xyz/token/disassociate) pages like so:

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/a680d452-c6e2-41c8-b1f0-48b6043da6ee)

At the very least each of these should use the page's proper title (which also need to be improved, see https://github.com/vegaprotocol/frontend-monorepo/issues/3798). Ideally each should also have a description, and we should consider what other options are available.

## Tasks

- [ ] Research best practice for metadata and page unfurls
- [ ] Consider in particular how proposal unfurls could give some insight into the content (and maybe status) of the proposal
- [ ] Write meaningful descriptions for all pages
- [ ] Implement metadata according to the above
- [ ] Test/QA

**Comment by sam-keen** [comment]
I've started some investigation into how to achieve this (it's not so easy with an SPA - most crawlers and social media bots don't execute JS so we can't control it within the JS of the app, and may need some static file generation). Awaiting a chat with @edd as something similar may be needed for Explorer.

@ckpringle if we opt for descriptions too, who should I go to for content? Thanks

**Comment by JonRay15** [comment]
I dont care about this and am unsure we will ever do it .... unassignig myself..
