### ISSUE TITLE
Improve new market proposal details view

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3808]
## Story

As a governance user
When I am considering voting on a new market proposal
I want to be able to see the full details of the proposal in a human readable way 
So that I can review them without having to decipher the proposal JSON

## Acceptance Criteria

When understanding the proposal 
- [X] There is a way to see the full summary description 
- [X] I can see the market specification in human readable format (UI components) with descriptions (e.g. mouseovers)to understand what all of these fields mean 
- [X] There is a way to see the proposal in raw JSON (e.g. in a popup)
- [ ] There is a way to copy the JSON to clipboard
- [ ] I can see the date and time the proposal closes 
- [ ] I can see the enactment date
- [ ] I can see who the proposer is 
- [ ] I can see when the proposal was made 

## Tasks

- [x] Detailed sketch
- [x] Work out what we can reuse from the Console implementation 
- [x] Implement UI
- [x] Integrate with backend
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release

## Sketch 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/a26ba02c-5c5c-4135-b2e6-2a05c052f2b3)

## Notes

- Relates to ticket #3791 to make the accordion currently used for market info in Console and market details in Explorer configurable which we hope will make it possible to use that common component to render  the details of a market proposal more fully. 
- [Example on block explorer](https://explorer.fairground.wtf/markets/e6561f69c2a76858866aab2896eeb529b46040614566e0665602d67bc682c31f)

**Comment by JonRay15** [comment]
FYI that markets "view JSON" pop up in explorer is pulling in a heck of a lot of market info, volumes, prices, account balances of some sort.

Not saying it cant be used here too but just pointing out it might need tweaking slightly to use just the governance API.

**Comment by sam-keen** [comment]
On pause for a mo until #3791 gets merged

**Comment by sam-keen** [comment]
Based on conversation with @JonRay15, I've amended the ticket to focus on new market proposals, as update market proposals will need to be dealt with differently
