### ISSUE TITLE
Connect dapp to browser wallet

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3819]
## Story

As a user
I want to be able to use the browser wallet beta release with the Console and Governance dapps to approve / reject transactions
So that I can experience it's awesomeness AND help Vega test and improve it 

## Acceptance Criteria

There are A/Cs already written and covered for Connect Wallet, Disconnect Wallet and Select and Switch Keys should pass against the browser wallet https://github.com/vegaprotocol/specs/blob/master/user-interface/0002-WCON-connect_vega_wallet.md

These may also be useful to consider if not already captured in the A/Cs above:
- [ ] I can use `client.connect_wallet` on the Vega API
- [ ] I can list permitted keys with `client.list_keys` after permissions are granted
- [ ] If I have no permissions for a given key `client.send_transaction` should fail
- [ ] If I have no permissions at all all `client.*` endpoints should fail except `client.connect_wallet`
- [ ] I can call `client.get_chain_id` without permissions
- [ ] I can receive and understand a message I receive from the browser wallet dapp telling me that it has disconnected from Console / Governance  

## Tasks

This ticket is dependent on https://github.com/vegaprotocol/vegawallet-browser/issues/211 as the browser wallet team would like the Console / Governance teams to be able to complete the integration using only the browser wallet documentation (not having any direct help from the team) in order to verify it is possible to do self serve.

Also, the browser wallet option may need to be live in fairground for ~6-8 weeks before being released to mainnet

- [ ] Read the documentation provided by the Browser Wallet team
- [ ] Detailed sketch (to incorporate the addition of another wallet option to the connect flow)
- [ ] Visual design (if needed)
- [ ] Implement UI tweaks and integration
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release

## Notes

Speak to Dex who can guide you through the integration

Documentation https://github.com/vegaprotocol/documentation/pull/629

Deploy previews of browser extension stuff

https://deploy-preview-629--vega-docusaurus.netlify.app/testnet/api/vega-wallet/reference/browser-extension/get-started

https://deploy-preview-629--vega-docusaurus.netlify.app/testnet/api/vega-wallet/reference/browser-extension/javascript-api

**Comment by pennyandrews** [comment]
@mattrussell36 in refinement for browser wallet, it came up that we would only expect Console / Governance connect Vega wallet flow to offer browser wallet as an option to connect if it detected the user had it installed, otherwise we wouldn't 'advertise' it's existence right now. 

I suspect this is likely NOT how we have done it right now so would be good to verify and discuss what we might do about this. Ta
