### ISSUE TITLE
Queue multiple trading transactions and approve all in one go

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/frontend-monorepo#3912]
## Story

As a trader
I want to make multiple trades in the UI (like a buy at a certain price, and a sell at some different price) and then approve both of them afterwards
So that I don't have to switch back and forth between the browser and the wallet

## Acceptance Criteria

- [ ] I can place two or more transactions one after the other without having to approve in between
- [ ] I can then approve all one after the other in the wallet itself.

## Tasks

- [ ] Investigate if this is a wallet problem or a console problem.]
- [ ] Adjust specs to include AC for sending multiple transactions
- [ ] Dev
- [ ] Test

## Additional details / background info

Not sure how high priority this would be, or whether anybody else would usually care about this. I just noticed it earlier while trading on the fresh mainnet markets, which had quite a large spread, and being impatient, just attempted to optimise by placing multiple trades before going to approve, which didn't work. I _did_ get an error displayed, so I was aware it was not supported, I just wondered whether it was something we thought other people might want to do.

**Comment by JonRay15** [comment]
Not doing this ... its been discussed
