### ISSUE TITLE
Review proposals journey in governance app

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3937]
## Story

As a user
I want to easily understand how to create and submit governance proposals on Vega and to be able to do so (as easily as possible) using the Vega app ecosystem    
So that I can feel confident to actively participate in Vega governance 

## Additional details / background info

The current journey got stripped back because it didnt quite work and we were out of time, so currently it goes:

1. Create new proposal
2. Directed out towards the docs
3. Create your proposal using the docs and paste it to the forums
4. Submit the proposal using the proposals/raw form

All the other individual forms and template generators etc have been removed from the flow completely because things didnt quite hang together. 

## Tasks

- [ ] Identify key stakeholders to agree improved journey
- [ ] Agree how conceptually we want this flow to go (forums / UI / Docs / who is making the proposals?)
- [ ] Build a new flow which achieves this and uses the components we have in the most efficient way
- [ ] Review the existing A/Cs and requirements in the related tickets
- [ ] Define the new set of ACs for the new flow

## Acceptance Criteria TBC

Relevant existing ACs can be found here and should be reviewed and refined as part of this ticket (bare in mind that Joe is working on adding coverage so the links referenced as not yet covered might be by the time we work on this so we'll need to do a bit of de duping):

- [Selecting a proposal type - not yet covered](https://github.com/vegaprotocol/frontend-monorepo/issues/3500)
- [Propose](https://github.com/vegaprotocol/specs/blob/master/user-interface/3002-PROP-propose.md)
- [Propose New Market - covered](https://github.com/vegaprotocol/specs/blob/master/user-interface/3003-PMAN-propose_new_market.md)
- [Propose New Market - not yet covered](https://github.com/vegaprotocol/frontend-monorepo/issues/3499)
- [Propose Market Change - covered](https://github.com/vegaprotocol/specs/blob/master/user-interface/3004-PMAC-propose_market_change.md)
- [Propose Market Change - not yet covered](https://github.com/vegaprotocol/frontend-monorepo/issues/3493)
- [Propose New Asset - covered](https://github.com/vegaprotocol/specs/blob/master/user-interface/3005-PASN-propose_new_asset.md)
- [Propose New Asset - not yet covered](https://github.com/vegaprotocol/frontend-monorepo/issues/3498)
- [Propose Asset Change - covered](https://github.com/vegaprotocol/specs/blob/master/user-interface/3006-PASC-propose_asset_change.md)
- [Propose Asset Change - not yet covered](https://github.com/vegaprotocol/frontend-monorepo/issues/3491)
- [Propose Change to Network Parameters - covered](https://github.com/vegaprotocol/specs/blob/master/user-interface/3007-PNEC-propose_network.md)
- [Propose Change to Network Parameter(s) - not yet covered](https://github.com/vegaprotocol/frontend-monorepo/issues/3492)
- [Propose Freeform - covered](https://github.com/vegaprotocol/specs/blob/master/user-interface/3008-PFRO-propose_freeform.md)
- [Propose Freeform - not yet covered](https://github.com/vegaprotocol/frontend-monorepo/issues/3490)
- [Viewing Governance Proposals - not yet covered ](https://github.com/vegaprotocol/frontend-monorepo/issues/3705)
- [Understanding vote status - not yet covered](https://github.com/vegaprotocol/frontend-monorepo/issues/3714)
- [Voting - not yet covered](https://github.com/vegaprotocol/frontend-monorepo/issues/3715)

## Relevant tickets / requirements 

That we want to consider as part of this work:

- #2212 
- #3731 
- #3729 
- #3728 
- #3713
