### ISSUE TITLE
Proposal list tile and summary enhancements

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3939]
## Story

As a user with a keen eye for community governance but potentially limited time to review all proposals in detail 
I want to be able to see the key details of a proposal and its status on the proposal list view
So that I can more readily assess the broad state of governance on the vega network at a glance

## Acceptance Criteria

On the Proposals list 
- [ ] I can see the closing date and time on the tile 
- [ ] I can see how long is left to vote (might do this) 
- [ ] I can see colourful / shouty things that prompt me to vote urgently on things "CLOSING SOON" 
- [ ] I can see the current voting status and whether it will pass 
- [ ] I can see the current participation and whether it will pass

On the Homepage
- [ ] I can see the top most recent 4 proposals with the same information as the cards on the proposals listing

On opening a proposal, I can see a summary of the most important information for a proposal first 
- [ ] I can see the proposal title [ rationale / title ] 
- [ ] I can see the market code [ instrument / code ]
- [ ] I can see whether majority has been reached for or against 
- [ ] I can see if participation levels have been reached to close the vote 
- [ ] I can see when the vote will end 

When my wallet is connected 
- [ ] I can see if I have voted for / against immediately on opening a proposal 
- [ ] I can see whether I have already voted or not on the card / list view (s) 

## Tasks

- [ ] Explore and sketch 
- [ ] Team and stakeholder review
- [ ] Design in context of whole page, considering the ID, Closed on, Enacted on, Proposed by, Proposed on summary placement as well as the rest of the page
- [ ] Team review
- [ ] Etc.

## Designs 
Homepage and proposal list cards: https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance?type=design&node-id=2838-20488&mode=design&t=YxXEdT3jxszC76M5-0

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/f54a5a34-1caa-4e12-ac7e-c9a0200fea67)

Proposal details page (summary at the top): https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance?type=design&node-id=2846-23539&mode=design&t=3nQAyhFgGK4tDRCu-0

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/1f28b6ca-9013-4792-97ce-fb19de0bc409)

## Sketches

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/a28a40f0-d033-4f6f-86c9-ed9447c19eed)

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/5220bb2d-d238-4c3d-be6a-759d09de4526)

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/a9c04643-5b59-435a-8b5b-22d6b5fdbfc3)

**Comment by jtsang586** [comment]
Hey @JonRay15 ,
Currently the proposal list shows how long left to vote rather than the close date. Even after user has voted, the tile still shows how long left to vote. Is this right?



![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/30622993/ad032921-d0a0-4d1b-81f1-492b7548d8a2)

**Comment by JonRay15** [comment]
I think its fine; even after you have voted you still in theory coudl change your vote until it closes.
