### ISSUE TITLE
Orderbook changes

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3945]
## The Chore

Changes to the order book to improve experience

## Tasks

- [x] Never show price levels with 0 orders (don't allow switching between modes)
- [x] Remove scrolling
- [x] Ensure the mid is centered
- [x] Show a single column for bid/ask volume
- [x] Improve aggregation to allow for more and less precision. Use quantum and asset decimals to determine min/max precision
- [x] Remove column headers
- [x] Prices should be vega-green for bids and vega-pink for asks
- [x] Ensure columns are price, volume, cumulative volme (from left to right)
- [x] Remove grid lines
- [x] Reduce padding within cells
- [ ] Don't show cumulative volume unless wide enough
- [x] Show as many rows as that can fit within each side

**Comment by barnabee** [comment]
General comments:

- important that at a glance you can see the shape of the depth by looking at the overall shape of the bars, i.e.
    - not excessive spacing between bars / rows
    - no grid lines
    - text colour / contrast isn’t overpowering
- needs to show the mid price in the centre
- ideally should be responsive - if narrow only show price and volume at price, if wider add cumulative volume
- No separate bid vol and ask vol
- No column headers

Cryptowatch (screenshot below) do it great. Ask @MM0819 for other examples of where it is done well.

<img width="247" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/1179257/2c297729-7f45-4106-aec2-8b0157d8d9f1">
