### ISSUE TITLE
Ability to "close" the settings page 

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#3951]
## Story

As a user
I want the ability to "close" the settings page 
So that I can get back to where I was before opening the settings page

## Acceptance Criteria

- [ ] I can click the settings cog to "close" the settings page
- [ ] There is a close button to "close" the settings page
- [ ] My state before going to the settings page is kept when I return

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Add ACs to Spec

**Comment by mattrussell36** [comment]
Blocking this as I think it may get superseded by incoming design changes

**Comment by JonRay15** [comment]
Will definitely be superseded by new changesto sidebar closing
