### ISSUE TITLE
Add quantum formatting to deal ticket

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3952]
## Story

As a user
I want to not see my estimated margin calculated to 0.000001 USDT 
So that my display looks nicer and doesn't end up text wrapping 

## Acceptance Criteria

- [x] I can see anything in the deal ticket currently using settlement asset decimals formatted using "Quantum Formatting" 
- [x] "Quantum Formatting" is defined as `Number DP = MAX(0, LOG10(100/Quantum))`
- [x] In the case where "Number DP" resolves as decimal round by normal logic to decide the number of decimal places
- [ ] There is a way to see the full number if I want to know the fully accurate number (e.g. with a tooltip)
- [ ] There is a way to find a definition of quantum, how it is calculated and why we use it in Console (i.e. [link to docs](https://github.com/vegaprotocol/documentation/issues/640))

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

NB. Ideally the 100 in the above would be configurable in the component, because we will probably use this in LP Dashboard too and in that we probably dont care about 1c .... we would only care about 1 USD min so having that configurable gives us flexibility.

**Comment by MadalinaRaicu** [comment]
@pennyandrews @candida-d @JonRay15 

not sure we have the docs to point the user to quantum formatting but I can add some information in the tooltip. 
for now, I added some tooltips so that user can hover on the formatted numbers and they can see the full price

**Comment by pennyandrews** [comment]
@MadalinaRaicu in case you haven't seen this thread discussing the ticket, might be helpful... https://vegaprotocol.slack.com/archives/C02TG33SX41/p1685117214158079

**Comment by MadalinaRaicu** [comment]
I think the docs ticket is not ready yet and I might be ready with adding the formatting in my linked PR. 
There is some general documentation related to quantum but it is mostly about [protocol level details]( https://docs.vega.xyz/mainnet/concepts/assets/asset-framework#protocol-level-details).

Right now I don't know where to add this information 

Should we split this ticket and create another one to show the docs when they're ready? Or should we specify more stuff in the tooltip? 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/b43277eb-7788-4534-8fb1-6a6cbe329fd1)

**Comment by JonRay15** [comment]
I think it is probably sufficient to show that full number with a note under it saying 

"Console uses the asset value of `quantum` to show figures to approximately 2 decimal places of precision, roughly equivalent to 0.01 USD.  For more information see the [docs](https://docs.vega.xyz/mainnet/concepts/assets/asset-framework#protocol-level-details)."
