### ISSUE TITLE
Recover lost withdrawals

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3953]
## Story

As a user whose incomplete withdrawal was lost due to network reset
I want a clear path to restore or complete that withdrawal
So that my funds are not irretrievably lost

## Acceptance Criteria

If feasible:
- [ ] Console automatically restores lost withdrawals to my list of withdrawals without any user input

If that is not feasible:
- [ ] I can find instructions actions to restore one or more lost withdrawals, in a place I expect, e.g. around the withdrawals tab
- [ ] Console acknowledges the possibility of lost withdrawals and explains why they happen

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by HenryEnrique** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110
