### ISSUE TITLE
Download withdrawal details

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3955]
## Story

As a user with any incomplete withdrawals
I want to back up my withdrawal details
So that I have all the information I need to complete the withdrawal in case of a network reset

## Acceptance Criteria

- [ ] I can download a file which contains all of the necessary withdrawal details
- [ ] The downloaded file has a meaningful name which helps me to distinguish it from other withdrawal details

## Tasks

- [x] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

From [the Miro board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764554009314529&cot=14):

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/006b7e2e-aea0-4382-892b-ee03a8dd4f90)

## Additional details / background info
- At present there is a button to copy the details to clipboard. This is useful, but does depend on the user pasting and saving the data somewhere. It's easy to forget to do this part. if we give a download button, we (and the user) know the file has been backed up, has a 
- @asiaznik has suggested the file could be json, which would also make it easier for us to process the file if it is uploaded in future.
