### ISSUE TITLE
Complete or back up withdrawals when a network reset is approaching

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3956]
## Story

As a user with incomplete withdrawals
I want to avoid losing those withdrawals due to a network reset
So that my funds are not irretrievably lost

## Acceptance criteria

If feasible:

- [ ] The system automatically backs up and restores incomplete withdrawals

If that is not feasible:

- [ ] If I have any incomplete withdrawals that are not subject to a delay, I am prompted to complete them
- [ ] If I have any delayed withdrawals, I am prompted to back up their details
- [ ] If I dismiss the prompt, it stays dismissed for 24hr

## Tasks

- [ ] Determine if it is possible/feasible to determine when network resets (or any other events which result in the loss of withdrawal records) are scheduled
- [ ] Sketch options
- [ ] Team and stakeholder review
- [ ] Implement
- [ ] QA

## Additional details / background info
Related:
- https://github.com/vegaprotocol/frontend-monorepo/issues/3459
- https://github.com/vegaprotocol/frontend-monorepo/issues/3953
- https://github.com/vegaprotocol/frontend-monorepo/issues/3955
