### ISSUE TITLE
Unable to reconnect to the selected node, even when it is suitable

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3958]
## User Story

As a Vega user
When my connection has been interrupted but is now back (i.e. I lost internet connection for a bit but am now back online)
I want to be able to reconnect to the same node I was previously connected to
So that I can quickly continue trading and am not mislead to think there is an issue with the node when there isn't

Here is a video of the current behaviour in Console:

https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/5fe68e88-562d-48d3-9567-d84f1b2ec264

## Acceptance Criteria
 
- [ ] I am automatically reconnected to the node I was previously connected to (best case)
OR IF THAT ISN'T POSSIBLE
- [ ] There is a way for me to reconnect to the same node I was previously connected to 
 
Options discussed for how we might achieve the alternative (less desirable) A/C if the more desirable one isn't feasible are:
- A retry button
- Clicking a different node and clicking back to the original node re-enables the 'connect to this node' button
- A way to indicate I am now online (i.e. I was offline and now I'm online 🤮  )

## Tasks

- [ ] UX
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
Old and node selector has moved on
