### ISSUE TITLE
List of transactions

### ISSUE THREAD

**Issue by sam-keen** [vegaprotocol/frontend-monorepo#397]
## Story

As a user 
I want to see a list of transactions ordered from most recent to least 
So that I can easily prove my transaction has occurred 

## Acceptance Criteria

- [ ] I can see a continuous list of transactions in order of most recent to least
- [ ] There is some pagination / staggered loading "load more" for speed 
- [ ] For each transaction listed I can see transaction type, submitter, transaction ID and time 

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [x] API support
- [x] Implement as per the infinite scroll component used on the blocks page
- [ ] Team review
- [ ] Etc.

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/191772574-640d09d0-baf8-4a6b-9bc4-6e0983f7bc08.jpg)

Miro - https://miro.com/app/board/uXjVPVRiSOM=/?moveToWidget=3458764534147549536&cot=14

## Additional details / background info

**Comment by dexturr** [comment]
Reopened as this feature had to be turned off due to issues in Tendermint. So we need an API provided by core in order to facilitate this new feature.

**Comment by joellecharlotte** [comment]
Attached is updated designs showing proposed Dropdown Styling, Mobile Nav + Search Behaviour and the Mobile TX List.

Question if we want to include the stats at the top on Mobile?

Also explored an alternative design for Mobile Search which hides the field until the icon is clicked ( Referenced [Christies ↳  ](https://www.christies.com/) ) - is bit tricky with the LHS switcher dropdown though and think similar to the current implementation makes more sense for now. 

![Image](https://user-images.githubusercontent.com/113684458/192255015-31c76bb3-3503-4729-be02-c6afcca48112.png)

**Comment by joellecharlotte** [comment]
Update after a review with @ckpringle.

More consistent active states for the Network Switcher and Explore Dropdowns. Simplified Nav on Mobile where everything is moved into one fullscreen modal. Search is as per the [Christies ↳](https://www.christies.com/) example where it's collapsed into an icon that exposes the field on tap. 

![Image](https://user-images.githubusercontent.com/113684458/192272085-e85751f4-0f2d-47ed-aa25-3dd9f1a4b319.png)
![Image](https://user-images.githubusercontent.com/113684458/192272086-3fef7e66-f384-4671-b45d-0f9b2bdb0666.png)
![Image](https://user-images.githubusercontent.com/113684458/192272084-116b2f66-e8ab-4c5f-b000-d60685727b91.png)
![Image](https://user-images.githubusercontent.com/113684458/192272083-f925a600-c8ef-482e-805f-3ea6e62d122f.png)
![Image](https://user-images.githubusercontent.com/113684458/192272087-dfc1d15f-a723-4985-a2c0-12eb917dc746.png)
![Image](https://user-images.githubusercontent.com/113684458/192272088-0bbab165-f3f6-4283-8acf-53390724f342.png)

**Comment by pennyandrews** [comment]
As discussed, I have created a separate file ticket to update this view based on the new designs https://github.com/vegaprotocol/frontend-monorepo/issues/1502 so we can review, estimate and prioritise this in the refinement session I'll pop in shortly

**Comment by AndyWhiteVega** [comment]
Vegacapsule currently does now show transactions, logged here: https://github.com/vegaprotocol/vegacapsule/issues/286
This is preventing QA from automating against this work.
