### ISSUE TITLE
Add sort by top traded to market selector

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#3970]
## Story

As a user
I want to sort the market list by total notional value in the market
So that I can trade on the most active market

## Acceptance Criteria

- [ ] I can sort by top traded (quantity traded, volume * current mark price price * quantum)

## Tasks

- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

- We can use the asset quantum value to normalize volume value across all markets for comparison
- More info on using the quantum value can be found here: https://github.com/vegaprotocol/frontend-monorepo/issues/3952

**Comment by mattrussell36** [comment]
While your there could you have a quick look into why the market selector is fetching markets every time you open it, we should have cached market data in the data provider
