### ISSUE TITLE
Console Transfer Window Asset selection dropdown improvement

### ISSUE THREAD

**Issue by ben-vegaprotocol** [vegaprotocol/frontend-monorepo#3972]
## The Chore

The asset selection feild in the transfer window of console behaves differently to the selection field of the vega key. 

These should behave more similarly for a consistent approach.

## Tasks

- [x] The selection dropdown is the same width as the field itself
- [x] The selection dropdown displays a please select when opened (same as vega key)
- [ ] ~~The the selection dropdown opens below the field (same as vega key)~~
- [x] The selection dropdown should looks and operate same as in deposit and withdraw dialougs
- [x] The highlight should be the same color as vega key
## Additional details / background info

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/7bf277bf-5d38-4b03-81d5-7931f6f846f4)

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/acfeccee-5973-43b3-bd56-caa6da9a8344)

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/e65b50e8-e784-46c2-8ef8-1a0de4a80fd1)
