### ISSUE TITLE
SPIKE: View profitability over time

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3979]
## The Spike

We want to investigate and decide what will be valuable to show our users in terms of profitability over time (the story outlined below) and work out how and where we can calculate the information required.... 

## User Story we want to Satisfy

As a Trader
I want to be able to view my profitability over time
So that I can understand how this has moved and changed and analyse what events have impacted my profitability 

## Acceptance Criteria (TBC)

- [ ] I can filter the data by date range
- [ ] I can filter the data by market
- [ ] I can filter the data by asset
- [ ] I can filter the data by account type (i.e. general, margin, bond etc.)
- [ ] I can view both realised and unrealised PnL
- [ ] I can see totals
- [ ] I can find detailed information about how profitability is being calculated

## Tasks

- [ ] UX + Dev + Accounting Expert (with input from key people from around the business i.e. Lewis) to further define what's valuable and how we go about getting it
- [ ] Team and stakeholder review
- [ ] Iterate and write ticket(s) for core and frontend as applicable

## Additional details / background info

In order to look at profitability over time we will need to have all ledger entry data and all trades and to be sure that we are doing it in a robust way as trying to do it and not getting it quite right could be misleading and therefore not valuable.

We would need core engineering to create the APIs to support this OR to create some other kind of layer to aggregate data and do the necessary calculations

**Comment by JonRay15** [comment]
Have pther tickets for this sort of thing
