### ISSUE TITLE
Publish /announcements library 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#3980]
## The Chore

There is a requirement to utilise the /announcements library to manage the banner on the vega.xyz marketing website:

https://github.com/vegaprotocol/frontend-monorepo/issues/3253

The work has been done on the announcements side I believe to update the website along with all the other apps but it seems that the library hasn't been published so the website is unable to consume it and therefore @goslingo is blocked from completing the work.

## Acceptance Criteria

- [ ] Ensure dependencies of announcements library are not unncessary

## Tasks

- [x] Publish announcements library
- [x] Check with @goslingo that he has everything he needs to be able to utilise this component
