### ISSUE TITLE
Display the notional value of last 24h traded volume somewhere in console or governance page

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#3982]
Blocked by: https://github.com/vegaprotocol/vega/issues/8409

## Story

As a DeFi user who may or may not be trading via Console
I want to see the notional value of the 24h traded volume on each market
So that that I can compare to other DeFi protocols and see that Vega is clearly a success. 

## Acceptance Criteria

- [ ] I can see the 24h notional value traded on a given market if it's displayed in the console
- [ ] The value should be rounded depending on total to display a compact but useful number (Eg. 5M, rather than 5,000,000)
- [ ] Value should be shown in the settlement asset of the market
  - [ ] Ideally it would be calculate as sum of `size * price` for every trade summed over the last 24h
  - [ ] If this is too painful / slow  then in my opinion `volume x mark price` is an acceptable approximation

## Tasks

- [ ] UX (if needed)
  - [ ] Decide on location for display
  - [ ] Decide on whether to show asset symbol 
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

Simply show in brackets in the following places

### On the market header

<img width="1193" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/ce02ca1e-2791-4d87-ade4-33214253fe34">

### On the markets dropdown

<img width="594" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/fe7682e3-50d2-43f4-ae2d-40bba1c3e208">

**Comment by mattrussell36** [comment]
@davidsiska-vega We don't have a feasible way of calculating this accurately without tracking every single trade, we think this should probably be added as a field to a candle

**Comment by mattrussell36** [comment]
@barnabee do you think this warrants a spot in the market header?

**Comment by barnabee** [comment]
If this is actual 24h notional (size * price for every trade, summed for the past 24h) then yeah I think this should be in the header. Probably in the volume cell, something like

> Volume (24h)
> 48.7151 (1.427m)

**Comment by JonRay15** [comment]
We can approx this a few ways

- Current price x 24h vol
- Price at some intervals over 24h x volume in those intervals (hourly sampling)
- Infra fees on that market / infra fee factor

Option 2 seems fair for now
