### ISSUE TITLE
Table action menu refinements

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#3984]
## The Chore

Refinements to the work carried out in https://github.com/vegaprotocol/frontend-monorepo/issues/2583

## Tasks

- [x] Change the “View asset” label to:
  - [x] “View asset details” on the collateral table
  - [x] “View settlement asset details” on the market page and positions table
- [x] Use the info icon in all instances of the above
- [x] Change the “Breakdown” label on the collateral table to “View usage breakdown”
- [x] This might be harder, but once you open the menu it’s unclear which row you are taking an action on. Could we maintain the mouseover style on the row (or if that’s too difficult, just the action button) until you close the action menu? _added to the action menu trigger ~Art_
