### ISSUE TITLE
Governance app (pre maintenance mode) review 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4000]
## The Chore

Once we have completed the work identified in the current prioritised backlog for the Governance app, we will need to make a decision whether it is in a good enough state to put into maintenance mode - by this we mean stopping having dedicated resource working on it continuously and instead just monitor feedback for any critical issues that we need to jump and collate feedback that we regularly review and decide if we want to address it and if so plan when to do the work. 

To make this assessment we plan to do a sweep of the app from both UX and QA perspectives (as well as a quick review of the icebox), collate a list of any significant issues we have remaining that could be tackled in the Frontend (without any dependency on core deployments) and make a proposal to our key stakeholders as to anything we think should be tackled before shifting to maintenance mode and releasing the resources to other projects. 

## Tasks

- [ ] Set up Miro board User Journey Map ready to capture issues
- [ ] Conduct a lightweight end to end UX review of all current Governance journeys, features and functionality and note issues
- [ ] Conduct an end to end Dev / QA review of all current desktop wallet journeys, features and functionality and note issues
- [ ] Review icebox and identify any issues that are still valid and we think should be considered further
- [ ] Review issues identified as a team and identify any we want to propose addressing before maintenance mode
- [ ] Discuss with key stakeholders (Barney, Ramsey, Jon, anyone else?)
- [ ] Reflect decisions made in the backlog and summarise in Slack
