### ISSUE TITLE
Add liquidation price estimate / range to positions view

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#4003]
## Story

As a user 
I want to see price estimate / range when my position is likely to get liquidatad
So that I don't get rekt. 

## Acceptance Criteria

- [ ] I can see the price estimate / range next to my open positions. 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

It's the same API that's used for estimating liquidation price on orders.

**Comment by MadalinaRaicu** [comment]
https://vegaprotocol.slack.com/archives/CFXA4EGN7/p1685531515692379

**Comment by bglownia** [comment]
I would suggest to make it depandant only on openVolume and collateral available (sum of margin and general account balances)

We will need to display it as range. But we may want to first format worst case and best case using quantum and check if they are  rounded to same value 

```
query Estimate {
  estimatePosition(
		marketId: "2718e2654fa6398769fc4fe661ceb7c79fa6e8f34a199422d91b5634323e1a3d",
		openVolume:"100",    
    collateralAvailable: "150"
) {
    liquidation {
      worstCase {
        open_volume_only  
      }
      bestCase {
        open_volume_only        
      }
    }
  }
}
```
