### ISSUE TITLE
Clean up orders, colume sizes and pane store dependencies

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4009]
## The Chore

These are being inadvertently bundled with the governance and explorer apps, even though they aren't required. This also results in the localStorage stores being created on startup

## Tasks

- [x] ensure dependencies on orders lib don't include orders store 
- [x] ensure dependencies on panes lib don't include panes store
- [x] ensure dependencies on column sizes lib don't include column sizes store

**Comment by mattrussell36** [comment]
columns sizes has already been cleaned up in https://github.com/vegaprotocol/frontend-monorepo/pull/4119
