### ISSUE TITLE
Don't start polling for Ethereum staking events until we know tx is in prog

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4011]
## The Chore

We currently immediately start listening for Ethereum events when you visit the app. This is so we can show update to date balance information when Vega APIs might be out of sync with data on the Ethereum chain. This leads to a lot of requests which can be avoid if we add some logic to start and stop the listener more smartly.

We need to wait to start the listener until 

A) we know there is a transaction in prog on startup
B) we know the user has initiated a transaction via the UI

Then when the transaction is complete we should stop the listener

## Tasks

- [ ] Only start listener if a transaction is in progress when the app starts (`getExistingTransactions`)
- [ ] Start the listener when the user executes a transaction
- [ ] Stop the listener when the user has no transactions in progress
