### ISSUE TITLE
Export CSV of rewards

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4023]
## Story

As a user
I want to easily export rewards and fees received by my key 
So that I can track my earnings over time 

## Acceptance Criteria

- [ ] I can export rewards and fees reflected on Governance dapp to CSV 
- [ ] I can understand what is included and what is not included in this export 
- [ ] I can see rewards across network upgrades i.e. not just since network restart (might need a separate ticket)
- [ ] Rewards / fees in the CSV are easily sorteable / formatted i.e. showing relevant timestamp 
- [ ] Rewards / fees are organised by reward type i.e. staking, infra fees, price taking, price making, liquidity provision, market creation

## Sketch / inspiration 
<img width="938" alt="Screenshot 2023-06-02 at 12 26 35" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/c3834e3d-272d-4985-955a-fa033abd5ad5">

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by ckpringle** [comment]
Duplicate / merged with #2319
