### ISSUE TITLE
Preserve state of Positions grid

### ISSUE THREAD

**Issue by ben-vegaprotocol** [vegaprotocol/frontend-monorepo#4033]
## Story

As a Console user
I want the positions form to be in the same state I left it in if I leave/close/refresh the page and return.
So that I can avoid having to change the grid to my preffered layout every visit.

## Acceptance Criteria

- [ ] The sort of each column is retained when leaving and returning.
- [ ] The ordering each column is retained when leaving and returning.

## Tasks

- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info
small thread about here: https://vegaprotocol.slack.com/archives/C037STCKMGC/p1685966926049119

**Comment by mattrussell36** [comment]
closing as will be covered by https://github.com/vegaprotocol/frontend-monorepo/issues/4063
