### ISSUE TITLE
Console should not prevent submitting an order just warn

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#4041]
## Story

**As** a user 
**I want to** be able to submit any order transaction 
**So that** I get only warnings if the order might be rejected/stopped

## Issue

Initially reported by @witgaw 

> So I sometimes get UI in the state where  “PLACE ORDER” button is greyed out (and not working). Not sure what the exact conditions are but it’s usually when I have my general account maxed out. The practical implication of that is that I cannot decrease my position in any other way than by just using the “close” button in positions. I’d argue that UI should never (except for entering a wrong data type) prevent a user from submitting an order (estimates and warnings is all there should be), it should be up to the actual app to reject the order. 

Clarification from @barnabee 

> Console should never prevent me trying to submit an order transaction, only warn

## Acceptance Criteria 

- [x]  be able to place any orders 
- [x] get only warnings when an order might be rejected / stopped 

## Tasks

- [ ]  UX (if needed)
- [ ]  Design (if needed)
- [x]  Team and stakeholder review
- [x]  Specs reviewed and created or adjusted
- [x]  Implementation
- [x]  Testing (unit and/or e2e)
- [ ]  Code review
- [ ]  QA review

## Additional details / background info

Created from: https://vegaprotocol.slack.com/archives/C037STCKMGC/p1686055859395639
