### ISSUE TITLE
landing page showing non validating nodes in Validators section 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4061]
## Description

On the Governance app landing page, the validator section is listing / counting nodes that are not validators
![image (23)](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/7d1fbe4a-8ac0-41c1-96b9-6eb9dc1a872a)

## Tasks

- Update all counts to include only validator nodes 
    - [ ] '_n_ active nodes' 
    - [ ] '_n_ consensus nodes' 
    - [ ] 'And _n_ more...'
- [ ] Review appropriateness of 'active nodes' label and revise if necessary
- [ ] Review appropriateness of 'consensus nodes' label and revise if necessary
- [ ] Only show logos for validator nodes
- [ ] Review with stakeholders
- [ ] Update automated regression tests to verify correct behaviour
- [ ] Exploratory testing

**Comment by pennyandrews** [comment]
Relevant intel in Edd's equivalent ticket here https://github.com/vegaprotocol/frontend-monorepo/issues/4155
