### ISSUE TITLE
Further optimise how the data tables are displayed 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4063]
## The Chore

- [x] Review ability to resize
- [x] Review implementation of persistent columns, we likely can persist more with a slightly different approach
- [ ] ~~Further reduce spacing in tables to be more efficient with space~~ Decided to actually add more space for some tables
- [x] Reduce minimum column width so that users can make them as narrow as they want (within reason)
- [ ] ~~Review filter icon and sort direction icon, can we ensure that they don't enforce col size or take up to much space.~~ These are fine

## Tasks

- [x] Adjust headers to match design
- [x] Adjust row height to match design
- [x] Make all columns resizable by default
- [ ] ~~Look into using autoSizeColumns column widths~~ Auto size is not suitable for most tables right now
- [x] Make column order persisted
- [x] Make removed columns persisted
  - Consider what happens if all columns are removed (reset all button in settings?)
  - Preferably we would keep ability to re size columns.
 - [x] Ensure we are using ag grid variables for compactness

## Additional details / background info

See the conversation in Slack here https://vegaprotocol.slack.com/archives/C037STCKMGC/p1684939669066659

**Comment by mattrussell36** [comment]
I think this is much more of an issue with how we currently persist columns widths:

- We are likely being too aggressive and storing widths before a user has even adjusted a column, these means that resizing a pane immediately pushes columns out of the panes element.
- We currently store column widths in exact pixel values, resizing a pane or window immediately 'breaks' this. Likely we should be using flex values or percentage
