### ISSUE TITLE
Improve visibility of 'add XXX $VEGA Tokens' button

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4065]
## The Chore

Reported by Gordon in Slack https://vegaprotocol.slack.com/archives/C038EB6V2RE/p1686212337486869

When managing stake The 'add XXX $VEGA Tokens' button is quite hard to see, it wasn't obvious that was the button I needed to press to complete the moving of stake.

![Screenshot 2023-06-08 at 09 10 35](https://github.com/vegaprotocol/frontend-monorepo/assets/47143694/02eb666d-360f-49f0-ae28-abcc3634be8a)

It looks like the button is using the secondary button style when perhaps it should be primary in this context?

## Tasks

- [ ] Sketch UX and design improvements to this staking interaction
- [ ] Implement
- [ ] Exploratory testing to check and verify the interaction works as expected
- [ ] Update / refine / add to relevant regression tests
- [ ] Release
