### ISSUE TITLE
Orderbook adjustments

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4069]
## The Chore

Some further enhancements for the order book

## Tasks

- [x] Brief Joëlle on these additions (and what they do / how they function)
- [x] Remove transition animation from volume bars
- [x] Add mid price direction arrow
- [x] Add resolution/zoom in/out buttons (may need icons)
- [x] Change resolution dropdown to use ui-toolkit dropdown
- [x] Hide columns depending on space available (hide cumulative volume first, then volume, price should always display)
- [ ] Add additional price level groupings (2, 5)

## Additional details / background info

- [ ] Use normal red/green (needs consideration alongside chart colors) - covered in existing ticket https://github.com/vegaprotocol/frontend-monorepo/issues/4104
