### ISSUE TITLE
Calculated `nx affected` JSON strings with less bash

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4072]
## The Chore

In order to make the build process more transparent and approachable for front end devs, we should rewrite some of the chunkier scripts in something more approachable than bash. The first one:

https://github.com/vegaprotocol/frontend-monorepo/blob/develop/.github/workflows/ci-cd-trigger.yml#L99-L161

This script produces valid JSON strings of which projects are affected. It had a bug in it, but otherwise largely works as expected. However exactly *how* is hard to work out if you aren't familiar with Bash, which no one online at the time was. We managed to get there. 

In order to reduce the dependency on bash writers, let's rewrite this in node.js

## Tasks

- [ ] Document expected inputs / outputs
- [ ] Extra script to node js script in a `tools` folder
- [ ] Update `.yml` to run the node script

**Comment by edd** [comment]
cc @mkjmdski @mattrussell36 - I'm probably OK to work on this task but need to take another look next week and will probably require some github action help

**Comment by gordsport** [comment]
Todo:

- [ ] re-write the bash script into Python so the FE team + devops can maintain
