### ISSUE TITLE
EPIC: Design changes

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4077]
## The Chore

Trading app design changes

## Tasks

**Prerequisites**
- [ ] Determine strategy for ui-toolkit/component library usage
- [ ] Implement library changes if required

**Ui toolkit updates**
- [ ] Update main site header/logo
- [ ] Tabs
- [ ] Buttons
- [ ] Notification
- [ ] Grayscale adjustment
- [ ] Use standard red/green for charts and price movements
- [ ] Switch font to Helvetica (so we have bold access)
- [ ] TBD...

**New components/features**
- [ ] Main site header/logo
- [ ] Pane context menu https://github.com/vegaprotocol/frontend-monorepo/issues/3114
- [ ] Tab badges
- [ ] Deal ticket changes. TBD...
- [ ] Market header changes
  - [ ] Remove name from market header (use code only)
- [ ] Market selector changes
- [ ] Add sidebar views with collapsed state (order submission, deposit, withdraw, transfer, settings, node health)
- [ ]
