### ISSUE TITLE
View 'Cancel Stop Order' Transactions

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4084]
## Story

As a Vega user
I want to be able to view 'Cancel Stop Order' transactions on Explorer
So that I can check and verify the details of the transaction / send to someone to evidence 

## Acceptance Criteria

- [x] I can see `Cancel Stop Order` transactions in the transactions list
- [x] I can identify `Cancel Stop Order` transactions in the transactions list (by type)
- [x] I can filter the transactions list to only view `Cancel Stop Order` transactions 

Check this one with Edd
- [x] I can view details of `Cancel Stop Order` transactions

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

The cancel stop order TX will have the same fields as a Cancel Order Transaction, so should look very similar. It has two fields:
- Market ID
- Stop Order ID

If Market ID is set and stop order id is not, cancel all stops in a market
If stop order ID is set and market ID is not, cancel one stop order
If both are set, cancel one stop order

As with Cancel Order, we should try to render the stop order as it was at the time of cancellation.
