### ISSUE TITLE
Description preview and read more pattern

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4091]
## Story

As a user
I want to see enough of a proposal description so I understand what this proposal is about without needing to expand all the collapsed sections
So that I can quickly work out if I want to learn more about this proposal or not

## Acceptance Criteria

- [ ] I can see the first few lines of the summary description when I first land on a proposal [ rationale / description ]  
- [ ] Vertical height should be fairly constant across diff screen widths
- [ ] There is a way to read the full description (Show More button) 
- [ ] There is a way to "collapse" back e.g. "see less"

## Background
e.g. read more pattern ![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/c8788c83-7651-43bb-9a1e-e1eef0814524)

https://snapshot.org/#/stgdao.eth/proposal/0x108a9e597560c4f249cd8be23acd409059fcd17bb2290d69a550ac2232676e7d

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Design

[See the design solution in situ in Figma here](https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance?type=design&node-id=2846%3A23539&mode=design&t=oMTYn2eS4bYPDQGK-1) ↳ 

<img width="941" alt="Screenshot 2023-06-27 at 12 26 13" src="https://github.com/vegaprotocol/frontend-monorepo/assets/113684458/4147b6ee-fea5-43cd-ac82-d56fd27b5d9d">

**Comment by sam-keen** [comment]
@ckpringle do you want design on this one or shall I crack on? Things that might need some consideration first:

1. How much text do we want to show? A character limit?
2. Does that character limit change based on screen width? i.e. do we want a fixed number of lines rather than characters?
3. For the 'show more', are you happy with the existing button styles I could use?

**Comment by ckpringle** [comment]
Re: char limit there it looks like others go with a pixel height of the container, which I'm happy with. This is very much inspired by snapshots implementation see example here: https://snapshot.org/#/stgdao.eth/proposal/0x108a9e597560c4f249cd8be23acd409059fcd17bb2290d69a550ac2232676e7d

**Comment by JonRay15** [comment]
I think this is worth a look ASSUMING it is a fairly easy to source component that we can just shove in.

Can we get a quick assessment of effort?

**Comment by JonRay15** [comment]
Whatever you think is best to get maybe 3/4 lines before the break
