### ISSUE TITLE
Simple diff highlight for update market proposals view

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4092]
The update market proposal equivalent of https://github.com/vegaprotocol/frontend-monorepo/issues/3808

## Story

As a user
I want to see the specification of the market being updated with the update highlighted
So that I can more clearly understand the impact of the proposal

## Acceptance Criteria

- [x] I can see the ~market specification in full~ fields that have been changed
- [x] There is a simple way to visually highlight / compare the difference with this market specification from the original markets specification e.g. using inline github style diff

## Background 

Breaks down into two main tasks:

### Technical Steps

- Maintain a list of the immutable fields to replicate the API
- Get the REST version of the proposal changes, as well as the original market's proposal changes, and the most recently enacted update of the market, if one exists
- Ensure the two version of the proposal to diff (the current proposal vs either the most recently enacted, or the original) contain all required fields, and that any values in the current proposal that are ignored by the API (i.e. won't change) are not reflected as things that will change in the diff

### How to display

Here we may need @ckpringle to do some design, but my thinking is there are two options:

1. Display ONLY the fields that have changed with some field / old value / new value formatting 
2. Display the entire new market with some additional annotation that shows which things have changed and their old values

~My preference is 2 because if we do this it will also solve the problem for Successor markets ... where I dont think 1 would be enough detail for that.  2 is also pretty easy given the way market updates are submitted you get the entire market definition in ... so you're just displaying that in full in the normal accordion, and adding some notation.~

We will go with option 1 here.  Successor markets is going to be handled slightly differently so worry about that later.

## Tasks

- [x] Identify possible libraries https://github.com/otakustay/react-diff-view, https://pschmucker.github.io/modiffy/
- [x] Work out the best approach 
- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketches

![Governance (  Token Utility) - Simple diff](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/8f0914c8-9350-4069-83d2-3e044c897c3d)
