### ISSUE TITLE
Submit Iceberg Order

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4095]
## Story

As a trader on vega console
I want to place orders with a relatively small "display quantity" and a larger total size
So the order is effectively split into multiple smaller orders and stays on the book for longer

## Acceptance Criteria

- [ ] I can create an iceberg order in the deal ticket
- [ ] I can specify a maximum size to display and trade at once
- [ ] I can specify a threshold beneath which the size of the order is "refreshed" to that maximum size
- [ ] I can find descriptions of iceberg orders and their parameters
- [ ] Form validation and messaging acknowledge restrictions on iceberg orders, such as:
  - Can only be applied to limit orders, not market orders
  - Time in Force (TIF) cannot be Fill or Kill (FOK) or Immediate or Cancel (IOC)
  - Peak size must be less than total size
  - Minimum size must be less than peak size and greater than 0

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

### Order form

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/59f8ae5f-6473-4757-9106-9323c7bbdd7e)

### Definitions

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/c2f27e4d-5ce9-4609-be05-33d9ec39d6e7)

## Additional details / background info
- See https://github.com/vegaprotocol/ux-and-visual-design/issues/96 for background and related tickets
