### ISSUE TITLE
View Iceberg Order Details

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4098]
See also: https://github.com/vegaprotocol/frontend-monorepo/issues/3394

## Story

As a trader who placed an iceberg order
I want to see the full details and progress of that order
So I can check I placed it correctly, and make informed choices about what to do next 

## Acceptance Criteria

- [ ] ~~In addition to the normal order parameters,~~ I can see the extra parameters I specified for my iceberg order: maximum peak size and minimum peak size
- [x] I can see how my iceberg order currently looks on the orderbook
- [x] I can see how much of the total size of my iceberg order has been traded, and how much remains

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [x] Testing (unit and/or e2e)
- [x] Code review
- [x] QA review

### Opening the details modal

Use the same pattern as the asset details modal: a link in the action menu with the info icon and the label "View order details"

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/28ec267e-ece2-4e17-8740-8c2f541ba5d8)

### Details modal

Use the same modal/table layout as the asset details modal

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/562fba4b-2c36-4097-b88c-8f451ccba441)

**Comment by neildawson** [comment]
Sorry @MadalinaRaicu I missed your mention

We now discussed this in a meeting, I'll write it up here so we can refer back

- In planning we opted not to develop the "amend iceberg order" function.
- It seems this is not supported by core anyway (to be confirmed, it might have been stagnet misbehaving).
- If we let people edit the normal fields, like size, this could still conflict with the iceberg fields. For example, if you edit size to be less than peak size, the change will be rejected.
- So for now **we agreed to hide the "Edit" button** for iceberg orders.
