### ISSUE TITLE
Submit OCO stop orders

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4099]
Dependent on https://github.com/vegaprotocol/frontend-monorepo/issues/4124. See also: https://github.com/vegaprotocol/frontend-monorepo/issues/4352.

## Story

As a trader with an open position
I want to place a stop loss and a take profit order at the same time
So that I can exert fine control over how and when I exit or reduce my position

## Acceptance Criteria

- [ ] I can submit:
  - [ ] a stop loss order on its own
  - [ ] a take profit order on its own
  - [ ] a stop loss order and a take profit order in a one-cancels-the-other (OCO) pair
  - [ ] a stop loss order and a take profit at the same time, but not paired
- [ ] I can find descriptions of stop orders and their parameters
- [ ] For each of the two orders (stop loss and take profit) I can:
  - [ ] specify a trigger, as either:
    - a fixed price
    - a trailing stop, expressed as percentage difference from the last traded price
  - [ ] specify a direction for the trigger: rises above or falls below – or this will be set automatically based on my open position
  - [ ] specify the order to be placed, including:
    - [ ] size
    - [ ] type: market or limit
      - [ ] for limit orders only, I can set a price
    - [ ] time in force: Fill or Kill (FOK) or Immediate or Cancel (IOC)
  - [ ] ~set an expiry date, and specify if the order should be placed or cancel on that date~ (this has been moved to another ticket, see [this Slack thread](https://vegaprotocol.slack.com/archives/C037STCKMGC/p1689759045502409?thread_ts=1689700230.514249&cid=C037STCKMGC) for details)
  - [ ] see the fees associated with the order
- [ ] Form validation and messaging acknowledge restrictions on stop orders, such as:
  - Can only place a stop order if you have a non-zero open position, or at least one active order
  - Cannot exceed the total number of open stop orders, defined by a (forthcoming) network parameter
  - Time in force (TIF) must be Fill or Kill (FOK), or Immediate or Cancel (IOC)
  - ~Must be "reduce only"~ (this restriction will be lifted in an upcoming core change)
  - If the trigger price is already met on submission, warn the user that the stop order will be triggered immediately

## Tasks

- [x] Chat to Lewis about trader expectations for this feature
- [x] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

From [the Miro board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764559765904928&cot=14):

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/cdf085f7-40a7-432f-8dbe-731212998f57)

## Additional details / background info

- [Slack thread on the outcomes of the stop order spike](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1686838755785979)
- [Slack thread discussing Vega's implementation of stop orders](https://vegaprotocol.slack.com/archives/CD4AKTFQT/p1689343084141839)
- [Slack thread discussing how to divvy up the stop order work](https://vegaprotocol.slack.com/archives/C037STCKMGC/p1689759045502409?thread_ts=1689700230.514249&cid=C037STCKMGC)

### Example behaviour from Barney

> Order type selector adds type = stop and then you can choose to add one or both directions of stops, but here you’d get all the fields from the stop submission instead of having them populated based on the order. Fields like size could be pre-populated to your current position size.
