### ISSUE TITLE
List Untriggered Stop Orders

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4100]
## Story

As a trader who placed a stop order
I want to see a list of my active stop orders (those which haven't triggered or expired)
So I can confirm it is in place, check I entered the correct parameters, and make informed decision about what to do next

## Acceptance Criteria

- [x] I can find a list of stop orders
- [ ] ~~I can see all parameters of my stop orders~~ Not feasible until we have an order details page, as there are too many attributes to fit into the existing order tables
- [ ] I can tell which orders have a one-cancels-the-other (OCO) relationship with another stop order

## Tasks

- [x] UX (if needed)
- [ ] ~~Design (if needed)~~
- [x] Team and stakeholder review (Bart, Neil, and Matt discussed)
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
  - [x] add "stop" to the order type: "stop limit" or "stop market"
  - [x] remove the "Updated at" column
  - [x] add a "Trigger" column to the right of the "Status" column
  - [x] Show the trigger values as per the sketch below
  - [ ] Don't show a filled amount for an untriggered order, show the "-" character used for empty cells
- [ ] Testing (unit and/or e2e)
- [x] Code review
- [ ] QA review

## Sketch

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/ed264a92-9fe5-4c54-854e-ec178c443fc9)
