### ISSUE TITLE
Amend stop orders

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4101]
## Story

As a trader who placed a stop order
I want flexibility to change the parameters of my stop loss and/or take profit orders before they trigger
So I can change my exit plan if my strategy changes

## Acceptance Criteria

- [ ] I can make changes to all parameters of my stop order(s)

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info
- There is no API support for amending stop orders. The old stop orders will need to be cancelled, and new orders opened.

**Comment by JonRay15** [comment]
Pretty sure this is done
