### ISSUE TITLE
Cancel Stop Orders

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4102]
## Story

As a trader who placed a stop order
I want the ability to cancel that stop order before it triggers
So I am not committed to an exit strategy I no longer want

## Acceptance Criteria

- [x] When looking at the list or stop orders, or detail of a single stop order, I can easily find a cancel control
- [ ] ~~I can tell if an order is part of a one-cancels-the-other (OCO) pair, and it is clear that cancelling one order will cancel the other~~ To be handled in OCO work

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [x] Testing (unit and/or e2e)
- [x] Code review
- [x] QA review
