### ISSUE TITLE
Revert chart colours to standard red and green (not the Vega brand colours)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4104]
## The Chore

Revert usage of vega-pink and vega-green for charts, buys/sell and up/down price movements to standard red/green colors

## Tasks

- [ ] Edit price chart colors
- [ ] Edit depth chart colors
- [ ] Edit order book colors
- [ ] Edit price change text

**Comment by joellecharlotte** [comment]
[This is the new red colour palette](https://www.figma.com/file/Zn0wrd1uZ0yBnCAATbI4gM/dApp-Foundations?type=design&node-id=6366%3A25999&mode=design&t=9WnuMedRHvQbuJLp-1) in the design system.

[Here is the new red](ttps://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=2917%3A6225&mode=design&t=JPJGXzMMIJ1AAbbO-1) as used in the dark mode version of the design.

red-500
red-550
red-600
red-700

The above tokens are the 4 reds used in the design from the full set of tones
