### ISSUE TITLE
Add Iceberg Order Details to Order Transaction Views

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4108]
## Story

As a Vega user
I want to be able to view iceberg orders on Explorer
So that I can check and verify the details of the order / send to someone to evidence 

## Acceptance Criteria

- [ ] I can see iceberg order data fields in the submit order details view
    - [ ] Initial peak size
    - [ ] Minimum peak size
    - [ ] Reserved remaining
- [ ] I can understand the progress/status of iceberg orders over time in the submit order transaction details view
  - [ ] I can see the visible size of the order on the orderbook at present
  - [ ] I can see how much of the total size of the iceberg order has been traded, and how much remains, at present

- [ ] I can get to the original Submit order from the cancel order transaction view (and see the iceberg details there)

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Frontend specs reviewed and created or adjusted to add A/Cs and codes
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
