### ISSUE TITLE
View 'Submit Stop Order' Transactions

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4109]
## Story

As a Vega user
I want to be able to view 'Submit Stop Order' transactions on Explorer
So that I can check and verify the transaction status and details  / send it to someone to evidence 

## Acceptance Criteria

- [x] I can see `Submit Stop Order` transactions in the transactions list
- [x] I can identify `Submit Stop Order` transactions in the transactions list (by their type)
- [x] I can filter the transactions list to only view `Submit Stop Order` transactions
- [x] I can view details of `Submit Stop Order` transactions, including:
    - [x] The Order instructions  (Direction, Trigger and Expiry)  
    - [ ] The Order ID of the submitted Order (if one has already been triggered)
    - [ ] The related submit Stop Order transaction (if it has one i.e. Stop Loss / Take Profit)  
- [ ] I can copy all IDs that are displayed in the view (Submit Stop Order ID, Party ID, Triggered Order ID, Party ID, Market ID)
- [ ] I can click on the IDs to find out more  

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

The shape of stop orders is not currently known yet (Edd)

**Comment by edd** [comment]
I put this down for a while as it was impossible to fetch the order created by a `stopOrderSubmission`. This is now in the API in 0.72.8+, so the branchi s active again.

First step was removing the 'deterministic ID' that never actually worked, now to actually add in the GQL query to fetch the orders ⌛

**Comment by edd** [comment]
Getting *somewhere*.

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/6678/c3386cf0-bef7-405d-936a-b1516a8d832d)
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/6678/5deff106-3029-4b34-b815-6de3d2f197e9)
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/6678/ba9666e6-2ed7-4005-91fd-935fd37df446)
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/6678/5e9b5137-ee1f-4de1-97a3-02aaa1aea553)
