### ISSUE TITLE
View Governance Initiated Transfer Proposals

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4110]
## Story

As a Vega user
I want to be able to view Governance Initiated Transfer proposals on the Governance Dapp
So that I can understand the details and implications of the proposed transfer and effectively participate in governance on Vega

## Acceptance Criteria

- [ ] I can see Governance Initiated Transfer proposals listed on the landing page
- [ ] I can see Governance Initiated Transfer proposals listed on the proposals page
- [ ] I can view Governance Initiated Transfer proposal details (in a human readable format)
- [ ] There is a way to copy source and destination IDs to clipboard easily 
- [ ] There is a way to see activity on source and destination e.g. link to block explorer 
- [ ] I can view the raw JSON for the Governance Initiated Transfer proposal details
- [ ] I can vote for or against a Governance Initiated Transfer proposal

## Tasks

- [ ] UX
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/267b8064-51e2-4267-a45b-71129257cdea)
