### ISSUE TITLE
Reduce footprint of "view as VEGA user" banner

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4117]
## Story

As a user of the "view as VEGA user" feature in console
I want an obvious indicator I'm in read-only mode that _doesn't use much space_
So that I always know what mode I'm in, and still have room to browse

## Acceptance Criteria

- [ ] I can see a clear indicator I'm in the read-only "view as VEGA user" mode
- [ ] That indicator cannot be overlooked; it is obvious I'm in a different mode
- [ ] That indicator takes up less space than the current full-width banner
- [ ] I can easily find a way to exit the mode

## Tasks

- [ ] Visual Design
- [ ] Team and stakeholder review
- [ ] Implement
- [ ] QA

## Sketch

The following suggestions are from @asiaznik

### Dismissable banner

You can also exit the mode from the wallet menu. If there was a clear relationship between the banner and the wallet menu, and/or the wallet menu itself communicated the read-only state of the app, we could allow the banner to be dismissed.

![image](https://github.com/vegaprotocol/ux-and-visual-design/assets/1080322/b94ba25e-5404-4bf7-a999-f48dfc06ae03)

### Reduced height banner

![image](https://github.com/vegaprotocol/ux-and-visual-design/assets/1080322/f60c36c6-cebe-417e-9ab1-34b006336cd7)

## Additional details / background info
- [Slack thread where we discussed alternative options](https://vegaprotocol.slack.com/archives/C037STCKMGC/p1682090003631399)

**Comment by asiaznik** [comment]
Partially sneaked into https://github.com/vegaprotocol/frontend-monorepo/pull/4289

**Comment by mattrussell36** [comment]
@asiaznik I'm going to re open this. Personally I think we should remove the banner entirely
