### ISSUE TITLE
Submit simple stop orders

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4124]
This is the "simple" stop order submission. See https://github.com/vegaprotocol/frontend-monorepo/issues/4099 for the "full" stop order submission.

## Story

As a trader placing an order
I want a simple way to add stop loss and/or take profit orders at the same time
So I can quickly establish a position with exit points

## Acceptance Criteria

- [ ] ~I can “add” a stop loss and/or take profit to a submission on the deal ticket to submit them in the same transaction as the main order (using a batch submission)~ This is no longer required
- [x] I can submit:
  - a stop limit order on its own
  - a stop market order on its own
  - ~both a stop loss order and a take profit order in a one-cancels-the-other (OCO) pair~ (this has been moved to another ticket)
- [ ] I can find descriptions of stop orders and their parameters
- [ ] Form validation and messaging acknowledge restrictions on stop orders, such as:
  - Cannot exceed the total number of open stop orders, defined by a (forthcoming) network parameter Lets leave this validation up to the wallet
  - Time in force (TIF) must be Fill or Kill (FOK), or Immediate or Cancel (IOC)
- [x] I can see a "reduce only" box which is ticked by default and cannot be unticked (for now this restriction exists though will be lifted in a later Core release
- [ ] If I attempt to untick that reduce only box a tooltip informs me that "Stop orders are for creation of take profit and stop loss orders and therefore must be reduce only"
- [x] I can choose a date and time at which my stop order will expire
- [x] I can choose a 'strategy' to be carried out at that time: execute (i.e. place the order) or cancel
- [x] If I click on the order book when using Stop Limit order the price populates (not the trigger price)

## Tasks

- [x] Chat to Lewis about trader expectations for this feature
- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [x] Testing (unit and/or e2e)
- [x] Code review
- [x] QA review

### For submission

From [the Miro board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764559661686617&cot=14):

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/996256e9-24a4-49b4-bb8c-007fb34cf22f)

### For expiry

From [the Miro board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764559687380384&cot=14):

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/d598e17b-9320-4ba3-974e-d12e85af5d4c)

### For submission

- [Slack thread on the outcomes of the stop order spike](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1686838755785979)
- [Slack thread discussing Vega's implementation of stop orders](https://vegaprotocol.slack.com/archives/CD4AKTFQT/p1689343084141839)
- [Slack thread discussing how to divvy up the stop order work](https://vegaprotocol.slack.com/archives/C037STCKMGC/p1689759045502409?thread_ts=1689700230.514249&cid=C037STCKMGC)

### For expiry

- [Slack thread on the outcomes of the stop order spike](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1686838755785979)
- [Slack thread discussing Vega's implementation of stop orders](https://vegaprotocol.slack.com/archives/CD4AKTFQT/p1689343084141839)
- [Slack thread discussing how to divvy up the stop order work](https://vegaprotocol.slack.com/archives/C037STCKMGC/p1689759045502409?thread_ts=1689700230.514249&cid=C037STCKMGC)
