### ISSUE TITLE
View stop order history

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4125]
Awaiting a release of https://github.com/vegaprotocol/vega/commit/03d818a59b77bb5607944124c59daf7ac9edbc9f

## Story

As a trader who placed a stop order that was triggered, cancelled, or expired
I want to see the details of that stop order and, if applicable, the order that was placed when it was triggered
So I can follow the trail of cause-and-effect, and understand how my choices affected my position

## Acceptance Criteria

- [x] I can see a list of triggered, cancelled, and expired stop orders
- [x] I can find all of the details and parameters of each stop order
- [ ] If the order was triggered, I can see the ID or a link to the order that was placed

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
