### ISSUE TITLE
View Cancel Governance Initiated Transfer Proposals

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4127]
## Story

As a Vega user
I want to be able to view Cancel Governance Initiated Transfer Proposals on the Governance Dapp
So that I can understand the details and implications of the proposed cancellation and effectively participate in governance on Vega

## Acceptance Criteria

- [ ] I can see Cancel Governance Initiated Transfer Proposals listed on the landing page
- [ ] I can see Cancel Governance Initiated Transfer Proposals listed on the proposals page
- [ ] I can view Cancel Governance Initiated Transfer Proposals details (in a human readable format) 
- [ ] I can view the raw JSON for the Cancel Governance Initiated Transfer Proposals details
- [ ] I can vote for or against a Cancel Governance Initiated Transfer Proposals

## Tasks

- [ ] UX
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/c7b835f8-a9fc-4749-a7c4-440ed50c8ecc)
