### ISSUE TITLE
View Governance Initiated Transfer Proposals

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4128]
## Story

As a vega user
I want to be able to find Governance Initiated Transfer Proposals in the [Governance Proposals list](https://explorer.vega.xyz/governance) in Block Explorer and see the details
So that I can understand what proposals are being submitted to the network (find out more about the implications of the proposals and participate in governance on Vega)

## Acceptance Criteria

- [ ] I can see Governance Initiated Transfer Proposals in the Governance Proposals list in Block Explorer
- [ ] I can identify Governance Initiated Transfer Proposals in list by type
- [ ] I can view key details of the Governance Initiated Transfer Proposals
    - [ ] Title
    - [ ] Type
    - [ ] State
    - [ ] Voting
    - [ ] Closing Date
    - [ ] Enactment Date
    - [ ] Terms (Raw JSON) in a modal
- [ ] I can click to view the proposal details on the Governance dapp (in a new window/tab) 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
We think this will happen for free based on the existing governance views in block explorer. Moving to in review.

**Comment by jtsang586** [comment]
Waiting for docs to be updated in order to get the details on how to submit transfer proposal
https://github.com/vegaprotocol/documentation/pull/698/files
