### ISSUE TITLE
View "Cancel Governance Initiated Transfer" Proposals

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4129]
## Story

As a vega user
I want to be able to find "Cancel Governance Initiated Transfer" Proposals in the Governance Proposals list in Block Explorer and see the details
So that I can understand what proposals are being submitted to the network (find out more about the implications of the proposals and participate in governance on Vega)

## Acceptance Criteria

- [ ] I can see Cancel Governance Initiated Transfer Proposals in the [Governance Proposals list](https://explorer.vega.xyz/governance) in Block Explorer
- [ ] I can identify Cancel Governance Initiated Transfer Proposals in list by type
- [ ] I can view key details of the Cancel Governance Initiated Transfer Proposals
    - [ ] Title
    - [ ] Type
    - [ ] State
    - [ ] Voting
    - [ ] Closing Date
    - [ ] Enactment Date
    - [ ] Terms (Raw JSON) in a modal
- [ ] I can click to view the proposal details on the Governance dapp (in a new window/tab) 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
Again ... in the block explorer we just show the list and we link back to the proposal in Governance. 

So again .... if the assumption on IDs holds this is easy.

**Comment by JonRay15** [comment]
Core now have a ticket and a PR to deliver the "fetch transfer by ID" API.

https://github.com/vegaprotocol/vega/issues/7461

**Comment by JonRay15** [comment]
Works 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/c3b5ec9c-0a6c-4e4a-bbd4-40fae2c3cde4)
