### ISSUE TITLE
Update Market Proposal tutorial to include Successor Markets

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4130]
## Chore

With the introduction of Successor markets feature, we need to update our documentation explainer content and tutorial: 
* concepts/governance
* proposals/new-market-proposal

## Acceptance Criteria

- [x] There is a description of what a successor market is and how it behaves
- [x] There is a tutorial on how to create a successor market proposal

## Background 

Specs: https://github.com/vegaprotocol/specs/blob/sucessor-market/protocol/0028-GOVE-governance.md#1-create-market

## Tasks

- [ ] Draft documentation
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
Lets get someone to run through the process once on fairground to make sure it works, then we close.
