### ISSUE TITLE
Successor Market proposals details

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4131]
## Story

As a user
I want to see when a market proposal is a successor market 
So that I know to look to see what has changed before voting

## Acceptance Criteria 
- [x] On the home page and proposal listing page summary, I can see which market proposals are successor markets 
- [x] On a proposal details view that is a successor market, I can see the Parent market ID and Insurance pool fraction in the market specification
- [x] On a proposal details view that is a successor market, I can see the Parent market ID and Insurance pool fraction in the proposal JSON
- [x] I can see an explanation of what "Parent market ID" is e.g. there is a tooltip "The insurance pool fraction is the fraction of the parent market's insurance pool to be transferred to this successor market. Once the parent market moves from "trading terminated" to "settled", the entire remaining insurance pool of the successor market is transferred."
- [x] If the proposal has been enacted, I can see the status of the market i.e. opening auction, continuous trading, rejected 

## Tasks

- [x] Sketch
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

![X Platform UX - Successor market proposal in governance dapp](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/11a84043-d16c-4a9e-a8b6-d906d283d98d)

Miro: https://miro.com/app/board/uXjVPUTU6m4=/?moveToWidget=3458764557843390355&cot=14
