### ISSUE TITLE
Highlight the differences for Successor Market Proposals

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4132]
Should get most of this for free after the work to do #4092 

## Story

As a user
I want to see the difference between the parent market and the Successor Market being proposed 
So that I can more clearly understand the impact of the proposal

## Acceptance Criteria

- [ ] I can see the market specification with the proposed update
- [ ] There is a simple way to visually highlight / compare the difference with this market specification from the original markets specification 

## Background 

Details of an existing market via the market API:  https://docs.vega.xyz/mainnet/api/rest/data-v2/trading-data-service-get-market, combined with governance API: https://docs.vega.xyz/mainnet/api/rest/data-v2/trading-data-service-get-governance-data details of a new proposal. 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch
![Governance (  Token Utility) - Successor market diff](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/cdd2f306-c3cb-4a3b-9308-86abaf1cec03)

Miro: https://miro.com/app/board/uXjVPUTU6m4=/?moveToWidget=3458764558106362635&cot=14
