### ISSUE TITLE
There is a successor market to this market

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4133]
## Story

As a user
I want to know if there is a successor to this market and whether there is trading volume there
So that I know to move there / consider it based on my current position

## Acceptance Criteria

- [x] In market view, I can see this market is nearing trading termination and has a successor
- [x] I can get to the successor market from the parent market i.e. there is a link 
- [x] I can see the trading volume of the successor market 
- [x] I can see when this current market (parent market) is due to terminate 
- [x] On the successor market, there is a way to see the parent market ID (in info tab)

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch
![X Platform UX - There is a successor market to this market](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/9758a770-2d0f-430e-9fba-4c643125a7e1)
