### ISSUE TITLE
See if a closed market was succeeded

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4134]
Might make sense to do together with https://github.com/vegaprotocol/frontend-monorepo/issues/4135

## Story

As a user
I want to know if a closed market has been succeeded 
So that I can easily find the successor market I can trade in

## Acceptance Criteria

- [x] I can see when a closed market has a successor market 
- [x] I can get to a successor market from a closed market i.e. there is a link 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch
![X Platform UX - Frame 20](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/2f9fc819-b168-49db-8aa7-80f3d6dd9fff)

## Additional details / background info
Related https://github.com/vegaprotocol/frontend-monorepo/issues/4135
