### ISSUE TITLE
View relationship between parent and successor markets

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4135]
## Story

As a user 
I want to see which markets are successors to which parents e.g. in market lists, market info panel
So that I can make an educated decision as to which market to trade on

## Acceptance Criteria

- [ ] In the left hand side market list I can see which markets have successors i.e. successor name
- [ ] From the left hand side market list there is a way to get to a successor market from the parent market  i.e.  there is a link to the successor market
- [ ] In the all markets list I can see which markets have successors i.e. there is a successor market name
- [ ] From the all markets list there is a way to view the successor market i.e. there is a link to the successor market
- [ ] In the proposed markets list I can see which proposed markets have parent markets existing i.e. parent market name
- [ ] From the proposed markets list there is a way to view the parent market i.e. there is a link to the parent market

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch
![X Platform UX - View relationship between parent and successor markets](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/d2b4d8e0-563a-46c1-a3ff-36024682281c)
