### ISSUE TITLE
Netlify tidyup

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4137]
## The Chore

No app is hosted on Netlify any longe

## Tasks

- [x] Remove `trading` `build-netlify`
- [x] Remove `explorer` `build-netlify`
- [x] Remove `lp-dashboard` `build-netlify`
- [x] Remove `explorer` `build-netlify`
- [x] Remove all `netlify.toml`
- [x] Fix governance README to remove Netlify references
