### ISSUE TITLE
Add toggle for network upgrades vs governance proposals to proposals list

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4145]
## Chore 

Completed network upgrades always show at the top of the closed proposals list because they do not have an enacted time and "hide" the governance proposals. We cant easily fix this unless Core make changes ... which they wont. 

This chore is to add a toggle in the CLOSED PROPOSALS section. 

## Acceptance criteria 
- [ ] There is a way to toggle between closed network governance proposals and closed network upgrade proposals
- [ ] When I toggle to network upgrades, I only see closed network upgrade proposals 
- [ ] When I toggle to network governance I only see closed network governance proposals 
- [ ] Open proposals is unaffected by this toggle 
- [ ] The closed network proposals are sorted with the most recent first 
- [ ] When I use the filter proposals search, only matching proposals will show on the page
- [ ] When I use the filter proposals search, and there are only results in one category of closed proposals, not the other, the view toggles to that view (right now it's only ever going to have results in network governance)
- [ ] I can see how many search results there are e.g. "(1)"
- [ ] When no proposals match my search, there is a message that tells me no proposals were found

## Tasks 

- [x] Sketch 
- [ ] Discuss 
- [ ] Implement
- [ ] Test
- [ ] 

## Design 
https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance?type=design&node-id=2838-18127&mode=design&t=O0exK4U6stOxMWet-0

## Sketch 
![Governance (  Token Utility) - Toggle network upgrade _ governance proposal](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/ec7cca03-cfe0-4deb-9ea6-9c27c9380d36)

## Background

* Add the toggle pattern from the validators page
* Values on it would be `Network Governance / Network Upgrades`.
* OPEN PROPOSALS should be left alone, because its unlikely that many will be open at once, and we dont want to hide anything.  the filter should only apply to CLOSED PROPOSALS. 
* The network proposals should be sorted by blockheight in descending order, so most recent first.

**Comment by sam-keen** [comment]
@ckpringle (assuming this sketch was yours): looks good, except once we paginate I'll not be able to show how many closed proposals exist, so I recommend we don't add the number in the toggle
