### ISSUE TITLE
Network treasury view

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4172]
## Story

As a user
I want to see how the network treasury is currently distributed for each asset type
So that I understand the current governance of treasury funds and can use this to inform any future governance transfer proposals 

## Acceptance Criteria

- [ ] I can see how much is in treasury, insurance pool, margin accounts, general accounts, how much in reward pools
- [ ] There is a way to see how the treasury is currently distributed per asset 
- [ ] I can see a total TVL of all accounts everywhere

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
