### ISSUE TITLE
Viewing recurring / future transfers

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4173]
## Story

As a user
I want to see all past, current and future transfers
So that I can easily track the history of transfers and spot any future transfers that might effect my decisions

## Acceptance Criteria

- [ ] There is a view of all Governance Initiated Transfers (the transfers themselves not the proposals) 
- [ ] There is a way to link from a Governance Initiated Transfer to the parent proposal for that transfer 
- [ ] There is a way to view transfers by account

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
Currently this is blocked by core - if indeed it is important enough to have an argument about. 

The BE will only ever show you the list of transactions that started recurring transfers.  It cant show the list of active recurring transfers or give you any useful info on "current status" of recurring transfers. And FUTURE transfers are impossible.

If we wanted any view like this we'd need someone from Core to help us work on some new API that could provide this info, or help build out the transfer API to do so.  But this is a completely different model to the current BE transaction list view so would be bespoke to showing these recurring transfers and it is not clear to me that this is important enough to bother doing all of that.
