### ISSUE TITLE
View successor markets

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4175]
## Story

As a user
I want to see successor markets on block explorer
So that I can identify which are related to which 

## Acceptance Criteria

- [x] I can see that this a successor market in the Proposal Submission transaction view
- [x] I can find out more about the parent market from the successor market proposal submission transaction view e.g. they are linked
- ~I can identify successor market proposals in the governance proposals list~ Not doing this - it's a poor use of space
- [x] I can see the additional fields for successor markets (at least parent ID) in the market details view (TBC where insurance pool fraction lives and if that's more relevant for the governance proposal only)
- [x] I can find out more about the parent market from the successor market view e.g. they are linked

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch
![X Platform UX - View successor markets (Explorer)](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/02c75ff0-2ee8-45ed-ba1d-df2882ac0632)
https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764558202640160&cot=14

**Comment by edd** [comment]
@pennyandrews There's a note in the Markets table:
> Shouldn't each row link to the market proposal?

This would be a good feature but it's not currently possible with the current API. A market's ID is based on the proposal ID, and the proposal ID is a hash of the Transaction signature. But I can't reverse that process and turn the ID back in to the transaction hash. This would require an API that could give me the proposal for a market.

**Comment by edd** [comment]
Added to the proposal summary view:
<img width="554" alt="Screenshot 2023-07-04 at 14 48 26" src="https://github.com/vegaprotocol/frontend-monorepo/assets/6678/c62b8fde-21dd-45d3-8b00-72ae4170be5f">
