### ISSUE TITLE
See a markets historical succession line

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4176]
## Story

As a user
I want to see a markets historical succession line 
So that I understand what has come before this market

## Acceptance Criteria

- [ ] There is a way to see a markets historical  succession line from a market view 
- [ ] I can view more about each market in that successor line e.g. they act as links to a market details view on console? Explorer?

## Additional details / background info
This could be accessible or visible in the console info tab + block explorer - it's to be decided the best place and way to handle it.

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
