### ISSUE TITLE
Group successor markets and parents in LP dashboard 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4177]
## Story

As a potential liquidity provider
I want to see markets grouped where there are successors and parent markets
So that it's clear where I should be looking to provide liquidity (the successor) 

For example, the main row for a market would have the title of the grouping BTC/USD with the successor market primary, and current / parent market(s) visible looking "secondary".

## Acceptance Criteria

- [ ] I can see successor markets and their parents visually associated to one another 
- [ ] Parent markets are treated secondary to successor markets 
- [ ] There is an explanation e.g. label that one market is a successor
- [ ] I can see the expiry of current / parent market 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
