### ISSUE TITLE
Show there has been a successor market proposed

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4180]
## Story

As a user
I want to know when a successor market has been proposed for the market I'm trading on 
So that I know where to go vote on it if I want to 

## Acceptance Criteria

- [x] There is a way to see if a successor market has been proposed for the market I am currently trading 
- [x] There is a way to handle when there are multiple proposals 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [x] Code review
- [ ] QA review
