### ISSUE TITLE
Group successor market proposals for the same Market ID

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4181]
## Story

As a user
I want to easily see if multiple successors have been proposed for the same market ID
So that I know that I have a choice to make

## Acceptance Criteria

- [ ] There is a way to see successor market proposals grouped by market ID in the event of there being multiple successor proposals for the same market

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
I remain unconvinced of the value of this.  It breaks our normal sorting pattern unless we create some new funky nested sort display thing, and that risks being a potentially long-winded piece of work... all for a situation that I remain unconvinced will happen any time soon.  ie. multiple parallel successor proposals AND lots of other open proposals that mean you cant already see them all next to each other.

So for now I'm pushing this out.

**Comment by JonRay15** [comment]
Not doing this until it becomes a problem
