### ISSUE TITLE
Liquidity provision fee formatted incorrectly

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4188]
## Description

In the Block Explorer's transaction view for Liquidity Provisions, the fee is formatted incorrectly.

## Steps to Reproduce

1. View a relevant transaction
```[tasklist]
### Tasks
- [ ] Fix LP Subsmission fee view
- [ ] Fix LP amendment fee view
- [ ] Add tests tests
```
