### ISSUE TITLE
Order list column changes

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4200]
## The Chore

Changes to the filter table to save some space and allow for additional information to be shown for stop and iceberg orders

## Tasks

- [x] Time in force. Use short version
- [x] Combine created at/updated at into single column
  - Show updated if order was amended, or only ever show created
- [x] Combine fills and size or alternatively remove size value from fills column
  - If combined sorting/filtering should still use the actual fill value
