### ISSUE TITLE
Public JS Library

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4204]
## Story

As an open source project team
We want to provide a publicly available JS library for browser wallet 
So that anyone can use it to integrate their dapp with Vega

## Acceptance Criteria

_A/Cs to be negotiated as a wish list by Barney but his direction is also that this isn't something that should hold up launching or radically change the design of browser wallet!_

- [ ] There is a single JS library that covers all Vega wallets (Browser wallet, CLI wallet (and desktop if still being supported))
- [ ] The library is well documented and easy to use (subjective 😄 )
- [ ] The library is available on NPM (Node Package Manager)??

## Tasks

- [ ] Create new package that's TS/JS only
- [ ] Keep UI bits in existing package, move the logic bits to new package (optionally publish this to make the lives of people using react easier)
- [ ] Publish new lib
- [ ] Document throughly
- [ ] OPTIONAL: Create an example connection dApp so people can use this al la web3 react
- [ ] Write unit tests ?
- [ ] Write end to end tests ?
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Notes

https://vegaprotocol.slack.com/archives/C052YCSFW6P/p1684743492882949

The Console team already have something a bit segmented for this in the form of the [wallet lib](https://github.com/vegaprotocol/frontend-monorepo/tree/develop/libs/wallet). This took inspiration from ethers and allows an adapter pattern for connections from different sources (REST, hosted, CLI and soon injected/extension).

We publish some of these libs already (e.g. ui toolkit) so the work to publish them should be pretty easy. At the moment this contains some react specific UI to help with connection which I don't think is what you're looking for, ideally this should be a JS only library that anyone can use to integrate with Vega and needs to be well documented.
