### ISSUE TITLE
List Spot Markets in the Market Switcher

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4212]
## Story

As a Console user
I want to be able to view a list of active spot markets in the Market Switcher panel
So that I know they exist and can choose to view one 

## Acceptance Criteria

- [ ] I can view a list of all Spot markets in the 'Spot' tab of the Market Switcher (ordered however we order normal markets)
- [ ] They obey all the normal rules of that selector in terms of filters / sorts etc

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by MadalinaRaicu** [comment]
This is done 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/b91d9808-ef5e-4aff-9bcc-47daefeb73ea)

**Comment by JonRay15** [comment]
This already worked ...
