### ISSUE TITLE
List Spot Markets on the Markets Page

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#4214]
## Story

As a Console user
I want to be able to view Spot markets in the Markets page lists (i.e. differentiating them from Futures, Perpetuals etc. via a 'Type' column or similar)
So that I know they exist and can choose to view one 

## Acceptance Criteria

- [ ] I can see spot markets in the open markets tab
- [ ] I can see spot markets in the proposed markets tab
- [ ] I can see spot markets in the closed markets tab
- [ ] The markets are shown with a "SPOT" tag under the code instead of PERP or FUTR
- [ ] Change "Mark Price" to simply "Price" to be more generic and use the `lastTradedPrice` instead

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/ad81b21d-7cae-4a94-b3e4-6dfe3d1d323c)

**Comment by MadalinaRaicu** [comment]
This works already as expected, the only change is renaming mark price column

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/dbff3cf7-ac83-40d5-b6ad-64db9e9054d2)

**Comment by MadalinaRaicu** [comment]
https://github.com/vegaprotocol/frontend-monorepo/pull/6151
