### ISSUE TITLE
Improve block explorer pagination

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4215]
## The Chore

After #4070 is complete, the inifinite loading will be gone! Pagination will rule again. Except it relies on a client side hack, because the API didn't support pagination in a way that allowed for going backwards nicely. This is coming in https://github.com/vegaprotocol/vega/pull/8627 - which is merged, but not redeployed. When it is, we can remove the hack and make some improvements

## Tasks

- [ ] Remove `previousCursor` from the state
- [ ] Update the URL with the cursor each time the page moves
- [ ] Take the cursor from the URL if it is set
- [ ] Persist the filters in the URL along with the cursor
- [ ] Take the filter (currently just one) from the URL (https://github.com/vegaprotocol/vega/pull/8543)
