### ISSUE TITLE
Chart quick trading

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4241]
## Story

As a user
I want to be able to edit and cancel orders directly from the chart
So that I can more trade more quickly

## Acceptance Criteria

- [ ] I can drag an order annotation to edit the price
- [ ] I can cancel the order by clicking a button on the annotation

## Tasks

- [ ] UX (if needed)
- [ ] Create issues for pennant
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
  - [ ] Pennant (provide necessary callbacks)
  - [ ] Console (plumb in order transaction submission)
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info
- [Michael's demo of chart trading on IG (skip to 27:43)](https://grain.com/share/recording/e2d3bc1e-e3a7-4708-af92-397a8ecef7d6/V7fGqFsEyC7Llkp87fEakbR33Mj4Ds3jXc6R6UAB) 
- [Competitor examples and sketching around annotations in Miro](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764560321434229&cot=14)

**Comment by mattrussell36** [comment]
@johnwalley would be good to touch base with you on this one
