### ISSUE TITLE
Place spot orders

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4243]
## Story

As a trader on vega
I want to place orders on spot markets
So I can own assets outright

## Acceptance Criteria

- [ ] When viewing a spot market, the deal ticket reflects the limitations and characteristics of spot orders:
  - [ ] An order in a spot market cannot be "reduce only" (as there is no position to reduce)
  - [ ] Long/short language is replaced with buy/sell (if deemed necessary)
- [ ] I can tell that fees may be deducted from my proceeds when selling

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
