### ISSUE TITLE
Show spot assets in Collateral tab and asset breakdown

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4244]
## Story

As a trader with an open order in a spot market
I want to see what funds are being reserved to support those orders
So I can trace all of my funds and make informed decisions

## Acceptance Criteria

- [x] The "total" balance in the collateral table should now include any funds set aside for spot orders
- [x] The asset breakdown modal lists funds reserved for orders in spot markets
- [x] Ensure holding account is specified in the user breakdown

## Tasks

- [ ] UX
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

The new accout type shoudl be `ACCOUNT_TYPE_HOLDING_ACCOUNT` but TBC

## Sketch

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/e6171fc8-102a-4d21-abcf-1a2854eb3472)
