### ISSUE TITLE
Support new proposal types for spot markets

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4245]
## Story

As a vega user creating or managing a spot market
I want governance site to acknowledge and support the proposal types 
So I can create and update spot markets

## Acceptance Criteria

- [ ] Ensure governance app can show spot market proposals
- [ ] Ensure governance app can submit spot market proposals via the JSON submitter

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
