### ISSUE TITLE
Update market info pane for spot markets

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4247]
## Story

As a trader on vega console
I want to see details of my spot market in the market info pane
So I can understand the market

## Acceptance Criteria

- [ ] Instrument needs to show the spot details properly 
- [ ] Remove funding / settlement / termination config (no oracles here)
- [ ] Remove mark price config
- [ ] Rename settlement asset "Quote asset" and show that content
- [ ] Add another section for "Base asset" and show the same content again for that asset 
- [ ] Remove risk model 
- [ ] Remove margin scaling
- [ ] Remove risk factors
- [ ] Remove liquidation strategy
- [ ] Remove succession line

## Tasks

- [ ] Review spot market proposal and market data to determine what differs from futures markets
- [ ] UX
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
