### ISSUE TITLE
Update to support new spot market proposal types

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4251]
## The Chore

The introduction of spot markets will bring new proposal types, and the browser wallet must be updated to support them.

## Tasks

- [ ] Update to support the addition of the new proposal types
  - [ ] New spot market
  - [ ] Amend spot market
  - [ ] Update market state (also applies to futures markets, states can be suspended, resumed, terminated)
