### ISSUE TITLE
Manage display of orders on charts

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4254]
## Story

As a user
I want to be able to manager order annotations
So that I can either see orders on the chart or not

## Acceptance Criteria

- [ ] I can toggle all order annotations off/on in the pane context menu for charts

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

- Assumption is we will add some toggle to this menu:
- Similar to the Show / Hide closed orders at the bottom, just have a toggle button on the far right.

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/76140c5b-d171-4a2b-9313-f78780262ef1)
