### ISSUE TITLE
Enhance positions table to deal with closed / settled positions and markets

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4270]
## Story

As a trader on console
I want to have my now dead positions on closed markets made less prevelant - or gone entirely - from the positions view
So that I dont take a few seconds each time i load the positions tab to identify those dead positions and either filter them out or sort them to the bottom

## Acceptance Criteria

- [x] I can click a toggle in the pane context area to hide/show closed markets
- [x] It should default to only show open markets
- [x] It should persist the toggle in the vega_positions_store.

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [x] Testing (unit and/or e2e)
- [x] Code review
- [x] QA review

## Sketch

Current view ... seems to be alphabetical so settled positions are scattered among open ones ... which is suboptimal.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/579cfb23-9a51-4bcd-bdb3-603c471d68e4)

## Additional details / background info

I could imagine various solutions to this of increasing difficulty
1. Just get rid of settled positions ... potentially not ideal at the moment as not sure we have anywhere else to view this P&L?
2. Just sort by last updated to the top, by definition the closed ones will sink to the bottom if you're still actively trading
3. Sort by market status first and then alphabetical so settled ones are at the bottom but alphabetical ordering is maintained 
4. Create some other place for reviewing historic P&L

**Comment by mattrussell36** [comment]
@JonRay15 We are proposing using the pane context menu to allow you to show/hide closed positions.

**Comment by JonRay15** [comment]
Ok that probably works
