### ISSUE TITLE
Improve wording for position resolution indicator tooltip

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#4278]
## Story

As a trader
I want to clearly know what happened to my position and why when position resolution occurs / I am liquidated
So that I am fewer confused

## Acceptance Criteria

- [ ] Hovering the indicator shows either "Your position was [closed|liquidated]" or "Your open orders were cancelled" etc. not things like "Your position was affected by market conditions" and "Maintained by network"
- [ ] Secondary text should explain things like "You did not have enough USDT collateral to meet the maintenance margin requirements for your position, so it was closed by the network." or "You did not have enough USDT collateral to for the orders you had placed on the book, so they were cancelled by the network." 
- [ ] For loss socialisation: "You received less USDT in gains that  you should have when the market moved in your favour. This occurred because one or more other trader(s) were [liquidated|closed out] and did not have enough funds to cover their losses, and the market's insurance pool was empty."

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [x] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
