### ISSUE TITLE
Add liquidation price back in the positions table

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#4282]
## Story

As a trader 
I want to be able to check the liquidation price in the positions tab
So that I can manage my positions effectively

## Acceptance Criteria

- [ ] See the liquidation price in the positions tab

## Tasks

- [ ] Add the liquidation price column back in the positions table
- [ ] Use estimatedOrder API
