### ISSUE TITLE
 Feature flag config

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4285]
## The Chore

Create a feature flag configuration to enable easier deployment

## Tasks

- [ ] Review explorer/governance feature flags and determine if same pattern can be used
- [ ] Create feature flag config based on app and core version
- [ ] Update cosmic elevator features to use the flag
