### ISSUE TITLE
Positions table improvements

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4301]
## Story

As a trader
I want to have a better experience using the positions table
So that I get the most useful values possible

## Acceptance Criteria

- [x] Remove updated column
- [x] Combine Market code and settlement asset/product type
- [x] Combine open volume/notional under column 'Size'
- [x] Combine AEP/Mark price under column 'Entry'
- [x] Combine Margin and leverage under column 'Margin'
- [x] Add 'x' after leverage.
- [x] Only show worst case for liquidation price

## Tasks

- [x] UX (if needed)
  - Determine which or if all fields should use quantum
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [x] Testing (unit and/or e2e)
- [x] Code review
- [x] QA review
