### ISSUE TITLE
Show new liquidity SLA info in market info

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4313]
## Story

As a trader on Vega
I want to know the requirements for liquidity providers 
So I can assess the health of the market

## Acceptance Criteria

- [ ] The new liquidity SLA parameters can be found in the market info area
- [ ] The information architecture of the market info area (groupings and titles) can be understood by a typical use
- [ ] All the information below (in the market section) is available in the market info
  - [ ] Price raneg should already be there under Liquidity Price Raneg so no change
  - [ ] Other 4 items should be nested under a new section called "Liquidity SLA"

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/f0321ea8-52df-448b-99dc-fb096df6ea25)

## Tasks

- [x] UX (if needed)
  - [ ] Reconsider the groupings and titles to ensure all info is findable
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/c7665d38-30fa-4a02-a1dc-8ea790046a87)

## Additional details / background info
- SLAs will only be in Spot markets at first

**Comment by JonRay15** [comment]
I suspect this stuff is _fairly_ simple and just comes down to what data we are getting from the markets API. 

I cant see anywhere that any information is **crucial** in this area to ensuring the users have what they need, so suspect it is just a case of whatever is there we will publish.

Have pasted the section from the spec above .... not clear to me how much of that is new.

**Comment by bwallacee** [comment]
@MadalinaRaicu @JonRay15 So it works but looking at it from a base macbook resolution etc
<img width="308" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/efaaa961-dfc7-4b3f-8d5f-cb193e3fc1a0">
It can be "hard" to tell what is the title and what is the value. I wonder if there's anything we can do with colours or font weight or something so the values are clearer. If that makes sense?

**Comment by MadalinaRaicu** [comment]
I am very open to update all these SLA labels, maybe we can make them a little bit shorter. 

Also open to change font colors or sizes to make the labels clearer. @mattrussell36

**Comment by JonRay15** [comment]
I agree ... I think we do:

1. Reduce the font size of both the field and value so it is appreciably smaller than the heading (liquidity SLA protocol)
2. Change the text of the field to be grey, this would align to how we show field / value in the deal ticket 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/9aadc3fe-f83b-4620-8bfa-9cb324411a21)

**Comment by JonRay15** [comment]
Will move that part to another ticket
