### ISSUE TITLE
Show new liquidity SLA info in market LP table

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4314]
## Story

As a trader on Vega
I want to know if liquidity providers are meeting their commitments
So I can assess the health of the market

## Acceptance Criteria

- [ ] I can see the relevant parameters from the market proposal & the network parameters that allow me to get a full sense of the required SLAs that LPs are supposed to be meeting for that market.
  - [ ] Maybe this could sit in a tooltip or a popup if you click on the market liquidity info at the top?
  - [ ] Remove market ID (its in the URL if people need it)
  - [ ] Add quantum formatting to target stake and supplied stake
  - [ ] Add market.liquidity.priceRange to the top market bar
  - [ ] market.liquidity.committmentMinTimeFraction to the top market bar
  - [ ] Add time to next epoch? (Nice to have)
- [ ] Change "Commitment" to "Committment Amount" and use quantum formatting
- [ ] Market valuation at entry should use quantum formatting
- [ ] Obligation should be taken from `requiredLiquidity` on the API and use quantum formatting
- [ ] Buy volume supplied can now be taken from `notionalVolumeBuys` on the API
- [ ] Sell volume supplied can now be taken from `notionalVolumeSells` on the API
- [ ] If either of those values falls below `requiredLiquidity` we should highlight them in warning colours
- [ ] Must show fraction_of_time_on_book for each LP for the current epoch - needs to be on the LP API
- [ ] Must show liquidity fees received in the previous epoch - needs to be on the LP API
- [ ] Must show the SLA scores and penalties received in the previous epoch - needs to be on the LP API
- [ ] ~COULD show the LP rewards received by each LP based on the rewards API~
- [ ] ~COULD show the SLA bond penalty if applicable but requires looking at specific transfer type on the ledger entry API~

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

Can we add the market info up here somewhere?

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/f9b32bb9-0057-4c9b-b112-19c6c26bc6c5)

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/359fcee4-65fe-4c4f-9f07-f4006376f538)

**Comment by JonRay15** [comment]
This one is more complex ... and I am not clear here what we'd ideally show, or what we can show! Have tried to have a stab above.

**Comment by JonRay15** [comment]
"Earmarker fees"?

LPs can get fees attributed to them which they will get if they do not incur any penalties.   Need to check if this is possible.

**Comment by JonRay15** [comment]
Have added links to new Core issue to close out the APIs here. 

https://github.com/vegaprotocol/frontend-monorepo/issues/4314

**Comment by JonRay15** [comment]
Not sure on the core ticket but I THINK this is now in Staging and could be built.
