### ISSUE TITLE
Show total Liquidity Provision fees paid last epoch across the whole market

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4317]
## Story

As a potential liquidity provider
I want to see examples of returns
So I can make an informed decision about providing liquidity on vega

## Acceptance Criteria

- [ ] ~I can see the total Liquidity Provision fees paid out over the lifetime of each market~
- [ ] I can see the total liquiditu provision fees paid out to all LPs in the last day
- [ ] These should be shown in the headline stats on the market's liquidity provision table

There might now be a [new API](https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-list-paid-liquidity-fees) that gives this number very easily

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

Think we put it up here in the headline bar.

If we need to save some space we could apply the shortened market ID with the copy button?

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/eb853205-9579-4225-a7af-fd70a9b13c4b)

## Additional details / background info
- [Suggestion from Barney in Slack](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1689168706295309?thread_ts=1689162667.366119&cid=C8WS7M50E)
- Ticket for the same task on the Vega.xyz liquidity dashboard: https://github.com/vegaprotocol/vega.xyz/issues/733
- This will I think involve querying the ledger entries API and filtering for the appropriate account / transfer type for that market
- Note I dont think it requires the ledger summaries API, the existing one is fine (if it works)

**Comment by JonRay15** [comment]
I dont think this is viable until we have the below ledger movements summary API imho.

https://github.com/vegaprotocol/vega/issues/7393

**Comment by JonRay15** [comment]
This might become more possible if we have that view of the prior epoch fees paid because then this might become easier to source?

**Comment by JonRay15** [comment]
Could also look at the total "earmarked" fees across all LPs on the accounts API. 

That should be available already and could be an easier way of doing this.  So instead of showing the historic total paid we would show the expected total to be paid in THIS epoch (so far).  Or if there is a way to do it maybe we can look at the max value of that just prior to payment going out?  Might give us a way around this until that ledger entry summary API is done.

**Comment by JonRay15** [comment]
Note there seems to be an API for thsi now 

https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-list-paid-liquidity-fees
