### ISSUE TITLE
Predict the fees each LP will get at the end of this epoch

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4318]
## Story

As a liquidity provider
I want to understand my expected upcoming fee earnings, and if I am heading for penalties
So I have an opportunity to correct, or am not surprised by low fees

## Acceptance Criteria

- [ ] I can see a prediction of what my "earmarked" fees will be at the end of this epoch, ~after~ EXCLUDING penalties and bonuses
- [ ] I can see my fraction on book live during the epoch
- [ ] If that fraction on book is less than 1 highlight in orange and display tooltip saying "Current fraction on book is less than 1, penalties may apply at end of current epoch depending on performance of other liquidity providers. Click to learn more" (with link to docs.)
- [ ] If that fraction on book is less than the `commitment minimum time fraction` then highlight in red and display tooltip saying "Current fraction on book is less than the commitment minimum time fraction for this market, if this continues no fees will be received at the end of the epoch. Click to learn more" (with link to docs.)
- [ ] I can see all this information in the LP table for a market

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

### Implementation Notes

- Earmarked fees can be found by querying the existing accounts API and looking at the balance on some new account related to LP .... I dont know the type yet ... hopefully you can find it on dev! 
- Expectation is that `fraction on book` will be omitted throughout the epoch on some API which Core have not yet defined.  So that part of this will be blocked until that is ready. 
- Below is an extract for the only LP on fairground ... you can see these fees market ACCOUNT_TYPE_LP_LIQUIDITY_FEES

```{
  "accounts": {
    "edges": [
      {
        "node": {
          "owner": "76fd0e0a7970b1af6250abffc49d4414edeaba25c673f4cf91f376563b53a2a5",
          "balance": "125479809269",
          "asset": "8a246b15bf185065d3f41a710f3eea0fbbe8754a8464501cf4a6d253d69c6423",
          "marketId": "c467ebc497abb1eb546f6ed77f2d82ab5ae05fb26bfa3c1d611d782b1adada29",
          "type": "ACCOUNT_TYPE_MARGIN"
        },
        "cursor": "eyJhY2NvdW50X2lkIjoiZGVhZTdlYjkyZjNiZTJhOGU3NTRlM2ZiOWMzOWExOGMyNjRiMTgxZWNlN2ZiN2E0ODZkZjRjZGMzYTQzZjBlYiJ9"
      },
      {
        "node": {
          "owner": "76fd0e0a7970b1af6250abffc49d4414edeaba25c673f4cf91f376563b53a2a5",
          "balance": "2465325777547",
          "asset": "8a246b15bf185065d3f41a710f3eea0fbbe8754a8464501cf4a6d253d69c6423",
          "marketId": "",
          "type": "ACCOUNT_TYPE_GENERAL"
        },
        "cursor": "eyJhY2NvdW50X2lkIjoiZDZjNDI1MTQ5MmI2MTkwMTVlNGI3ZmQ0MDU0NjI0NTgwNmMyZTNkNTY1YWZiZWFmMjExZWU0Y2UxYjQ3ZDJjMSJ9"
      },
      {
        "node": {
          "owner": "76fd0e0a7970b1af6250abffc49d4414edeaba25c673f4cf91f376563b53a2a5",
          "balance": "228118283",
          "asset": "8a246b15bf185065d3f41a710f3eea0fbbe8754a8464501cf4a6d253d69c6423",
          "marketId": "c467ebc497abb1eb546f6ed77f2d82ab5ae05fb26bfa3c1d611d782b1adada29",
          "type": "ACCOUNT_TYPE_LP_LIQUIDITY_FEES"
        },
        "cursor": "eyJhY2NvdW50X2lkIjoiYTMwMWVmMjdhYzUyZThjMWYxM2M4ZDk5ZmE2ZjlhNTY3NjYzNGYyYmVmYmUyZmE4NWFhMzMxMjY2MGU5Nzk0ZCJ9"
      },
      {
        "node": {
          "owner": "76fd0e0a7970b1af6250abffc49d4414edeaba25c673f4cf91f376563b53a2a5",
          "balance": "800000000000",
          "asset": "8a246b15bf185065d3f41a710f3eea0fbbe8754a8464501cf4a6d253d69c6423",
          "marketId": "c467ebc497abb1eb546f6ed77f2d82ab5ae05fb26bfa3c1d611d782b1adada29",
          "type": "ACCOUNT_TYPE_BOND"
        },
        "cursor": "eyJhY2NvdW50X2lkIjoiMTQwOWE1OWMzZDIzZjgwZGNjNDZiYWExNjZjYzE4YTcyNzRmMjlkMDhhMDg4OGRmMWQ2ODIwOGIxZmZhMmVmMyJ9"
      }
    ],
    "pageInfo": {
      "hasNextPage": false,
      "hasPreviousPage": false,
      "startCursor": "eyJhY2NvdW50X2lkIjoiZGVhZTdlYjkyZjNiZTJhOGU3NTRlM2ZiOWMzOWExOGMyNjRiMTgxZWNlN2ZiN2E0ODZkZjRjZGMzYTQzZjBlYiJ9",
      "endCursor": "eyJhY2NvdW50X2lkIjoiMTQwOWE1OWMzZDIzZjgwZGNjNDZiYWExNjZjYzE4YTcyNzRmMjlkMDhhMDg4OGRmMWQ2ODIwOGIxZmZhMmVmMyJ9"
    }
  }
}
```

### Other

- [Barney's comment in Slack](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1689168706295309?thread_ts=1689162667.366119&cid=C8WS7M50E)

**Comment by MadalinaRaicu** [comment]
https://vegaprotocol.slack.com/archives/C037STCKMGC/p1693992884576839

**Comment by JonRay15** [comment]
Suggested tooltips 

Scenario 1: This LP's time on the book in the current epoch is less than [variable], so they could lose some fees to a better performing LP.

scenario 2: This LP's time on the book in the current epoch is less than the minimum required, so they could lose all fee revenue for this epoch.
