### ISSUE TITLE
Distinguish spot, futures, and perpetual markets

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4319]
## Story

As a trader on Vega Console
I want to know what type a market is when I see it in a list
So I can better understand my overall position when browsing orders etc.

## Acceptance Criteria

- [x] I can determine the type of market wherever it is mentioned:
  - [x] "All" tab on the markets page
  - [x] market switcher "All" tab ([when implemented](https://github.com/vegaprotocol/frontend-monorepo/issues/4384))
  - [x] orders tables
  - [x] positions table
  - [x] asset usage breakdown modal table
  - [ ] ~~watchlist/favourites (when/if this is implemented)~~
  - [x] ledger entries

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [x] Code review
- [x] QA review

### Example: Tags

Tags are easiest to understand as they can be read, but they are harder to scan and tell apart. Colour could be used to improve this, however.

<img width="1395" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/a34564f9-1baf-4473-925b-d01430ba027c">

## Additional details / background info
- This might be evident from the name of the market, but having a clear visual indicator could assist with scanning lists.

**Comment by macqbat** [comment]
There are still core works on unifying product property in `type InstrumentConfiguration`, which is used on proposals list https://github.com/vegaprotocol/vega/issues/8951
