### ISSUE TITLE
First use console intro & get started steps

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4323]
## Story

As a new user
I want to understand what Console is and what I can do here when I first land on it
So that I know what I'm looking at if I've come here from a direct link

Assumption is if you clear your browser cache you'd see it again i.e. we base it off local storage. 

## Acceptance Criteria
- [x] When I open Console for the first time I can see what it is i.e. a short description and key features 
- [x] If your wallet is already connected you don't see the first use popup
  - [x] If window.vega is detected dont open (browser wallet)
  - [x] If we detect previous connection using localStorage for desktop/cli wallet
- [x] There is a call to action to browse markets, linking to the market view market/all 
- [x] I can see the steps I need to take to get started trading 
- [x] There is a call to action to get started, triggering the connect modal - to be replaced with #4350 
- [x] There is a link to try out trading on Fairground when I'm on Mainnet 
- [x] There is a link to trade with real funds on Mainnet when I am on Fairground 
- [x] When I am on the Fairground version, I can see a warning / call out that this is Fairground meaning I can try out with virtual assets at no risk
- [x] If I dismiss the popup, I land on the default market 

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Content review
- [x] Testing (unit and/or e2e)
- [ ] Code review
- [x] QA review

## Design 

https://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=3660-16870&mode=design&t=tBiAg6urPvdKr7nb-0

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/0b83f369-e434-4a8f-8999-7dae1e755a5d)

## Sketches

https://miro.com/app/board/uXjVM2wamp8=/?moveToWidget=3458764559434853588&cot=14

<img width="1750" alt="Screenshot 2023-07-20 at 16 46 26" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/54e3e586-6658-481d-a384-0ac28cb40a6b">

<img width="1281" alt="Screenshot 2023-07-19 at 12 12 47" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/2489c1f7-ec24-4227-a9e4-6b0afc0ebadf">

**Comment by bwallacee** [comment]
@macqbat minor but the close cross is highlighted on arrival:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/073459ef-ca52-406d-a5c3-0d363aa1d3d5)
