### ISSUE TITLE
Upgrade pennant dependency to v1.10.0

### ISSUE THREAD

**Issue by johnwalley** [vegaprotocol/frontend-monorepo#4328]
## The Chore

Upgrade pennant dependency to `v1.10.0`.

## Tasks

- [x] Update `package.json`
- [x] Update `yarn.lock`
- [x] Update `data-source.ts` in line with API changes

## Additional details / background info

Pennant now supports an array of price monitoring bounds for a market, i.e. we can now pass more than one bounds to the candlestick chart
