### ISSUE TITLE
Add missing metadata

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4340]
## Chore

Add metadata for when links to console.vega.xyz, IPFS and/or ETH console URLs are shared.

Dependent on Multisig contract storage. If it's on ETH, how does this effect the URL? 

## Acceptance Criteria

- [ ] I can see what Console is when I share a link to it i.e. a name, description, image
- [ ] I can see what Console is when I share a link to a specific market i.e. a name, description, image

## Tasks

- [ ] Work out what can be controlled and what can't (IPFS?)
- [ ] Define meta data
- [ ] Implement

## Additional details / background info
<img width="1412" alt="Screenshot 2023-07-18 at 16 03 45" src="https://github.com/vegaprotocol/vegawallet-desktop/assets/46783148/b88182da-136c-45e5-bfb3-32c78c4614a2">
