### ISSUE TITLE
SPIKE: Try out trading on mainnet mirror without a wallet or Ethereum deposits

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4346]
Timebox this!

## Spike

Identify who needs to be involved across Vega and collaborate to establish how we can achieve the below user story.

How we'll know we're done / tasks:
**- [ ] Ask Emil how easy it would be to use what we've done to create an in browser signer so you don't have to download a wallet in order to trade**
- [ ] There is a solution outlined in an Epic ticket (could repurpose this ticket)
- [ ] The work is broken down into tickets representing it's component parts across functions / teams / projects / apps etc.
- [ ] The tickets are referenced in the Epic ticket 
- [ ] The tickets are prioritised and assigned to target sprints for delivery in the[ x-platform board](https://github.com/orgs/vegaprotocol/projects/110/views/74) to support planning and tracking 

## Story

As a user 
I want to be able to experiment with trading on Vega with the least friction possible
So that I can quickly establish if I want to use Vega and understand how it works 

This epic is to establish what we need to do to give mainnet mirror the lowest possible barrier to entry.

## Acceptance Criteria

- [ ] There is a way to trade without a wallet 
- [ ] There is a way to deposit funds without an Ethereum transaction 
- [ ] There is a way to get to mainnet mirror that is clearly visible on mainnet i.e. copy and a call to action "Experiment for free with virtual assets on the Mirror Testnet → network", replacing the link to Fairground #4323 
- [ ] There is a way to get to mainnet that is clearly visible on mainnet mirror e.g. Ready to trade with real funds? Switch network to Mainnet →

## Background
* Can we do something with browser javascript
* Can we use Vega chain based assets 
* Can we build in faucets

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketches
<img width="881" alt="Screenshot 2023-07-19 at 11 12 58" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/cae88d8a-d4d4-4742-b78d-731352619c4d">

<img width="1260" alt="Screenshot 2023-07-19 at 11 13 23" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/1e057798-ee6b-4801-99da-70b8ce558718">

<img width="1298" alt="Screenshot 2023-07-19 at 11 14 22" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/e527fcc2-6a6b-40dd-8ae9-8028f90a7e0c">

## Additional details / background info

<img width="448" alt="Screenshot 2023-07-19 at 11 14 36" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/d73a7c12-554f-4f22-9859-baa461bdc878">
