### ISSUE TITLE
Get started in a walk through / checklist 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4351]
## Story

As a new user
I want to see visually my progress through onboarding 
So that not only I am reminded how few steps remain but also can see the stage I am at in onboarding on to Vega

## Acceptance Criteria

- [x] There are additional states added to the onboarding flow rather than just true / false
  - [x] New
  - [x] Has wallet >> Once wallet detected set to this
  - [x] Has connected >> Once user has connected set to this
  - [x] Has deposited >> Once user has made AT LEAST one deposit of ANY settlement asset set to this
  - [x] Ready to trade >> Once user has made at least one deposit AND has dismissed the "Get Started" box in the ticket
- [x] For each state "Get started" section (both in the sidebar and in the onboarding dialog) should be updated with tick or cross indicating whether that stage is complete.  If complete also grey out the text.
- [x] For each state the button beneath should adjust to allow the user to complete whatever the next step is in their journey. ie.
  - [x] If state = New >> "Get Vega Wallet" and clicking launches the get wallet flow
  - [x] If state = Has wallet >> "Connect" and clicking launches the wallet connection
  - [x] If state = Has connected >> "Deposit" links to the new deposits page
  - [x] If state = Has deposited >> "Dismiss" and clicking updates the state to Ready to trade - Get started box should now disappear forever
- [x] The Get Started modal popup that is launched when you arrive at Console should follow exactly the same logic as the above.  So it should launch only when the user is not "Ready to trade" and should send the user to the next step in the journey in just the same way as the deal ticket dialogue box.
- [x] Once the above is all done, check we are not now displaying any redundant / contradicting messages such as the other normal deposit funds box.  

## Sketches 

The whole flow should be handled via the Get Started box in the deal ticket, and reused in the main modal that opens when you startup console.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/273333e7-db93-48a0-a1b7-861da8a5cae0)

https://miro.com/app/board/uXjVM2wamp8=/?moveToWidget=3458764559770726796&cot=14

<img width="2246" alt="Screenshot 2023-07-20 at 16 34 21" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/96061411-d979-47db-91fe-e8f37d125c62">

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by bwallacee** [comment]
@macqbat When i have completed the steps, connected deposited, made a trade etc.

If i disconnect my wallet The get started instantly reappears.

Would we want something to remember if we have already gone through the steps before?
