### ISSUE TITLE
Submit stop orders with expiry date and time

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4352]
Dependent on https://github.com/vegaprotocol/frontend-monorepo/issues/4124. See also: https://github.com/vegaprotocol/frontend-monorepo/issues/4099.

## Story

As a trader with an open position
I want to submit stop orders with an expiry date
So my stop order does not execute unexpectedly in future

## Acceptance Criteria

- [x] I can choose a date and time at which my stop order will expire
- [x] I can choose a 'strategy' to be carried out at that time: execute (i.e. place the order) or cancel

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [x] Code review
- [ ] QA review

## Sketch

From [the Miro board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764559687380384&cot=14):

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/d598e17b-9320-4ba3-974e-d12e85af5d4c)

## Additional details / background info
- [Slack thread on the outcomes of the stop order spike](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1686838755785979)
- [Slack thread discussing Vega's implementation of stop orders](https://vegaprotocol.slack.com/archives/CD4AKTFQT/p1689343084141839)
- [Slack thread discussing how to divvy up the stop order work](https://vegaprotocol.slack.com/archives/C037STCKMGC/p1689759045502409?thread_ts=1689700230.514249&cid=C037STCKMGC)
