### ISSUE TITLE
Add take profit and/or stop loss conditions to a position

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4353]
## Story

As a trader managing an open position on Console
I want to add take profit and stop loss conditions to my position
So I can exit the position on my terms without constant monitoring

## Acceptance Criteria

- [x] There is a new column in the position table for "Manage TP / SL"
  - [x] If there are no stop orders on the market this shows "Add"
  - [x] If there are open stop orders on the market this shows "Edit" 
- [x] When clicked this opens up a dialogue box titled "Manage TP / SL for position" (slightly diff text to sketch)
- [x] The symbol, entry, and market price are shown at the top
- [ ] If you click Add TP boxes appear to enter price / quantity and the Add SL button is now disabled with a tooltip saying "Only one TP / SL can be added at a time" (and vice versa if you Add SL
- [ ] A "Use Max" button is available on the size
- [x] Text is derived below in the format "When the mark price reaches `price + asset` it will trigger a `take profit / stop losss` order to close `size`% of this position for an estimated `profit / loss` of `calculated P&L + asset` (colour coded green / red for profit / loss)
- [x] When user clicks Add TP / Add SL it "arms" that part of the form and allows them to edit the order
  - [ ] This disables the _other_ add button because you can only do one at a time
  - [ ] There needs to be a back button by the form to "deactivate" that part of the form
- [x] When the user clicks the activated (yellow) "Add TP" or "Add SL" button it sends an order to the wallet to be approved, deriving all the relevant info for the order:
  - [x] Order type = stop market
  - [x] Order ref = some derived text string indicating that this is a position level stop order (in case we need this)
  - [x] Time in force = FoK
  - [x] Size = Use the new position linked order and use the % given
  - [x] Price = Use the value given
  - [x] For direction it needs to be implied
    - [x] If position is LONG
      - [x] TP is SHORT and trigger is RISES ABOVE 
      - [x] SL is SHORT and trigger is falls below
    - [x] If position is SHORT
      - [x] TP is LONG and trigger is FALLS BELOW
      - [x] SL is LONG and trigger is RISES ABOVE
- [x] Shoud get a toast with the status of the transaction as always
- [x] Any open TP / SL orders should be shown with the text derived "TP/SL X: `buy/sell` `size`% at `price + asset` for estimated PnL of `(mark - entry)*size` + `asset`
- [x] Whether it is a TP or SL can be determined using the same rules on direction as above 
- [ ] The ordes should be shown on the donut graph as a % of the total size of the position using the % on each position linked stop order  
- [x] Users should be able to add as many TP / SL as the network param `spam.protection.max.stopOrdersPerMarket` allows
- [x] Symbols should be show for close each TP / SL
- [x] Edit will not be in MVP because you cant edit a stop order
  - [x] Close should send a `cancel order` transaction to the wallet 
- [x] To exit the screen once the user is finished they can click an X button in the top right
- [ ] For mobile we might need a simpler version
- [ ] And for MVP we might skip the charts

## Tasks

- [x] Research competitor implementations of TP/SL, especially in comparison to stop orders
- [x] Investigate feasibility of managing position-level TP/SL using batch transactions in the FE
- [x] Propose potential solutions
- [x] Team and stakeholder review
- [ ] Plan tasks and create tickets with input from the front-end teams involved

## Sketch

**Figma**: 
https://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=5829-10455&mode=design&t=vq7lHa2iw16jsTtd-0

**Comment by JonRay15** [comment]
I think this is worth exploring after we put stop orders live so we can see if we get any feedback to this effect.  If we do maybe it is something to look at for the October release.

**Comment by JonRay15** [comment]
I added this ... and I severely doubt it will happen quite

**Comment by mattrussell36** [comment]
@JonRay15 at least some part of the goal of this ticket has been unblocked by core here
https://github.com/vegaprotocol/vega/pull/10290
