### ISSUE TITLE
Link straight to deposit form (interim solution)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4357]
## Story

Dependent on timing of [guided deposit work](https://github.com/vegaprotocol/frontend-monorepo/issues/4365)

As a new user
I want to immediately "get to" the deposit form on Console from the wallet
So that I can deposit as quickly as possible

## Acceptance Criteria

- [ ] I can follow a link from the vega wallet browser extension https://github.com/vegaprotocol/vegawallet-browser/issues/409 to the deposit form on Console with minimal friction

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation (add /deposit page
  - [ ] Add a /deposit page with the current deposit component
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info
- Consider we have a page for it with the form rendered there 
- We can imagine the IPFS interupt goes away with the ETH links for linking from wallet to console
- Talking about storing in session memory to link to the IPFS link rather than have to go via the interstitial page
