### ISSUE TITLE
Expandable deal ticket section for margin values

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4359]
## The Chore

Put total margin available and current margin allocation in expandable section in the deal ticket

## Acceptance criteria

- [x] Confirm with stakeholders which fields to put in expandable container
- [x] Clicking margin required should open collapsed section
- [x] Total margin should show in panel
- [x] Current margin allocation should show in panel
- [x] All margin values should be quantum formatted
  - [x] Margin required
  - [x] Deduction
  - [x] Allocation
  - [x] Projection 

## Tasks

- [ ] Adjust ACs
- [x] Dev
- [ ] Test
