### ISSUE TITLE
EPIC: Guided deposit (target experience)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4365]
Need to break this up

## Story

**As a** new user
**I want** an easily understood way to deposit the right assets in order to trade
**So that** I feel confident in depositing the right assets and am ready to trade more quickly

## Acceptance Criteria

- [ ] There is a clear call to action to deposit from the wallet 
- [ ] When I have no funds in my wallet already, I can see an explanation of how to deposit i.e. I need to deposit funds from an Ethereum wallet 
- [ ] If I don't have an Ethereum wallet, there is a link to get one [https://ethereum.org/en/wallets/find-](https://ethereum.org/en/wallets/find-wallet/)
- [ ] There is a stepped flow to connect my Ethereum wallet 
- [ ] I can see the types of supported Ethereum wallets
- [ ] I can select one and it triggers the connection request from my wallet
- [ ] There is a way link to Trade on Console if / when I have deposited funds

Upon successful connection
- [ ] There is a way to see my connected key and disconnect 
- [ ] I can see a view of the funds in my Ethereum wallet 
- [ ] I can see my total balance per asset 
- [ ] I can see how to deposit each i.e. there is a call to action 
- [ ] There is a way to get more funds i.e. a link to uniswap
- [ ] I can see which markets each of my assets is currently traded in on Console at a glance e.g. in a lozenge / tag 
- [ ] There is a way to go see each of these markets on Console e.g. they are linked
- [ ] There is a way to see a full list of the assets currently being traded on Vega 
- [ ] When I select an asset for deposit, there is a way to first of all approve that asset for use in my Ethereum wallet 
- [ ] If I select an asset that is not currently traded on Vega, I am warned of this

Upon selecting to approve the asset
- [ ] I can see visual feedback to go approve the asset in my Ethereum wallet 
- [ ] When I've approved, I can see visual feedback that my approval is being confirmed by the Ethereum network 
- [ ] Once confirmed, I can see visual feedback that I have approved deposits of this asset type and to what limit
- [ ] There is a way to see the confirmation on Etherscan i.e. a link

Upon successful approval of the asset to deposit 
- [ ] There is a way to complete my deposit from here 
- [ ] I can enter the amount I want to deposit
- [ ] I can see my total balance 
- [ ] I can easily toggle to a different asset to deposit 
- [ ] There is feedback if I try to deposit more than my balance 
- [ ] There is a way to easily deposit the maximum amount of that asset
- [ ] There is a way to understand deposit limits i.e. a list of the remaining deposit allowance, Ethereum deposit cap and  link to https://docs.vega.xyz/mainnet/concepts/assets/deposits-withdrawals to understand more
- [ ] There is a way to cancel the deposit, returning to the list of assets

Upon depositing 
- [ ] There is visual feedback through awaiting confirmation(s), processing deposit, to transaction confirmed

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch
Latest wireframse:
https://www.figma.com/file/8SXfX86E1Qf6Gr15tykrDT/Guided-deposit-flow?type=design&node-id=31%3A357&mode=design&t=DmdT7ki6knHzIzHV-1

https://miro.com/app/board/uXjVM2wamp8=/?moveToWidget=3458764559544280107&cot=14

![Vega onboarding - Deposit funds](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/3d52ae47-59a2-4e12-96e7-47bcc1777bbd)

## Design

This is how far I've gotten with the designs for this: [Figma link ↳](https://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=3717%3A27666&mode=design&t=sbyj8nMdPyVRhnXM-1) 

## Notes

Reference Uniswap for UX patterns.

**Comment by JonRay15** [comment]
Per onboarding prioritisation assigning this to @joellecharlotte now because @ckpringle says his diagram is now enough for the proper design to start.

**Comment by JonRay15** [comment]
SQUID
