### ISSUE TITLE
Update deposit notification on a market you don't hold assets for

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4366]
Make the orange bit smaller / quieter

## Story

As a new user
I want help getting funds / the asset of that market and even an Ethereum wallet if I've dismissed the get started content
So that I can still easily deposit and open a position

## Acceptance Criteria

- [ ] There is a way to get an Ethereum wallet if I don't have one i.e. a link to https://ethereum.org/en/wallets/find-wallet/
- [ ] There is a way to get more funds i.e. a link to uniswap

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
