### ISSUE TITLE
Highlight just-made deposit in collateral

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4367]
## Story

As a user who's just completed a deposit in Console
I want to see a visual indication of the deposit being added to my collateral 
So that I become familiar with how Console is organised and assured my deposit has been successful

## Acceptance Criteria

- [ ] I can see a visual cue / highlight when a deposit has been added to my collateral 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch
<img width="1885" alt="Screenshot 2023-07-20 at 17 59 17" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/38b30b59-503e-407e-ad50-5dd2f2f9ac0d">
