### ISSUE TITLE
Updated connect modal to get or connect Vega Wallet browser extension

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4370]
## Story

As a new user 
I want to easily get the Vega Wallet browser extension if I don't have it already, but also have an easy way to use my Desktop or CLI wallet or connect my existing browser extension if I have it already
So that I can start trading 

## Acceptance Criteria
 
- [ ] There is a description of what the Vega Wallet enables / lets me do
- [x] If I don't have the browser wallet installed, when I press "get started" I can see immediately a way to _get_ the Vega wallet browser extension 
- [x] The browser extension you need is automatically detected if you are using Chrome or Firefox, presenting the specific call to action to install that browser extension in a visible way e.g. with a Chrome icon. We might want to reach for something like https://www.npmjs.com/package/bowser for this.
- [x] The browser extension store opens in a new tab on the Vega Wallet extension page i.e. https://chrome.google.com/webstore/detail/vega-wallet/nmmjkiafpmphlikhefgjbblebfgclikn or https://addons.mozilla.org/en-GB/firefox/addon/vega-wallet/
- [x] When the browser I am using is _not_ Firefox or Chrome, there is a way to download the browser extension anyway but at my own risk i.e. I can see options for both the chrome and firefox extensions in the CTA
- [x] There is a way to understand the browser extension is an Alpha release e.g. there is a label / description
- [x] If I do have the browser wallet installed, I can easily choose to connect to it
- [x] If the desktop wallet or CLI is detected as running, I can see that and choose to connect with my desktop / CLI wallet
- [x] If there is not running desktop wallet or CLI detected, I can see that I need to open my wallet 
- [ ] I can find out more about supported browsers  i.e. there is a link (once we have the documentation https://github.com/vegaprotocol/vegawallet-browser/issues/360)
- [x] I can find out more about the Vega Wallet and see what "other" versions there are i.e. there is a link to the page on the website https://vega.xyz/wallet#overview
- [x] If I select to enter a custom wallet location, there is a way to go back to the default view i.e. a back button or similar

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Design 

Multiple variations here: 
https://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=3660-37358&mode=design&t=tBiAg6urPvdKr7nb-0

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/ecc4face-6aec-4831-a601-c3e00399e89d)

## Sketch

Variations of the modal: https://miro.com/app/board/uXjVM2wamp8=/?moveToWidget=3458764560239877559&cot=14
<img width="2355" alt="Screenshot 2023-07-26 at 12 21 35" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/61becb2e-4a8e-4634-bc35-b29735c670aa">

## Background 
Onboarding journey sketches for context: 
https://miro.com/app/board/uXjVM2wamp8=/?moveToWidget=3458764559434853349&cot=14

**Comment by mattrussell36** [comment]
@ckpringle Can you clarify what we are doing with the 'View as' feature?

**Comment by emilbayes** [comment]
Metamask has this onboarding helper that we could replicate: https://github.com/MetaMask/metamask-onboarding
