### ISSUE TITLE
SPIKE: Faster "verifying chain" step

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4371]
## Spike

How can we make verifying chain faster? Spike is to identify and decide on the best approach to make this faster and do it / write ticket to do it e.g. 

- Remove check from connect wallet
- Request it at a different time
- Give visual progress / feedback when verifying chain 
- Describe at least what it's doing

<img width="954" alt="Screenshot 2023-07-21 at 10 16 11" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/11ae1d67-ac9e-4c8a-a9e3-c59257cdfb78">

## Tasks

- [ ] Investigate what browser wallet does 
- [ ] Check its fast
- [ ] If it's slow on desktop wallet, fine

## Additional details / background info
On mainnet this takes a long time and there's no user feedback to give confidence "it's working" and you are left just looking at your wallet, waiting. This chore is to add some visual clue that there is progress being made.
