### ISSUE TITLE
Deal ticket type and long short selectors

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4374]
## The Chore

Update the type and long/short toggle UI

## Tasks

- [x] Add/update order type selector component with dropdown for 'sub' types
- [x] Update long/short toggle design
- [x] Make stop order options only show if feature flag is enabled
- [ ] Test

## Design

[Figma link here ↳](https://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=3803%3A12214&mode=design&t=JkvBVtRe4MJJNtEn-1)

We're going with v1, truncating the currently selected label in the toggle when the label is too long for the max toggle width. On smaller breakpoints this will likely collapse into a dropdown.

<img width="966" alt="Dropdown-Stop-Orders" src="https://github.com/vegaprotocol/frontend-monorepo/assets/113684458/29f3a710-75b0-408d-be0c-c041472ad807">

## Additional details / background info

https://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=3456%3A13966&mode=design&t=Kc6IZN318zcKqTlo-1
