### ISSUE TITLE
Add sort by top traded to market selector

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4377]
## Story

As a user
I want to sort all markets by total volume traded
So that I can find the most active markets

## Acceptance Criteria

- [ ] I can sort by top traded
- [ ] I can change selected sort

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

Note: To accurately compare all the markets' total volume you will need to 'normalize' the notional volume between all markets using the settlement asset's quantum value

**Comment by mattrussell36** [comment]
Closing as dupe of 3970
