### ISSUE TITLE
Browse perpetuals

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4381]
## Story

As a trader using vega console
I want to browse, compare, and visit perpetual markets
So I can add perpetual positions to my portfolio

## Acceptance Criteria

- [x] I can find perpetual markets on the markets page under all markets
- [x] I can find perpetual markets in the market switcher under all markets
- [x] For both market switcher and markets page we default to showing all markets.

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [x] QA review

## Sketch

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/589889e9-8417-4b21-93a3-9b67045ad340)

## Additional details / background info
- Related: https://github.com/vegaprotocol/frontend-monorepo/issues/4319
- Note: it was agreed to note add specific tabs for market types in the all markets page.

**Comment by bwallacee** [comment]
@MadalinaRaicu  if i resize the window for funding rate the whole chart disppaears:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/b27976e5-65df-483d-9633-d4aaa4db95d6)


Also should we show a mid line or 0 in the chart?
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/d763cbfe-ef56-4da3-aef1-e70a57753da0)


Is it correct to show the message perp markets coming soon if i filter by an asset type that we don't have a market for:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/798b6b07-3242-487d-991b-50b8838aaccc)

**Comment by MadalinaRaicu** [comment]
Hi @bwallacee 

I am able to update the wording for `Perpetual markets coming soon` to `No perpetual markets` in one of my open PRs. 

Regarding the chart, I am not really able to control what pennant library is rendering. 
I am also not sure if we're planning to leave the "Funding" chart or we will replace it with a table? 
Perhaps @bglownia knows better what are the plans
