### ISSUE TITLE
Show funding info in perpetual markets

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4382]
## Story

As a trader browsing Vega console
I want to understand the configuration and funding behaviour of each perpetual market
So I can make an informed decision about when to open or change my position

## Acceptance Criteria

- [x] I can find the most fundamental information in the market header info of a perpetual:
  - [x] Add header stat projected funding rate
  - [x] Add header stat for countdown to next funding event and/or funding frequency
  - [ ] Add handling to show "Unknown" if the next funding event cannot be predicted (because there is no schedule info in the market info)
- [x] I can find all other perpetual and funding information in the market info pane in the data source spec
  - [x] Funding schedule (expected in form "every 8h from XXXXX" - see additional info below)
- [x] Expiry does not show for perps in market header and market info
- [x] Add perp label to market header
  - [x]  Added future label to future markets

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

More sketches and competitor examples on [the Miro board](https://miro.com/app/board/uXjVPUenJos=/?moveToWidget=3458764559780353464&cot=14):

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/1080322/94e69eed-6143-4fd4-b692-1ea84a2729b4)

## Competitor examples

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/2eb8fb77-4622-49af-9d94-5e58e1a7ae44)

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/c6c5b8e0-3737-4078-96cb-d34429c5e7a6)

### Funding schedule info

- It is expected that the market API will be enhanced to show something approximating the below
- Console will need to use that information (evey 8H from XXX) to predict the next funding event
- An more robust approach would probably be to use the `funding period start time` from the funding rate API and add the duration to that to avoid potential for long term drift from that schedule if we just baselined from the very first payment

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/491b648a-7971-47e3-851d-dba9ff2fb963)

### Funding rate info

- The following information is expected on the funding API 
- Check back on the actual [spec](https://github.com/vegaprotocol/specs/blob/669cd7f398a9280a521bc002d55ea11d74621578/protocol/0053-PERP-product_builtin_perpetual_future.md#api-considerations) to ensure nothing has changed
- Console will need to use the funding rate estimate to show the value required
- As mentioned above probably the most accurate way to predict the next settlement is by using the `funding period start time` and adding the duration taken from the API above

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/aeda9f5d-6743-45db-94a0-d83baf422d24)

**Comment by barnabee** [comment]
The specific most relevant parts for funding are the countdown and projected rate:

<img width="129" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/1179257/67b3d11f-4b74-400b-b9db-bf0a5697f5e6">
