### ISSUE TITLE
Default to an "all" markets view in the switcher

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4384]
## The Chore

While the number of markets on Vega is small, it is better if we present one list to give visitors an overview of all activity.

The Markets page has an "All" tab for this purpose, but the market switcher only has tabs for product types.

Introduce an "All" tab on the market switcher.

## Tasks

- [x] Add an "All" tab to the market switcher, which shows all markets sorted by volume
- [x] Default to the "All" tab
- [ ] When viewing the "All" tab, introduce a label or other cue to distinguish spot, future, and perpetual markets from
- [x] Rename (or possible remove) 'All markets' link as it'll be weird to have it next to the 'All' tab
 each other, for example [pills or icons](https://github.com/vegaprotocol/frontend-monorepo/issues/4319)

## Additional details / background info
- Related: https://github.com/vegaprotocol/frontend-monorepo/issues/4319
