### ISSUE TITLE
Show perpetuals product type in proposals

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4385]
## The Chore

Ensure all fields unique to perpetual markets can be browsed when inspecting related proposals.

## Tasks

- [ ] Clearly label the product type in proposals in both perpetuals AND existing futures markets
  - [ ] One for FUTR
  - [ ] One for PERP 
- [ ] Add some sort of pill to the top tier info (that matches Console)

## Sketch

In the market panels future would need to handle perps too 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/d6da627c-ea66-4041-b006-fa63831559b4)

In the top level view 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/62967b7b-72aa-46ce-ab5b-a7165651af7a)

Console pill thingy

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/583a7a57-86a0-415d-b18e-044989a9e29e)

**Comment by JonRay15** [comment]
Worth noting on this that Matt decided he didnt like the pills in Console so now they look like this

All of which is to say ... we dont really have any styling we need to align to ... just do what you think looks decent.

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/d8811d44-97e1-4e12-af8b-cab19f2e5447)
