### ISSUE TITLE
Show when a market MAY be closed through governance

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4386]
## The Chore

TBD: Check this

We show a notice if there is an open `market update` proposal for the selected market.

We should also show a notice if there is an open `close market` proposal for the selected market.

## Acceptance Criteria

- [x] Display the same banner we use for a market taht WILL be closed 
- [x] However we should change the wording to indicate the vote is in progress not decided
- [x] Ideally we shoudl show the vote status and link to the proposal on governance site

## Things to check

- [x] Check if we need to fetch NewMarket proposals in the case of a perpetual market being succeeded by a new perpetual market - in other words, does enacting a successor market to perp marker automatically closes the parent market?
- [x] Check what proposal fields of UpdateMarket (or perhaps a new proposal type) govern the close date of a perp market (currently UpdateInstrumentConfiguration only supports UpdateFutureProduct)

## Tasks

- [x] Switch current proposal notification for market banner
- [x] Update the proposal logic to include close market proposals as well as market update proposals
- [x] Write meaningful message to announce the proposal

## Additional details / background info
- Related: https://github.com/vegaprotocol/frontend-monorepo/issues/4387
