### ISSUE TITLE
Show when a market WILL be closed through governance

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/frontend-monorepo#4387]
## Story

As a trader with a position in a perpetual market
I want plenty of warning that it is due to close
So I have time to adjust my position and strategy, and am not surprised by the closure

## Acceptance Criteria

- [x] I am given enough forewarning of market closure to make meaningful choices and change to my position (ideally I should be informed immediately when a close market proposal for a market I have a position in is successful)
- [x] I can tell how much time remains before the market will close and/or the exact time of closure
- [x] I can tell what the final price will be at the time of closing
- [x] The notification is showed regardless of market type

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [x] Implementation
  - [ ] Remove MarketProposalNotification from market header and change to a 'market proposal banner' using the same patterns as MarketSuccessorBanner and OracleBanner
- [ ] Testing (unit and/or e2e)
- [x] Code review
- [x] QA review

## Additional details / background info
- Related: https://github.com/vegaprotocol/frontend-monorepo/issues/4386
