### ISSUE TITLE
Notify of referral programme and volume discount proposals in  toast

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4395]
## Story

As a console user
I want to know when there is a proposed update to the referral programme or volume discount programme 
So that I go find out more about it and vote either for or against it

## Acceptance Criteria

- [ ] I can see a toast when a proposal for an update to the referral programme has been made
- [ ] I can see a toast when a proposal for an update to the volume discount programme has been made
- [ ] There is a way to go to see the proposal to vote i.e. a link to the proposal on the governance dapp

## Tasks

- [ ] Specs reviewed
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch
<img width="1155" alt="Screenshot 2023-07-26 at 09 14 07" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/7007571d-d122-48db-93ae-18e7866d00d4">

## Additional details / background info
- Spec: https://github.com/vegaprotocol/specs/pull/1829

**Comment by JonRay15** [comment]
I am not sure this is a ticket....

Referral programs are governance proposals so existing toasts will cover them.  Not sure we need anything else.

**Comment by JonRay15** [comment]
Covered by another ticket now
