### ISSUE TITLE
Show referral programme proposals on governance app

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4397]
## Story

As a user
I want to see when a proposal has been made for a referral programme 
So that I can review and vote

## Acceptance Criteria 

- [ ] The governance app is able to handle new governance proposal types for referral program 
- [ ] On the home page and proposal listing page summary, I can see which proposals are for the referral programme 
- [ ] I can see the usual voting information
- [ ] I can see the usual description info
- [ ] I can see the "Program Details", ie. the benefit tiers in some sort of nice UI components (shown in screenshot below)
- [ ] I can see full proposal JSON at the bottom as usual

## Tasks

- [x] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

This is information that will be available per tier in a new API to be built by Core.

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/dd860ef9-0c31-483b-ae23-5cf856ddd552)

This is how it is laid out in the referral scheme page

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/4ef03ba0-7631-43eb-8cc5-2fc6b129415a)

We probably need some sort of simplified version of this table(s) to display this in the governance app.

## Additional details / background info

Spec: https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0083-RFPR-on_chain_referral_program.md

Core API Ticket: https://github.com/vegaprotocol/vega/issues/9255

**Comment by JonRay15** [comment]
Jon to ask question of the referrals team whether we want Joelle to do design wotk here too?

**Comment by JonRay15** [comment]
This should now be in staging as soon as that stabilises.
