### ISSUE TITLE
Show volume discount programme proposal on governance

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4398]
## Story

As a user
I want to see when a proposal has been made for an update to the volume discount programme
So that I know to look to see what has changed before voting

UPDATE: Volume discount schemes will just be a network parameter, so we will get most of this for free, but we need to check how we display multi-line network params

UPDATE 18th Sept: Volume discount schemes are NOT just network params! 😂  We will need to support another proposal type

## Acceptance Criteria 
- [ ] Governance app can handle a volume discount proposal types
- [ ] On the proposal details screen, we have some acceptable way of rendering the tiers. These will appear as under sketches.  We have a few examples of existing params like this (margin scaling factors, price monitoring bounds) but I dont know I have ever seen us try to update one and seen how the UI displays it.  Its not clear to me how the UI woudl handle this currently given it only shows the changed param at the very top currently
- [ ] I can see proposal JSON 

## Tasks

- [x] Check with Valentin to understand how and where this data is being presented (is it a new proposal type? YES)
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

Network parameter will appear like this in the API:

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/0fe44328-b0cc-4f1e-b3ba-d57661206635)

## Additional details / background info

Spec: https://github.com/vegaprotocol/specs/pull/1829 see https://github.com/vegaprotocol/specs/blob/9ae928fb95dfb511ae5e7a29c280ef0d9a8cf7b0/protocol/0083-VDPR-volume_discount_program.md

**Comment by JonRay15** [comment]
As per https://github.com/vegaprotocol/specs/issues/1912

It is not clear yet whether volume discount will be on the governances API or will be a network parameter .... optimisation things going on. On hold until we know.

**Comment by JonRay15** [comment]
At the moment Core have not built volume discounts ... so this can be parked

**Comment by JonRay15** [comment]
Note we have now confirmed this is all on network param

**Comment by JonRay15** [comment]
Think this is not yet built for now

**Comment by JonRay15** [comment]
This has changed again and WILL be a new proposal type now
