### ISSUE TITLE
Add link to Vega referral programme to console

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4403]
## Story

As a user 
I want to know if there is a referral programme on Vega
So that I can decide whether or not I want to take part

## Acceptance Criteria

- [ ] There is a way to access the referral programme in Console i.e. a tab or link
- [ ] I can see a short description of the referral programme 
- [ ] There is a way to get to the referral programme site from here

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch
<img width="1739" alt="Screenshot 2023-07-26 at 14 54 15" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/2b8c3f25-e528-45f5-bdfd-794e9243f202">

## Additional details / background info
Later, this panel will have the additional feature of a team leaderboard : https://github.com/vegaprotocol/frontend-monorepo/issues/4404

**Comment by JonRay15** [comment]
This is done by default given we are now putting it in the main nav.
