### ISSUE TITLE
See team leaderboard

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4404]
## Story

As a user
I want to see the leading teams in terms of trading volume and understand the discounts and rewards they are earning
So that I can get a better idea of the value of being a part of a team on Vega

## Acceptance Criteria

- [ ] I can see a list of teams on Vega 
- [ ] I can see their trading volume, discount applied to trading fees, referrer rewards
- [ ] Teams are ordered in order of trading volume using team_running_volume

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch
Miro https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764559943264282&cot=14

<img width="733" alt="Screenshot 2023-07-28 at 15 24 52" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/9d2a596b-347a-4c24-acf9-98860882f955">

## Additional details / background info
Related #4403

**Comment by JonRay15** [comment]
This wont be in Console, it will be in the referral / competitions site
