### ISSUE TITLE
New view as Vega user icon and modal

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4405]
## Story

As a user
I want to view Vega as another user key
So that I get a better idea of what to expect as a user

## Acceptance Criteria

- [ ] There is a way to "view as a vega user" outside of the connect dialogue e.g. an eye icon 
- [ ] I can access a dialogue to type in a Vega key to view Console as that key

## Tasks

- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch
https://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=3685-33708&mode=design&t=hOAz3Hg97kPsXaXp-0
<img width="616" alt="Screenshot 2023-07-26 at 15 30 17" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/a4eafb9d-1a0d-49f1-b85b-e47b4fbbf487">
<img width="784" alt="Screenshot 2023-07-26 at 15 30 33" src="https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/599811e0-6f3b-41f5-8575-afdf5059a6cd">
