### ISSUE TITLE
See referral discounts in deal ticket

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4408]
## Story

As a user connected with a key that is part of a referral code / team
I want to see the discount I will receive on my trading fees reflected in the deal ticket
So that I understand the fee I will be paying, but can see the discount applied

## Acceptance Criteria

- [x] I can see what my discount factor is
- [x] I can see the estimated fee I will pay for a position with my discount applied (calculate in client)
- [ ] I can see what the trading fee would have been otherwise 
- [ ] The total discount is volume discount + referral discount (NOT multiplied!)

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

Something iin the deal ticket next to the estimate would be fine I would think.

Bear in mind that we will also have volume discounts displayed here too at some point so the approach we choose to display them needs to scale to show those discounts too.

Should be something like this, but we can play around a bit

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/dfcd37a7-0b26-4f87-8e24-6418310fa639)

https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764559935654833&cot=14

## Additional details / background info

The factors applied can be found in this ticket:

https://github.com/vegaprotocol/vega/issues/9258

They will be provided on a new API to be built.

**Comment by JonRay15** [comment]
I am seeing my referral discounbt and my volume discount, and I see a nice lozenge

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/4b6e831d-92c7-48ea-99d3-5ba7d0c1cd86)

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/ea3c2889-f347-44c4-83d2-195c6c70451f)

My only comments are:

- I think either the lozenge should be shown next to the word fees OR the tooltip hover for the breakdown needs to be extended to cover the lozenge.  At the moment if you hover on the lozenge you just get the full value of the number rather than any info about your discount and I think ppl will assume they should hover on the lozenge for details. 
- The lozenge looks a liitle cramps and I'm not sure about the colour.  Maybe some larger margins and matching the light blue info colour would avoid introducing additional new colours?

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/f96d859f-a771-42fd-a1c0-6d75b3325b0c)

**Comment by JonRay15** [comment]
@mattrussell36 says he agrees

**Comment by bwallacee** [comment]
@bglownia I believe the fees are currently adding to the total cost rather than taking away:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/15f6e7b6-e6d9-4dc9-99b7-0e0e9c0896da)

**Comment by bglownia** [comment]
> @bglownia I believe the fees are currently adding to the total cost rather than taking away: ![image](https://user-images.githubusercontent.com/133853298/280767513-15f6e7b6-e6d9-4dc9-99b7-0e0e9c0896da.png)

It does not make sense to display total fees without discount, I changed it and now it displays discounted value
