### ISSUE TITLE
See the code my key is connected to

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4409]
## Story

As a console user
I want to easily see the team or referral code my key is connected to 
So that I can remind myself of the discount / reward I'm receiving 

## Acceptance Criteria

Relates to browser wallet ticket https://github.com/vegaprotocol/vegawallet-browser/issues/446

- [ ] There is a way to see I have applied a referral code
- [ ] There is a way to see which keys have a referral code applied 
- [ ] I can see see the fee discount I am receiving

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

First iteration is simple ... we just need to see a referral code has been applied and be able to link out to the referrals home page to view details. Team stuff will come in a later ticket once that stuff is ready from Core. 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/1e559a53-60d7-4b68-a9bb-00068f8b1617)

## Additional details / background info

Data will be made available on a new API being built here

https://github.com/vegaprotocol/vega/issues/9258

**Comment by mattrussell36** [comment]
We aren't sure of the value of showing the referral information in the key switcher and/or navbar. Now that referrals are included in the application as a top level nav item, it should be pretty easy to navigate there and find out which keys have what codes applied.

**Comment by JonRay15** [comment]
For now we are binning this
