### ISSUE TITLE
Display ethereum oracles information in market proposal

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4425]
## Story

As a governanance voter
I want to be able to see details of any ethereum oracles used in new markets
So that I can easily make judgements on the nature of that oracle and vote accordingly

## Acceptance Criteria

- [ ] I can view data about the ethereum oracle in the oracle spec part of the market data accordion as with any other market
- [ ] I can see any new types that are now valid due to the new ethereum oracles build
- [ ] I can click through to see the normal oracle details, and can navigate to the contract address on etherscan as usual

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

Example of oracle; changes likely to be in the sourcetype >signers> signer area.

```{
  "data": {
    "oracleSpec": {
      "dataSourceSpec": {
        "spec": {
          "id": "fb21f4de61b0427dca838d01eedcfa77346b81e3d4960970f450d9e9dbb9db4e",
          "createdAt": "2023-07-19T11:48:18.132746Z",
          "updatedAt": null,
          "status": "STATUS_ACTIVE",
          "data": {
            "sourceType": {
              "sourceType": {
                "signers": [
                  {
                    "signer": {
                      "key": "69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f",
                      "__typename": "PubKey"
                    },
                    "__typename": "Signer"
                  }
                ],
                "filters": [
                  {
                    "key": {
                      "name": "prices.BTC2.value",
                      "type": "TYPE_INTEGER",
                      "__typename": "PropertyKey"
                    },
                    "conditions": [
                      {
                        "value": "0",
                        "operator": "OPERATOR_GREATER_THAN",
                        "__typename": "Condition"
                      }
                    ],
                    "__typename": "Filter"
                  }
                ],
                "__typename": "DataSourceSpecConfiguration"
              },
              "__typename": "DataSourceDefinitionExternal"
            },
            "__typename": "DataSourceDefinition"
          },
          "__typename": "DataSourceSpec"
        },
        "__typename": "ExternalDataSourceSpec"
      },
      "__typename": "OracleSpec",
      "dataConnection": {
        "pageInfo": {
          "hasNextPage": false,
          "__typename": "PageInfo"
        },
        "edges": null,
        "__typename": "OracleDataConnection"
      }
    }
  }
}
```

**Comment by JonRay15** [comment]
Likely this may be no change at all since currently we just link to BE, therefore the change can be handled there.

**Comment by JonRay15** [comment]
Can we verify what this actually looks like these days now we have Edd's changes in?
