### ISSUE TITLE
Display ethereum oracles information in market accordion

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4428]
## Story

As a Block explorer / Console user
I want to be able to see details of any ethereum oracles used in markets
So that I can easily make judgements on the nature of that oracle 

UPDATE: This is now making it very difficult for us to assess the changes in successor markets because we dnt actually display the oracle specification nicely in the governance app in order to display any changes to it.  Therefore I would heavily request that we take this opportunity to improve / create some oracle version of the "market data accordion" that we can reuse across all apps. 
Believe the accordion is  common component so hopefully this can be done once and then used across all apps.

## Acceptance Criteria

- [ ] I can view data about the ethereum oracle in the oracle spec part of the market data info as with any other market
- [ ] I can see any new types that are now valid due to the new ethereum oracles build
- [ ] I can click through to see the normal oracle details from the repo, and can navigate to the contract address on etherscan
- [ ] I can see the filter conditions rendered more nicely in some sort of accordion view
- [ ] I can see the nice accordion view in the Governance App
- [ ] I can see the nice accordion view in the Console market info panel 
- [ ] I can see the nice accordion view in the Block Explorer 
- [ ] If the market is a successor market the Governance App properly renders the before / after (or if this needs Governance App work then let me know and I'll raise a ticket)

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

Current view is as below. The only real difference between the "Filter" and "JSON" section is we only show the nested part. 

Would be good if the "Filter" view was actually rendered nicely, simliar to the normal market data accordion.  So we'd create a new "Oracle Accordion" and have it expand to include however many filter conditions have been applied. We must have a nice table pattern somewhere that coule be used for this?

<img width="1481" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/205c5374-2f54-4700-ad98-6e18e8862cb1">

### Governance App View 

Then this could be updated to show the oracle data spec properly in the normal accordion.  Here it would really be preferable if we can see the full spec including addresses, filter conditions etc (noting that we can have multiple of these). At the moment we just show the link to the repo (the screenshot doesnt but thats a bug, this is fixed on testnet). This repo link would then become secondary info which is always what it was meant to be, but in the absence of the actual spec its become the be all and end all.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/1c59e9ab-0d90-4349-8f65-9e11749a7f92)

### Console App view 

Similarly, this new expanded accordion would need to render nicely in the Console - with the same implications for the oracle repo info.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/ff2e6c18-7209-4dd4-ac2e-df1a5d857740)

## Additional details / background info

Details on perps from the perps spec

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/45b6205b-5892-4e8e-a7c7-f7c9754a07e7)

Example of oracle; changes likely to be in the sourcetype >signers> signer area.

```{
  "data": {
    "oracleSpec": {
      "dataSourceSpec": {
        "spec": {
          "id": "fb21f4de61b0427dca838d01eedcfa77346b81e3d4960970f450d9e9dbb9db4e",
          "createdAt": "2023-07-19T11:48:18.132746Z",
          "updatedAt": null,
          "status": "STATUS_ACTIVE",
          "data": {
            "sourceType": {
              "sourceType": {
                "signers": [
                  {
                    "signer": {
                      "key": "69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f",
                      "__typename": "PubKey"
                    },
                    "__typename": "Signer"
                  }
                ],
                "filters": [
                  {
                    "key": {
                      "name": "prices.BTC2.value",
                      "type": "TYPE_INTEGER",
                      "__typename": "PropertyKey"
                    },
                    "conditions": [
                      {
                        "value": "0",
                        "operator": "OPERATOR_GREATER_THAN",
                        "__typename": "Condition"
                      }
                    ],
                    "__typename": "Filter"
                  }
                ],
                "__typename": "DataSourceSpecConfiguration"
              },
              "__typename": "DataSourceDefinitionExternal"
            },
            "__typename": "DataSourceDefinition"
          },
          "__typename": "DataSourceSpec"
        },
        "__typename": "ExternalDataSourceSpec"
      },
      "__typename": "OracleSpec",
      "dataConnection": {
        "pageInfo": {
          "hasNextPage": false,
          "__typename": "PageInfo"
        },
        "edges": null,
        "__typename": "OracleDataConnection"
      }
    }
  }
}
```
