### ISSUE TITLE
Spike: Auto open  (to onboard / connect) on load of the dapp

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4431]
**When you open console, open the wallet** 
Could be that if you connected once before, auto trigger it in the future 

## Spike 
To establish what the unknowns are to achieve the story below. 

## Story 
As a Vega user
I want connecting to my recently installed wallet to happen as quickly as possible
So that I can get started on Console without having to think about or find the connect wallet button 

## Acceptance Criteria 
- [ ] Given I have just installed the vega wallet and returned to Console / a Vega dapp - I want to immediately be prompted to complete onboarding or connect to dapp 
- [ ] There is a way to prompt the wallet to open from a dapp e.g. the tab auto refreshes and looks for a wallet installed on the right port, or something else 

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Notes
This is about finding a way to join up the journey of installing the wallet and coming back to your console tab e.g. triggering it to open to onboard / connect

For Firefox if we can't force the pop up to open we can open in a new window the same size and position as the pop up instead.

To make that work we'd need Console to refresh or something, might be some weird trickery required.. unless something can be built into the wallet itself

Wallet could look at your tabs, tell you to refresh your console tab if you have one open? And that could trigger connecting... could we include something in the URL to auto find tabs in that state - could apply to any dapp so any dapp can hook in and join up to the onboarding flow

**Comment by JonRay15** [comment]
@mattrussell36 I'm not sure if we are / shoudl be / want to do this ... lets discuss next week  Doesnt seem to have come up in any of our plannig.

**Comment by JonRay15** [comment]
This should presumably be @macqbat and @dexturr on this.  Barney confirmed its pretty high priority for onboarding.
