### ISSUE TITLE
Ledger entries changes

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4432]
## The Chore

The download ledger entry CSV button doesn't show until ledger entry query resolves even the two features are not connected.

## Tasks
- [x] Remove ledger entry table completely
- [x] Show a basic form for the ledger entries download
  - [x] Dropdown with all assets
  - [x] Date filter 
  - [x] Download button

**Comment by mattrussell36** [comment]
@barnabee do you still think we should remove the ledger entry table completely

**Comment by barnabee** [comment]
Can you think of a way in which it can be useful
without new APIs and a complete rewrite?

If not then I'd definitely remove it, if so let's discuss what that looks like and decide.
