### ISSUE TITLE
Date range filter for ledger entry download

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4433]
## Story

As a user
I want to configure the date range for ledger entries
So that I can review more precise ledger entry data

## Acceptance Criteria

- [x] I can choose a start date
- [x] I can choose an end date
- [x] A default date range of 7 days is applied
- [x] A loader is shown whilst fetching

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [x] Testing (unit and/or e2e)
- [x] Code review
- [ ] QA review

**Comment by bwallacee** [comment]
@macqbat I'm not sure if the loader is supposed to be over the download button or not:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/a3887d79-c906-49b2-b59e-fd0b1ca99331)

I think the error message datetime formatting needs fixing:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/3eb5f15b-07a0-4fb6-8933-968a810ff371)



There is no time picker or ability to set date to now in firefox.
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/c8d6e26a-9b22-42cd-a2c2-de3136ef50f7)

**Comment by bwallacee** [comment]
Also i think if i selected todays date, ideally it would also set the current time so I don't have to manually add.

**Comment by macqbat** [comment]
It's because we use there browser's native `input datetime` element. Each browser handles it differently. We don't have much influence on it...
