### ISSUE TITLE
Improved ordering within the portfolio positions grid

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#4437]
## Story

As a user I want the ordering within the positions grid to be most relevant and useful
So that I can see the most important information first.

## Acceptance Criteria

- [x] I have the ability to see only active markets
- [ ] There is a secondary sort within the grid by `key name`

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
