### ISSUE TITLE
FEATURE EPIC: Governance initiated transfers (revisited)

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4465]
## Core Feature

Governance initiated transfers

## Tasks

- [x] Define high level requirements
- [x] Create basic mockups
- [ ] Update "API Requirements" in core spec
- [ ] Update "User-Interface Spec" in relevant front end repo
- [x] Create detailed user stories using normal template

## High Level Requirements

See [slack](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1686828059520239)

## Basic Mockups

There are small mockups on each of the linked tickets and these are enough for what we need.

## Link to API Requirements in Core spec

Issue for the changes requested are [here](https://github.com/vegaprotocol/specs/issues/1883).  Not sure where the actual spec is ... it may be split across a few specs.

Questions for Core:
~1. When there is a transfer which has been created via governance, do we have the ID of the proposal that created it anywhere on the transfer?  We would want to be able to link back from a transfer on block explorer to the governance vote that created it, so we will need this. Likely the transer ID is inherited from the proposal ID, so confirming this with Core.~ CONFIRMED THIS TO BE TRUE SO WE'RE FINE
2. If we want to do more user-friendly views of active recurring transfers and things like that we will need to work with Core to get this info out of the transfers API and build something bespoke into BE, because ore standard transaction views will not work for this.  If people regard this as sufficiently important we will have to revisit with Core. (https://github.com/vegaprotocol/vega/issues/7461)

## Linked User Stories

See "Governance initiated transfers" in the [X-Platform Delivery](https://github.com/orgs/vegaprotocol/projects/110/views/74?layout=roadmap) view
