### ISSUE TITLE
Create REST API switcher

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4485]
## Story

As a user
I want to have a REST API switcher
So that when the REST API the Gov App is connected to dies I have options to swap to other healthy nodes similar to how it works for GraphQL nodes

## Acceptance Criteria

- [ ] I can see a version of the graphQL node switcher appear when the current REST API is down
- [ ] I should NOT have this option when clicking the normal node switcher button (This is not an expected case and will only happen during rare outages of the Devops run REST API)
- [ ] I can see the full list of REST APIs (TBC if we should lean on the network TOML here or some Devops defined list)
- [ ] I can select a new node from the list
- [ ] I am directed back to the normal default node the next time I visit (ie. it should not be sticky)

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

Current GraphQL switcher looks like this ... we should just be copying it and reusing it.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/66ffb72c-f2d8-4d6c-abb2-d16d49c771e7)

**Comment by JonRay15** [comment]
Never going to happen
