### ISSUE TITLE
De-emphasise successor market column in market list

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4506]
## Successor Markets

<img width="1269" alt="Screenshot 2023-08-08 at 12 27 47" src="https://github.com/vegaprotocol/frontend-monorepo/assets/6678/9434513b-4208-4eee-a449-912453a70bfa">

## Tasks

- [x] Remove successor market column
- [x] Choose an indicator that can go next to the name to indicate that the market is a successor
  - [x] ~~Suggest a pill with market's sequence in the succession line~~ Uses stack cell design from positions table

## High Level Requirements
Successor Markets is a new feature. It makes some sense to have a table column to display these details. However the column is quite wide (which will be fixed by another change), and pushes more useful information of the table. Most markets will not be or have successors, so we need to change how this information is displayed.
