### ISSUE TITLE
EPIC: Referral Program

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4507]
## Core Feature

Referral Program

## Tasks

- [x] Define high level requirements
- [x] Create basic mockups
- [x] Update "API Requirements" in core spec
- [x] Update "User-Interface Spec" in relevant front end repo
- [x] Create detailed user stories using normal template

## High Level Requirements
TBC

## Basic Mockups
Lewis & Steven to provide

## Link to API Requirements in Core spec
**Spec**: https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0083-RFPR-on_chain_referral_program.md

**API Sections**: 
- [On chain referral program](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0083-RFPR-on_chain_referral_program.md#apis)
- [Volume discount program](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0084-VDPR-volume_discount_program.md#apis)

## Link to User Interface Specs
TBC

## Linked User Stories
Go to [X Platform Delivery Board](https://github.com/orgs/vegaprotocol/projects/110/views/74) and filter for "Referral Program"
