### ISSUE TITLE
Metamask snaps

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4510]
## Story

As a user
I want to connect with Metamask snaps
So that I can connect as quickly as possible without downloading other wallets

## Acceptance Criteria

- [x] I am prompted to install the vegaprotocol snap into metamask
- [x] I can connect using the vegaprotocol snap
- [x] I can submit transactions using the vegaprotocol snap

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [x] Code review
- [x] QA review

## Additional details / background info

A POC for this has already been put together for this on the branch feat/snaps, but we need to harden it up for prod
