### ISSUE TITLE
Order book changes

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4511]
## The Chore

- Remove the blue dot from the order book when no price change is detected and ensure that last price movement is preserved even if the price is not changing
- Switch to using last trade price rather than the mid price
- Show the order book spread
- Scale the volume bars using the entire (visible) book
- Fix overflow of values
- Adjust volume bar colors

## ACs
- [x] Order book mid section should use last trade price
- [x] If there is no previous last trade price value (Eg on load) render nothing
- [x] If the current last trade price is the same as the previous last trade price, continue to use the last known price movement 
direction.
- [x] I can see the order book spread (highest buy price minus lowest sell price)
- [x] I can see the bars scaled according to entire order book, not only one side. (https://vegaprotocol.slack.com/archives/C037STCKMGC/p1691884279664069)
- [x] Reduced brightness on the volume bars (perhaps match the volume bars on the candles chart)
- [x] Ensure cells in the book handle overflowing text

## Tasks

- [x] Adjust/update specs
- [x] Dev
- [x] Test

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1691502886778259

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/6803987/d31ff314-4d54-4a85-83fb-811ec050bba9)

**Comment by mattrussell36** [comment]
@barnabee @MM0819 can you confirm if we should be using midPrice or last trade price
