### ISSUE TITLE
Handle negative positionDecimalPlaces

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4518]
## The Chore

- [x] Fix chart breaking
- [x] Ensure formatting of openVolume in positions table is correct
- [x] Ensure formatting of size in order tables is correct
- [x] Ensure formatting of size in fills table is correct
- [x] Only valid size values should be allowed in the deal ticket (positionDecimalPlaces 2, means min size increments of 100)

## Tasks

- [x] Add/Amend ACs
- [x] Dev
- [x] Test
