### ISSUE TITLE
Create v2 market proposal details

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4529]
## Story

As a voting user
I want to see a visually engaging view of a new market that focuses my attention on the most important areas for my review
So that I can more easily zero in on whats important and make good voting decisions

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Input from Research on the most important parts of a market proposal
- [ ] Design
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

I think basically he's thinking something more like this .. but it will need a lot of thought to get there.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/b5fc4cbd-f9d8-47b6-9be1-837fa97472ce)

**Comment by JonRay15** [comment]
This needs to be considered alogside Shopify for Perps .... does it still exist?

**Comment by JonRay15** [comment]
I'm suggesting we do this alongside the SFP work, because the work to understand whats really importnat in a market and display it nicely is common across these tasks, and its also not totally clear to me what happens to the original governance app market creation flow if SFP has made all this "1-click" in console or somewhere.
