### ISSUE TITLE
Improve the display of Governance app on Mobile

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4530]
## The Chore

On mobile some of the tiles on the homepage and proposals page in particular seem to struggle with fitting to screen.  Needs to be cleaned up.

## Tasks

- [x] Review which pages arent good on mobile
- [ ] Fix them

## ACs following review

- [x] Homepage: Proposal tiles fit to mobile nicely (note these are fine on the proposal page)
- [x] Homeage: Tiles for REWARDS and VEGA TOKEN fit to mobile nicely
- [x] Homepage: Buttons for SEE REWARDS and MANAGE TOKENS are aligned
- [x] Proposals: Toggle for closed proposals fits to screen
- [x] Vega Token: screen is just a touch wide
