### ISSUE TITLE
Update rewards view

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4532]
## Story

As a user 
I want to see details of various discounts / rewards I'm getting 
So that I feel like a valued customer and can tell what I should be doing to earn / maximise my rewards

## Acceptance Criteria

- [x] I can see the sketches in the figma
- [x] For now we will put this in the top level nav (until we can rework portfolio properly)
- [ ] All the numbers work
- [ ] There is a disconnected state that is still useful
  - [ ] The tiers are still shown just with no progress
  - [ ] The reward pool would be empty
  - [x] Vesting base rate would still show
  - [x] The multpliers would be blank 
  - [x] The reward history should be shown for the network rather than for the user 
- [x] There is a way to toggle the reward history to show "Earned by me" vs "Total distributed"
- [x] There is a way to paginate / filter the reward history
  - [x] MVP is simple pagination back through epochs
  - [x] Better would be to have the ability to show specific epoch or epochs 
  - [x] There is a default sort on epoch and then by the asset alphabetically
- [x] INclude a view of active rewards 

## Tasks

- [ ] UX - Determine which parts of console you need to surface this
- [ ] UX - Create ACs for each of these
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

Figma 

We are going for v2.4 in the Figma

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/4481758a-83cd-4206-8b85-0e2326f9338b)

Where there are various levels as indicated in the additional sketch in the Figma

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/1a851e19-6d9a-4161-a36b-093f988eec36)

Also using v2.1 of the reward cards. 

https://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=3166-5839&mode=design&t=GXj0QjK0d268FwQ1-0

### API details

- The total rewards pot comes from the party accounts API with the account type `ACCOUNT_TYPE_VESTED_REWARDS` + `ACCOUNT_TYPE_VESTING_REWARDS`
- The amount available to withdraw is the balance in `ACCOUNT_TYPE_VESTED_REWARDS`
- The vesting base rate is a network param: `rewards.vesting.baseRate`
- Most of the other multipliers can be found on the below API;
  - Vesting multiplier =  `rewardVestingMultiplier`
  - Streak reward multiplier = `rewardDistributionMultiplier`
  - Hoarder reward multiplier = MISSING >> Jeremy is working on this
  - Streak length = `activeFor`
  - Reward hoarder bonus =  `ACCOUNT_TYPE_VESTED_REWARDS` + `ACCOUNT_TYPE_VESTING_REWARDS`
- Activity streak details can be found on network param = `rewards.activityStreak.benefitTiers`
- Reward hoarder bonus tiers can be foudn on network param = `rewards.vesting.benefitTiers`
- The full reward breakdown can be found on the rewards API and can be copied from the Governance implementation and expanded to cover the other reward types. 
 

```
{
  partiesConnection(id:"89fd87b86727fa4d9ab06b9f4e64b51c9b07055e8a0c8f0bc40f0a249e321525"){
    edges{
      node{
        id
        activityStreak{
          activeFor
          isActive
          inactiveFor
          rewardDistributionMultiplier
          rewardVestingMultiplier
          epoch
          tradedVolume
          openVolume
        }
      }
    }
  }
}
```

Note that we have had some issues with pagination on that rewards page on the governance page, which are documented on the ticket below, so we should make sure we handle this nicely on the new console version. 

https://github.com/vegaprotocol/frontend-monorepo/issues/3471

**Comment by JonRay15** [comment]
This is now covered by #4713 and #4714 

We dont need this

**Comment by JonRay15** [comment]
Given the above, the only likely thing to do here would be some sort of summary savings in the Portfolio page. 

But that will require the ledger entries summary API in order to get this detail out, so until we get some movement there this is blocked.

**Comment by mattrussell36** [comment]
If we cant show summary data. As a first step it might still be good to show your current discount tier status and perhaps volume required to hit the next tier (same for referrals), based on [the API requirements here](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0084-VDPR-volume_discount_program.md#apis) we should be able build something, and it would be a nice step towards a more interesting portfolio page

**Comment by JonRay15** [comment]
Note Matt's comment above is old and not relevant for this ticket now that it has been broken out to cover only the rewards stuff ... so if you're thinking it is confusing, thats why.

**Comment by JonRay15** [comment]
We should make a start on this @mattrussell36 

We can hide a bunch of things and focus on getting the important stuff for vesting out.

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/f2d976bf-7439-4c7f-8294-57ab2ee4d4fa)

**Comment by mattrussell36** [comment]
This first part of this is done. But we still need to implement the activity streaks and the reward tiles

**Comment by JonRay15** [comment]
We also need to have handling for when there is no activity streak and no reward hoarder streak active in mainnet ... which is currently the case.

**Comment by JonRay15** [comment]
Agreed card option 1



![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/086a6ba7-0a2d-4856-b4dc-a62d937ab7f9)
