### ISSUE TITLE
Change monospace font to something with narrower characters

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4536]
## The Chore

What we need to achieve and who for

## Tasks

- [ ] Choose a font (iosefka? open source and widely used), something that is narrower than the current one
- [ ] Agree that font with Matt / Barney etc
- [ ] Try it out
