### ISSUE TITLE
Show full funding event history

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4541]
## Story

As a user 
I want to see the full history of the funding data for a market
So that I can see how it has varied over time

## Acceptance Criteria

- [x] 'Funding' tab added to the trade grid if the market is a perp (Chart / Depth / Liquidity / Funding)
- [x] Shows a chart (same as account history) - see some proposals below
- [ ] I can see a full history of the following fields for any perps market
  - [ ] start time
  - [x] end time
  - [x] funding rate
  - [ ] funding payment
  - [ ] external twap
  - [ ] internal twap

## Tasks

- [x] UX (if needed)
- [ ] Design (Find another exchange and copy it)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

Should look something like [this](https://www.binance.com/en/futures/funding-history/perpetual/funding-fee-history)

I think either we go simple, and just do a simple chart of funding rate which can go positive or negative and just use the normal chart functions. 

Or we could try to go a bit more advanced and maybe show a splitscreen view like the below example using the volume study.

This would allow us to have two Y axes of differing sizes so we could maybe show the values at the end of each period for:
- Graph 1: Internal twap and external twap, shown in units of the price
- Graph 2: The funding rate shown in decimals

This would allow the user to see "ok external twap was higher than internal, so market was running low, hence funding rate went negative so shorts are paying longs" (NB. I may have screwed up which way round that is but you get the point!) 

Suggest whoever works on this experiments and decides if such a veiw is useful or it ends up looking too complex.

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/03c3acd0-bc95-45d4-876a-5d41e9184509)

## Additional details / background info

Info all available [here](https://github.com/vegaprotocol/specs/blob/669cd7f398a9280a521bc002d55ea11d74621578/protocol/0053-PERP-product_builtin_perpetual_future.md#api-considerations) 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/2cc00920-484b-4645-94c8-12b673df5075)
