### ISSUE TITLE
Uplift LP dashboard with SLA related changes

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4552]
## Story

As a LP
I want to know what sort of range and commitment I would need to make on a market
So that I can decide if I am able to make such a commitment

## Acceptance Criteria

- [ ] I can see the required `market.liquidity.priceRange` in which LPs must quote (from the markets API)
- [ ] I can see the required `market.liquidity.committmentMinTimeFraction` LPs must commit to (from the markets API)

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
Done
