### ISSUE TITLE
Explorer Oracles display incorrectly shows no matched data

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4553]
## Description

On mainnet (see https://github.com/vegaprotocol/vega/issues/9075 for why not testnet), where data has been submitted and matched filters, those filters still show no matched data. It's likely the query is incorrect, or they rely on the `updated` field which appears not to actually update when data is matched.

# Tasks
- [x] Ensure ✅ is shown when data matches
- [x] render data when it matches
- [x] Fix queries to use dataConenction if they are not
