### ISSUE TITLE
Requested tweaks to the deposit panel

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4555]
## The Chore

Barney has requested a few minor tweaks to the deposit panel to make some of it easier to disgest.

## Tasks

- [x] For the wallet address at the top, follow the standard pattern for most sites where you show 0x123...4567 with the usual copy button.  I assume we have a icon for copy somewhere.  Ref image from metamask shown in sketches.
- [x] For the Asset view fix the text wrapping on the asset ID.   Here we should again show b340c...4567 but instead of a copy button a click should take you to the block explorer page for that asset.
- [x] Remaining deposit allowance can be left as is, but we should apply quantum formatting to avoid the excessively long decimal places
- [x] For Ethereum deposit cap to recognise the fact many ppl just approve the max in metamask we should:
  - [x] If > 0.8 x (2^256) then display text "Unlimited"
  - [x] Else display the number, again formatted with quantum formatting
- [x] In the green box at the bottom we shoud do the same 
  - [x] If > 0.8 x (2^256) then display text "Unlimited"
  - [x] Else display the number, again formatted with quantum formatting

## Additional details / background info

We're talking about this view:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/cb1388e4-e8e5-42f3-bc36-97760c060ebc)

Metamask wallet address depiction:
<img width="152" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/591a7e60-7cbc-4df8-9550-4939334e29d5">

**Comment by bwallacee** [comment]
@asiaznik I am still getting a long decimal places in the amount field.
![image (2)](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/4b54e094-e4c6-4618-b030-3900bef66d9e)


Also we are missing the copy button for the eth address

**Comment by asiaznik** [comment]
@JonRay15 @bwallacee should the input's step attribute also be based on the quantum for the asset? or should it allow full length of the asset's decimals?
