### ISSUE TITLE
Add E2E tests for transaction types on block explorer

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#4560]
## The Chore

Since transactions page is still blocked by capsule. The other option for testing transactions would be to mock individual transactions and validate elements on each transaction id page. 

Transaction types: 

- [x] [[OrderCancellation transaction #2108](https://github.com/vegaprotocol/frontend-monorepo/issues/2108)](https://github.com/vegaprotocol/frontend-monorepo/issues/2108)
- [ ] [[OrderAmendment transaction #2109](https://github.com/vegaprotocol/frontend-monorepo/issues/2109)](https://github.com/vegaprotocol/frontend-monorepo/issues/2109)
- [ ] [[WithdrawSubmission transaction #2110](https://github.com/vegaprotocol/frontend-monorepo/issues/2110)](https://github.com/vegaprotocol/frontend-monorepo/issues/2110)
- [ ] [[ProposalSubmission transaction #2111](https://github.com/vegaprotocol/frontend-monorepo/issues/2111)](https://github.com/vegaprotocol/frontend-monorepo/issues/2111)
- [ ] [[VoteSubmission transaction #2112](https://github.com/vegaprotocol/frontend-monorepo/issues/2112)](https://github.com/vegaprotocol/frontend-monorepo/issues/2112)
- [ ] [[LiquidityProvisionSubmission transaction #2113](https://github.com/vegaprotocol/frontend-monorepo/issues/2113)](https://github.com/vegaprotocol/frontend-monorepo/issues/2113)
- [ ] [[DelegateSubmission transaction #2114](https://github.com/vegaprotocol/frontend-monorepo/issues/2114)](https://github.com/vegaprotocol/frontend-monorepo/issues/2114)
- [ ] [[UndelegateSubmission transaction #2115](https://github.com/vegaprotocol/frontend-monorepo/issues/2115)](https://github.com/vegaprotocol/frontend-monorepo/issues/2115)
- [ ] [[LiquidityProvisionCancellation transaction #2116](https://github.com/vegaprotocol/frontend-monorepo/issues/2116)](https://github.com/vegaprotocol/frontend-monorepo/issues/2116)
- [ ] [[LiquidityProvisionAmendment transaction #2117](https://github.com/vegaprotocol/frontend-monorepo/issues/2117)](https://github.com/vegaprotocol/frontend-monorepo/issues/2117)
- [ ] [[Transfer transaction #2118](https://github.com/vegaprotocol/frontend-monorepo/issues/2118)](https://github.com/vegaprotocol/frontend-monorepo/issues/2118)
- [ ] [[CancelTransfer transaction #2119](https://github.com/vegaprotocol/frontend-monorepo/issues/2119)](https://github.com/vegaprotocol/frontend-monorepo/issues/2119)
- [ ] [[AnnounceNode transaction #2120](https://github.com/vegaprotocol/frontend-monorepo/issues/2120)](https://github.com/vegaprotocol/frontend-monorepo/issues/2120)
- [ ] [[BatchMarketInstructions transaction #2121](https://github.com/vegaprotocol/frontend-monorepo/issues/2121)](https://github.com/vegaprotocol/frontend-monorepo/issues/2121)
- [ ] [[NodeVote transaction (validator) #2122](https://github.com/vegaprotocol/frontend-monorepo/issues/2122)](https://github.com/vegaprotocol/frontend-monorepo/issues/2122)
- [ ] [[NodeSignature transaction (validator) #2123](https://github.com/vegaprotocol/frontend-monorepo/issues/2123)](https://github.com/vegaprotocol/frontend-monorepo/issues/2123)
- [ ] [[ChainEvent transaction (validator) #2124](https://github.com/vegaprotocol/frontend-monorepo/issues/2124)](https://github.com/vegaprotocol/frontend-monorepo/issues/2124)
- [ ] [[KeyRotateSubmission transaction (validator) #2125](https://github.com/vegaprotocol/frontend-monorepo/issues/2125)](https://github.com/vegaprotocol/frontend-monorepo/issues/2125)
- [ ] [[StateVariableProposal transaction (validator) #2126](https://github.com/vegaprotocol/frontend-monorepo/issues/2126)](https://github.com/vegaprotocol/frontend-monorepo/issues/2126)
- [ ] [[ValidatorHeartbeat transaction (validator) #2127](https://github.com/vegaprotocol/frontend-monorepo/issues/2127)](https://github.com/vegaprotocol/frontend-monorepo/issues/2127)
- [ ] [[EthereumKeyRotateSubmission transaction (validator) #2128](https://github.com/vegaprotocol/frontend-monorepo/issues/2128)](https://github.com/vegaprotocol/frontend-monorepo/issues/2128)
- [ ] [[ProtocolUpgradeProposal transaction (validator) #2129](https://github.com/vegaprotocol/frontend-monorepo/issues/2129)](https://github.com/vegaprotocol/frontend-monorepo/issues/2129)
- [ ] [[IssueSignatures transaction (validator) #2130](https://github.com/vegaprotocol/frontend-monorepo/issues/2130)](https://github.com/vegaprotocol/frontend-monorepo/issues/2130)
- [ ] [[OracleDataSubmission transaction (oracles) #2131](https://github.com/vegaprotocol/frontend-monorepo/issues/2131)](https://github.com/vegaprotocol/frontend-monorepo/issues/2131)
- [ ] Create Successor Market Proposal
- [ ] Submit Stop Order
- [ ] Cancel Stop Order

**Comment by jtsang586** [comment]
In order for the transactions to show it requires the rest url which is not possible with Capsule. The alternative is to use Fairground or Stagnet which may go down. 
Closing this ticket as:
- don't want to introduce dependency on other environments being up to run tests
- Transaction tests would not check for api changes so have limited benefit
