### ISSUE TITLE
SPIKE: What would it take to support mobile trading for Vega

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#4567]
## The Spike

Understand the work needed and options to enable use of the wallet on mobile.

## Questions we need to answer

- [ ] Can we make the wallet work in default browsers for Android and iOS devices?
- [ ] Can we make key trading features in Console work in default browsers for Android and iOS devices?
- [ ] What would it take to enable the majority of users to run vega wallet on their mobile? 
- [ ] What would we need to work on default browsers on Android?
- [ ] What would we need to work on default browsers on iOS?
- [ ] What would we need to tell users about mobile capability so that they know what they can / can't do?
- [ ] Consider the journey beyond installing to include connecting and approving / rejecting a transaction. How does the wallet (can it?) come into focus?

## Tasks

- [ ] Identify current limitations
- [ ] Research routes for mobile support 
- [ ] Identify work 
- [ ] Prioritise 
- [ ] Write tickets in relevant backlogs

## Notes

On iOS - one route is turning the extension in to an iOS browser extension, there's also something like Orion browser.

**Comment by JonRay15** [comment]
This can be side of desk ... it is not a requirement for October.

**Comment by JonRay15** [comment]
We have moved on from this now ... it is ongoing
