### ISSUE TITLE
Successor market diff price monitoring improvements

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4576]
## Story

As a user
I want to see cnanges to price monitoring bounds made in successor market proposals
So that I can tell if they have been changed

## Acceptance Criteria

- [ ] Price monitoring bounds should be logically identified by a unique combination of `horizon`, `probability`, and `auctionExtension`
- [ ] Price monitoring bounds should therefore only ever be "added" or "removed"
- [ ] Price monitoring bounds should never be shown to be "updated" because a change to any of the above effectively makes it a different logical bound, not an update to a new one
- [ ] We should not be "indexing" price monitoring bounds into 1, 2, 3 etc
- [ ] We should just be showing the collection of bounds that apply
- [ ] The test examples provided in the additional details should work as shown

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

Example 

```
Parent

"priceMonitoringParameters": {
          "triggers": [
            {
              "horizon": "2000",
              "probability": "0.9",
              "auctionExtension": "600"
            }
	   {
              "horizon": "4000",
              "probability": "0.8",
              "auctionExtension": "400"
            }	
          ]
```

```
Child

"priceMonitoringParameters": {
          "triggers": [
             {
              "horizon": "5000",
              "probability": "0.7",
              "auctionExtension": "400"
             }	
           {
              "horizon": "2000",
              "probability": "0.9",
              "auctionExtension": "600"
            }
          ]
```

In this example:

- The bound defined by 2000 / 0.9 / 600 appears in both parent and child therefore should appear as unchanged.  It shouldnt matter that it is now appearing as bound 2.  Although it is worth checking if that order is just arbitrary based on the order they appear in the proposal JSON or if they are somehow ordered before assigning that number.
- The bound defined by 4000 / 0.8 / 400 was in the parent but not in the child so it should be shown as removed and be formatted with the usual strikethough / fade
- The bound defined by 2000 / 0.9 / 600 is new in the child so should be shown as added and formatted in the usual way for a change / new value
