### ISSUE TITLE
First pass of all priority transaction receipts

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4587]
## Story

As a user
I want to see the basic view of transactions for all types
So that I can review my Txs

## Acceptance Criteria

- [ ] I can see the basic info for all priority types (below)
- [ ] I can NOT yet see nicely formatted price etc 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

Transaction types supported:
-
