### ISSUE TITLE
CI Optimisations

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4594]
## The Chore

Optimise the CI process

## Tasks

- [x] Make sure any impacts on Governance & Block Explorer are understood and sync up with them if needed
- [x] Ensure the CI is running the build and lint first, then starting unit tests and e2e tests in parallel
- [ ] ~~Explore building the app once and caching rather than rebuilding every time~~
