### ISSUE TITLE
Move away from Cypress

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4595]
## The Chore

All tests should be migrated out of cypress so we are exclusively using console-test

## Tasks

- [ ] Check with Governance / Block Explorer for any impacts
- [ ] Migrate all tests
- [ ] Fix any that are flaky / failing
