### ISSUE TITLE
Review buildable libraries

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4597]
## The Chore

Review what needs to be built and published. Simplify where possible. This will make migrating the console app out of the monorepo easier.

## Tasks

- [x] Review build-able libraries. The following must be buildable/publishable as they are in use (or will be very soon):
  - announcements
  - tailwindcss-config
  - ui-toolkit
  - types
  - wallet
  - react-helpers (we can possibly unpublish this, its not used extensively, see vega.xyz deps)
  - utils (we can possibly un-publish this, its not used extensively, see vega.xyz deps)
- [ ] Make all other libs non-buildable and unpublish from npm if needed
- [ ] Check with Governance & BE & vega.xyz
- [x] Consider migrating to SWC for remaining libs that must be built/published
- [x] Ensure everything still builds

**Comment by bglownia** [comment]
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1754247/a2a77c63-b12d-43d5-bddf-8ac7fcdb1043)
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1754247/bd6c6a3c-7e77-4b42-bfbb-25c7adf1d343)

**Comment by bglownia** [comment]
@mattrussell36 Do we need to deliver publishable libs in "cjs" format ? "umd" should be enough for frontend libs
https://github.com/vegaprotocol/frontend-monorepo/pull/3518
