### ISSUE TITLE
EPIC: Move Console out of monorepo

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4598]
## The Chore

Move out of the monorepo.

## Tasks

- [ ] Plan out what we need to do in order to manage this; includes ....
- [ ] Ability to publish components
- [ ] Move awauy from nextjs
- [ ] Explore different build tool (SWC?)
- [ ] Combining specs and console tests
- [ ] Work out how vegaprotocol.eth feeds into this
- [ ] Can we get to a bog standard fleek flow
- [ ] Ensure publish of dependencies to MPN(?)
- [ ] POC of setting up a new repo to prove we can do this

**Comment by JonRay15** [comment]
We have decided against this for now
