### ISSUE TITLE
Set up referral program project

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4600]
## The Chore

Set up all the necessary bits in github to support the new referral program project.

## Tasks

- [ ] Set up a new repo
- [ ] Copy the relevant bits from vega.xyz & front-end-monorepo
- [ ] Dunno, what else?
