### ISSUE TITLE
Add wallet connection flow to referral site

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4604]
## Story

As a user
I want to be able to connect my wallet to the referral site
So that I can see information associated to my key including referral code I'm on and rewards etc

## Acceptance Criteria

- [x] I can see the standard "CONNECT WALLET" CTA in the top right as per Console
- [x] I can go through the full normal wallet connection process 
- [x] I can see the key that is connected afterwards as I do in Console 

NB. How other screens should now change as a result of this connection will be covered in other tickets.

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
Comment from Matt on DM 

yo so yup, just created a fresh vite project and installed @vegaprotocol/wallet and its working..
Art you’ll need to install some peer deps

@vegaprotocol/types
@vegaprotocol/utils

You’ll also need to wrap it with an apollo provider which is annoying (edited) 

There was some discussion about only getting REST apis for this.. So I’ll need to refactor the chain id query out of the connect dialog.. tomorrow
