### ISSUE TITLE
Switch dropdowns, inputs, form groups and buttons to use trading variant

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4606]
## The Chore

We have new components in ui-toolkit to enable different designs in console, we aren't using them everywhere yet so this task is to switch to the trading variant.

```
// Trading specific components in ui-toolkit/src/components/index
export * from './trading-button';
export * from './trading-checkbox';
export * from './trading-dropdown';
export * from './trading-form-group';
export * from './trading-input-error';
export * from './trading-input';
export * from './trading-radio-group';
export * from './trading-select';
```

## Tasks

- [ ] Switch all buttons
- [ ] Switch all checkboxes
- [ ] Switch all dropdowns
- [ ] Switch all from groups
- [ ] Switch all input errors
- [ ] Switch all inputs
- [ ] Switch all radio groups
- [ ] Switch all selects
- [ ] Test

**Comment by bglownia** [comment]
Easiest way to replace components is to import as. In most cases API is the same and there is no need to change any props
```
import {
  TradingButton as Button,
  TradingCheckbox as Checkbox,
  TradingDropdown as Dropdown,
  TradingFormGroup as FormGroup,
  TradingInput as Input,
  TradingInputError as InputError,
  TradingRadio as Radio,
  TradingRadioGroup as RadioGroup,
  TradingSelect as Select,
} from '@vegaprotocol/ui-toolkit';
```
