### ISSUE TITLE
Update deal ticket submit buttons

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4608]
## The Chore

Update the deal ticket submit buttons per the design. They'll likely need a bespoke button component to show the price/size information within

## Tasks

- [ ] Adjust/Add ACs
- [x] Dev
- [ ] Test

## Acceptance Criteria

- [x] Move the notional to match new designs
- [x] Change colour and design of submit button
- [x] Any other changes?

## Additional details / background info

https://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=3166%3A5839&mode=design&t=4IBlhkbpaOFLzIKm-1
