### ISSUE TITLE
Ensure that we have double checked all the main flows to installing and running a wallet

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4615]
## Story

As a user
I want to have a seamless install of the wallet and general onboarding process regardless of how I enter the system
So that I dont get bored or frustrated and decide its not worth it

## Acceptance Criteria

- [x] I can do it if I land initially on the website and click Console
- [x] I can do it if I land initially on the website and install the wallet
- [x] I can do it if I land initially on Console via some twitter link for instance
- [x] I can do it if I land initially on the Chrome or Firefox stores because I've been sent a link
- [ ] I can do it if I land initially on the Governance App
- [ ] I can do it if I land initially on the Block Explorer
- [x] In each case above the full flow through get wallet > connect wallet > deposit funds > start trading is fully supported
- [x] In each case any conditionality around maybe already having completed some steps is fully supported

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

There are a bunch of tickets for all of these already ... this one is meant to be a final pass looking holistically at everything and making sure we havent missed anything.

**Comment by JonRay15** [comment]
I think this is all fine.

Everything leads to Console as expected and we're finalising that flow in #4627 

I think Governance & BE intentionally do NOT have links to Console for legal reasons.

**Comment by JonRay15** [comment]
NB.  There is no required review or testing here.  I'm just leaving it there until I hear back from Barney

**Comment by JonRay15** [comment]
I did this ... it is fine.
