### ISSUE TITLE
Adjust Asset popout to avoid wrapping on IDs

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4624]
## The Chore

On https://github.com/vegaprotocol/frontend-monorepo/issues/4555 I have suggested we build a component for showing asset strings using the fairly standard 0x17g...2i34 <copy button> type format that you see in most crypto sites and metamask etc rather than show the full string.

Barney has suggested we do the same on the Asset popout screen to avoid the asset ID and contract address wrapping. 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/497f1d41-eaee-4577-bfa1-b85d7b8f76b4)

## Tasks

- [x] Build (or use if that other ticket is done) a component to standardise how we should long string IDs 
- [x] Use that to display the ID and Contract Address on the asset popout
- [x] Avoid text wrapping on the final "There is 1 unit of the settlement asset tUSDC to every quote unit" either by shortening the sentence or making the box slightly wider.

**Comment by bwallacee** [comment]
LGTm, although one tiny thing.

On a larger high resolution screen/monitor, the text at the bottom is quite small:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/15f354cf-1fab-4bff-978e-2b3d2a5c544e)


It looks ok on normal laptop screen.
