### ISSUE TITLE
Improve on boarding flow so it can be dismissed and better handles CLI wallet/Snap

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4627]
## The Chore

Improve on boarding flow

The addition of metamask snaps has complicated our onboarding a bit and we need to change the flow slightly in addition to the  changes already requested below. The reason for this is that currently when you land here as a new user with NOTHING installed ....

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/36dce37f-4e47-46fc-813e-39ac1bbd82ad)

(Or in the primary dialogue) 

The button will link you straight off to the chrome store, before you get any option around snaps.  This isnt ideal.

At a high level, we want to 

1. Simplify the onboarding component to just 3 steps: Connect, Deposit, Trade
2. Connect step should launch the connect component in sketch 1
3. Inside that component we should detect connection status and display the appropriate buttons based on this

Full ACs below.

### Onboarding related ACs

- [x] There should be a way to by pass get started dialog so it does not appear again
- [x] Reduce the set of onboarding statuses to:
  - [x] 1. Connect
  - [x] 2. Deposit
  - [x] 3. Trade
- [x] If a user has connected via the JSON RPC service and account balances are seen, step 1 & 2 is complete.
- [x] If a user has installed the snap and account balances are seen then step 1 & 2 is complete
- [x] Once 1 & 2 are complete (via either method), onboarding should be marked as complete if either:
  - [x] The user clicks "Ready to trade" on the button which should appear on the dialogue
  - [x] The user enters a position

~- [ ] You should not need to click 'Dismiss' to complete the flow. If accounts and deposits are present, get started flow is complete.~

### The ACs below are for the connection dialog ALL THE TIME, they are outside of onboarding and will run any time someone tries to connect

- [x] When the user clicks "Connect" it should open the wallet connection dialogue in sketch 1
- [x] If a Vega wallet is not detected then the Vega Wallet button should say "Download Vega Wallet" and link to chrome/firefox.  
- [x] If a Vega wallet is detected then the Vega Wallet button should display "Connect" and launch the connect flow
- [x] If Metamask snap is already installed, then the Metamask connect button should say "Connect with Metamask Snap" and launch the snap
- [x] If Metamask is detected but NOT the snap, then button should say "Install Metamask Snap"
- [x] If Metamask is not detected **at all** then button should be greyed out and some text displayed beneath that allows people to learn more (this is current implementation)

### The ACs below were here already and relate more to general onboarding (I think they are dead now)

~- [ ] If a user has connected via the JSON RPC service or the service is running, then the get wallet step is complete~
~- [ ] If the user clicks Connect at that point they should see the same options as defined above depending on which wallets are available~

## Tasks

- [ ] Adjust/Add ACs
- [x] Dev
- [x] Test

## Additional details / background info

Sketch 1

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/72932c44-3800-43e3-b5c5-74f8a8f3531e)

**Comment by JonRay15** [comment]
Probably want to hold off on this for now @macqbat ... still finalising approach and ACs.

**Comment by macqbat** [comment]
@JonRay15 @mattrussell36 please let me know if there will be still something to do here
