### ISSUE TITLE
Dedicated withdraw page

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4646]
## Story

As a user
I want a simple dedicated withdraw page
So that I can be linked to a page to withdraw from other websites or the wallet extension

## Acceptance Criteria

- [x] I can go to /withdraw to withdraw
- [x] I can go to /withdraw?assetId=xyz and have an asset already selected

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [x] Testing (unit and/or e2e)
- [x] Code review
- [x] QA review
