### ISSUE TITLE
Dedicated transfer page

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4647]
## Story

As a user
I want a simplified dedicated transfer page
So that I can easily be linked to transfers from other apps

## Acceptance Criteria

- [x] I can transfer on /transfer
- [x] I can transfer with a preselected asset at /transfer?assetId=xyz

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [ ] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [x] Testing (unit and/or e2e)
- [x] Code review
- [x] QA review

**Comment by bwallacee** [comment]
@macqbat Can we make the asset box to match vega key and amount when no asset has been selected?
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/dee9ff0f-1fa6-4082-aaa1-bedf99acebc8)

**Comment by macqbat** [comment]
> @macqbat, @mattrussell36 Can we make the asset box to match vega key and amount when no asset has been selected? ![image](https://user-images.githubusercontent.com/133853298/266964155-93098d17-3e06-4900-afa4-00acbb07ec6b.png)

this has been done in the last commit

**Comment by bwallacee** [comment]
@macqbat All looks good to me.

Is this going through a team review or can we move to closed?
