### ISSUE TITLE
Website navigation changes

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4650]
## Story

As a user 
I want the website to be simple and easy to use
So that I can find what I want and am not scared by many options

## Acceptance Criteria

- [ ] The top nav bar now appears in the structure given in the "Website Nav & Footer" tab of the sheet
- [ ] Using the "page inventory" tab in the spreadsheet move all the relevant pages to their new home in the new nav
- [ ] The nav bar can now be clicked directly to take you to a homepage, while the second level nav appears when hovering
- [ ] Where there is a bold italic page in the "website nav & footer" that page should NOT appear in the dropdown but should be the page you are sent to if you click the main nav item

NB. Any pages designated as changed will have those changed provided in a different ticket, for now just move them as is. Any pages marked new ignore for now until those are ticketed. 

## Tasks

- [x] Publish website inventory
- [ ] Make all changes to nav
- [ ] Tick them off in the inventory

## Additional details / background info

Link to website inventory:

https://docs.google.com/spreadsheets/d/1_l__0MaKZZFzk-7Mnt_g8ontALbBUL1qAQT9da7-vLI/edit#gid=687966258
