### ISSUE TITLE
Explorer: support `contractCall` tx (oracles)

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#4653]
## The Chore

Part of supporting Ethereum Oracles is displaying the Vega TX that contains the data resulting from an Ethereum call.

## Tasks

- [x] Learn how to decode result data (See :`feat/explorer-eth-oracle-call` for a hacky version)
- [ ] Add `contractCall` component
- [ ] Add `contractCall` view
