### ISSUE TITLE
Add Order type to block explorer transaction view

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#4656]
## Story

As a user
I want to see my order type (limit order / market order etc)
So that I know my order type

## Acceptance Criteria

- [x] "Order" should be displayed with the full "Submit Order" text as the type .... all others (ie. Cancel order, amend order) follow this sort of pattern
- [x] I can see the order "type" when viewing an order transaction (ie. Market / Limit)
- [x] Ideally I can see that type in the transaction list too so I can filter for it (or at least look for it)
- [x] Add "Stop Order" as a type ... we are missing this and only have "Stop order cancellation" currently

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
