### ISSUE TITLE
Improve ui/ux of interactive elements in deal ticket margin details section

### ISSUE THREAD

**Issue by bglownia** [vegaprotocol/frontend-monorepo#4673]
## Story

As a user 
I want to have clear visual indicator that elements are interactive
So that I can easily see I can expand the section

<img width="171" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/1754247/1f270693-0e16-4797-882b-f760cec3d65b">

## ACs

- [ ] It should be clear the section is expandable
- [ ] Labels should be muted color
- [ ] Review tooltips and ensure any breakdown information is captured in the now expandable section. 
- [ ] Margin values and other estimates should use monospace font

## Tasks

- [ ] Adjust/amend ACs
- [ ] UX
- [ ] Design
- [ ] Implementation
- [ ] Code review

**Comment by JonRay15** [comment]
This was deployed
