### ISSUE TITLE
Add some extra wording to the connect wallet dialogue to make the benefits of browser vs snap clearer

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4674]
## The Chore

Extend the messaging on wallet connect to be a bit more informative as per the below

## Tasks

- [x] Jon to add the text 
- [x] Separate out the options a bit more graphically so it is clearer the two primary CTAs are browser wallet and snaps
- [x] Update the text in line with below
- [x] Test it

### Full Text

NB. In each case the text in regular brackets is some sort of subscript or maybe pill component to be displayed next to the name given.  The square brackets indicate where the message needs to change based on the onboarding status or the browser used. 

#### Vega Wallet (Full Featured)
[Install / Connect] Vega Wallet extension for [Chrome/Firefox] for access to all features including key management, asset breakdown, and detailed transaction views from your browser.

#### Metamask Snap (Quick Start)
Connect directly via Metamask with the Vega Snap for single key support without advanced features.

#### Advanced options

- Desktop Wallet (Legacy)
- CLI Wallet (Developers)
- View as party

## Additional details / background info

<img width="312" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/c702995e-3d83-4887-887c-402f7de6486b">

**Comment by bwallacee** [comment]
My personal opnion is we should choose either Advanced or other options.

Rather than have the / split. But other than that it looks good.
