### ISSUE TITLE
Prompt to install browser wallet from key dropdown

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4675]
## The Chore

If a user has installed the Metamask Snap, we still want to prompt them to install a Vega wallet extension so they can use multiple keys more easily

## ACs

- [ ] There is a link to the extension download page in the key dropdown to prompt users to install the browser wallet
- [ ] There is a corresponding icon (like the get started link)
- [ ] The prompt/link only shows if you are connected with snaps

## Tasks

- [ ] ACs adjusted/added
- [ ] Dev
- [ ] Test

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1693478934457989

Something like this

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/2d7aac68-13ad-4ded-a6d8-5376354f00ad)

I included both a Vega and Chrome symbol here ... but maybe just chrome is fine. Also obviously it should detect if you're on firefox and use that symbol if appropriate,
