### ISSUE TITLE
Stop order details dialog

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4676]
## Story

As a trader
I want to see how stop orders are linked
So that I can monitor them

## Acceptance Criteria

- [ ] I can click to open a dialog (like the order detail dialog for normal orders)
- [ ] I can see the stop order setup
- [ ] I can see the oco orders

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

We already have an order dialog. Would be good to use the same UI patterns if possible
