### ISSUE TITLE
Account history

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#469]
Depends on https://github.com/vegaprotocol/pennant/issues/625

## Story

**As a** user
**I want** to be able to inspect my account history
**So that** I can understand the value of my portfolio over time

This would use the balanceChanges api, no subscription required

## Acceptance Criteria

- [ ] I can see my account balance for an asset over time on a chart
- [ ] I can select a different asset
- [ ] I can multi select different account types
- [ ] Default account type is General
- [ ] Default asset is whatever is first when listed alphabetically
- [ ] I can select different time ranges
  - 1D, 7D, 1M, 3M, 1Y, YTD, ALL

## Sketch 
<img width="1383" alt="Screenshot 2022-11-30 at 16 28 52" src="https://user-images.githubusercontent.com/46783148/204853966-aa45776a-5b94-4e2f-aa44-886ae5a1afcd.png">

## Tasks

- [ ] Add a sketch of what we talked about to help illustrate what needs to be done
- [ ] Link to coin market cap example for reference

**Comment by PeteWilliams** [comment]
Initial design for closed positions here:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1616%3A25672

**Comment by campbellssource** [comment]
removing blocked label as this looks like it is now available.

![Image](https://user-images.githubusercontent.com/13255539/178988888-f0403a77-9ca6-428d-9ee2-88ab7ea2b2df.png)

**Comment by macqbat** [comment]
Looks like it's blocked by https://github.com/vegaprotocol/vega/issues/6297

**Comment by macqbat** [comment]
Moreover we need a little more information which exactly data should be displayed and where. After some investigations I have come to conviction, we can't easy tie historic balance of account with trade on certain market. I've got information that the best way for calculate profit/loss closed positions would be getting closed positions (currently not exposed by any api) and/or detect the transfers from margin accounts to general ones.

**Comment by asiaznik** [comment]
@macqbat Shall we then create a ticket for data node?

**Comment by macqbat** [comment]
@asiaznik we need maybe to groom it before. @mattrussell36 Can you confirm? [Here](https://vegaprotocol.slack.com/archives/C037STCKMGC/p1664189922688339) we had a mention about it

**Comment by gordsport** [comment]
Hey,
Please can you let me know when you have refined this and if there is / when you create at ticket on core side for this.

We can then review this and update on scheduling to align the work.

**Comment by pennyandrews** [comment]
We don't seem sure what this ticket is really about now and whether or not it is blocked by something we need from core. So I am putting it in the sprint but just to REFINE it and work out if we need anything from core to be able to complete it, if in fact it is still relevant / desired to do. Once we know it can go back in the backlog or where ever else relevant :)

**Comment by mattrussell36** [comment]
So I've been looking into this today, there isn't really a specific API for historical positions. The positionsConnection query is historical in the sense that it will show all positions regardless of state. However what we can do is show account history over time via the balanceChanges query and allow for filtering by asset, account type, date and market
