### ISSUE TITLE
See volume discounts in the deal ticket

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4714]
## Story

As a user connected with a key that is part of a referral code / team
I want to see the discount I will receive on my trading fees reflected in the deal ticket
So that I understand the fee I will be paying, but can see the discount applied

## Acceptance Criteria

- [ ] I can see what my volume discount factor is
- [ ] I can see the estimated fee I will pay for a position with my discount applied (calculate in client)
- [ ] I can see what the trading fee would have been otherwise 
- [ ] ~The total discount is volume discount + referral discount (NOT multiplied!)~
- [ ] The fully_discounted_fee as defined below is displayed on the ticket 
- [ ] The discount_factor as defined below is displayed on the ticket

Given you get `estimatedFee` from the API

```
referralDiscount = floor(referral_discount_factor * estimatedFee)
discounted_fee = fee - referralDiscount

then 

volumeDiscount = floor(volume_discount_factor * discounted_fee)
fully_discounted_fee = discounted_fee - volume_discount

and 

discount_factor = fully_discounted_fee/fee
```

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

Shoudl already have a pattern for this established based on the referral ticket #4408 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/1ec29d85-f0ef-450c-9e1b-fcb6d92c6e5e)

https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764559935654833&cot=14

## Additional details / background info

The factors applied can be found in this ticket:

https://github.com/vegaprotocol/vega/issues/9258

They will be provided on a new API to be built.
