### ISSUE TITLE
See the team my key is connected to

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4715]
## Story

As a console user connected to a TEAM
I want to easily see the key team info
So that I can feel part of that team

## Acceptance Criteria

Relates to browser wallet ticket https://github.com/vegaprotocol/vegawallet-browser/issues/446

- [ ] There is a way to see which keys are a part of a team e.g. I can see the team image or a generic referral code image next to my key
- [ ] There is a way to see which keys have a referral code applied e.g. the image is repeated in the list
- [ ] Where my key is part of a team, I can see the team name, image and team reward 
- [ ] For referral codes in teams and not, I can see see the tier, fee discount and referrer reward
- [ ] There is a way to see how long you have been a part of this referral code tier
- [ ] There is a way to see how long left there is to enter the next tier 
- [ ] There is a way to see / get to the details of my savings and earnings i.e. a link to the referral programme site
- [ ] Stretch task. As a fallback use the generated icon (currently used for pubkeys) for the team avatar if one doesn't exist

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/46783148/434ae849-0782-478a-8cb4-58c5455abd36)

**Comment by JonRay15** [comment]
I do not think we will do this, we have decided we wont do various things like this araound referrals ... I dont see why we'd do it here.

**Comment by JonRay15** [comment]
I dont think we care about this .... pushing it out into the future a long way.
