### ISSUE TITLE
i18n language provider

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4718]
## The Chore

Set up a our i18n provider with our default English translations.

## Tasks

- [ ] Add i18n language provider
- [ ] Convert usage of our placeholder `t` function with the one provider by our i18n provider
- [ ] Set up default `en` translations
- [ ] Translations should be fetched from somewhere and not bundled in the app
- [ ] language files should not be served from a service (like locize). The backend component to this should be static file fetching
- [ ] Test
