### ISSUE TITLE
i18n language switcher

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4719]
## Story

As a user
I want to be able to switch language
So that I can use the website

### Main Change

- [ ] I can switch to a different language in the top nav
- [ ]  The selected language is persisted
- [ ] Detect language (window.navigator.langauge or something else) and use it as the default
- [ ] If users language is not supported fall back to English
- [ ] Selected locale should change the formatting of dates and numbers. getUserLocale will need to be updated to return the selected language code

### Late addendum

- [ ] I can also switch the light / dark mode in the top nav (for consistency with website)
- [ ] No need to add a chevron, just two buttons

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

Assumption is we will go with a pretty simple UX similar to the approach on the website but we'll use the sidebar

So in the top nav we can have a simple icon like:

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/20cff686-5e21-48fc-adae-383824c9d77f)

This should also cover light / dark mode switcher while we're at it.
