### ISSUE TITLE
Remove dependency on apollo from wallet lib

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4723]
## The Chore

As per the title. Currently the connect dialog makes a query for the chain id _and_ uses apollo client to start subscriptions in order to detect complete transactions. This library shouldn't depend on this as it makes it difficult to install and use

## Tasks

- [ ] Remove dependency on apollo
  - [ ] Remove chain id query
  - [ ] Remove apollo subscriptions/queries for transaction detection
- [ ] Review deps to see if anything else should be removed
