### ISSUE TITLE
Improve tooltip configurability

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4733]
## The Chore

The current tooltip underline feature is annoying, because:

- Too many field names have some sort of tooltip associated to them and end up underlined
- Too many values now have quantum formatting and end up underlined 

Between these factors, basically everything in the app ends up underlined... which looks bad.

## Tasks

- [x] Come up with some way of doing this that is better.  Maybe have it be configurable what is underlined and what isnt? Maybe get rid of underlines and have some sort of cursor change when you move over something with a tip? Maybe there are other options.
- [x] Implement that everywhere for names
- [x] Remove the underline on values generally ... we cant underline everything ... just have the hover
- [x] Consider how we would handle values which are not numerical (eg tradign mode and status). We may still want these underlined
