### ISSUE TITLE
Remaining tweaks to market list screen

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4748]
## The Chore

Make a few changes to the market list screen as there are still some issues here. 

## Tasks

- [x] Remove successor market from this view completely, it is too niche, most ppl wont know what it is, and it takes up too much room
- [x] Add 24h volume
- [x] Reorder columns (Market, description, trading mode, status, mark price, 24h vol, settlement asset)
- [x] Remove Bid Price & Ask Price
- [x] Instead replace them with a single calculated "Spread" field (calculated as `Ask price - bid price`) shown on far right
- [x] Tweak column spacing to remove space from numbers where its redundant and provide more room in the "market" & "description" for long names if they are provided. 
- [x] Add handling for Trading Mode - Monitoring Auction .... dont show the extra info, just show "Monitoring Auction" and pull the full details into a tooltip

**Comment by barnabee** [comment]
I quite like the sound of option 3 but anything other than option for works for me.

**Comment by JonRay15** [comment]
Went with option 3

**Comment by JonRay15** [comment]
This went out
