### ISSUE TITLE
Further adjustments to default zoom on 13in monitor 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4769]
## The Chore

This is a screenshot from a 13in monitor on startup ... to me everything is still a little large.

<img width="1533" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/9412f2ad-db31-4719-90d0-3b5e52cc1477">

Binance for comparison

<img width="1534" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/4a216558-acd4-4079-ad02-a37a80231828">

Here is a screenshot from a 20 something inch monitor where I think the sizing is much better.  So I do think this is probably an "optimizing for smaller screens" task.

<img width="1913" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/27d4e139-69f0-4aea-b9bf-a952c6928325">

## Tasks

To my eye we could still do with:
- [x] Slightly bigger gap between candles (this one I think is true for both screen sizes, the rest are only for small ones)
- [x] More candles on the screen by default
- [x] Studies being a little smaller vertically. Use 90px
- [x] Order book columns being slightly narrower. This is important for number of candles being shown. Use fix width px value instead of percentage value. Check current markets to find a good default. 
- [x] Deal ticket being slightly narrower. Consider lg: media query for sidebar width
- [ ] ~~Probably all fonts being a bit smaller~~
- [ ] Add media query for AgGrid cell/header padding. For small screens reduce the padding.

I'm also not 100% sold that an MACD should be up by default ... but I am assuming that was a preference thing from @barnabee !
