### ISSUE TITLE
Text on the connection modal changes depending on state

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4775]
## The Chore

NB. Might make sense to do with #4774 and #4772

We're showing two versions of the connection modal depending on what you have installed.  We think we dont want that.

With nothing installed you get all this info 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/11e5fd2c-b383-434f-9866-109af7d5bab7)

Once you have installed both things you get this 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/3f9b1298-4e56-4b58-9185-84dc334a68b2)

We think you should get exactly the same descriptive text, ie. 

<img width="304" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/4dab0dfe-2c5c-4038-87b8-df4b67fa9ab5">

and

<img width="288" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/c4fd1fb8-bbc2-4d5b-82d7-7c0bd26d2040">

with the only exception that once something is installed and detected it should say "Connect with" instead of "Install"

Also ... the font looks slightly different on the two ... greyer on once maybe?

## Tasks

- [ ] Adjust wording for once vega wallet is detected
- [ ] Adjust wording for once snap is detected
- [ ] Make sure both fonts are the same
- [ ] Test it
