### ISSUE TITLE
Add support for market state update governance proposals to Governance App

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4807]
## Story

As a user
I want to be able to see markket governance proposals and their potential effects
So that I can be aware of upcoming changes to markets I am trading in

## Acceptance Criteria

- [x] I can see `MarketStateUpdateType_MARKET_STATE_UPDATE_TYPE_SUSPEND` proposals in Governance app
- [x] I can see all relevant details from the suspension proposal in the proposal details page including:
  - [x] The market ID
  - [x] The market code & name (looked up from /market)
  - [x] The usual closing / enactment details
  - [x] The usual rationale etc details
- [x] I can see `MarketStateUpdateType_MARKET_STATE_UPDATE_TYPE_RESUME` proposals in the Govenance app
- [x] I can see all relevant details from the resume proposal in the proposal details page including:
  - [x] The market ID
  - [x] The market code & name (looked up from /market)  
  - [x] The usual closing / enactment details
  - [x] The usual rationale etc details
- [x] I can see `MarketStateUpdateType_MARKET_STATE_UPDATE_TYPE_TERMINATE` proposals in Governance app 
- [x] I can see all relevant details from the terminate proposal in the proposal details page including:
  - [x] The market ID
  - [x] The market code & name (looked up from /market)  
  - [x] Termination price formatted by `market decimals`
  - [x] The usual closing / enactment details
  - [x] The usual rationale etc details

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

Spec: https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0028-GOVE-governance.md#6-change-market-state

Example payloads in tutorials:

[Tutorial: Proposal to resume suspended market](https://github.com/vegaprotocol/documentation/issues/694)
[Tutorial: Proposal to suspend market](https://github.com/vegaprotocol/documentation/issues/695)
[Tutorial: Proposal for closing a futures market](https://github.com/vegaprotocol/documentation/issues/696)
