### ISSUE TITLE
Add market governance proposal label types to Explorer

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4808]
## The Chore

The [governance proposals page](https://explorer.vega.xyz/governance) needs to be able to cope with new market governance proposal types.

## Tasks

- [x] Add support for `MarketStateUpdateType_MARKET_STATE_UPDATE_TYPE_SUSPEND`
- [x] Add support for `MarketStateUpdateType_MARKET_STATE_UPDATE_TYPE_RESUME`
- [x] Add support for `MarketStateUpdateType_MARKET_STATE_UPDATE_TYPE_TERMINATE`

## Additional details / background info

Governance ticket has more exhaustive details but I dont thikn we need that here

https://github.com/vegaprotocol/frontend-monorepo/issues/4807

**Comment by JonRay15** [comment]
Its handling terminations ... I see no reason it woudnt handle the others. 



![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/6736e426-8cdb-4959-ab20-e87be6d1ba8d)

**Comment by JonRay15** [comment]
Suspends are fine 


![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/45b46311-e695-4aa1-a195-53fafa517dfa)

**Comment by JonRay15** [comment]
And resumes

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/a20644bd-8aa2-4b12-8ca7-5988f9eab01c)
