### ISSUE TITLE
Show worst case instead of ranges on deal ticket estimates

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4824]
## The Chore

One more observation ... one that I think has been made before ... I tend to agree that showing ranges on all these things is unnecessary.

It just creates lots of text and therefore risk of wrapping which looks bad.  Margin, deduction from collateral, projected margin, and liquidation could all just be shown as worst case figures surely?

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/4bf093bf-619e-4653-88ba-a50fe57d3928)

I also dont 100% understand why I need to see all these figures. How does "deduction from collateral" differ from "Margin required"? I can see they are different ... but not materially, and what exactly i should infer from that minor difference is unclear to me

## Tasks

- [x] Agree that we can do worst case (and agree logic for choosing the "worst")
- [ ] ~~Agree whether any fields can simply be removed~~
- [x] Show both worst case and best case in tooltip
- [x] Values should not be underlined when they are tooltips
- [x] Build it
- [x] Test it
