### ISSUE TITLE
Add handling for no active referral programs

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4830]
## Story

As a user 
I want to see something rather than an error state when their are no active referral programs
So that it doesnt look rubbish

## Acceptance Criteria

- [x] I can see some message saying "No active referral program currently" displayed instead of the tiers 
- [x] I can no longer see the staking multipliers
- [x] I can see this treatment on any page that would have displayed some version of this information
  - [ ] Referrer stats
    - [ ] Commission should show zero 
    - [ ] Multipliers should show n/a
    - [ ] Total commission should show zero 
    - [ ] Max discount factor should show zero
    - [ ] TIers beneath should show "no active referral program currently"
  - [ ] Referee stats
    - [ ] Current tier n/a
    - [ ] Discount zero 
    - [ ] epochs to next tier n/a
    - [ ] Max discount factor 0

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
I actually dont know that I have ever seen this in order to verify it. So not sure I can approve this. Has @bwallacee got a market sim env with no active program that we can test on?

**Comment by JonRay15** [comment]
This is covered under #5176
