### ISSUE TITLE
Improve time of checking desktop/cli is ready to connect

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4857]
## The Chore

What we need to achieve and who for

## Tasks

- [x] Decrease 10 seconds period, change it for flexible time depending on response time - use Exponential backoff algorithm in case of very long time of response.
- [x] Remove chain Id check so we don't send requests to nodes
- [ ] ~Add possibly abort signal on too long requests~ Long requests were likely triggered by waiting for chain Id. So this shouldn't be necessary
- [ ] ~Display loader on the button so user is aware of periodical way of checking wallet accesibility~

## Additional details / background info

Based on feedback @davidsiska-vega received from important user
