### ISSUE TITLE
Rejig the perps market info slightly

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4858]
## The Chore

The order on the market info doesnt feel right for perps.

I personally think it is partly because its wrong for futures too, and by following the same format we've got into trouble.

**Perps**
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/7c7b1b00-800b-4d5e-8af8-89502c6fbe7f)

**Futures**
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/8ea44261-dbf7-499e-8c12-eb09375035d6)

## Tasks

I would 

- [x] Move the expiry to the far right of the page 
- [x] That will mean we naturally move the funding / countdown to the right too
- [x] That leaves price as the first thing which feels correct ... and we should change it to "Mark Price" so its more explicit
- [x] We then also want to add a "Index Price" (External TWAP from market data API, formatted using asset decimals) to the far right of the perp one, as this is the price that is driving the funding rate
- [x] We also want to rename "Funding" to "Funding Rate" to be more explicit
- [x] We probably then want to optimise the spacing so the words and numbers line up nicely, currently they're a bit off and will get worse with the addition of "rate" as above

**Comment by davidsiska-vega** [comment]
@JonRay15 I with you, to me it make sense as you say (but I am not an UI designer). 

For me the two main things are:
- if a price is displayed next to the funding rate it should be the last input of the underlying spot price going into the funding rate 
- if a price is displayed anywhere we should say mid / mark / oracle feed price to make it clear (or at least a tooltip).

**Comment by JonRay15** [comment]
Well ... we dont have UI designers right now ... the best we've got is my screenshots and random thoughts ...

**Comment by JonRay15** [comment]
Need to be using asset decimals to format the index price / external TWAP.

**Comment by macqbat** [comment]
> Need to be using asset decimals to format the index price / external TWAP.

Done
