### ISSUE TITLE
EPIC: Feedback from an investor and institutional/professional trader

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/frontend-monorepo#4860]
See below feedback items raised:

- [x] Gap between trades list / order book and deal ticket (may be related to frozen allotment panes issue)
- [ ] Fills and any other lists that may not load all history need to show the time period
- [ ] Any panel that filters by default should make this clear (e.g. where showing only fills for the current market)
- [ ] Any panel that flters results by default should either show this filter in a way it can be toggled/disabled or link to e.g. the portfolio view where the full unfiltered data set is available 
- [ ] Add a tooltip or similar to liquidation price showing breakdown of how this is calculted and/or the reference data used so a user can see how the number is derivate. Link to docs if can't be made fully clear how it's derived in a tooltip.
- [ ] Review testing to ensure we have coverage for all financial amounts, remediare where necessary. Reminder it should be treated as a "production" mainnet incident if any financial value is wrongly displayed in a full (mainnet) release of any UI code.

**Comment by JonRay15** [comment]
Response to these:

Gap between trades list etc 
- I'm not sure I understand or can easily reproduce, think we need more info and to check if its already fixed by the resizing fix we already made

Showing time pereiod 
- Created #4898 

Showing default fiters 
- Created #4897 

Better explaining liquidity estimate 
- I am not convinced this is possible in a tooltip given its so complex
- I am not sure its evven properly described in docs, but I have raised with Candida & Witold

Review test coverage of critical fields
- This is something we will look at ... but no ticket raised.

**Comment by barnabee** [comment]
Gap between trades list- must be fixed I think, pretty sure it was related to pane sizing and/or toggling the sidebar. I only saw it on a Zoom call though. We can assume fixed (delta the remaining pane sizing issues that persist at least in Firefox).
