### ISSUE TITLE
Create ops feature toggles

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#4861]
## The Chore

We need to be able to quickly toggle features on and off without needing to deploy.

These flags differ from release flags which will still be added and managed via .env files.

## Tasks

- [x] Agree an approach
- [ ] Agree which features should be flagged
- [ ] Agree naming convention for toggles
- [ ] Add documentation to incident management on how to toggle features
- [ ] Implement
  - [ ] toml file for feature flags
  - [ ] add wrapping toggle component
- [ ] Test

**Comment by JonRay15** [comment]
Put this on a list to discuss with Matt when he's back next week

**Comment by bwallacee** [comment]
Thoughts:

- [ ] How can we ensure no one could maliciously enable toggles (unauthorised users etc)
- [ ] Do we need logging around toggles for traceability?
- [ ] Toggles need to work across environments, and not affect environments other than their own.
- [ ] Anyone on the on-call rota need to know how to enable toggles and their effects
- [ ] Is there any considerations with IPFS and toggle status not being consistent across nodes etc?
- [ ] will it be easy to see the current state of toggles/
- [ ] Keep feature/release toggles separate from ops toggles
- [ ] We will need to test to ensure UI handles components disappearing correctly
- [ ] Can we enable toggles locally ( on mainnet but only affect our own version of console)?
- [ ] Depending on what ops toggles are in place we may want to duplicate some of our tests with toggles enabled/disabled.

Some thoughts around release toggles:

- [ ] Could we use a similar strategy to release features?
    - [ ] Could we do canary releases?
    - [ ] Could we release features to mainnet with them turned off, enable locally to test they work, then turn the toggle on to release feature. Once happy, delete the toggle or turn to ops toggle.

**Comment by JonRay15** [comment]
Pretty sure I recall Barney being strongly allergic to this as it implied very close control of the app which is something we cannot have. Pushing it out a long way.
