### ISSUE TITLE
adjust console-test branching to reflect frontend-monorepo state

### ISSUE THREAD

**Issue by radoslaw-szpiech** [vegaprotocol/frontend-monorepo#4886]
## The Chore

We want to have tests being run on both main and develop branches of frontend-monorepo.

## Tasks

- [x] Create develop branch in console-test
- [x] Adjust jobs in console-test 
- [x] Adjust jobs in frontend-monorepo

## Additional details / background info

Use 4-cores as runner in CI jobs.

**Comment by radoslaw-szpiech** [comment]
Decided to move with 8-cores, as 4-cores was not enough in few cases.

**Comment by radoslaw-szpiech** [comment]
Everything was set up and tested. Console-test is again enabled on frontend-monorepo PRs.
