### ISSUE TITLE
Add a better "working on it" animation to the ledger CSV extract

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4895]
## Story

As a user
I want better feedback about my ledger entry download
So that I understand its still in progress

The CSV can take quite a long time.  

We want to add better processing animation to it so that users know it can take some time and that their app is not broken.

## Acceptance critieria

- [x] I can see a message saying that this can take several minutes
  - [x] After half a minute,  the message is updated to to say something like 'Still in progress'
- [x] A toast is shown when the download is complete
~- [x] The download is shown as already in progress if the user returns to the download view~
- [x] The download button should never be disabled
  - [x] If user tries to download file which is already in download:
    - [x] if notification stayed open, nothing happens
    - [x] If notification was closed, will be open
    - [x] If something has changed in the form (asset, dates, `Date.now`) new download will start.
- [x] The state of the download form should be in sync with the download itself if you navigate away from the page or reload

## Tasks

- [x] Detach download from the view so that you can navigate freely without cancelling the download

**Comment by mattrussell36** [comment]
@candida-d could you provide some support for the messaging here
