### ISSUE TITLE
Where lists filter by default, make this filtering clear

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4897]
## The Chore

Some tables like fills filter by default to only show the market you're currently on.

In these cases the UI needs to make that clear

## Tasks

- [ ] Identify all the places this occurs 
- [ ] Somehow show the default filter anywhere that this is done 
- [ ] Provide a link to the portfolio page or some info to navigate there to see all records
