### ISSUE TITLE
Update no rows found messaging in datagrids

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4898]
## The Chore

Some lists such as fills and orders do not show the full history when there are many entries. 

In these cases we need to indicate how many are shown and why.

## Tasks

- [x] Identify all places this happens
- [ ] Update no rows message to indicate if filters are affecting rows displayed.
- [ ] If table has 0 rows include some wording around the fact that the number of rows is capped and that depending on datanode retention you _may not_ be able see the "full" history
  - Note that there is still an edge case where if there are more than 5000 rows (for orders) you will not be 
- [ ] ~~Provide some guidance on how to see full history~~ This will be covered by #5086 

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1696518683350629

**Comment by JonRay15** [comment]
Could we do this with filter applied by default? Like if we automatically always filtered by date last 30 days and showed that?

**Comment by JonRay15** [comment]
This is linked to datanode retention so shoudl be covered in full when that arrives. 

For now @bglownia is doing some research and we will use this in combination with the above onc we can look at this properly.

**Comment by bglownia** [comment]
In console there are three lists that are not showing all results: trades, fills and orders. Where fills are trades but shown per party not per market. Both trades and orders has date range filters available, which are not in use. We are showing first 5000 orders and first 500 trades, without pagination support.

**Comment by JonRay15** [comment]
Break this down into two tickets

Initially lets just immediately make sure that we have a message indicating if we are truncating or not. 

Then we can look at UX to improve that.
