### ISSUE TITLE
See list of members in a referral set

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4903]
## The Chore

The original ticket [here](https://github.com/vegaprotocol/vega.xyz/issues/822) will not be possible to do in full because the last part of the API is not yet delivered. 

We will need the extra build on this [ticket](https://github.com/vegaprotocol/vega/issues/9541) to do this.

## Tasks

- [ ] Wait for Core to deliver the above ticket
- [ ] I can see a list of my team members 
- [ ] I can see the trading volume of each referral 
- [ ] I can see what I have earned in commission from each referral

**Comment by asiaznik** [comment]
On `"I can see what I have earned in commission from each referral"`:
https://github.com/vegaprotocol/vega/issues/9818

**Comment by bwallacee** [comment]
@asiaznik @JonRay15 
Should this say "last epoch" rather than "last 1 epochs"
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/0f36b9cd-8714-42f1-830f-73763334512e)

**Comment by asiaznik** [comment]
Yes, it should
