### ISSUE TITLE
Show funding payment history in Console

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4915]
## Story

As a user 
I want to see the funding payments made to me 
So that I can see whether I am successfully gaming the funding mechanism or not

## Acceptance Criteria

- [ ] I can see some table somewhere (probably along with fills / stop order etc) showing my funding payment history
- [ ] I can see both the wins and losses
- [ ] I can see the payment amount 
- [ ] I can see the funding rate that caused that payment amount
- [ ] I can see whether I was long or short at the time
- [ ] I can see when that payment was made
- [ ] I can see the market that payment was for

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

I'm kind of assuming another table down here ... but open to suggestions:

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/b16b91a5-d199-4ae8-969d-1c3f6abed776)
