### ISSUE TITLE
Expose datanode retention policy

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4929]
## Story

As a user of Console
I want to know if any view that I am looking at is impacted by data retention on the datanode I'm connected to
So that I am clear on the potential impacts of data I may not be seeing, and can choose to switch nodes if desired

## Acceptance Criteria

- [ ] I must see the valid data retention policy on any view that might be impacted by it
- [ ] I should be prompted to switch nodes if necessary
- [ ] This information will need to be exposed on:
  - [ ] Trading
    - [ ] The chart itself
    - [ ] Positions (relevant for closed ones
    - [ ] Closed
    - [ ] Rejected
    - [ ] All
    - [ ] Fills
  - [ ] Portfolio
    - [ ] The equivalent of all the above tables
    - [ ] The ledger entries CSV
  - [ ] Markets 
    - [ ] Closed Markets

## Tasks

- [ ] Determine which views could be impacted by this
- [ ] UX (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

Core ticket: https://github.com/vegaprotocol/vega/issues/9606

**Comment by JonRay15** [comment]
Can we do something in this area based on the network config TOML rather than asking for a Core change?

Could be worth exploring if we're not going to get a Core change until at best Nebula.
