### ISSUE TITLE
Add slippage factors and margin scaling factors to market accordion

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4931]
## The Chore

We are missing a bunch of things from the risk model section of the accordion ... and presumably always have been. 

These need to be added

## Tasks

- [ ] Add margin scaling factors to accordion
- [ ] Add slippage factors
- [ ] Remove "Risk Parameters" heading and just put sigma under the "Risk Model"
- [ ] Add max initial leverage and max leverage (both long and short) to the risk factors

## Additional details / background info

Current view:

<img width="276" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/0bb31945-1d09-4834-a1cf-e1b866ebc3af">

Margin scaling needs to be in, and formatted nicely:

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/36cf0e03-c771-4d98-8fee-97af79193481)

Slippage factors are easier ... not sure why they werent always there.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/382f685f-04a8-47b8-a8ed-0398c5199762)

**Comment by davidsiska-vega** [comment]
Once we are pulling in all the data additionally display:

Max. Initial leverage long: which is calculated as 
```
(1.0/initial_margin) x (1.0 / (linear_slippage_factor + rf_long)) 
```
which should give us, with the numbers in the screenshots about `(1/1.5) x (1/(0.001 + 0.023) = 28`. 

Max. Initial leverage short: which is calculated as 
```
(1.0/initial_margin) x (1.0 / (linear_slippage_factor + rf_short)) 
```
which should give us, with the numbers in the screenshots about `(1/1.5) x (1/(0.001 + 0.023) = 28`. 
 
Max leverage long:
```
(1.0 / (linear_slippage_factor + rf_long)) 
```

and Max leverage short:
```
(1.0 / (linear_slippage_factor + rf_short)) 
```

**Comment by MadalinaRaicu** [comment]
do we need all of these decimals? 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/e1835596-9de6-4417-a1dd-4f41446a3533)

@davidsiska-vega @JonRay15
