### ISSUE TITLE
chore: refactor console navigation - each main tab should start from different path

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/frontend-monorepo#4961]
## The Chore

Currently we have two other tabs in main navigation (Markets, Trading) with the same basic starting path `/markets`. It's caused some problems when we need to add some deeper routes and mark certain menu position as active in `Navlink` react router component. 
Because of that in this [PR](https://github.com/vegaprotocol/frontend-monorepo/pull/4958) was needed to add not nice looking path for closed markets, like _/markets/all/closed/:marketId_ to make as active different main tab in main navbar. If each main routes had have different starting path, such long path shouldn't be necessary and other navi configurations would be easy and seemed exactly as how it should be done. 

So the proposal of change are: 
- first navi tab Markets should have path started from `/markets`, e.g `/markets/all`, `/markets/open`, `/markets/closed` etc.
- second navi tab should have path started from `/market`, e.g.` /market/:marketId`

These would allow for greater order in the configuration.

## Tasks

- [ ] Change trading path and url where user can trade for starting from `/market`
- [ ] Change `to` parameter of NaviLink from `/markets/all` to `/markets`
- [ ] Review all links and internal redirects to make sure they not follow to old url's nor cause redirection loop

## Additional details / background info

All urls of tradable markets will be affected by this, so some redirecting in `MarketPage` component would be needed
