### ISSUE TITLE
Add banner to settled markets

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4975]
## Story

As a user
I want to see more obvious information when a market is settled and be directed to any successors
So that I can more easily find the new market to trade on 

## Acceptance Criteria

- [x] There is a banner displayed on settled markets indicating it has been settled (I guess this would be yellow / blue?)
- [x] The banner includes a link to a successor market if one is available (think we have already done this)

Some of this may already be done so lets check whst we have already and go from there.

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

Feedback from user:

https://github.com/vegaprotocol/feedback/discussions/166
