### ISSUE TITLE
Created blocked route on governance site

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#4981]
## The Chore

Currently `<ClaimRestricted />` is rendered conditionally but using a cookie that is never set, since the new deployment. This should be moved to /claim/blocked.

## Tasks

- [ ] Move component to its' own route
- [ ] Add link to fairground terms
- [ ] Change copy to be something similar to "We need to say something like users in $COUNTRY are not eligible for VEGA rewards, see section 5.5 of the Fairground [terms and conditions](https://fairground.wtf/general-terms)"
- [ ] May need to alter https://github.com/vegaprotocol/terraform/blob/master/frontend/cloudfront-functions/claim.js#L33 to pass country as query param

**Comment by JonRay15** [comment]
Pretty sure this is done ... closing
