### ISSUE TITLE
Improve Cypress reporter

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#4986]
## The Chore

Currently there is no visibility on slack for when tests fail and the flow for viewing the test report requires quite a few steps which most non-testers are currently not doing.

## Tasks

- [ ] Use alternative reporter if better one is available
- [ ] Integrate Slack hook with test results
- [ ] Provide link to test report without needing to manually download the report

**Comment by jtsang586** [comment]
After spending some time looking at different reports and slack integrations I couldn't find anything satisfactory that didn't require a lot of work custom building a slack webhook for the test reports.

Really the best alternative is to host our own cypress dashboard using `https://sorry-cypress.dev/`
Since we already have our own servers in the office this seems to be a viable alternative. Will create a separate ticket for that if it's a serious option for us
