### ISSUE TITLE
New fees page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5014]
## Story

As a user
I want a view of all the fees on the network
So that I can see what fees I'm paying and the discounts i'm receiving

## Acceptance Criteria

- [x] We have a new tab on the portfolio page labelled "fees"
- [x] I can see all the different base fees (infra, maker, liquidity)
- [x] I can see the active volume discount program and the discounts I am receiving
- [x] I can see the active referral program and the discounts I am receiving

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

https://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=3166-5839&mode=design&t=4RMokerNnhCNS3t5-0

## Additional details / background info

Implementation details:

- Volume discount tiers can be taken from `currentVolumeDiscountProgram`
- Referral discount tiers can be taken from `currentReferralProgram`
- Infra / maker fees are network params
- All market info including liquidity fees can be taken from `markets`
- Individual running volume can be take from `volumeDiscountStats`
- Referral set running volume can be taken from `referralSetStats` i _think_
