### ISSUE TITLE
Adjust layout for funding payments

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#5016]
## The Chore

Clarify funding payment information

## Tasks

- [x] Remove funding payments from trading page bottom section
- [x] Split funding tab in top section into two sections, one side for funding payments for the current market and the other side for funding history (as it is now)
- [x] Add a funding payments tab to portfolio page showing funding payments for all markets

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1696943212113669
