### ISSUE TITLE
Refine funding rate behaviour in auctions

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5035]
## The Chore

Currently I think for both funding rate / countdown we will display a dash / unknown for any suspended market. 

I believe we need to refine this to be more specific depending on the auction type.

## Tasks

- [ ] For opening auction >> Dash / Unknown
- [ ] For liquidity auction >> normal funding rate / normal countdown
- [ ] For price monitoring auction >> normal funding rate / normal countdown
- [ ] For market suspended by governance >> Dash / unknown (I assume ... since we dont know when - if ever - that market might be restarted?)
