### ISSUE TITLE
Size should be given in units of quoteAsset on orders view

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/frontend-monorepo#5049]
## Story

As a user
I want to see the units my size is measured in
So that I can evaluate my size

## Acceptance Criteria

- [ ] I can see the units of size

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/938a2c54-2462-4318-a6c3-7d72431f7383)

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/367f9498-3f8b-4738-a564-fb892ae9f30c)

## Additional details / background info

This is the `quoteAsset` field from the market.

**Comment by JonRay15** [comment]
I think we did this in console and concluded it was nonsense.
