### ISSUE TITLE
Remove conditional feature rendering

### ISSUE THREAD

**Issue by sam-keen** [vegaprotocol/frontend-monorepo#5052]
## The Chore

Once mainnet goes live with referrals, governance transfers etc, remove all fragments, flags, conditional rendering etc, and ensure the main proposals/proposal query deals with all required data

## Tasks

- [ ] Remove conditional queries
- [ ] Remove feature flags
- [ ] Remove conditional rendering logic
- [ ] Update proposals/proposal queries
