### ISSUE TITLE
Make sure that governance notifications via toast are generic

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5064]
## The Chore

These needs to cover all proposal types

## Tasks

- [ ] Identify all governance proposal types we care about, or is it simply "all"?
- [ ] Ensure toasts fire for each of these
- [ ] Ensure the messaging on each of these is appropriate
