### ISSUE TITLE
See referrer stats page

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#5071]
## Story

As a user 
I want to see the performance of my referral code / team 
So that I can understand easily the size of my team and rewards

## Acceptance Criteria

When the key I used to create a team is connected to the referral site...
- [ ] I can see the base commission rate from the tier the set is in
- [ ] I can see the combined running volume that placed us in that tier
- [ ] I can see the staking multiplier I am getting
- [ ] I can see the staked amount that I have in order to get that multiplier
- [ ] I can see the final commission rate I am receiving: ie base commision x multiplier (ignore the 30 days thing in the sketch)
- [ ] I can see my referral code (ignore the extra tier info in that box)
- [ ] I can see the total number of traders referred 
- [ ] I can see the max discount available in my set as taken from the top tier 
- [ ] I can see the total commission I've earned over the past 30 days
- [ ] I can see the headline info aaround tiers, multipliers, and how it works as on the homepage

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764560351105468&cot=14

Final Designs

![Image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/bf378755-3a21-40f2-b95e-4e88fe1c05a7)

**Comment by bwallacee** [comment]
@JonRay15 @asiaznik 
Sounds dumb but there's nothing that tells/shows me what tier I am in (other than seeing my discount matches a particular tier)
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/8dd3267a-7297-440d-9b4a-3826cfa42384)
