### ISSUE TITLE
Simple referral site meta data for sharing

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#5072]
## The Chore

When a referral link is shared, it should carry with it some site meta data so that users know what is being shared with them. 

## Tasks

- [ ] Add the ability to copy "link" in addition to the copy code
- [ ] Add metadata to that link to make it look nice with a nice preview (Vega logo / thumbnail of referrals page / something else?)
- [ ] Ideally have the ability to programmatically generate a thumbnail with key referral stats (number of ppl in set, current discount factor etc)

## Additional details / background info

![Image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/d9aee594-d1f6-4bde-aad5-7b3718729158)

We have this sort of info here that we could use

![Image](https://github.com/vegaprotocol/vega.xyz/assets/89918817/82ef69e9-f97d-4342-b13a-5431284ae733)
