### ISSUE TITLE
See fee savings due to referree discount

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#5073]
## Story

As a refereee
I want to see my savings due to being in a referral set
So that I can understand my savings

## Acceptance Criteria

- [ ] I can see my current saving on trading fees over the past 30 epochs by asset

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

Would be some expansion of this

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/b82ec7f1-da0a-4160-8d23-dd49f079c2d4)

## Additional Info

I am not sure Core finished this API ... and I doubt we will push very hard for it for now.

**Comment by JonRay15** [comment]
Not convinced we will ever do this
