### ISSUE TITLE
EPIC: Trading View integration

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5078]
## Core Feature

<Name>

## Tasks

- [x] Define high level requirements
- [ ] ~~Create basic mockups~~ Not required
- [ ] ~~Update "API Requirements" in core spec~~ Not required
- [ ] Update "User-Interface Spec" in relevant front end repo
- [ ] Create detailed user stories using normal template

## Linked User Stories

- [x] #5335
- [x] #5336
- [x] Create repo for trading view lib
- [x] https://github.com/vegaprotocol/devops-infra/issues/2110
