### ISSUE TITLE
Close positions from the chart

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5080]
## Story

As a user
I want to be able to close out my positions from the chart
So that I dont have to click on the positions table beneath

## Acceptance Criteria

- [ ] I can see my position on the chart shown where my average entry price is
- [ ] I can see the size of my position
- [ ] I can see the liquidation price for that position
- [ ] I have a X button that allows me to close the position

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
