### ISSUE TITLE
Display orders on the order book

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5088]
## Story

As a user
I want to be able to see my orders on the depth chart and order book
So that I can see at a glance how my volume compares to other volume on the book and adjust accordingly if needed. 

## Acceptance Criteria

- [ ] I can see my order volume on the order book and visually identify it relative to other volume
  - [ ] Highlight the rows my volume is in taking into account the curren aggregation level
  - [ ] Add a new column if you widen the order book to show your exact volume
  - [ ] Add a lighter colour to the bar to show your portion of the overall depth at that price

NB. We will soon be wanting to find a way to display volume generated by hybrid AMM pools in both these places too, so whatever we do here needs to scale to that also. 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
I think we should do this when we do hybrid AMM because at that point we need to amend the UX to cover showing AMM volume on the book somehow, so this solution needs to work with that too.

**Comment by JonRay15** [comment]
Covering this under #5077
