### ISSUE TITLE
Add additional intervals to all charts

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5089]
## The Chore

We are missing some intervals on the main chart.

## Tasks

- [x] Add 1w
- [x] Add 12h
- [x] Add 4h
- [x] Add 30m
- [x] Update pennant to support new intervals
- [x] Update trading view lib to map new intervals to trading view resolutions
- [ ] Do we need to add any to the funding rate chart or is that completely separate?

## Additional details / background info

Core ticket raised now.

https://github.com/vegaprotocol/vega/issues/10180

**Comment by JonRay15** [comment]
Jon to create a core ticket for this
