### ISSUE TITLE
Add icons for markets

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5096]
## Story

As a user
I want to be able to see nice icons in Console for markets and assets
So that I think "wow ... Console looks cool"

## Acceptance Criteria

- [ ] Show in market header for current market
- [ ] Show in the market selector
- [x] Show in the markets page

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by mattrussell36** [comment]
Parking this until https://github.com/vegaprotocol/frontend-monorepo/pull/5015 is merged as it contains asset icons
