### ISSUE TITLE
EPIC: Competitions & Teams

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5101]
## Core Feature

<Name>

## Tasks

- [x] Define high level requirements
- [x] Create basic mockups
- [x] Update "API Requirements" in core spec
- [x] Update "User-Interface Spec" in relevant front end repo
- [x] Create detailed user stories using normal template

## Link to API Requirements in Core spec

https://github.com/vegaprotocol/vega/issues/9981
https://github.com/vegaprotocol/vega/issues/9257
https://github.com/vegaprotocol/vega/issues/9980
https://github.com/vegaprotocol/vega/issues/9260

## Linked User Stories

- #5485 
- #5486 
- #5196 
- #5487 
- #5194 
- #5488 
- #5195 
- #5557 
- #5558 
- #4715 (may not do)

**Comment by JonRay15** [comment]
I think we can safely close this as done at this point.

Minor improvements are continuing but can be treated as BAU at this point IMO.
