### ISSUE TITLE
Create size slider

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5102]
## Story

As a user
I want a order size slider
So that I can size my order without manually typing out numbers 

## Acceptance Criteria

- [x] I can set the size I want on a slider (sketch is stolen from Binance, ignore, use the one we already used for leverage)
- [x] When I set my size on the slider the written size in the ticket updates on screen
- [x] If i set my size manually in written text the slider moves to reflect this
- [x] In isolated margin mode:
  - [x] When I have no open position the max size on the slider is the position size that would use up all my remaining general account as margin, eg. MAX = `balance in general account` / `margin factor`
  - [x] When I am making an existing position larger then same approach as above
  - [x] When I am flipping an existing position then the max is the amount needed to use all my balance on the other side, eg. MAX = (`current margin that would be returned to you` + `balance in general account`) / `margin factor`

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [x] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

<img width="328" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/0dd633cb-0c91-4e84-9d31-b93f197097da">

## Additional details / background info

Core PR for slippage removal: https://github.com/vegaprotocol/vega/issues/10754

**Comment by JonRay15** [comment]
Moved the cross margin onto #5963
