### ISSUE TITLE
Add a "Max" button to the transfer sidebar

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5103]
## Story

As a user
I want to have a max button when asked how much to transfer
So that I can easily empty a key without typing the full amount manually

## Acceptance Criteria

- [ ] I can see a button offering "max" (I'd expect it to be below and on the right)
- [ ] That button populates the page with the full balance of that asset on that key
- [ ] The include fees should be auto-ticked when using this option

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/1d6b2a00-b760-4e70-b884-97b0f5f6c459)

**Comment by JonRay15** [comment]
This is now a dupe of one in progress now
