### ISSUE TITLE
Add active rewards to the rewards page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5114]
## Story

As a user 
I want to see which reward schemes are active right now
So that I can see which rewards I could be trying to access

## Acceptance Criteria

- [ ] I can see a table in the reward page showing live rewards that includes
  - [ ] Asset Symbol eg. VEGA
  - [ ] Status eg. Active
  - [ ] Start epoch eg. 690
  - [ ] End epoch eg. 750
  - [ ] Reward type eg. Price Taking
  - [ ] Reward amount per epoch eg. 1000
  - [ ] Lock period eg. 10 epochs
  - [ ] Funded by eg. PUBKEY or "Network treasury"

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

https://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=3166-5839&mode=design&t=bFtiBgX844KapIEv-0

## Additional details / background info

This info can be found on the transfers API ... and there is Core work in flight to filter that to show only recurring transfers. 

Note this is dependent on #4532 to create the basic page. 

It is also dependent on this [core issue](https://github.com/vegaprotocol/vega/issues/9883) to add the filter. 

```
query transfers {
  transfersConnection{
    edges{
      node{
        id
        from
        fromAccountType
        to
        toAccountType
        asset{
          id
          symbol
        }
        reference
        status
        timestamp
        kind{
          ...on RecurringTransfer{
            dispatchStrategy{
              dispatchMetric
              dispatchMetricAssetId
              marketIdsInScope
              entityScope
              individualScope
              teamScope
              nTopPerformers
              stakingRequirement
              notionalTimeWeightedAveragePositionRequirement
              windowLength
              lockPeriod
              distributionStrategy
              rankTable{
                startRank
                shareRatio
              }
            }
          }
        }
        reason
      
      }
    }
  }
}
```

**Comment by JonRay15** [comment]
That core issue is now merged so just waiting on a stagnet push
