### ISSUE TITLE
Add validation for stop orders during an auction

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5127]
## The Chore

We have validation on limit and market orders when a market is in auction but nothing for stop orders ... we probably should. 

## Tasks

- [ ] At minimum put a similar message to what we have for limits saying that any stop orders will not trade until after the auction ends
- [ ] In theory there is an edge case where you could create a stop market with a nnonsense trigger price that woudl trade immediately, we could add detection for such a moronic order and say it will be rejected by core (since it will convert to market order and get rejected)
- [ ] There are probably other edge cases, and we shoudl discuss core behaviour with the team so we fully understand how it treats stop orders during auction.

**Comment by JonRay15** [comment]
In theory it should not trade until after the auction anyway becaise it should require a trade to print a price for this to get triggered.

**Comment by JonRay15** [comment]
Ben to test the behaviour

**Comment by bwallacee** [comment]
If I create a stop market order that would trigger immediately it is rejected.
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/623325b6-4bbf-43dc-a198-b6ab9c2d5941)

**Comment by JonRay15** [comment]
I have now completely forgotten what we wanted to happen ... 

Oh yes ... @barnabee thought that it should not trade until the market leaves auction right?  

So has this now become a "core isnt doing quite what we expect" ticket?

**Comment by JonRay15** [comment]
Asking protocol design if this is expected behaviour

**Comment by JonRay15** [comment]
Core bug ... closing
