### ISSUE TITLE
Study resize isnt working exactly as I'd expect

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5136]
## The Chore

Hate to raise another one of these damn pane resize things ... but....

If you start off like this with the studies at the bottom the same size:

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/ac40669c-e28a-4cf8-bb47-ba1184e75114)

Then you adjust the size of your positions table so the chart shrinks to almost nothing the bottom study (volume) seems to reach a min size and stop shrinking while the other becomes tiny. Also the header texts start to overflow when you do this ... not sure how to fix that.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/22e8036a-5473-4392-83c2-6852a0e6a72f)

Then if you drag the positions pane back down again the main chart will fill the screen but the study that went tiny will stay tiny, while the other one keeps that same min size obviously.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/7ba8262c-0124-4951-9136-a9d63bbd90b1)

If I remove the volume study completely then now the MACD doesnt scale .... so it appears that whatever is the bottom study will not scale. 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/24148404-9499-4b20-aae6-a34ccd306fd1)

## Tasks

- [ ] Decide how it should be behave
  - [ ] I dont see why any study has a min size ... shouldnt it just collapse all the way down?  Maybe this is related to trying to keep it at an optimised size for small screens?
  - [ ] If we DO have a min study size they should both obey it
- [ ] Implement
- [ ] Test

**Comment by JonRay15** [comment]
I never want to talk about this again
