### ISSUE TITLE
Review and finalise all words on the referrals page with legal

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5144]
## The Chore

The text is a bit rubbish currently ... and needs legal signoff. Write it with Dave.

## Tasks

- [ ] Test on the landing page before any codes are applied
- [ ] Text when you have created a code
- [ ] Text when you have applied a code

**Comment by JonRay15** [comment]
I'm taking this as approved by Dave ... or at least closer than what we have so lets do it and then do a final review.

**Comment by JonRay15** [comment]
Fully reviewed with @dalebennett1992 ... he's left some minor comments on the PR
