### ISSUE TITLE
Further tweaks to referee stats page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5155]
## The Chore

A few observations on this view 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/467ce213-f12c-438b-a25b-c148887e5ef8)

## Tasks

- [ ] Combined volume >> Combined set volume (last <windowLength> epochs)
- [ ] Volume to next tier (3) >> I dont know what this 3 is ... guess its <windowLength> ... I think just remove it
- [ ] Epochs to next tier (3) >> again dont know why the 3 is relevant.... remove it

**Comment by JonRay15** [comment]
Have split the last bit of this out into [this ticket](https://github.com/vegaprotocol/frontend-monorepo/issues/5203) and will close this as done.
