### ISSUE TITLE
Disconnected / no active programs state on Fees page is broken 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5164]
## The Chore

Currently it looks like this

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/5f6681a9-e486-4651-bb6c-a8c839c97549)

Or with connected wallet like this 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/fc90be48-fa48-469e-a708-900c106cd01c)

It should look like this 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/8f296ea1-4640-42b1-b67b-090bb49e2ab6)

## Tasks

- [ ] The bottom table needs to be called something like "Fees by market" since "liquidity fees doesnt make sense anymore
- [ ] The total fee after discount is showing as 0% even though I have no discounts .... it should be equal to the fee before discount
- [ ] Display no active programs in the 3rd and 4th tiles on the top row

**Comment by JonRay15** [comment]
This is now covered under https://github.com/vegaprotocol/frontend-monorepo/issues/5215
