### ISSUE TITLE
Fee estimate discount UX clarity

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5165]
## The Chore

The tooltip on the deal ticket is rounding fee values to 2DP and in some cases this is causing a precision issue

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/01cf94e3-80c6-4e33-b81c-025cc873a75b)

It is also now seemingly displaying the estimate as "0 ~ value" .... do we need the zero there?

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/0210f6f5-2f3b-45bd-8db9-f3629323095b)

## Tasks

- [x] Check the precision on the market params for infra and maker fees and the market param for LP fees and match these
- [x] Do not show trailing zeros though
- [x] INvestigate the 0 to estimate thing and let me know what you find

**Comment by JonRay15** [comment]
Fee estimates are all coming out halved 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/edc81994-d265-4266-b2c4-141568795d14)

Reopening

**Comment by JonRay15** [comment]
This is not a bug, the volume discount is being included in the infra / liquidity / maker estimates which is why they're lower than anticipated (50% lower in this case).

We are reviewing whether this implementation is ideal or not, but it is not a bug as such so will not patch urgently.  Leaving this here so people are aware.

**Comment by mattrussell36** [comment]
Seeing as the initial bugs here were fixed, I'm closing this in favour of this ticket which captures more information on the tooltip ux

https://github.com/vegaprotocol/frontend-monorepo/issues/5244
