### ISSUE TITLE
Improve handling when no current referral program

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5176]
## The Chore

Currently the handling for no active programs is a little flaky. 

It will let you try to create a code, and then the screen stays unchanged, it doesnt flip to some reduced version of the stats page, it just goes back to teling you you can ctreate a code. 

## Tasks

- [x] Add an extra check when someone creates a code to see if there is a program active.  
  - [x] If there is no program display an extra step in the modal to say "There is currently no referral program active, are you sure you want to create a code?"
  - [x] If they click yes, it should continue the flow as normal
- [x] Once they create the code the screen should change to the referrer stats page which should keep certain bits and replace others with a "No active programs" text
- [x] We should also change that text at the bottom a bit. We're not "sorry" ... :) ... change text to the below: 

There are currently no active referral programs. 
Check the [Governance App](https://governance.vega.xyz/proposals) to see if there are any proposals in progress and vote.
You can propose a new program via the [Docs](https://docs.vega.xyz/mainnet/tutorials/proposals/referral-program-proposal).

## Additional details / background info

Sketch below

<img width="703" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/578470a6-21a2-4ee0-ba35-365fa7a1be08">

**Comment by JonRay15** [comment]
@dalebennett1992 made a couple of comments on the PR but the rest of this looks good.
