### ISSUE TITLE
Block height intervals

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#5180]
## Story

As a trader
I want a block height interval for charts
So that I can aggregate the candles in a non time based scale

## Acceptance Criteria

- [ ] I can select block height from the interval list
- [ ] Candles chart updates to show candle data for a block

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
