### ISSUE TITLE
Snags on markets suspended by governance

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5188]
## The Chore

Markets suspended by governance have a couple of issues.

First; there is no banner .. I feel like these should have the banner as we have these for liquidity / price suspensions right?

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/56f8d3d7-4894-4703-a4bc-e6a8a17395e6)

Second, when the market is suspended your position disappears.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/25c7c121-943e-4c64-8b73-a23a54f92ddf)

It is presumably getting filtered out because if you click to show closed markets it appears

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/ff49dcc3-4872-40fe-aa3e-416c995f4df8)

## Tasks

- [ ] Add a banner, only if suspended by governance, I guess whatever banner we have for other price / liquidity related suspensions
- [ ] Follow whatever pattern we have in the text but I would assume it would mention the suspension and link to the governance proposal that suspended it.
- [ ] Filters on positions should only filter out settled / terminated markets .... not suspended ones.

**Comment by MadalinaRaicu** [comment]
We do not have a banner for markets that are suspended for Liquidity or Price Monitoring. All the info is in trading mode and status in the trade header. 
Most probably this is because we still want to allow users to place limit orders. 

I can change the logic for "Hide/Show closed markets" to filter out only settled/terminated markets and not the suspended ones.

**Comment by JonRay15** [comment]
Have agreed no bannr needed ... I was confused in my initial statement
