### ISSUE TITLE
Refactor tx decode / chain event contract call view

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#5189]
Do we need this JSON.parse and outputs.map ? It should be the same as `defaultAbiCoder.decode(["int256"], data)`

_Originally posted by @bglownia in https://github.com/vegaprotocol/frontend-monorepo/pull/5135#discussion_r1381611013_

This comment from @bglownia made me realise that this function isn't actually even wired up. I didn't finish Chain Event > Contract Call, the view that actually uses this function

# Tasks
- [x] Add tests for that result decoding  
- [x] Simplify result decode as per @bglownia's suggestion above
- [x] Add `ChainEventContractCall` component 
- [x] Update `ChainEvent` component to render Contract Call details & result
- [x] ~Make it not look like a confusing pile of random numbers and letters~

Current status:

<img width="1040" alt="Screenshot 2023-11-03 at 15 50 19" src="https://github.com/vegaprotocol/frontend-monorepo/assets/6678/1392b9a8-f38f-4a4a-8207-8f8911f846c3">
