### ISSUE TITLE
The validator penalties dont disntinguish between NULL and actually zero

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5191]
## The Chore

The validator scoring relies quite heavily on the rewardScore part of the epochs API. 

But if you are a candidate (pending) validator this part is null as below.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/1356ef63-d1ab-4169-b5cb-4d4491f88893)

This means the scores for Candidate validators are always misleading 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/182966f7-8bab-441e-8522-3fec79eb9bde)

And it means in the first epoch after promotion the scores for Standby validators are misleading
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/16b39cb1-9e37-46dc-b700-6c96156d1c14)

## Tasks

- [ ] For Candidate validators
  - [ ] Set total penalties to "-" as rewardScore will always be null so there is no validatorScore to use
  - [ ] Set overstaking penalty to  "-" because it requires the rawValidatorScore from rewardScore so will always be null
  - [ ] Performance penalty should be ok because it is taken from rankingScore in current epoch and this is never null

- [ ] For Standby validators 
  - [ ] If rewardScore is null then apply treatment as above
  - [ ] Else calculate scores as usual
