### ISSUE TITLE
Do not redirect to last market id if that market is not active

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#5193]
## The Chore

Its possible if you bookmark the home page and then don't use Vega for a while the last market you used will be used as the default market even if its settled or expired. This means you may be greeted with a market showing the 'market expired' banner or worse the 'market does not exist' state.

## Tasks

- [ ] When landing on the home route, check that the market is active before redirecting
- [ ] If market is active go to that market
- [ ] If market is inactive use top traded

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1699036552276329
