### ISSUE TITLE
Create a team

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#5194]
## Story

As a user
I want to understand the benefits of creating a team for my referral code 
So that I can decide whether to go ahead and do that as well, or if I'm happy with just a referral code

## Acceptance Criteria

- [x] From the competitions homepage there is a CTA to create a team and to compete as lone wolf
- [x] If I click Create Team I am taken to a new create team page
  - [x] I can set a team name
  - [x] I can set a team avatar (we might disable this in the short term until we agree a solution for pictures)
  - [x] I can set a team URL
  - [x] I can set the team type to public or private
  - [x] If I choose private a box opens which allows me to type a list of comma separated pubkeys (and I am given a tooltip or line of text telling me to do this)
- [x] This page should inherit the basic styling / background as the team profile
- [x] When I click create team a transaction is sent to core to `createTeam`
- [x] Once this is confirmed I am taken to my team profile page
- [x] If I select Lone Wolf I should be taken to the same screen but it shoudl be automatically set to private and the allow list should be greyed out and empty since no one can join

## Tasks

- [x] Explore and sketch
- [x] Team and stakeholder review
- [x] Visual Design
- [x] Team review
- [x] Etc.

#### Sketch 1 - Homepage

<img width="783" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/2fdf74cb-bea7-4fb5-9eba-d0df62596e36">

#### Sketch 2 - Create team

<img width="779" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/9a9d3c71-d028-4099-9978-a6666b01f7a7">

**Comment by JonRay15** [comment]
This still needs some work from @JonRay15 to define the flows / UX between these different methods of team / referral creation

**Comment by JonRay15** [comment]
Ignore the text on the sketch ... that wont be needed cos we'll go to team profile and you'll be able to share

**Comment by JonRay15** [comment]
We could in theory - rather than linking over the the referrals page - just show the referral tiers below here at this point.  Not sure if that feels like overloading this, open to ideas.
