### ISSUE TITLE
Disband my team

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#5195]
## Story

As a team creator
I want a way to disband my team
So that I can start a new one on this key

## Acceptance Criteria

- [ ] I can disband a team from the team view 
- [ ] There is a way to confirm I want to disband my team and I understand I need to confirm / reject in my wallet
- [ ] When my team has been disbanded, I can see I no longer have a team on the referral site, Console, in my wallet

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by JonRay15** [comment]
There is no way currently to disband a team so this is blocked .... and we need to deciide if we actually care about that fact.

**Comment by edd** [comment]
Not supported, as @JonRay15 said. It could be approximated, poorly.
