### ISSUE TITLE
Update team

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#5196]
## Story

As a team maker 
I want to update my team
So that it reflects our new name / logo 

## Acceptance Criteria

- [ ] If I am a creator of a team then when on the team profile I should be able to see an addtional button to "Edit Team" (sketch 1) 
- [ ] This button should take me to the Create Team screen with the fields prepopulated and the titles tweaked to indicate you are editing
- [ ] When the user presses Save Changes at the botton an `updateReferralSet` transaction should be sent to my wallet and I should be able to approve
- [ ] When I click confirm the transaction is sent to the network and I get a toast to acknowledge its success or failure

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

#### Sketch 1

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/2f21c1ce-4899-4784-8488-693a76a2c715)

#### Sketch 2

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/fac9de5a-8736-4143-9e9d-53425f4fe091)

**Comment by JonRay15** [comment]
I remember we said previously that it was odd that you stay on the update form.

Preferably it would take you straight back to the team profile imho....

**Comment by JonRay15** [comment]
Or it is acceptable to put a button here after you have saved that gives you the abiliy to go back to team profile
