### ISSUE TITLE
Create Competitions homepage

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#5197]
## Story

As a user
I want to see the leading teams in terms of trading volume and understand the discounts and rewards they are earning
So that I can get a better idea of the value of being a part of a team on Vega

## Acceptance Criteria

- [ ] I can see the list of active games right now on Vega 
- [ ] I can see the Team / Individual leaderboard 
- [ ] I can see my team card 
- [ ] I can see my individual profile card

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch
Miro https://miro.com/app/board/uXjVOs_PBKk=/?moveToWidget=3458764560265784550&cot=14

https://www.figma.com/file/SPSdqynG3Xk4RzBJ7NKpdi/Referrals?type=design&node-id=3166-5839&mode=design&t=EtkwjJMfyQiYEJm1-0

## Additional details / background info
Related #4404
