### ISSUE TITLE
Commission earned on referer stats should be over 30 days

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5203]
## The Chore

On referrer stats

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/744cef95-4304-49bf-b000-cd889d059e3b)

## Tasks

- [x] Confirm we want to use 30 epochs here
- [x] Change text to "Commission earned in qUSD (last 30 epochs)"
- [x] Check on the query on referralSetReferees ... ensure we're setting aggregationEpochs to 30 for the commission (but still using `windowLength` for the volume)
- [x] Add a tooltip over the 30 saying "Depending on data node retention you may not be able see the full 30 days"

**Comment by JonRay15** [comment]
Have agreed this with Lewis now so lets move on this
