### ISSUE TITLE
Adjustments to preview referral set view

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5221]
## The Chore

- [ ] Replace "You are joining" with "You are joining the group shown, but will not have access to benefits until you have completed at least `epochs to next tier` epochs
- [ ] On the apply code preview 
  - [ ] We show current tier NONE, we should be showing the tier of the **set**
  - [ ] Discount is showing 0, it should be showing the discount you can get once you access the tier

General comment on the referral page as a whole (agreed with Barney / Lewis)
- [ ] We need to flip the order of volume / referral discount tiers on both the referral page and fees page

<img width="1225" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/f2127a28-63c0-49d5-85dd-0ae07517458c">

## Tasks

- [ ] Make changes to referral page preview 
- [ ] Make changes to referral tiers order as above
- [ ] Make changes to referral and volume tiers on fees page as mentioned above
