### ISSUE TITLE
Manage AgGrid table state

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#5245]
## Story

As a user
I want to be able to reset or control AgGrid state
So that I can get back to the default state or better control table setup

## Acceptance Criteria

- [x] I can reset column state removing all applied filter, sort and columns rules
- [x] I can switch view to a settings view which provides a space for a reset table button

## Tasks

- [x] Verify there isn't a built in AgGrid UI to handle this
- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [x] Implementation
- [x] Testing (unit and/or e2e)
- [ ] Code review
- [x] QA review

## Additional details / background info

https://vegaprotocol.slack.com/archives/C037STCKMGC/p1699553640171639

Column and filter state from AgGrid gets persisted in local storage. For some actions, for example if you drag a column off the table, there is no way to reverse it and get that column back, so we need a way to reset table state or better, control it via some UI.

**Comment by mattrussell36** [comment]
New issue here: https://github.com/vegaprotocol/frontend-monorepo/issues/5394
