### ISSUE TITLE
Transfer fee changes

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#5334]
## The Chore

https://github.com/vegaprotocol/vega/pull/9983 was recently merged to accommodate changes to transfer fees. We need to update the transfer fee UI to use the new endpoints to provide more accurate estimations

## Tasks
- [ ] Check if vested account transfer fee will always be 0. If so remove fees information when doing a transfer from vested account
- [ ] Remove hard coded calculation on the client
- [ ] Connect to the new core endpoints covered [here](https://github.com/vegaprotocol/vega/pull/9983) that will expose the fees
- [ ] Dev
- [ ] Test

**Comment by JonRay15** [comment]
Changes are merged but not in stagnet yet .. once they are we need to do this asap, and we need a good way of deploying it preferably in a way that doesnt mean we need to sync up with Core release in mid-Dec.

**Comment by JonRay15** [comment]
While core change is merged it did not make it into the patch release, and now the "Palazzo I" release is not due until January. 

Therefore this can be pushed out.  We can pick up once we know we have a new Core version into Stagnet that includes these changes

**Comment by mattrussell36** [comment]
Closing as dupe of https://github.com/vegaprotocol/frontend-monorepo/issues/5554
