### ISSUE TITLE
Restore to defaults from settings

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#5343]
## Story

As a user
I want to clear all stored state
So that I can easily troubleshoot issues with persisted settings

## Acceptance Criteria

- [x] I can click a button in the settings sidebar
- [x] I can see a warning message that says you will lose all persisted settings and be logged out
- [x] After I've clicked all localstorage should be cleared (table state, wallet state etc)

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
