### ISSUE TITLE
Re-enable close position button in mainnet console

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#5351]
## Tasks
- [ ] Revert: https://github.com/vegaprotocol/frontend-monorepo/pull/5350
- [ ] Update size of close position transaction to align with core by halving the amount we use (see thread)
- [ ] Only enable on testnet

## Additional information

About the original issue:
https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1701076962684339

About re-enabling:
https://vegaprotocol.slack.com/archives/C8WS7M50E/p1701341967722039
