### ISSUE TITLE
Review the tooltips on the liquidity view

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5365]
## The Chore

A few of these are outdated or not that clear.  Needs a review.

## Tasks

- [x] Write new ones 
- [x] Get Candida to review
- [x] Add them to the code
- [ ] Swap `Adjusted stake` and `Share` columns

## Additional details / background info

Adjusted stake 
> The effective stake of the liquidity provider, adjusted for length of commitment and impact on equity like share.

Live liquidity score
> The liquidity score of the provider, used to determine allocation of fees to the best performing LPs.  Posting volume closer to the mid on both sides of the book will improve this score.

Last time on book 
> Fraction of time on the book at the end of the last epoch.

Last fee penalty
> Penalty applied on the fees a liquidity provider collected in the last epoch. This number increases if an LP did not meet the SLA, or if they met it but other LPs outscored them in the previous epoch.

Last bond penalty (do we need to keep given this has been set to zero now?)
> Penalty applied on a provider's bond penalty at the end of the last epoch. This percentage increased if an LP: had a shortfall and their bond needs to be used to cover it, did not meet the SLA, and/or reduced their commitment to the point that the market was below its target stake.

**Comment by JonRay15** [comment]
This is ready to go @MadalinaRaicu so whenever you're ready
