### ISSUE TITLE
Add error boundaries

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#5389]
## The Chore

Add error boundaries to prevent app crashes

## Tasks
Add error boundaries with logging for the following:
- [ ] All panes in the trade grid
- [ ] All panes in the portfolio page
- [ ] Sidebar components
- [ ] Standalone pages, referrals, fees, rewards
