### ISSUE TITLE
Review logger lib and usage

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#5395]
## The Chore

Review logger implementation and usage

## Tasks

- [ ] Ensure not all events are sent to sentry, decide on which log levels should be captured
  - Initial suggestion: call captureMessage only for log and warning, use captureException for error, critical and fatal
- [ ] Change boolean silent mode to instead use the log level, libraries like [loglevel](https://www.npmjs.com/package/loglevel) make this pretty easy
- [ ] Review current usage of logging module. In some places its being called within a render function which results in too much logging
- [ ] Add additional logging to core flows: connect, disconnect, deposit, withdraw, transfer, and deal ticket
