### ISSUE TITLE
Add environment themed icons to browser tabs

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5403]
## The Chore

All the icons are black and its annoying

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/734cbe43-ee00-4c6c-9297-2db60b9e9f40)

## Tasks

- [ ] Fairground Console should have a yellow V
- [ ] Fairground Governnace should have a yellow V
- [ ] Fairground Explorer should have a yellow V
- [ ] Stagnet Console should have some other  V
- [ ] Stagnet Governnace should have a some other V
- [ ] Stagnet Explorer should have a some other V
- [ ] Update the navbar icon on stagnet for trading to use a similarly styled bg as testnet, ensure its the same base color as the favicon

I dont have another colour icon for stag ... just make somethign up .. we're the only ones that use it ... its just for our ease.

**Comment by JonRay15** [comment]
Will be more important now that we have network switcher

**Comment by mattrussell36** [comment]
I think it would be nice to use the blue-ish purple-ish color for stagnet

**Comment by bwallacee** [comment]
The browser wallet uses these colours for each environment:
**Mainnet:** 
`
color: '#000000',
secondaryColor: '#FFFFFF',
`
**Testnet:**
`
color: '#D7FB50',
secondaryColor: '#000000',
`
**Devnet:**
`color: '#00F780',
  secondaryColor: '#FFFFFF',`
 
 **Stagnet:**
`color: '#0075FF',
  secondaryColor: '#FFFFFF',`
  
  **Mirror:**
`color: '#FF077F',
  secondaryColor: '#FFFFFF',`
  
 **Validator Testnet:**
`color: '#8028FF',
  secondaryColor: '#FFFFFF',`
