### ISSUE TITLE
Tooltip change on fills table to clarify discounts

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5416]
## The Chore

Two small changes

## Tasks

- [x] If Taker change from "Fees to be paid by the taker" to "Fees to be paid by the taker; discounts are already applied"
- [x] If Maker change from "The maker will receive the maker fee" to "Fee revenue to be received by the maker, takers' fee discounts already applied"
- [x] Then for second sentence if Maker:
  - [x] If continuous "During continuous trading the maker pays no infrastructure and liquidity fees"
  - [x] If in auction "During auction, the maker pays half the infrastructure and liquidity fees"
- [x] Increase the timeout on these tooltips, they disappear before you can read it all

**Comment by mattrussell36** [comment]
@candida-d could review these text changes

**Comment by candida-d** [comment]
I've been thinking this over, and I am not sure that one column that covers both "fees paid by the user" and "fee revenue received by the user" is enough to make this easy to understand. If you're scanning to see what you've earned or paid, you'd have to read the tooltips to know. 

Had a chat with @MadalinaRaicu about this and we discussed having 2 columns, 1 for fees you've paid and another for fee revenue you've received.

**Comment by MadalinaRaicu** [comment]
@candida-d @JonRay15 until I get an answer for the last comment I am raising this PR that addresses the description on this ticket https://github.com/vegaprotocol/frontend-monorepo/pull/5512

**Comment by MadalinaRaicu** [comment]
Note: we don't know who's the taker/the maker in auction, so I rephrased 
`During auction, the maker pays half the infrastructure and liquidity fees` to 
`During auction, half the infrastructure and liquidity fees will be paid`
