### ISSUE TITLE
Console  Mobile Review Issues found REFERRALS

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5427]
1. "Landing" page of referrals uses excessive size font, margins on the left and the right could be improved.
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/a014b6af-5228-41fb-a9bb-822de3e09bf9)
2. ~~Do we have Referrals title in the header bar ?~~
3. Create/ apply code section doesn't use space very well.
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/726a22c7-b73f-4e3e-8ef9-258a329c6bb4)

## Tasks

- [x] Reduce padding of page container
- [x] Reduce font size of title
- [ ] TBD reduce font size of sub titles and text
- [x] Reduce x padding of apply code/create code buttons
- [x] Reduce padding between page title and apply/create codes
- [x] Ensure that the page CTAs have moved up sufficiently so content is shown
- [ ] Review fees/rewards pages to ensure page containers are shared if possible, so we get consistent mobile spacing
