### ISSUE TITLE
Console Mobile Review Issues found FEES and REWARDS

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5428]
FEES:
1. ~~Should we move the title into the header:~~
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/a1ab97e0-962f-4815-acdc-80cd0e068a1b)
2. Could we remove some of the shaded card padding so we can utilise more screen width

REWARDS:
1. ~~Should we move the title into the header.~~
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/359c201f-c703-4b72-bf09-192e55e9d786)
2. text overlap:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/f01a680e-a865-4ddd-a545-56ccad189a8d)

## Tasks

- [x] Overflowing/line breaks in rewards history table
- [x] Adjust cards to not show on mobile. We'll want to ensure we are using the same card component as the referrals page
- [x] Fees page adjust volume discount tiers and referral discount tiers to use the same component as on the referrals page
  - [ ] Ensure that content fits within page container (cards should be removed)
- [x] Add 'your tier' lozenge to the tiers tables (as above)
- [x] Fees by market table.
  - Disable column re-arranging
  - Pin the market code to the left.
  - Move liquidity fee and total to the left so the less important figures (maker/infra) will have to be horizontally scrolled to
  - Review tooltips. Are we missing any? Does it work on touch device
- [x] Rewards history table
  - Pin market code to the left
  - Mobile layout for epoch filter and 'earned by me' filter. Stack where necessary
  - Review tooltips. Are we missing any? Does it work on touch device
