### ISSUE TITLE
Console Mobile Review Issues found MARKET SWITCHER

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5429]
1. Market type pills not aligned:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/3b716791-6ea8-4584-a3f8-696641806a08)
2. Search box alignment:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/f44e9a0f-9724-4632-a4cd-ff804c79da3b)
3. Can't see price asset due to width constraints: ( Should we lower Market name font, reduce decimals for volume, Remove the sparkline, change the pill location?
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/db0aac4f-77bb-4d97-81b8-0b990ab94faa)
4. scroll on market switcher scrolls the background
5. Market can push the nav items off
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/6803987/c4b2a9e3-d765-4fc5-9487-d40621788902)

https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/9deb13bd-23d9-4234-9318-fdcced08ef45

## Tasks

- [x] Alignment of values needs fixing
- [x] Make instrument code text-xs
- [x] Make product pill styles aligned with positions table (no pill just uppercase de-emphasized text)
- [x] Dont show sparkline on smallest breakpoint
  - Consider dropping product type underneath code if we still need space
- [x] Disable background scrolling perhaps this might just be ios bounce behaviour
- [ ] In the navbar market text, long instrument code can push the main navigation off screen
  - [ ] Reduce font size
  - [ ] Add max width/ellipsis
- [ ] Show up chevron when switcher is open (both mobile and desktop)
