### ISSUE TITLE
Console Mobile Review Issues found

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5430]
1. 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/7dfad8e9-f581-452d-b3dd-6ae1b3a63fc1)
text overlap

2. Should we only use one indicator on mobile?
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/53c6f2c1-309c-462a-810a-2372133fd8c9)

3. not obvious i need to scroll this to see funding etc.
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/33e07a89-153f-4e48-869c-ea04ee6de90e)

4. Unable to interact with funding chart: ( There is no ability to hover, so i can't get any number specifics etc)
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/650f818f-2fbf-48ae-bb7d-7d7a56209c11)

5. 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/5397449b-534f-43d3-a881-7450e0428477)

can we move the cog so that we can a row in space?
6. Maybe extreme, But I wonder if we remove the ability to show and hide closed markets in mobile. Remoev the cog for reset columns and make it so you can't edit the columns (or move this cog into settings). So that we can gain another row of space
7. Another more dramatic change:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/191de50c-795f-4265-b4dd-a20861175906)
Could we combine these two rows (again to give us more vertical space.
8. If there is space in the orderbook can we bump up the positions table:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/5041f427-ae3b-40f5-8113-d810d74585b7)
9. Simmilar to above with this cog.
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/76e3c44e-bf85-4074-bdab-0acb83237810)
10. Should we reduce the space for trades to gain space in positions table
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/6244f298-48e9-46b5-9a3f-8f24d5d5f837)
11. Same as above but for liquidity
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/dc504bf1-ea3d-4df4-87cd-88eab8d11ac1)
12. same as above but for funding payments:
![Uploading image.png…]()

13. Remove or collapse pane context buttons (for example the interval on the chart or the 'show closed markets' button on positions) into a dropdown
14. Make the two pane layout resizable using allotment
15. Possibly move the market selector back to the main top nav. We will need to consider where and how market stats are displayed as we will then have quite an empty section there

## Tasks

- [ ] Add ellipsis for date/ohlc data
- [ ] For perps move index and funding countdown to the 2nd and 3rd spots in the trade header
- [ ] Make funding payments chart show price on touch (normally this is on hover)

**Comment by mattrussell36** [comment]
Pushing this out as we have #5952 somewhat superseding this
