### ISSUE TITLE
Console Mobile Review Issues found OTHER

### ISSUE THREAD

**Issue by bwallacee** [vegaprotocol/frontend-monorepo#5433]
1. Data grids in general need re thinking. (Liquidity table: columns are too small to be able to resize etc)
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/745f514d-4abd-41db-804f-eeb0459b2419)

2. It takes multiple taps in order to open the row actions
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/c804a989-d96c-4ffd-8a84-b8c9a6285c98)
3. Asset details padding (left hand side):
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/8839dd6b-e0ac-4a9c-81d0-4c3a6324cc29)
4.Connect to Eth wallet performance is very bad: 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/50e51cc8-04ad-4f0b-a122-c3476eede911)
5. Asset dropdown padding:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/a3c808d9-7570-4262-9486-e48ba4593f7f)
6. Toast location seems a bit pointless:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/97c2655f-4241-42fe-812b-a62ab63b5550)
7. Should propose a new market open in a new tab: 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/0afbb60c-7b5a-4b74-a16c-5217fde04ccb)
8. Tooltips on hover obviously dont work
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/a0eeaf06-1627-4ee9-af2d-4a36e017a693)
9. No hover so there is no dismiss all etc for toasts. ( the X could be bigger and easier to click)
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/7c0e33b6-9a7a-4dae-866d-a0aa6573d67e)
10. Its not obvious how to get back to the charts etc (may just me being dumb)
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/eb467fa4-847a-454c-a2aa-f5d576ef0645)

## Tasks

- [x] Fix asset details padding
- [x] Fix toast drop shadow when not in the bottom right (toast location ui is fine)
- [ ] Make propose new market open in a new tab
- [ ] Make tooltip component work on touch devices (on touch)
- [ ] Ensure dismiss all toasts works on touch
  - Perhaps detect if its a touch device and always show the dismiss all button if there are more than one toast
- [ ] Give the sidebar components an obvious back/close button
