### ISSUE TITLE
Support new connection model for Browser Wallet API

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5443]
## The Chore

In addition to requirement covered in #4717 the Browser wallet will soon emit an event to say that iit has been disconnected. 

Apps need to respond to this properly.

## Tasks

- [x] Change `InjectedConnector` to support new model
- [x] Add event handling to the `InjectedConnector`
- [x] Notify user that the wallet has been disconnected (Console)
- [x] Notify user that the wallet has been disconnected (Governance)
- [x] Tweak the `is alive timeout` (to 1s) so it doesn't appear as disconnected when a bit lagged behind (happened on gov 🤷 )
- [ ] Test
