### ISSUE TITLE
Add filtering to the proposals page and support URL based filtering

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5452]
Blocked by #2990 

## The Chore

This would help us to support users in Console that need to see any proposals impacting a single market for instance.

## Tasks

- [x] Proposal page should accept a query string eg `/proposals?type=UpdateMarket&marketId=xyz&votePubkey=123` so that a link can be shared or available on other apps
- [x] Add UI to set type
- [ ] Should include:
  - [x] Ability to filter by market ID on market updates
    - There is no market Id filter this will need to be done client side
  - [x] Type
  - [x] Un-voted vs voted (votepubKey)

**Comment by JonRay15** [comment]
Looks good on fairground.
