### ISSUE TITLE
Competitions home page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5485]
## Story

As a user
I want a homepage where I can see all info about comps and teams
So that I can find and join a team and compete in games

## Acceptance Criteria

- [x] I can view the homepage when I am NOT part of a team as per figma 2
- [x] There are CTAs to (details behind these to follow):
  - [x] Create a team
  - [x] Join a team
  - [x] Play as a lone wolf 
- [x] A grid is displayed showing the active games (these are to be reused directly from the work done by @MadalinaRaicu over [here](https://github.com/vegaprotocol/frontend-monorepo/issues/4532).
- [x] A leaderboard is displayed showing the top 10 teams as sorted by total rewards earned (full logic for defining this table is on #5487)  

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

<img width="435" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/a18219ba-945e-4385-9057-ffb99640bdac">

## Additional details / background info

Figma here: https://www.figma.com/file/SPSdqynG3Xk4RzBJ7NKpdi/Competitions-%26-Referrals?type=design&node-id=3166-5839&mode=design&t=lti5mow1FpKvrv78-0

**Comment by JonRay15** [comment]
Marking this as done since all ACs are covered and any additional work / snags has been covered in other tickets.
