### ISSUE TITLE
Team profile page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5486]
## The Chore

Create team profile page so that users can view details about a given team.

## Acceptance Criteria

- [x] There is a page as below to see a team profile
- [x] The page handles states when the user is
  - [x] In the team
  - [x] Not in the team
- [ ] The page displays the following static info, which should all be available on [this api](https://github.com/vegaprotocol/vega/issues/9980)
  - [x] name
  - [x] teamURL
  - [x] avatarURL
  - [ ] createdAt
  - [ ] createdAtEpoch
  - [ ] closed
- [ ] The page displays the following stats from the same API (once enhanced) and these should be displayed over the time horizone given by `aggregationEpochs` which we can set on the front end .... suggested starting with 7 days.
  - [x] totalReward (not PNL as is shown in figma)    
  - [ ] totalVolume
  - [x] totalGamesPlayed
  - [x] Number of members
- [ ] There is a table to show the game history, which contains the following info taken from the [game details API](https://github.com/vegaprotocol/vega/issues/9257)
  - [x] Rank 
  - [x] Date
  - [x] Type (ie. reward type)
  - [x] Amount earned
  - [x] Number of teams participating
  - [ ] Game status
- [x] The following are calculated from that game details API and shown in the header:
  - [x] Favourite game - taken by taking the games played over the past `aggregationEpochs` and displaying the reward type most earned
  - [x] Form - taken by taking the last 5 games on the API and displaying rank for each with most recent on the right
- [x] There is a table (toggled with the above) to show the following info about team members taken from [this api](https://github.com/vegaprotocol/vega/issues/9980) again summed over `aggregationEpochs`
  - [x] Pubkey
  - [x] Date joined
  - [x] Games played
  - [x] Rewards earned
- [ ] There should be a toggle to show the referral benefits associated to this team
  - [ ] If the user is part of that referral set already it should show the information in sketch 2
  - [ ] If the user is not part of a referral set already it should show the information in sketch 2
  - [ ] If the user is already part of ANOTHER referral set then they cannot leave that set so we should not preview the set and should show a message instead as shown in sketch 3 
- [ ] The profile page should have a share button on it somewhere which copies the URL - sketch 5

#### Sketch 1 Team profile

<img width="670" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/7c5f2b85-207c-445c-8061-7a9752451ce9">

#### Sketch 2 Referral benefit: 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/cf9f2254-131c-4939-88ad-be34c6684af3)

#### Sketch 3 Already in referral set 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/72dca3f4-dccb-4400-857e-599a54b47f44)

#### Sketch 4 Joined

<img width="674" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/79a95b0e-c621-49a6-a4a3-23a4a6de4880">

#### Sketch 5 - referral link (It could be here, or anywhere really ... just find a home)

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/21d23632-0128-45df-9854-bf08531bf37d)

or this

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/267feb94-807e-497f-b857-52ffdea53ede)

## Additional details / background info

Figma here: https://www.figma.com/file/SPSdqynG3Xk4RzBJ7NKpdi/Competitions-%26-Referrals?type=design&node-id=3166-5839&mode=design&t=lti5mow1FpKvrv78-0

**Comment by JonRay15** [comment]
Missing ACs have been moved onto 
https://github.com/vegaprotocol/frontend-monorepo/issues/5744
https://github.com/vegaprotocol/frontend-monorepo/issues/5745
https://github.com/vegaprotocol/frontend-monorepo/issues/5746

Marking this as closed.
