### ISSUE TITLE
Find team flow

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5487]
## Story

As a user
I want to be able to find and join a team
So that I can play in games

## Acceptance Criteria

- [x] There is a CTA on the homepage to launch "Join Team" (see #5485)
- [x] This CTA takes me to the page below
- [ ] There is a table based on data from [this API](https://github.com/vegaprotocol/vega/issues/9980) which displays:
  - [x] Team name
  - [x] Team avatar
  - [x] Rewards earned
  - [x] Games played
  - [ ] Team members
  - [x] Status (open / closed)
  - [ ] Total volume 
- [x] The list should be sorted by default by total rewards
- [ ] It should be possible to sort the columns using standard agGrid sorting
- [x] There should be a search box in the top right that supports basic text search

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

<img width="723" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/fd824275-ea5f-482c-abd7-d93067a42c0d">

## Additional details / background info

Figma here: https://www.figma.com/file/SPSdqynG3Xk4RzBJ7NKpdi/Competitions-%26-Referrals?type=design&node-id=3166-5839&mode=design&t=lti5mow1FpKvrv78-0

**Comment by asiaznik** [comment]
There's no num of members in the teams API and querying referees of all teams is not the best scenario here as it would basically explode 💥

**Comment by bwallacee** [comment]
Missing volume data but we have a ticket to track: https://github.com/vegaprotocol/frontend-monorepo/issues/5725
