### ISSUE TITLE
Add team card to competitions home page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5488]
## The Chore

The homepage should show a team card / banner providing the highlights of your team

## Tasks

- [ ] Add a team card as shown in diagram
- [ ] The information on the card is all taken from the team profile and has been defined [here](https://github.com/vegaprotocol/frontend-monorepo/issues/5486)
- [ ] I can still see the other CTAs to the right but smaller
- [ ] If I created the team they should be greyed out with a tooltip indicating I am the creator of a team and therefore cannot leave it... ever

#### Main card

<img width="966" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/edf93710-7fec-48a1-b330-ab8181eff954">

### De-empahsised CTAs to the right

<img width="533" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/6677fb0b-509d-4872-880b-10ec6f8d0844">

## Additional details / background info

Figma here: https://www.figma.com/file/SPSdqynG3Xk4RzBJ7NKpdi/Competitions-%26-Referrals?type=design&node-id=3166-5839&mode=design&t=lti5mow1FpKvrv78-0

**Comment by JonRay15** [comment]
An alternative layout to this would be to show the team banner as full width rather than stacked in the card .... then you can just show the other cards beneath it as usual.

**Comment by JonRay15** [comment]
I think we're agreeing the full width banner is nicer here 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/e563973e-19f9-412e-b786-afbc077b1843)
