### ISSUE TITLE
EPIC: Mobile enhancements 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5508]
## Tasks

- [ ] Define high level requirements
- [ ] Create basic mockups
- [ ] Update "API Requirements" in core spec
- [ ] Update "User-Interface Spec" in relevant front end repo
- [ ] Create detailed user stories using normal template

## High Level Requirements

- [ ] Make mobile really good

## Linked User Stories

- #5427 
- #5428 
- #5429 
- #5430 
- #5433
