### ISSUE TITLE
Add an estimate of gas fee's for withdrawals when releasing funds

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#5510]
## Story

So when you prepare to withdraw and release funds from Vega you will not know the gas cost until your funds are ready for withdrawal and at that point you can't change your mind.
We have had users trying to withdraw 25 USD but at the time they realised gas fee's were so high that it basically cost them 25 USD to withdraw it was too late, so now they leave them at pending.

Would be good to give an estimate of the fee so that someone does not try to withdraw a tiny amount that does not end up being financially viable.

<img width="322" alt="Screenshot 2023-12-18 at 11 21 11" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/230e218e-9e03-4e61-a769-da3091ce5568">
<img width="329" alt="Screenshot 2023-12-18 at 11 15 38" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/a462310d-d039-4ab6-a8a0-0033cf3aacb1">

## Tasks

- [x] Add the gas estimate to the table above with the linits / delays etc
- [x] If the cost of gas is "high" show a warning
  - [ ] ~~Ideally we could look at historic withdrawals and compare to an average and~~ show it as green / amber / red relative to this
  - [x] An easier solution might be to just compare the gas cost to the size of your withdrawal, if your're paying more in gas than you're withdrawing ~~that could be a warning~~
  - [ ] ~~Or we could simply look at historic data and set some thresholds manually, that would be the easiest (LETS DO THIS cos its easy)~~

## Current implementation:

 It compares the gas fee to the withdrawal amount and colours the gas fee estimation:
   - red - if the amount is lower than the base gas fee
   - amber - if the amount is lower than the maximum gas fee
   - white/black - otherwise

## Additional notes

Check ethers methods and / or metamask API to have a look at this stuff.
