### ISSUE TITLE
Isolated / cross margin mode selector

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5523]
## Story

As a user
I want to be able to toggl between cross and isolated margin mode
So that I can make use of the new isolated margin feature and understand the implications on my general account balances

## Acceptance Criteria

- [x] I can set my margin mode on the deal ticket from cross / isolated
- [x] When I set my margin mode there is a pop up which:
  - [x] If setting to cross explains what this means and asks me to confirm
  - [x] If setting to isolated explains what this means and asks me to set my leverage level on a slider
- [x] When I click confirm, a [transaction](https://github.com/vegaprotocol/vega/blob/develop/protos/sources/vega/commands/v1/commands.proto#L111-L126) is sent to Core to set my margin mode
- [ ] When the transaction is successful I am notified of the success in a toast and my mode switches on the ticket (currently this cant be done because the API is not working)
- [ ] If I have never set the margin mode I am blocked from submitting a deal ticket and am notified that I must set the margin mode before placing an order

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

#### https://miro.com/app/board/uXjVOs_PBKk=/

<img width="1268" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/c3d1dc54-55c2-42b2-bc8c-a230055eb9c5">

## Additional details / background info

Core changes:

A new margin mode API will provide details on each market for the current margin mode if set, as well as the max leverage available on that market: https://github.com/vegaprotocol/vega/issues/10275
