### ISSUE TITLE
Support isolated margin the deal ticket

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5524]
## The Chore

In theory not much changes here ... but just make sure that the API calls to estimatePosition still work and the deal ticket is still happy, and there are some wording changes.

## Tasks

- [x] We will need to provide new variables to our `estimatePosition` query from the deal ticket 
  - `averageEntryPrice` added
  - `marginAccountBalance` added 
  - `generalAccountBalance` added
  - `orderMarginAccountBalance` added
  - `marginMode` added
  - `marginFactor` added 
  - `includeCollateralIncreaseInAvailableCollateral` added
  - `collateralAvailalbe` removed
- [x] We will need to ensure we still get back the right values and nothing falls over (currently I dont think we expect the response to change)
- [ ] We should change some of the words as they dont really make sense for isolated mode and we actually decided the other day that they are a little redundant in cross anyway (see thread extract below), I suggest we change it to only include :
  - [x] Current margin allocation
    - [x] For cross this is simply margin account balance
    - [ ] For isolated we shoud show both margin account balance and the new order margin account balance (which simply shows the margin set aside for orders until they trade and become your regular margin)
  - [ ] Total collateral available (this should be  the balance of your general account imo, I dont see why we do margin account - maintenance level here currently?  Maybe someone can advise?)
  - [ ] New margin required (is taken from the estimatePosition API just as currently but with margin factor / mode inputs)
  - [ ] Projected margin (if we want consistency we can show for both, but in isolated it will always equal new margin required)
  - [ ] LIquidaition (unchanged for both)

### Proposed Isolated Margin words
- Current position margin
- Current order margin
- Total collateral available
- New margin required
- Liquidation

### Proposed cross margin words
- Current margin
- Total collateral available
- New margin required
- Projected margin
- Liquidation

### Current deal ticket words

<img width="288" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/152c4aa8-fb66-4825-811a-bda59733e9ff">

### Thread on slack

Jonathan Ray
  [6 days ago](https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1702468293085649?thread_ts=1702406306.677829&cid=CAHA5EX0F)
in terms of what is needed, I agree I've looked at this before and thought some of it was redundant...
Logically I need to know:
Current margin allocated
Total available money
New margin required
Margin after order

Bart
  [6 days ago](https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1702474633421449?thread_ts=1702406306.677829&cid=CAHA5EX0F)
For margin estimation we use EstimatePosition API.
We use openVolume from party positions, for orders we get list of remaining orders and add extra order with values from deal ticket, collateralAvailable is sum of general account and margin account balance
To show values in deal ticket we use values from EstimatePositon, current party margins (party.marginsConnection) and accounts balances (general and margin)
Margin required is estimatedMargin.initialLevel - currentMargins.initialLevel
Total margin available is  general account balance + margin account balance - currentMargins.maintenanceLevel
Deduction from collateral is estimatedMargin.initialLevel - margin account balance
Current margin allocation is margin account balance
Projected margin is  estimatedMargin.initialLevel

Matt
[Jan 2](https://vegaprotocol.slack.com/archives/C02KVKMAE82/p1703697277339689)
The estimatePosition query now requires averageEntryPrice as an argument. We'll need to do some additional calculation to get an accurate AEP value and therefore an accurate liquidation price and margin estimate. There are two main options:

1. Calculate AEP in its entirety using the current position AEP and the hypothetical AEP of unfilled orders and the order armed in the deal ticket.
2. Calculate a more crude estimate. For market orders use the best bid/offer and assume the whole order will trade at that price. For limit orders use the limit price

**Comment by bglownia** [comment]
Current implementation of margin detials:

`estimatedMargin = estimated initialLevel + estimated orderMarginLevel`
`currentMargin = current initialLevel + current orderMarginLevel`
`totalMarginAccountBalance = marginAccountBalance + orderMarginAccountBalance`
`totalBalance = generalAccountBalance + totalMarginAccountBalance`


Margin required `estimatedMargin - currentMargin`
-  Total margin available `totalBalance - current maintenanceLevel`
-  Deduction from collateral `estimatedMargin - totalMarginAccountBalance` (shown only if > 0)
-  Current margin allocation  `totalMarginAccountBalance`

Projected margin `estimatedMargin` (shown only when totalMarginAccountBalance > 0, otherwise it will show same value as "Margin required")

In new API there is also availabe collateralIncreaseEstimate which we are using in margin mode selector #5567
