### ISSUE TITLE
Support isolated margin in the position table

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5525]
## Story

As a user
I want to see details of my isolated margin positions
So that I understand how this differs to cross margin

## Acceptance Criteria

- [x] There is a lozenge shown in the margin column indicating whether I am in isolated or cross mode
- [x] Any calculations on margin, liquidation price etc need to now exclude the general account since this will not be used (How do we confirm we have covered all the changes here? Who understands these calcs?)
- [x] On hover there is a chart illustrating the margin situation 
  - [x] In isolated this will show
    - [x] The total margin allocated as one bar including maintenance & initial margin
    - [x] A line showing the maintenance margin and therefore liquidation
    - [x] The liquidation price
    - [x] A seperate bar for the order margin which is a new account type and only exists while a user has open orders (and will be converted to normal margin if those orders trade)
  - [x] In cross this will show
    - [x] The total margin, maintenance level, and liquidation price as above
    - [x] An additional bar showing the general account balance that can be used to top of your position

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

### https://miro.com/app/board/uXjVOs_PBKk=/

<img width="1096" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/c72e1907-fe5d-4423-9c71-fb25e8c66de1">

## Additional details / background info

These changes are related to those discussed on 
- #5118
