### ISSUE TITLE
Smooth reward redemption flow

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5533]
## The Chore

From the reward screen it is slightly janky to pull out your rewards.  Suggest the following.

## Tasks

- [x] Add tooltip to REDEEM saying "Click to move all vested rewards for this key into its general account" 
- [x] REDEEM button should send a TX to the wallet immediately 
- [x] The TX shoudl assume all VESTED balance to be redeemed
- [x] The TX shoudl assume all are sent to the GENERAL account for the same key
- [x] There is no fee
- [x] The values on your reward card should update live after this TX - no need to refresh your reward page

**Comment by mattrussell36** [comment]
@candida-d based on the changes above, what do you think would be a nice message about the transferring to another key risks

**Comment by candida-d** [comment]
@mattrussell36 I like JR's suggestion above, particularly adding the detail about redeeming. You could save some retail space and write "If you are unsure" instead of "If you are at all unsure", I think the point still stands in either phrasing. 

For the risk of transferring to a different key, how about: "This Vega key you're transferring to is not in your wallet. If you proceed, the transfer cannot be reversed."

**Comment by JonRay15** [comment]
Bumping this up because in the post-sidebar world this is even jankier than it was.
