### ISSUE TITLE
Rewards history UX tweaks

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5534]
## The Chore

The reward history table currently sums up rewards over a range specifed in the selectir.  This is sort of nice but sort of not.... suggestions

## Tasks

- [ ] Add a toggle for "show details" vs "show summary" 
  - [ ] In show detail mode we want to see the epoch breakdown, so could 
    - [ ] Just duplicate the entire grid for each epoch and show a header, and allow paging between them, including moving to a specific epoch if the user wants to
    - [ ] Add the epoch to the table and group them up
    - [ ] Add the epoch to the table and just sort them 
  - [ ] In show summary mode follow existing behaviour
- [ ] You cannot currently type an number into the TO selector so if you want to move that a long way you have to click many times
- [ ] There's also some glitching when you type

**Look at options during implementation and see what we can do.**

## Additional details / background info

Something more similar to the governance one 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/f0d8c4d2-20a4-46b2-9181-79786f132556)

**Comment by mattrussell36** [comment]
@JonRay15 can we get a few more details or a quick sketch of how you see this working
