### ISSUE TITLE
EPIC: Explain pending balances

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#554]
## Story 

As a user 
I want to see an accurate balance including for "pending" associations given I have associated some tokens and vega has not seen these yet
So that I have a clear picture of how much I have where

## TODO
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2056
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2057
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/2058

## Background 

Currently there are some [designs](https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Design-system?node-id=734%3A47721) in progress.

#### Linked issues to be consolidated or migrated to the mono-repo:
- [tickets in old repo](https://github.com/vegaprotocol/token-frontend/issues?q=is%3Aissue+is%3Aopen+) e.g.
- [Clarify amounts in the sidebar when transactions are pending](https://github.com/vegaprotocol/token-frontend/issues/1051)
- [supporting some less mainstream scenarios](https://github.com/vegaprotocol/token-frontend/issues/1015)
- [testing](https://vegaprotocol.slack.com/archives/C03CJFX2F5G/p1654793512004069)

#### Next steps:
1. a time boxed snagging session, 
or 
2. I can schedule some time to complete the designs (addressing open tickets that are design issues)  and adding documentation that helps write test cases. 

From one of these actions we can start to define the scope of what we can do for pre/post enabled trading

**Comment by campbellssource** [comment]
This ticket could/should be done at the same time https://github.com/vegaprotocol/frontend-monorepo/issues/594

**Comment by daunatv** [comment]
[On the staking page](https://token.fairground.wtf/staking/disassociate) I get a bit confused about the associated tokens, it gives me mixed info, on the Ethereum key  associated with vega wallet it indicates  the address as having 1 Vega associated,
In the area where I can Disassociate and press max (not pushing the button to dissaociate) it shows me 1 Vega that can be dissacociated, but on the Vega wallet (down right) it says 0 Vega associated.

<img width="500" alt="Screenshot 2022-08-09 at 09 29 22" src="https://user-images.githubusercontent.com/100769129/183603820-163e46dd-f35c-4720-8551-958cfffda721.png">
