### ISSUE TITLE
Update market info to support removal of quadratic slippage factor

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5551]
## The Chore

The "Quadratic Slippage Factor" in the "Margin scaling factors" section of the market info will be removed.  

## Tasks

- [ ] Check usage of these values and make sure they aren't used anywhere else
- [ ] Update the market info component to handle it
- [ ] Check Console is happy 
- [ ] Check Explorer is happy
