### ISSUE TITLE
Enhancements to transfer fee

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5554]
## The Chore

Palazzo includes changes to change the way transfer fees are calculated because the flat fee is too prohibitive for large transfers.

We need to respond to this change in Console.

## Tasks

- [ ] Confirm that Core will be providing an API to estimate the fee on a given transfer
- [ ] Update the transfer side panel to call this API and return the value
- [ ] Update the dedicated transfer page to do the same

## Additional details / background info

Slack thread where I am attempting to get the info on the API.

https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1704213658734299

**Comment by bglownia** [comment]
now we calculate the fee
min(transfer amount * transfer.fee.factor, transfer.fee.maxQuantumAmount * quantum)
