### ISSUE TITLE
Support modified funding payment calc

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5555]
Blocked by: https://github.com/vegaprotocol/vega/issues/10656

## The Chore

This is changing

## Tasks

- [ ] Will have a new market param (presumably in "Funding" section) which needs to be supported and get some tooltips
  - [ ] `scaling_factor`: optional scaling factor applied to funding payment.
  - [ ] `rate_lower_bound:` optional lower bound applied to funding payment such that the resulting funding rate will never be lower than the specified value.
  - [ ] `rate_upper_bound`: optional upper bound applied to funding payment such that the resulting funding rate will never be greater than than the specified value.

## Additional details / background info

Thread https://vegaprotocol.slack.com/archives/CLFN5CUMT/p1704214242174609

**Comment by mattrussell36** [comment]
@JonRay15 @barnabee Is there anything else to consider here with regard to where we display these values? For example on the funding payments chart? Or is it only required in the market info tab

**Comment by JonRay15** [comment]
Hold this off until we're confident Core have pusged the above fix to testnet
