### ISSUE TITLE
Support for liquidation improvements 0.74.0

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5556]
## The Chore

Some changes are being made to how liquidations work in Core.

## Tasks

- [x] Changes should be market params only ... based on spec it looks like we're adding:
  - [x] disposal time step
  - [x] disposal fraction
  - [x] full disposal size
  - [x] max fraction of book side within liquidity bounds consumed
- [ ] If someone is being liquidated the network may be holding a position for some period of time 
  - [x] In market params change "insurance Pool" to "Liquidations"
  - [x] Change the "balance" to just be "insurance pool balance"
  - [ ] #5682

## Additional details / background info

Slack thread: https://vegaprotocol.slack.com/archives/CLFN5CUMT/p1704214242174609

Spec changes: https://github.com/vegaprotocol/specs/blob/palazzo/protocol/0012-POSR-position_resolution.md

Slack thread on liquidation balances: https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1704818105242939

## Sketch

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/e9dacd53-9608-4e86-95fc-244de27aebe9)
