### ISSUE TITLE
Enhance Explorer for Competitions and Teams

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5557]
## The Chore

New competitions and games need to be identifiable from Explorer.

## Tasks

- [x] Expand transfers view so you can recognise a game
  - [x] Basically any transfer which is recurring, status pending, isReward TRUE, and has a dispatch strategy
  - [x] Need to show the dispatch strategy
  - [x] Need to show the entity scope
  - [x] Need to show the eligibility criteria
- [x] Add handling for `JoinTeam` (if not done already)

## Additional details / background info

See changes in Console to see how to do this easily and consistently https://github.com/vegaprotocol/frontend-monorepo/issues/4532
