### ISSUE TITLE
Enhance explorer for margin segregation

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5559]
## The Chore

Some small changes to support isolated margin mode.

## Tasks

- [x] Support for new transaction (`UpdateMarginMode`) to set the margin mode for a party/market
- [x] Improve label for isolated margin accounts
- [x] Show what margin mode each market 
- [x] showing the leverage (i.e. `1/margin_factor`) as well on the tx
for the margin account showing whether the market is in isolated or cross mode and if isolated, the the margin factor and/or leverage

## Additional details / background info
Blocked by https://github.com/vegaprotocol/vega/issues/10604, should be fixed in 0.74-preview-12
