### ISSUE TITLE
Support batch proposals in Governance app

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5561]
## The Chore

Need to support these, and it will require some UX to work out how to show this.

Note that this will also require changes in the GraphQL due to this change:
https://github.com/vegaprotocol/vega/blob/develop/datanode/gateway/graphql/schema.graphql#L6115-L6125

## Tasks

- [x] Design the UX
- [x] Build it
- [ ] ~~Add a form to handle multiple proposals within a batch~~
- [x] Adjust proposal list to show that its a batch
  - [x] Show sub proposal lozenges across the top
- [x] Adjust proposal page to show that its a batch and include each proposal data in the batch
  - [ ] Add an accordion for each sub proposal type
- [ ] Share design changes with team for signoff

## Additional details / background info

API ticket for Core: https://github.com/vegaprotocol/vega/issues/10069

Also dependent on this bug: https://github.com/vegaprotocol/vega/issues/10525

Be aware there's come complicated voting shenanigans on this because the way batches work is that each propsal is evaluated against ITS OWN THRESHOLDS and then if ALL pass then the batch passes.

That means:

- You will have overall vote majority and participation
- To get the status and details for each proposal you will have to compare those values to the thresholds for that specific proposal type to determine if it is passing of failing currently
- If it is a market update it is even worse because you need to also check whether you have enough LP votes for that market 
  - in theory that info is on the API and is given by market ... which you need because you might have more than one market update and those markets have different LP breakdown so the vote counts for different amounts against them! 
  - The text generation will need to be smarter on those too ... and its painful, and its late ... so for now write "Market updates are complex, please come back later" because its 7:15pm and I want to go home
- Once you know the pass / fail of each individual proposal and have generated the relevant status and text you can generate the summary figure at the top to say whether the batch as a whole is currently passing

## Sketch 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/7c0a84e9-6531-4b4e-8d74-c1e3ead55a18)

**Comment by JonRay15** [comment]
Blocked by bug https://github.com/vegaprotocol/vega/issues/10525
