### ISSUE TITLE
View list of active recurring transfers from the network treasury

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5615]
## The Chore

Need to see a list of all of these

## Tasks

- [ ] Use the transfer list https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-list-transfers
- [ ] Filter for isReward: true
- [ ] Filter for pubKey: network treasury (whatever that is)
- [ ] Filter for the relevant direction so you're only gettign transfers out
- [ ] Filter for status: Pending (I think - check with Madalina for the Console build)
