### ISSUE TITLE
Console Mobile Review LAYOUT UPDATES

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#5625]
## User story

_As a_ user
_I want to_ use console on mobile 
_So that_ I can connect my wallet, trade on my phone, and view my positions

## Acceptance criteria

- [x] Split the main view into market data on top and user data below
- [ ] Add/modify our bottom actions (sidebar when horizontal) to have clear CTAs to trade (IE make it super clear how to get to the deal ticket)
- [x] Change the market data (or MarketHeader) to be a popover or collapsible section, so that the default view only shows the most important info.. EG price/change

## Sketch

![mobile](https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/e8343efb-4512-41f3-9a81-b6346a2b7626)

```[tasklist]
### Tasks
- [ ] https://github.com/vegaprotocol/frontend-monorepo/issues/5741
```
