### ISSUE TITLE
Test usage of candlesConnection query

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#5626]
## The Chore

We need to test all areas of the code that use candles queries, due to empty candles now being returned from the API

## Tasks

- [ ] Test pennant chart
- [ ] Test TradingView chart
- [ ] Market selector
  - 24hr volume
  - Sparkline
- [ ] /markets page 24hr volume
- [ ] /markets/:marketId
  - 24hr price change in header
  - 24hr volume change in header

**Comment by JonRay15** [comment]
Matt says we can close
