### ISSUE TITLE
Full (or as much as is possible) functionality in the deal ticket without connecting a wallet 

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#5672]
## Story

As a user browsing markets without a wallet connected or a newcomer to the protocol
I want to be able to use the deal ticket as I would `normally` (and all with the possible information added in #5671 if the general/margin account is not known) without connecting my wallet (if I have one at this point)
So that I can see as much information about a possible trade and get a feel for how things are working before I get/connect a vega wallet

## Acceptance Criteria

- [ ] I can

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
