### ISSUE TITLE
Link to etherscan needs to point to the relevant L2 explorer instead where appropriate

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5685]
## The Chore

In explorer / market accordian we currently point to the etherscan link for the contract

## Tasks

- [x] Get a list of chain ID to explorer 
  - [x] 100 is Gnosis
  - [x] 42161 is Arbitrum
- [x] Use the source chain ID in the data sourcing spec to tell if something is ethereum vs Gnosis vs Arbitrum
- [x] Point to [GnosisScan](https://gnosisscan.io/) or [ArbiScan](https://arbiscan.io/) appropriately using the contract ID as usual 

## Additional details / background info

One day we may get more chains and need more maps, but for now its fine
