### ISSUE TITLE
Re-enable `simple-trading-app` tests

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#569]
vegaprotocol/frontend-monorepo#568 disabled some tests to unblock merges. 

# Tasks
- [ ] Work out if they're valid tests
- [ ] If they are, fix 'em
- [ ] If they aren't, remove 'em

**Comment by edd** [comment]
Two notes:
1. I initially filed this in the wrong repo. Oops
2. Re-running `nx test simple-trading-app --skip-nx-cache` was required to see all three of these tests fail. They don't *always* fail, and don't always fail together.
