### ISSUE TITLE
Team profile member view snags

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5701]
## The Chore

This page is slightly off ... dont thnk we ever put this in a mock up which is probably why, but some of it was in [here](https://github.com/vegaprotocol/frontend-monorepo/issues/5486) as ACs

<img width="1501" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/faabba7c-4f55-403e-8b46-3b6fcd17f2a4">

## Tasks

- [x] Instead of **referee** it should say member ID
- [ ] ~~We need to add Member name~~
- [x] We should have the reward earned by member
- [x] We should have the volume by member
- [x] We should have the games played by member

## Additional details / background info

All that data SHOULD be available on the teams stats API by member 

https://github.com/vegaprotocol/vega/issues/9980
