### ISSUE TITLE
Conditional scenarios when you own / are part of a team

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5704]
## The Chore

There are various scenarios we need to cover

## Tasks

- [ ] If you are creator of a team
  - [ ] On Competitions homepage
    - [ ] Create a team should be disabled, grey out the button, add a tooltop "As the creator of a team you cannot create another"
    - [ ] Solo team / lone wolf as abov
    - [ ] Join a team, grey out the button, add a tooltip saying "As the creator of a team you cannot join another"
- [ ] If you are member of a team
  - [ ] Create a team should be disabled, grey out the button, add a tooltop "As a member of a team you cannot create another"
  - [ ] Solo team / lone wolf as above
- [ ] If you are the creator of a referral set that is NOT a team 
  - [ ] On Competitions homepage
    - [ ] Create a team should be changed to "Upgrade to team", add a tooltip "Upgrade your existing referral set to a team"
    - [ ] Solo team / lone wolf should be changed "Upgrade to team", add a tooltip "Upgrade your existing referral set to a solo team"
    - [ ] Join a team, grey out the button, add a tooltip saying "As the creator of a referral set you cannot join another team"
  - [ ] Once you Upgrade to team
    - [ ] Change the title to "Upgrade to team"
    - [ ] Rest of form as usual
    - [ ] Change the button at the bottom to "Upgrade"
    - [ ] Add a note to the bottom saying "Note that your existing referrees will not be automatically added to your team, share your team profile to have them join you in competitions. You will still earn commission from their trading even if they do not join."
  - [ ] Once you Upgrade to solo team
    - [ ] Change the title to Upgrade to solo team
    - [ ] Rest of form as usual
    - [ ] Change button to upgrade 
    - [ ] Add a note saying "Note that your existing referrees will not be automatically added to your new solo team but you will continue to earn commission from their trades"
- [ ] If you are a member of a referral set that is NOT a team
  - [ ] Create a team should be disabled, grey out the button, add a tooltop "As a member of a referral set you cannot create a team, but you can join one"
  - [ ] Solo team / lone wolf as above
