### ISSUE TITLE
Set party profile alias in Console somewhere

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5717]
## The Chore

To support team leaderboards you can now set a party alias for your key.

We need somewhere that we can actually set this in Console....not sure where.

Maybe in the key dropdown in the top right?

Maybe directly in the team profile page?

Maybe we introduce another "individual banner" which records your individual stats if you have them (though we dont have leaderboards for individuals yet).

## Tasks

- [ ] Move the copy button to the far right 
- [x] Add a pen button to each row in the key dropdown to allow you to edit
- [x] If clicked it can just bring up a dialogue allowing you to edit
- [ ] Submitting should send a TX to `UpdatePartyProfile`
- [x] Show the party profile in the dropdown
- [ ] Look at multiline options and some labelling to make sure that the wallet name / private name is distinguished from the public name

## Additional details / background info

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/6705ccce-d206-4777-aa6c-ea344aa30584)

```
message UpdatePartyProfile {
  // Alias given to the party. It must be unique network-wide.
  string alias = 1;
  // Freeform data to associate to the party.
  // Support a maximum of 10 entries.
  repeated vega.Metadata metadata = 2;
}
```
