### ISSUE TITLE
Add more data to the games tab

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5765]
## The Chore

This tab needs a bit more data to make proper sense of it.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/28c89323-34ae-43f1-ad9a-bc7139b7ad7e)

And also could do with rearranging slightly.

## Tasks

- [ ] Move epoch to far left
- [ ] Add the end datetime - can be taken from expiry time on the epoch API using the epoch above
- [ ] Add the actual reward amount in the asset it was awarded in (need the Core ticket below for this)
- [ ] Rename "Amount earned" to "Amount earned in qUSD" and add the normal tooltip

## Additional details / background info

Core ticket: https://github.com/vegaprotocol/vega/issues/10578

**Comment by JonRay15** [comment]
Duplicate
