### ISSUE TITLE
Team profile game view snags

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5767]
## The Chore

Currently the game detail breakdown view looks like this:

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/d0888fb0-06fd-4999-aa77-38e57cdc6530)

But there are some issues with this, some caused by the Core API which I have requested changes to, some just due to extra things we could put on here to make it more understandable.

## Tasks

- [x] This ticket assumes the `epochFrom` is now being set properly so we get a full history
- [x] Move epoch to far left
- [x] Add the end datetime - can be taken from expiry time on the epoch API using the epoch above
- [x] Add the reward asset code based on lookup of the asset ID on the assets API
- [x] Using the gameId to look up the transfer on the transferConnection
  - [x] Display "Daily reward pool", taken from `amount` on `transfersConnection`
- [x] Display the rank
- [x] Display the `rewardsEarned` (which is in THIS epoch) adjusted for asset decimals; call it "Amount earned this epoch"
- [x] Display the `totalRewardsEarned` adjusted for asset decimals, call it "Cumulative amount earned"
- [x] Expand `Reward type` to instead be "Game Definition" and show the full derived name from the reward card, ie. "Maker fees paid - JUP/USDT"
- [x] Sort list by Epoch with more recent first and then reward type
- [x] Check that the "last 5 games result" on the team profile banner still works ... it would need to look at the last 5 results on the API now, ordered by epoch and game type (currently this is broken on testnet)

## Additional details / background info

So it would end up looking a bit like this:

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/0cfb22a1-e7cb-4386-bad6-9522b7cad757)

Dependent on Core ticket: https://github.com/vegaprotocol/vega/issues/10578

In this I have requested to have all the below explicitly on the API:

- rewardAssetId
- rewardEarned
- totalRewardsEarned
- rewardEarnedQuantum
- totalRewardsEarnedQuantum
