### ISSUE TITLE
View new market proposals 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#577]
**As a** console user
**I want to** be able to view market proposals
**So that** I can see if a market idea has already been tabled or to create my own

## Acceptance Criteria
I can see what markets are existing
I can see what markets new markets have been proposed
I can see relevant details about the new proposed markets (TBC)
I can click on the new market proposal and be taken to the proposal details

## Tasks
- [ ] Add tabs to /markets page (markets, proposed markets) 
- [ ] Render a table of NewMarket proposals with status of STATE_OPEN, STATE_PASSED and STATE_WAITING_FOR_NODE_VOTE
  - Note no subscription required as this data will be fairly static. Instead lets poll every 10 seconds
- [ ] Render the following columns
  - [ ] Market (NewMarket.instrument.code)
  - [ ] Description (NewMarket.instrument.code)
  - [ ] Settlement asset (FutureProduct.settlementAsset)
  - [ ] State (Proposal.state)
  - [ ] Vote data, yes/no  (Proposal.votes)
    -  Note. Lets hold off on the progress bar UI and just display the data for now. This already exists in the token app. We need to move the logic and component to the governance lib and consume it from there
  - [ ] Closing date (Proposal.terms.closingDatetime)
  - [ ] Enactment date (Proposal.terms.enactmentDatetime)

**Comment by PeteWilliams** [comment]
Are we thinking this would just be a link to https://token.vega.xyz/governance or are we bringing the list of proposals into Console?

**Comment by PeteWilliams** [comment]
Matt's confirmed we can show the list of proposals into Console.

**Comment by PeteWilliams** [comment]
Initial idea here: https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=3911%3A36550

![image](https://user-images.githubusercontent.com/1325606/200593293-4b0bb89c-79a0-4766-9348-08b01120db9b.png)

Proposed fields, and my best guesses at where they come from:

Market - Proposal.terms.change.instrument.code
Description - Proposal.terms.change.instrument.name
Settlement asset - Proposal.terms.change.instrument.futureProduct.settlementAsset
State - Proposal.state
Voting - Proposal.votes
Closing date - Proposal.terms.closingDatetime
Enactment date - Proposal.terms.enactmentDatetime

**Comment by mattrussell36** [comment]
Lets do the above but as a new tab on /markets. This will be much simpler to implement as well as test

**Comment by ckpringle** [comment]
Some columns disappear when the screen is re-sized @PeteWilliams how would this work here in this case, which columns are priority? Or do we make this scrollable? And / or perhaps we show less columns but again link to the markets page to see all markets with all data? 

![Image](https://user-images.githubusercontent.com/46783148/201637087-1326b6f0-f84b-49c7-beb4-ae07524fab0a.png)
