### ISSUE TITLE
View AMM orders in the order book

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5799]
## Story

As a user 
I want to be able to see AMM orders in the order book
So that I can tell the difference between AMM depth vs normal depth

## Acceptance Criteria

- [ ] AMM volume should be added to the existing order book view
- [ ] All figures should now be the sum of AMM vs regular volume 
- [ ] The portion of the depth that is AMM should be indicated by a different shade of green / red in the book
- [ ] The Core API is likely to only provide the AMM depth out to a certain distance from the midprice for performance reasons
  - [ ] Where it is provided, Console should use those figures
  - [ ] Where it is not provided, Console will need to approximate the AMM curve in the client and show a representation of this depth in the same way as above

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

<img width="229" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/23b58085-7ee0-4788-b3a1-9a758a32e8f4">

## Additional details / background info

Core ticket: https://github.com/vegaprotocol/vega/issues/10670

Research will need to tell us how to approximate these depth outside of the range provided on the API.
