### ISSUE TITLE
LP voting still not quite right on governance app

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5814]
## The Chore

This vote seems to indicate we're still not quite right with the app - which is probably my fault.

https://governance.vega.xyz/proposals/332f89f1e75e2017b5dd91e48ace4de9b29d9ef0d98d3cea3a5b0574a436b048

The app seems to be suggesting this vote would fail and yet it went through.  I think therefore the LP voting should be shown the same as the token votes .... ie. if you meet LP participation (currently 0%) you can get a vote through even if you the LP voting only command 21% of the share ... because you are 100% of the LP vote that voted.

## Tasks

- [x] Confirm the behaviour
- [ ] Fix the view
- [ ] Propose a governance vote to increase the required participation because 0% here is mad and if it behaves like this it means I could provide $500 of liquidity on a market tomorrow, propose a stupid vote, run it for the min 24 hours, and likely get it through because no one will notice.

## Additional details / background info

1. Right hand participation is fine 
2. Left hand majority should be 
    i. Sum up all `totalEquityLikeShareWeight` that has voted yes OR no to get denominator
    ii. Sum up all `totalEquityLikeShareWeight` that has voted yes as the numerator
    iii. Numerator / Denominator is your majority

eg. for current vote it would be 
0.2173913043478261 / 0.2173913043478261 = 1 = 100% = PASS
