### ISSUE TITLE
Batch governance proposal vote status broken

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5820]
### Vote breakdown

- [ ] the overall status iis saying currently expected to fail, 0 of 4 passing, even though the breakdown actually shows that all 4 are currently passing
- [ ] This continued once the proposal completed, it stil says it failed even though it did not...and it says in the top right it passed so it is contradicting itself
- [x] ~~The title of each breakdown is just showing the proposals type (update market) rather than showing the full title shown at the top of the page which makes it hard to read between~~ I've added indicators to the breakdown in [here](https://github.com/vegaprotocol/frontend-monorepo/pull/5825), so I think it solves the issue of not knowing what is what 😉 (Art)

<img width="706" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/0ac66585-a7aa-459a-b6a8-bb64107a6560">

<img width="347" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/d3773e17-524f-4aeb-9f8b-416c4d783691">

### Summary tile

All the above issues obviously feed through to the summary view, but I assume that fixing them in the details will ultimately get pulled through.

## Tasks

- [ ]
- [ ]

## Additional details / background info

https://governance.stagnet1.vega.rocks/proposals/e2bd2f75e07001b19aae12ce9b7dfb0613802c85264a3ff61fb347c23e0a0dce
