### ISSUE TITLE
Batch governance proposal summary / titles

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5821]
### Proposals in batch

For updates we are allowing a copy of the market ID and giving a link to console ... for resume market we arent .. we should follow same pattern for both market updates and market lifecycle governance.

<img width="605" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/bdba3376-dd49-4ab2-86f4-d6b7c9a74d10">

- [x] Ideally we would look up the market name from the ID and show this here rather than the ID
- [x] Then we would show the copy button which would show a tooltip "Copy market ID" since users are far more likely to want to copy an ID than a name
- [x] Then we can include the link to console as usual
- [x] We should follow that pattern for both market updates and market lifecycle governance 

### Proposal details 

- [ ] As above we're just showiing the proposal type ... we need the full title of the update here so you can tell what you're looking at.  I would expect this to match the top of the page

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/eabf07b0-b907-48df-a2c3-d1408c0862e4)

## Tasks

- [ ]
- [ ]

## Additional details / background info

https://governance.stagnet1.vega.rocks/proposals/e2bd2f75e07001b19aae12ce9b7dfb0613802c85264a3ff61fb347c23e0a0dce
