### ISSUE TITLE
USDT volume in markets table

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5832]
## The Chore

This doesnt look very nice and causes text wrap issues. 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/734b6dab-e99a-4789-9389-87b34b09c166)

I suggest we use the same two line / lower in grey option as we use here.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/dbf85fe2-4b67-44ea-8848-5febdcfcc33e)

I also think we should do the same with Open Interest ... and I wonder if we can add the basis points to the spread?

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/54765ea3-858d-4867-9f76-9b6dc41b924f)

## Tasks

- [ ] Drop the  24h volume into a two line format with contracts on top and USDT value beneath
- [ ] Do the same with OI ... contracts on top and USDT equivalent beneath
- [ ] For the spread show the basis points below ... so `spread / mark price * 10000`

**Comment by JonRay15** [comment]
Will cover this under overhaul ticket
