### ISSUE TITLE
Batch proposal enhancements

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5838]
### Dropdown titles

Can we maybe add  a bit more detail to these dropdowns? The colours make it clearer, but having an actual name would be best.

<img width="319" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/8be76634-de7a-4012-b080-326ee56dec2f">

- [x] For a market update pull in the name like we do above
- [x] For a market lifecyctel change pull in name 
- [ ] For a create market we should be able to pull in the market name too 
- [ ] For a network param we should be able to pull in the network param like we so in the summary
- [ ] For a create asset we should be able to pull in the asset symbol

### Vote breakdown

<img width="956" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/2467c3ce-9f05-46c6-a5aa-21074e29e5e2">

- [ ] As above if we can pull in more detail to the title it will be easier to follow
- [x] We could also show the same coloured numbering to link to the top
- [x] It would probably be good to put each proposal vote inside the curved corner border tile we use elsewhere because - particularly with market updates - it can be hard to see that the LP vote & token vote are both relevant
- [ ] Do something to emphasise the overall status, currently its just that little tick / cross and can get lost.. maybe make it bigger? Maybe give it a border tile too?

## Tasks

- [ ]
- [ ]

**Comment by JonRay15** [comment]
This is already merged
