### ISSUE TITLE
Enhancements to explorer network treasury view

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5841]
## The Chore

Some suggestions to improve the treasury view:

## Tasks

- [x] Add some intro text 
- [ ] For recurring transfer show the below (put n/a for one-offs - alternatively you could make a really big tooltip on hover if you prefer not to have lots of n/a columns?)
  - [ ] Epoch to / from
  - [ ] Reward type - Concat dispatchMetric + dispatchMetricAssetId + marketIdsInScope (same as we do on reward cards)
  - [ ] EntityScope
  - [ ] lockPeriod
  - [ ] distributionStrategy
- [ ] Ensure that recurring transfers appear every epoch that they are sent
- [ ] Add epoch to the far left (and sort by epoch desc)
- [ ] Can we add details of active governance initiated transfer votes which are currently in progress
- [ ] Can we make it clear that delayed transfers have been created since these will be used by the CAF
- [ ] Can we explore splitting out the "Active" transfers which are pending and therefore likely to happen each epoch vs the historic ones which would be the one-offs and any recurring transfer payments in historic epochs

## Additional details / background info

Proposed intro:

```
The network treasury can hold funds from any active settlement asset on the network.  It is funded periodically by transfers from Gobalsky as part of the Community Adoption Fund (CAF), but in future may receive funds from any sources. 

Funds in the network treasury can be used by creating governance initiated transfers via community governanance.  These transfers can be initiated by anyone and be used to fund reward pools, or can be used to fund other activities the CAF is exploring.

This page shows details of the balances in the treasury, pending transfers, and historic transfer movements to and from the treasury.
```

**Comment by edd** [comment]
Point 2 is blocked by https://github.com/vegaprotocol/vega/issues/10374#issuecomment-1957362956

**Comment by edd** [comment]
Marking as blocked until https://github.com/vegaprotocol/vega/issues/10374#issuecomment-2004492143 is valid. Trying to work around it via the `transfers` API is unsatisfying at best.
