### ISSUE TITLE
Batch proposals need to be able to handle more proposals

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5855]
## The Chore

On staging we have a batch wiit 10 proposals in it.

https://governance.stagnet1.vega.rocks/

And the wrapping has become unhappy.... 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/e4ec95ba-ae73-463c-b46c-3ff98fe9116c)

We will have one this size on mainnet very soon ... so we need it to be less sad.

## Tasks

- [ ] For the top row with the proposal type tiles can we do "Update market state x 5" and "Update market x 5" on the tiles instead?
- [ ] In the list of proposals below can we make this a 2 width grid so we use fewer rows?
- [ ] If it is more than say 10 ( so 5 rows of 3) can we do a fade out on the summary tiles on the proposals page?  On the details page we can show them all
