### ISSUE TITLE
Allow batch propsal via json on governance site

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#5890]
## The Chore

Currently when proposing on the governance site, you can paste in json for your proposal. However, this is not the full transaction, and behind the scenes we wrap the propsoal json in an object specifying that its a normal proposalSubmission. We need to change this so that the full payload is pasted in which will allow users to create either a normal proposal or a batch proposal

## Tasks

- [ ] Change propose form to send a full transaction payload, allowing specifying the transaction type
- [ ] Update the templates in the docs
- [ ] Also scrolling doesnt work in this JSON input box, fix that
