### ISSUE TITLE
Move reward history up on reward view and other minor tweaks

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5894]
## The Chore

What we need to achieve and who for

## Tasks

- [x] Move reward history to under the top 3 tiles and above the reward cards and put the graident border on it so it stands out a bit more
- [x] Get rid of the scroll on scroll, just render all reward cards down to the bottom of the page and remove the grey tile they sit on 
- [x] Reduce the size of the cards on default 100% zoom ... they're really large, we should be able to fit at least 4 on a 13in screen, maybe 5 across
