### ISSUE TITLE
Redesign market info panel / page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5906]
## The Chore

These changes all need to be considered and agreed.... there are some concerns that actually grouping these up so heavily might mean you get a very large panel with a wall of text and issues with scrolling on mobile in particular.

### Proposed changes

- [ ] Combine the price monitoring bounds 
  - [ ] Single header for "Price monitoring bounds"
  - [ ] Show each bound with "Price monitoring bound 1" etc in large font 
  - [ ] Reduce the font of everythgin else to be the same (dont need the 99.9999% part large)
- [ ] Consolidate all the liquidity stuff
  - [ ] Liquidity
    - [ ] Method (from "Liquidity fee setting") > Rename "Fee setting method"
    - [ ] Target stake
    - [ ] Supplied stake
    - [ ] Time Window (from "Liquidity monitoring parameter") > Rename "Monitoring time window"
    - [ ] Scaling factor (from "Liquidity monitoring parameter") > Rename "Monitoring scaling factor"
  - [ ] Liquidity SLA protocol
    - [ ] Liquidity price range (put that text as a tooltip rather than showing it above)
    - [ ] Lowest price
    - [ ] Highest price
    - [ ] Everything in SLA protocol already 
- [ ] Fix the broken oracle link on "View settlement data specification" at the bottom of the market info page 

## Tasks

- [ ]
- [ ]

**Comment by JonRay15** [comment]
Superseded
