### ISSUE TITLE
Add reward cap to reward cards

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5923]
## The Chore

**Any** reward can now be set up so that it is capped at some fraction of the taker fees paid.

The idea of this is to prevent people gaming / farming rewards with modest amounts of volume.  

This will be stored on the `DispatchStrategy.capRewardFeeMultiple` on the transfer API.

eg.

If `DispatchStrategy.capRewardFeeMultiple` = 2 then you can only earn 2 x what you paid in fees.
If `DispatchStrategy.capRewardFeeMultiple` = 0.5 then you can only earn up to half of your fees back 

The reward cards will need to be updated to show this cap if one is present.

## Tasks

- [ ] Add a third column on the same line as "Assessed Over" for "Capped at"
- [ ] Display `capRewardFeeMultiple` X etc under it
- [ ] On hover show tooltip "Reward will be capped at `capRewardFeeMultiple` X of taker fees paid in the epoch"

## Additional details / background info

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/076780be-5e25-45ea-9694-f4d70642ced8)
