### ISSUE TITLE
Enhance Console for changeable tick size

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5924]
## The Chore

**Tick size**: the minimum change in quote price for the market. 

Order prices and offsets for pegged orders must be given as an exact multiple of the tick size. For example if the tick size is 0.02 USD. then a price of 100.02 USD is acceptable and a price of 100.03 USD is not. The tick size of a market can be updated through governance. Note, the tick size should be specified in terms of the market decimals, e.g. for a scaled tick size of `0.02` (USDT) in a market using `5` decimal places, the tick size would be set to `2000`.

## Tasks

- [ ] The market accordion "Key Details" will need to be updated to ensure it can display the new tickSize which will be on the market API
- [ ] The deal ticket will need to validate the order sizes being put in
  - [ ] When user types in the field check whether the value is a multiple of the specified tick size
  - [ ] If it is not then display a message saying "Order size must be a multiple of `tickSize` and do not allow order to submit

## Additional details / background info

```
query marketConfig {
  marketsConnection{
    edges{
      node{
        id
        decimalPlaces
        positionDecimalPlaces
        tickSize
      }
    }
```
