### ISSUE TITLE
Creating a market order that will settoff price auction will fail but not tell you why

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#5953]
## Story

When submitting a market order that will put market into auction the order fails (not red) due to Error— OrderError: non-persistent order trades out of price bounds, but for the users this means ver little.

## Acceptance Criteria

- [ ] Receive information on why my market order failed, Error— OrderError: non-persistent order trades out of price bounds, does not tell the user much

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Screenshots

https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/04f1e598-7175-47f4-9c70-26e3150b8b61
