### ISSUE TITLE
IPFS deploys for Token Frontend

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#596]
Following on from #126, which configured the _how_, this ticket involves getting token-frontend hosted on IPFS.  

# Tasks
- [ ] Create site on ⚡fleek
- [ ] add `.fleek.json` to `token` app
- [ ] Repoint hostname to ⚡fleek
- [ ] Test a deploy, ensure CSS/etc loads properly

**Comment by edd** [comment]
Marked as blocked, waiting for a deploy later today

**Comment by edd** [comment]
This was switched over, but is now back on Netlify due to a report from Dan that deeply nested routes do not work:

https://console.fairground.wtf/markets should not show an IPFS folder index
