### ISSUE TITLE
Add slider for Cross Margin

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#5963]
## The Chore

Currently it is too complicated to calculate the max size on slider for cross margin so we have not done it as part of #5102 

But once Witold has done some Core work for Colosseo tjis will get easier and we can simply do:

MAX would be = `Balance in general account` / `(risk factor * mark price)`

Same other logic as isolated margin with respect to direction ie. 

## Tasks

- [x] When I have no open position the max size on the slider is the position size that would use up all my remaining general account as margin, eg. `Balance in general account` / `(risk factor * mark price)`
- [x] When I am making an existing position larger then same approach as above
- [x] When I am flipping an existing position then the max is the amount needed to use all my balance on the other side, eg. MAX = `current margin that would be returned to you` + `Balance in general account` / `(risk factor * mark price)`

**Comment by JonRay15** [comment]
Closed by #6006
