### ISSUE TITLE
IPFS deploy

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#597]
Following on from #126, which configured the _how_, this ticket involves getting explorer hosted on IPFS.  

# Tasks
- [ ] Create site on ⚡fleek
- [ ] add `.fleek.json` to `token` app
- [ ] Repoint hostname to ⚡fleek
- [ ] Test a deploy, ensure CSS/etc loads properly

**Comment by elmargasimov** [comment]
@edd @dexturr: Is this still blocked or can we move it to the backlog to be prioritised and refined?

Cc: @pennyandrews
