### ISSUE TITLE
[console] IPFS deploys for testnet

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#598]
Following on from #126, which configured the _how_, this ticket involves getting `trading` hosted on IPFS.  

# Tasks
- [x] Implement hash routing
- [x] Test a deploy, ensure CSS/etc loads properly
- [x] Change build to use export instead of build (for static build)
- [x] Repoint hostname to ⚡fleek
- [x] Ensure that ~~https://console.fairground.wtf/markets~~ https://console.fairground.wtf/#/markets resolves correctly
- [x] https://console.fairground.wtf/ resolves correctly
- [ ] Bonus points: subfolder gateways should also work (non-essential)

# Reopened
This was reopened after it was pointed out that deeply nested URLs work fine if you're clicking around the apps, but deep links (e.g. https://console.fairground.wtf/markets/1234512312) didn't. This should have been obvious - `next.js` exports of course do not know every market id to pre-generate a static `market/1234512312.html`, and IPFS has no server that is doing HTTP redirects. So I've roped someone in to help me fix the static deploys.

## Workarounds
- The whole app *could* be switched to use client-side routing (`#/markets/`), if next.js supports it.
  - If this is possible, it *could* be done only on IPFS, or on all deploys

**Comment by edd** [comment]
Marked as blocked, waiting for https://github.com/vegaprotocol/frontend-monorepo/milestone/1 to be more complete

**Comment by edd** [comment]
Marked as blocked - I think @dexturr had a reason *not* to set this up right away

**Comment by edd** [comment]
https://vega-fairground-console.on.fleek.co/ is deploying, but the DNS for console.fairground.wtf has not been repointed.

There are some situations in which this app specifically fails to load correctly:

- [Subdomain-based IPFS gateways](https://docs.ipfs.tech/concepts/ipfs-gateway/#subdomain) work fine
- [Path-based IPFS gateways](https://docs.ipfs.tech/concepts/ipfs-gateway/#path) don't load the assets correctly due to the way next.js export references static assets in the exported output.

Currently this is acceptable, as there's no straightforward workaround (next.js *effectively* expects you to know where the content is being served from, which we can't guarantee here), but this is tolerable. [Path-based gateways](https://docs.ipfs.tech/concepts/ipfs-gateway/#violation-of-same-origin-policy) have security implications that don't map well on to Trading while it is using Wallet API v1 anyway.

**Comment by edd** [comment]
This was switched over, but is now back on Netlify due to a report from Dan that deeply nested routes do not work:

https://console.fairground.wtf/markets should not show an IPFS folder index

**Comment by edd** [comment]
Blocked by https://github.com/vegaprotocol/frontend-monorepo/pull/1921 currently
