### ISSUE TITLE
Align TP SL and reduce only boxes on ticket

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6001]
## The Chore

Align the reduce only and the TP/SL check boxes

<img width="286" alt="Screenshot 2024-03-13 at 19 52 45" src="https://github.com/vegaprotocol/frontend-monorepo/assets/83510148/0ea813fd-25b1-40e1-8b46-2965f2c00543">

## Tasks

- [x] Align them
- [x] Tick boxes on market order:
  - [x] TP/SL on the left
  - [x] Reduce only on the right
- [x] Tick boxes on limit order
  - [x] TP/ SL then Iceberg orders stacked on the left
  - [x] Post then Reduce only stacked on the right

**Comment by MadalinaRaicu** [comment]
Is there an issue if we leave Reduce then Post only when we stack them? 
This way there is one less condition in the code and it looks more consistent when we switch between Market / Limit tabs




![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/9fa74196-7d03-4a56-b90d-e876d99d1ecc)
![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/068ea5cd-563f-4c8f-9f8a-3dd3e00cedfe)
