### ISSUE TITLE
Rework liquidation notification in Console

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6019]
## Story

As a user
I want to know i've been closed out, at what price, and for what loss
So that I dont label Vega a scam and stop trading there 

## Tasks

- [x] Check the latest trade on the market for that key
- [x] If it is of type: `TYPE_NETWORK_CLOSE_OUT_BAD` then you have been closed out
- [x] Do not look at the position API for positionStatus at all anymore because it is rubbish
- [x] If last trade shows a close out then 
  - [x] Show the tooltip indicating you have been closed out
  - [x] The price from that trade can be taken as the `closeoutPrice` 
  - [x] Display message below

NB. We have the tradestream subscription to monitor the last trade on that market for this pubkey.  This logic should be built off that.

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

### Current view 

<img width="369" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/be489515-66f2-41a5-9415-81898d8fa9f1">

## Additional details / background info

```
Your position was closed. 

You did not have enough `settlementAsset` to meet the margin required for your position, so it was liquidated by the network at `closeoutPrice`.

Read more about position resolution(link)
```
