### ISSUE TITLE
Simple swap UI in asset mgmt component

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6033]
## Story

As a user
I want a simple swap UI screen 
So that I can easily exchange my Ethereum USDT for Arbitrum USDT and vice versa once the Axellar bridge is done, and can use it for other assets in the future

## Acceptance Criteria

- [x] There is a simple screen modelled on unswap or similar for swapping spot assets
- [x] This would be displayed in both the portfolio page and the trading sidebar
- [x] The form sends an order to the relevant spot market to trade for you
  - [x] Market ID (will need to be found from the asset ID of the asset you're swapping to)
  - [x] If paying the QUOTE asset to receive the BASE asset use BUY and use the BESK ASK price to calculate received amount
  - [x] If paying the BASE asset to receive the QUOTE asset use SELL and use the BESK BID price to calculate the received amount
  - [x] Size is just taken from the form
  - [x] The form should allow you to enter a price impact tolerance
  - [x] Send the order as a LIMIT FOK where the price is determine by the tolerance, eg. 
    - [x] If order type is BUY use BEST ASK + TOLERANCE
    - [x] If order type is SELL use BEST BID - TOLERANCE
- [x] The form gives you a estimate of the average price of the asset you will receive
- [x] The form sends a TX to the wallet to be confirmed
- [x] Once confirmed the form tells you how much of that asset you have received and links you to explorer 
- [x] There is a link to the spot market where this swap is being executed
- [x] If the TX fails because the FOK cant execute the toast needs to show this failure AND we will display red text beneath the swap button to let the user know

## Tasks

- [x] UX (if needed)
- [x] Design (if needed)
- [ ] Team and stakeholder review
- [x] Specs reviewed and created or adjusted
- [x] Implementation
- [ ] Testing (unit and/or e2e)
- [x] Code review
- [x] QA review

## Sketch

See "SWAP" drawing here:

https://www.figma.com/file/ywcCZvXdvG28bg0AmCY9mF/Console-v3?type=design&node-id=6158-40256&mode=design&t=ABCsSihKRELNzJxI-0

## Additional details / background info

Current thinking is this will either live in the sidebar or if that is too busy with all the options we're now ending up with we could have a standalone page similar to what we have fo deposits etc ... I think building that out into an "Assets" page is the best approach here.
