### ISSUE TITLE
Update market screen for spot

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6034]
## Story

As a user
I want to be able to see spot markets
So that I can:
1. Trade directly on the market if I want to
2. Investigate why I might be getting high slippage on the simplified swap UI 

### Header

- [x] Add "Base asset" 
- [x] Change mark price to "Last traded price"
- [x] Show volume in terms of base asset first and in brackets quote asset terms eg. 10 Arbitrum USDT (10.67 Ethereum USDT)
- [x] Change settlement asset to "Quote asset" (and source it from here on the market API) (covered in #6090)
- [x] Remove funding
- [x] Remove index price

### Deal Ticket

- [x] Change long / short to Buy / Sell
- [x] Remove "Reduce only" since this is not an option 
- [x] Remove all margin & liquidation section
- [x] Not enough collateral error not showing in toast

### Chart

- [x] Remove funding history tab
- [x] Remove funding payments tab

### Bottom panel

- [ ] ~~Remove positions tab~~ Not doing because positions is across all markets

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review
