### ISSUE TITLE
Include asset swap in deal ticket

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6035]
## Story

As a user 
I want the system to detect if I have a swappable asset and perform that swap automatically on the deal ticket
So that it saves me the extra clicks of converting it

## Acceptance Criteria

- [ ] The deal ticket detects if I have none of the asset required for the market BUT do have some of another asset which could be swapped using a spot market
- [ ] If this is the case the deal ticket shows an info box 
  - [ ] Box explains that I can swap from asset X into the required asset in order to make this trade
  - [ ] Box tells me the expected slippage on that swap
- [ ] If the user clicks the submit button the system sends a batch transaction that first swaps the asset and then performs the desired trade

## Issues 
- [ ] The system somehow deals with slippage here ... ultimately you will not know the exact amount that is going into the resulting order until the first TX has executed ... which presents a problem
- [ ] Might be this needs to be a two click operation in reality ... swap first ... then execute trade

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
There is not enough spot liquidity on the network currently for this to be remotely viable
