### ISSUE TITLE
Create Nebula homepage

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6042]
## Story

As a user
I want a nice homepage on Nebula
So that I can tell what the product is about and understand how to navigate it

## Acceptance Criteria

- [ ] I can view a homepage
- [ ] I can navigate to other places on the site
- [ ] I can view various important info about the site 
- [ ] I can see stats for total markets
- [ ] I can see stats for total providers
- [ ] I can see the total liquidity committed
- [ ] I can see the total fees earned

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

<img width="561" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/eee30852-10dc-4bb7-aef9-96c9cf342dd7">

https://www.figma.com/file/N5U7olQWcW6HcZG6lauHYL/Nebula-aka-Shopify-for-Perps?type=design&node-id=6370-4059&mode=design&t=Susd1dXodvMjxeFt-0
