### ISSUE TITLE
Create pools page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6043]
## Story

As a user
I want to see a list of all markets / pools available on Vega
So that I can decide where to provide my AMM liquidity

## Acceptance Criteria

- [ ] I can see a list of all markets on Vega
- [ ] I can see all columns in the sketches
- [ ] I can see icons for the market and settlement asset
- [ ] There are tabs for 
  - [ ] Esablished markets - new community tags will indicate approved
  - [ ] Innovation zone - new community tags will not indicate approved
  - [ ] New markets - markets that have been created but are still in opening auction
  - [ ] Proposed markets - markets that are still in the governance voting stage
- [ ] All columns can be sorted
- [ ] There is a button to create a new market which links to the relevant page
- [ ] There is a search box to find markets

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

<img width="1235" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/39be4f3d-1042-499d-8dad-76774e591ecc">

https://www.figma.com/file/N5U7olQWcW6HcZG6lauHYL/Nebula-aka-Shopify-for-Perps?type=design&node-id=6370-4059&mode=design&t=Susd1dXodvMjxeFt-0
