### ISSUE TITLE
Create explore page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6044]
## Story

As a user
I want to see some highlights on available markets within Nebula
So that I will be intrigued by certain areas

## Acceptance Criteria

- [ ] I can see a page with the highlights in panels
- [ ] Each of those panels has some description on what those highlights are
- [ ] If I click on that panel the Pools page is opened with the filters preconigured to show that type

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

<img width="691" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/818aa4ca-8cca-4910-8ed1-0448106ffade">

https://www.figma.com/file/N5U7olQWcW6HcZG6lauHYL/Nebula-aka-Shopify-for-Perps?type=design&node-id=6370-4059&mode=design&t=Susd1dXodvMjxeFt-0
