### ISSUE TITLE
Create market details page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6046]
## Story

As a user
I want to see the details of a market
So that I can understand that market and decide if I will provide liquidity to it

## Acceptance Criteria

- [ ] I can see the name of the market and its icons
- [ ] There is a button to edit the market which sends you to the docs for edit market
- [ ] I can see the key details of the market
  - [ ] Current price (and price change in 24h)
  - [ ] Total rewards per epoch
  - [ ] Volume in 24h
  - [ ] Order book depth
  - [ ] Total fees in 24h 
- [ ] I can see a graph with tabbed options for what to view
  - [ ] Fees / Volume shown on a two scale approach since these are always a set fraction of each other
  - [ ] Liquidity showing the AMM liquidity at each price level
- [ ] I can see high level total liquidity committed 
- [ ] I can see high level total fees earned
- [ ] I can see a table showing me details of liquidity provided
  - [ ] Each individual AMM commitment should be a line of data showing
  - [ ] The key providing 
  - [ ] The amount provided
  - [ ] The fees they've earned in 24h
  - [ ] The rewards they've earned in 24h
- [ ] There is a button to add liquidity which takes me to that screen
- [ ] That button becomes Manage liquidity if I already have a commitment
- [ ] There is a button to trade which takes you to that market on Vega via the interstitial page
- [ ] There is a button to share the link
- [ ] if the market is still in governance
  - [ ] Show when the voting period ends
  - [ ] Show a countdown
  - [ ] Show a button to vote which links you to Governance app
  - [ ] Most of the rest will be empty at this point obviously

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

<img width="1217" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/4a5557fb-cbed-4c9b-b23b-ba65f75f2623">

https://www.figma.com/file/N5U7olQWcW6HcZG6lauHYL/Nebula-aka-Shopify-for-Perps?type=design&node-id=6370-4059&mode=design&t=Susd1dXodvMjxeFt-0

## Additional details / background info

Many of these APIs should already be available but some wont ... Core tickets are currently being raised and will be linked back here.
