### ISSUE TITLE
Add a toast for liquidation notification

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6055]
## The Chore

Add a toast when you have been liquidated.

Continuation of work in #6019 

## Tasks

- [x] Add toast
- [x] Make sure the toast message contains all the nice info
- [x] Make sure the toast pops up if the liquidation happened while you were away
- [x] Probably the toast will need to pop up every time you open console and your last trade is still the network close out, even if you've seen it before ... unless we can keep in local storage ... but I doont know that we need to
- [x] Once you have made a new trade the toast should not appear again next time you open console
- [x] In this toast there could be a button which sets the new "show closed positions" button to on so that you can see the position that was closed
