### ISSUE TITLE
Game results view

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6061]
## Story

As a user playing a game
I want to see the results of that game
So that I know how i did in it ... SOMEHOW WE COMPLETELY FORGOT THIS 

## Acceptance Criteria

- [ ] If I click on the game card I get taken to the game detail page
- [ ] The game detail page shows me a view where the top lin info is the main details of that game ... and is very similar to the headline view of the reward details given in #5580 (which will now be done AFTER this change!) 
- [ ] The only diifference is we want to see number of participants in that header here which should be available on the API
- [ ] The rest of the page displays the leaderboard for that individual game which is very similar to the main team leaderboard except it will have an epoch on it and will not display the aggregates... all this info is available on the `game` API and is basically the same as what we show on the team profile "results" section but we would filter for THIS game only and would want to use the styling from the leaderboard component rather than a simple AG grid
- [ ] We will need to filter for epoch desending then rank ascending so we get most recent game first with 1st place at the top
- [ ] Show 100 rows by default with a load more button at the bottom

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Sketch

<img width="927" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/0ff644c0-3c89-4b5d-9151-e1d9c95f057c">

**Comment by JonRay15** [comment]
Dont show volime .... there is a core bug .... they wont provide it
