### ISSUE TITLE
Expand Vaguer to catch missing referral programs

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6074]
## The Chore

The API shows a program but the page shows nothing.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/6729eea6-4b36-4c4c-a296-eb095b1588a0)

Seems like this is a datanode issue.

## Tasks

- [ ] Check with Nodes Guru what has happened here, ther retention?
- [ ] Enhance Vaguer to catch this case
- [ ] Can we move to the well-known repo to mitigate against this?

## Additional details / background info

The data sits on this API 

https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-get-current-referral-program
