### ISSUE TITLE
Add asset icons to relevant places

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6089]
## The Chore

Edd now has nice icons ... we should add these places

## Tasks

- [ ] Add them to deposit form (incl sidebar)
- [ ] Add to withdrawal form (incl sidebar)
- [ ] Add to transfer form (incl sidebar)
- [ ] Add to swap form (incl. sidebar
- [ ] Add to spot markets (two icons for base / quote)

**Comment by JonRay15** [comment]
Lets do this in the asset mgmt epic tasks .... I will add the ACs there
