### ISSUE TITLE
Add intervals to the slider

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6093]
## The Chore

Would be nice to add a simple 0%, 25%, 50%, 75%, 100% to the slider so users can click and set it quickly.

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/60eae666-df00-4c2e-b716-3c1aafc94b72)

Or could have a little % input box somewhere too?

## Tasks

- [x] Add 0, 25, 50, 75, 100 % clickable intervals to the slider
- [x] When you hover over these the icon should change to a hand pointer to show you can click
- [ ] Adding % tooltip when you're dragging

## Additional details / background info

Follow the same style guide as the ;leverage slider intervals

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/64d43a9e-c325-41ea-b79f-3fe22e7f2a51)
