### ISSUE TITLE
EPIC: Enhanced auction & price monitoring features

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6112]
## Story

_As a_ user
_I want_ better visibilty of auctions in console
_So that_ I can tell what is going on, when it will end, how this impacts me etc

```[tasklist]
### Tasks
- [x] https://github.com/vegaprotocol/frontend-monorepo/issues/6225
- [ ] https://github.com/vegaprotocol/frontend-monorepo/issues/6224
- [ ] https://github.com/vegaprotocol/frontend-monorepo/issues/6290
```

## Acceptance Criteria

Key objective: All of this has to be MUCH more obvious

Task 1:
- [x] Show the normal blue warning banner 
  - [x] I can see when the auction started
  - [x] I can see when the auction might end 
  - [x] I can see a live countdown to that time
- [x] Colours shouldnt all be orange ... it makes it look bad .... can we use the blues instead? 
- [x] Can we include more words in Console that make it clearer why this is happening and that it is a good thing, with links to docs too 
- [x] Changes to deal ticket to make orders easier 
  - [x] When on market order show the warning box in blue, and say "Market orders cannot be placed while in auction, click to switch to limit orders"

Task 2: 
- [x] Show details of the auction in order book
  - [x] Highlight / outline any currently crossing orders on the book in the blue 
  - [x] Replace the last trade / spread with "Estimated uncrossing: XX"
  - [x] Work out the next price monitoring bound that may get hit and show this on the order book in blue (stretch)

### Udated Current state order book

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/ce5964da-b435-49a1-bf97-9609bb93be7c)

- Seems pretty good ... I can see the crossing orders
- I get an icon showing me the auction
- I get an uncrossing price 
- I get a tooltip explaining things

### Updated banner 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/c2541253-ffb1-49fb-95a4-c838b66a1161)

- I get all the info and a countdown as you'd expect

**Comment by MadalinaRaicu** [comment]
what if we have no est. uncrossing price?  is this enough?


![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/5fa6d49e-3356-4eea-819c-55a0c49c3914)



![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/976bb914-4b90-4142-af50-f95d4ae68b4f)

**Comment by MadalinaRaicu** [comment]
Let me know if you are ok with the wording on the banner? 

cc @JonRay15 @candida-d

**Comment by MadalinaRaicu** [comment]
> Banner looks good @MadalinaRaicu. Is this ticket just to cover monitoring auctions, or is it intended to address opening auctions too? @JonRay15 

is think monitoring only

**Comment by JonRay15** [comment]
I think at this point we have covered what we wanted to cover in terms of making auctionc clearer.

So have closed those tickets.

Now doing a review of price monitoring to see if we can make this clearer.

**Comment by JonRay15** [comment]
Closing this as the other ticket is available now and cant be bothered to close it later.
