### ISSUE TITLE
Games Core API bug hacks

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6114]
## The Chore

In this view 

<img width="1440" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/ac251535-eca5-4489-93b1-baad87e2401f">

## Tasks

- [x] Remove the Cumulative amount earned for now because there is a Core bug
- [ ] Either 
  - [x] Derive the rank on the fly by querying for each epoch results, ordering by rewards earned, and deriving rank 
  - [ ] Remove the rank completely 

## Additional details / background info

These hacks will need to be unwound later once these are resolved.

- https://github.com/vegaprotocol/vega/issues/11003
- https://github.com/vegaprotocol/vega/issues/10998

They also will likely impact 
- #6061
