### ISSUE TITLE
Show fills in context

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6161]
## Story

As a user
I want to see my fill information in context of my orders rather than just in a big table
So that I can make more sense of it, and it saves showing that tab so saves space

## Acceptance Criteria

- [ ] There is an "Order History" table instead of a trades table
- [ ] That table shows your closed orders
- [ ] Where that order filled you can expand to view details
- [ ] Expanding gives you details of the fills on that order
- [ ] There is a tile version of this for mobile

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
I created this because dealing with fills on mobile is a bit difficult .... this is a potential way of dealing with it imo ... so raising so I dont forget ... and ppl can debate
