### ISSUE TITLE
Improve consistency of the experience when we send TX that dont use toasts

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6170]
## The Chore

We have some randomness here as more of these TX have been added. 

Joelle has done some work in Nebula in this sort of area so potentially can help.

## Tasks

- [x] Identify where we are sending these sorts of TX
- [x] Put together a standard approach for dealing with them
- [x] Must include error feedback when TX fails

## Acceptance criteria 

- [ ] Apply standard treatment for all TXs based on the attached sketch
- [ ] Add any inline text for warning / info if required

## Additional details / background info

All sketches here: 

https://www.figma.com/design/ywcCZvXdvG28bg0AmCY9mF/Console-v3?node-id=6575-32612&t=ycbq8JgXVMbgAhpO-0
