### ISSUE TITLE
Explorer: Show asset source chain 

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#6223]
## The Chore

The asset by ID page does not show what chain an asset came from. See also [Icon support for multi chain](https://github.com/vegaprotocol/icons/issues/8)

```[tasklist]
### Tasks
- [x] Add source chain ID to asset query
- [x] Add row on asset by ID showing source chain ID
- [x] Make source chain ID link to the source chain explorer and contract
```

Originally poitned out by @jeremyletang

**Comment by edd** [comment]
```graphql
{
  assetsConnection {
    edges {
      node {
        id
        source {
          ... on ERC20 {
            chainId
          }
        }
      }
    }
  }
}
```

Works on testnet and below, but is not yet supported in mainnet. Rather than add in an environment switch, I'm going to wait for this version so be deployed.
