### ISSUE TITLE
Portfolio interim changes

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#6267]
## The Chore

Changes to the portfolio page to enable new deposit methods

## Tasks

- [x] Remove sidebar layout
- [x] Add a new tabbed pane with tabs for deposit, withdraw, transfer
- [x] Add deposit, withdraw and transfers components to the relevant tab
