### ISSUE TITLE
USD value on collateral tab

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6268]
## Story
Considering we will be adding spot markets, is is kind of default for exchanges to show "my assets" in descending order in terms of USD value, which will be more important adding spots since otherwise a token like SHIBA could be on top even though it is the lowest usd value.

![Screenshot 2024-04-20 at 14 23 48](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/f4b0cba9-da25-4bdc-b4d9-2b3b9d6dc1f7)
Example
![Screenshot 2024-04-20 at 14 27 45](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/e75302f1-4bc3-45ed-a772-e7c4621f79f6)

## Acceptance Criteria

- [ ] I can see usd value of assets in collateral
- [ ] I can sort by usd value 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
Cuurrently backlogged for reasons given in additional details
