### ISSUE TITLE
Explore calling the pyth price feeds to support currency conversions

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6273]
## The Chore

In theory the Pyth contract could provide us a reference price in USD for all assets on Vega which would then allow us to do all conversions to USD and solve various historic problems we have for this issue. 

## Tasks

- [ ] Set up a call to Pyth for every asset on: https://gnosischain-mainnet.rpc.grove.city/v1/59aab3a8
- [ ] Call the getPrice method on: https://gnosisscan.io/address/0x2880ab155794e7179c9ee2e38200202908c17b43#readProxyContract
- [ ] Cache all USD prices for all our current settlement assets

## Additional details / background info

Later we will come up with ways to use it.
