### ISSUE TITLE
Enable stop orders on spot markets

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6285]
## The Chore

Core are attempting to fix the stop orders on spot markets.

Once this is done we need to make sure they work.

## Tasks

- [x] Enable stop orders on spot markers
- [ ] Give the option to do post only 
- [x] Remove the option to do reduce only (as there is never a "position" to reduce)

**Comment by bglownia** [comment]
Post only are available only for limit orders that are **not** FoK and IoC. Stop orders can be only Fok or IoC. Post only is not possible with stop order.
