### ISSUE TITLE
Combine orders and stop orders into single table

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6289]
## The Chore

Currently we have the below in the panel at the bottom of the trading screen.

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/b455562a-b4e1-4ce0-a130-0c52ab7bea48)

This is good, and an improvement on where we were ... but what would be really nice is if we could condense the orders and advanced orders into a single table. 

## Tasks

- [ ] Work out how to do it
- [ ] Decide if its worth it
- [ ] Do it (or dont)

## Additional details / background info

It is something like this, but its not ideal.

The main issue is that when the stop order is triggered it will create an actual order off the back of it.  Therefore you end up seeing that order twice unless you start to do something very fudgy to pull some details of that created order into the initial view of the stop rather than displaying it.  Not sure how to link IDs so unsure how feasible that is, or desirable.

Also simply not sure how important this is given having a stop ordes / advanced orders tab is pretty standard on all exchanges I've seen. 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/2e17aeec-79bd-4411-a67c-084195ea2519)
