### ISSUE TITLE
Update Console to handle new realised PnL reward type

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6313]
## The Chore

Think this will only impact the rewards page

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/d33f1d0d-aba5-4f66-9c87-9d3e80f0b63b)

New reward type = DISPATCH_METRIC_REALISED_RETURN

## Tasks

- [ ] Add a new column for "Realised Returns"
- [ ] Add a new card type for this too ... use the same color as we use for relative return
- [ ] Change text to "Get rewards for realising a high profit in relation to your position size"
