### ISSUE TITLE
Add status icons to new markets page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6344]
## The Chore

What we need to achieve and who for

## Tasks

- [x] Select the appropriate size icons based on what looks best
- [x] Add an icon for each status (note that normal active trading doesnt have an icon)
- [ ] Note that as part of this we need to add the product pill to the new markets page as I have suddenly realised it is missing
- [x] Each status icons needs a tooltip on hover for each status
  - [x] Voting is in progress on this proposed market
  - [x] In opening auction, liquidity and crossed orders are required to set an opening price and start trading
  - [x] In protective auction due to large price movement, crossed orders are required to set price and restart trading
  - [x] Trading is suspended due to governance
  - [x] Market is permanently closed due to governance 
  - [x] Market is terminated and awaiting settlement data
  - [x] Market is settled and all positions are closed

### Market code component 

Need to add the status icon in here somewhere

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/59dffe37-648f-4f17-bcc5-3a239fafcc26)

### List of market status icons

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/e68b0d8b-44cc-4787-bb43-e147e0f527cd)
