### ISSUE TITLE
Add market status icons to explorer

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#6383]
https://github.com/vegaprotocol/frontend-monorepo/pull/6370#issue-2275589854 adds a new set of icons to describe teh current status of a market. They're handy! 

```[tasklist]
### Tasks
- [ ] Market List: Add market status icon
- [ ] Market Link: Add market status icon
- [ ] Market Details Page: ensure market status icon is shown
```
