### ISSUE TITLE
Further enhancements to market code / status icons

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6391]
## The Chore

Some tweaks to these 

## Tasks

- [x] In the market dropdown selector 
  - [x] Show the full code + product icon + status icon
  - [x] Remove the yellow status text
  - [x] Dont bother showing tooltip on the status icon hover
- [x] In the markets page 
  - [x] Add the product pill + status icon 
  - [x] Include the tooltip on status hover
- [ ] In the market header 
  - [ ] Show the same info and tooltips (push everything to the right to make room)
