### ISSUE TITLE
Improve error messaging on batch transactions

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6399]
## The Chore

Once Core deliver this: https://github.com/vegaprotocol/vega/issues/7245

We will have better errors on batches, so anywhere we use these we should improve the console error messaging. 

## Tasks

- [ ] Attached TP / SL should have better messaging depending on whether the main order / stop order failed
  - [ ] Your limit / market order and your stop order both failed
  - [ ] Your limit / market order went through but your stop order failed so you have no TP / SL on your orde
  - [ ] Your limit / market order failed but the stop went through so you might want to cancel that because its pointless
  - [ ] These all need to be replayed to the user via the toasts and the toast should be orange in each case
- [ ] Close position already has some good custom messaging but maybe this can be improved / cleaned up after the Core fix
