### ISSUE TITLE
Support for capped futures and binary options

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6418]
## Story

As a
I want
So that

### Capped Future

If there is a `FutureCap` object inside the `future` definition then you are dealing with a capped future
 - [x] Any market of this type should be treated as a different "capped future" product type and display a "FCAP" pill
   - [x] In the market dropdown 
   - [x] In the markets page
   - [x] In the market header
   - [x] In the fees page
 - [x] The `max_price` should be displayed in the market header as "Price cap", probably on the end next to "Index price"
 - [x] The market info should be updated 
   - [x] Change Instrument >> Product Type to "Capped Future"
   - [x] Add the `max_price` to this section as "Price cap" and add a tooltip stating "The maximum price that this capped future can be traded at, given in market decimals"
   - [x] Add the `fully_collateralised` flag to this section as "Fully collateralised"
- [ ] When on limit or stop limit orders if the user sets a price that is greater than the price cap show an error state and the text "Price cap for this market is XXX" and do not allow the order to be submitted
- [ ] The price cap should be shown on the trading canvas on both pennant an trading view as a horizontal line or maybe as a grey shaded area since price cannot go there (STRETCH)

### Binary Options

If `binary_settlement` = `true` then you have a binary option, and in this case `fully_collaterised` always = `true`.  These products allow people to bet on the outcome of a certain event and receive a set (or binary) payment of either zero if they lose or the `max_price` if they win.

 - [x] The `max_price` should be displayed in the market header under the title "Price Cap"
 - [x] The market info should be updated 
   - [x] Change Instrument >> Product Type to "Binary Option"
   - [x] Add the `max_price` to this section as "Price cap" and add a tooltip stating "The maximum price that this capped future can be traded at, given in market decimals"
   - [x] Add the `fully_collateralised` flag to this section as "Fully collateralised"
- [ ] When on limit or stop limit orders if the user sets a price that is greater than the price cap show an error state and the text "Price cap for this market is XXX" and do not allow the order to be submitted
- [ ] The price cap should be shown on the trading canvas on both pennant an trading view as a horizontal line or maybe as a grey shaded area since price cannot go there (STRETCH)

### Fully collateralised flag

This will be true sometimes for capped futures and always for binary options.  In both cases the treatment is the same.

- [x] Liquidation estimate on the deal ticket should be set to "n/a" 
- [x] Liquidation on the position table should be set to "n/a"
- [x] Cross / Isolated switcher needs to be disabled and replaced with a "Fully Collateralised" banner which cannot be changed

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

### Protos changes

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/43c1c371-0eda-4b49-9849-3819253c48be)

Spec link: https://github.com/vegaprotocol/specs/pull/2251

**Comment by JonRay15** [comment]
I have asked Research whether we still set margin mode on these ... since it doesnt make a huge amount of sense to have a margin mode on a fully collateralised product.

**Comment by JonRay15** [comment]
Moved non-delivered ACs to another ticket and closing
