### ISSUE TITLE
Refactor Emblem to take `size` instead of `width` and `height`

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#6444]
## The Chore

`Emblem` currently provides `width` and `height` properties. There are no instances where `width` and `height` have been different. It's also *slightly* weird that for a market icon you can provide `width` and `height`, but that is the `width`/`height` of each icon individually, rather than the containing element. `size` feels a little clearer

## Tasks

- [ ] Remove `width` and `height` prop from all Emblem components
- [ ] Add `size` prop
- [ ] Refactor all usages to provide `size` instead of `width`/`height`

**Comment by edd** [comment]
This was going to be closed in #6530 but that got merged early to get the other fix in
