### ISSUE TITLE
Remove trading dist build `--nx-skip-cache`

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#6469]
## The Chore

#6463 adds a build time `--nx-skip-cache` because nx-cloud was giving us an old, cached build. NX Cloud has broadly worked until this one case, which suggests there's a configuration error. #6463 also attempts to fix that configuration error, but we need to see if it works by inspecting the build logs for a while.

## Tasks

- [ ] On next release, check https://cloud.nx.app/ for the build outputs comparison
- [ ] Ensure that changes in `trading`s dependencies triggers a build
- [ ] Remove `--nx-skip-cache` in `publish-dist.yml`

## Additional details / background info
https://github.com/vegaprotocol/frontend-monorepo/compare/01f1c15ffe04045570dfa53d262ccd93aae5a1af...97f3fa2 is the start of this. That commit made a change in `libs/utils`. Running `yarn nx build trading --graph` will show that `trade` is indeed a dependency of `trading`, so a change in there should trigger a rebuild:

<img width="528" alt="Screenshot 2024-05-24 at 11 34 57" src="https://github.com/vegaprotocol/frontend-monorepo/assets/6678/7c992c67-f0b1-425b-b59f-5997a68a70b5">

But the IPFS hash of the build remained `QmSag2UVUpM8AQVVW8c36C7zoo4P9fYBsgPzrcDSRDevkw`. Stepping back, this means:

1. The correct dist publish pipeline was triggered when `release/mainnet` was merged in to
2. Tests worked fine (at least enough to get to the build step)
3. The github pipelines correctly determined it as a build requiring a docker image be pushed
4. The trading app was built and `nx export`ed 
5. The output was pushed in to a docker image

Step 5 is where the weirdness is. The step only takes 28 seconds, which is not how long a full build takes. That's what tipped me off that NX Cloud is back in action. NX cloud is a SAAS addon to `nx` that optimises builds by caching outputs and giving them back if there's a cache hit. How the cache is calculated is determined in our configuration:

https://github.com/vegaprotocol/frontend-monorepo/blob/d1f91ea877c11e2073a92504d110126e85f3cba5/nx.json#L97-L109

sets the defauls, effectively to 'every file in the project, but not tests/storybookfiles/etc'. This includes `.env` files, but not environment variables. Semi-importantly, `trading` shows the output of `'git rev-parse HEAD` in the sidebar. This is not included in the cache diff

- ✅ That's good because a cache can persist across commits, saving time on subsequent commits
- ❌ It's bad because fully cached outputs might be valid, but it can end up with an old git commit shown on otherwise ok builds

So the important fix that #6463 is trying is to explicitly add `trading:build:production` **inputs** as cache inputs on `trading:build` (`^production` in `project.json` means 'inputs to the `production`task). You'd think this was default, but I'm not entirely sure. Hence this essay.
