### ISSUE TITLE
Fix missing USDT icon in Squid widget

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#6509]
## Description

https://github.com/vegaprotocol/frontend-monorepo/blob/afbabc7dc5f66827ced6c7d7350f7d348eba813b/apps/trading/lib/hooks/use-squid-router-config.ts#L372-L376

This logic fails with Arbitrum USDT because... it hardcodes logos for arbitrum assets to be missing? But it's also a function that Emblem could export. 

```[tasklist]
### Tasks
- [x] Make Emblem export a URL builder
- [x] Refactor squid configuration to use new URL builder
- [x] Allow icons for arbitrum assets
```
