### ISSUE TITLE
Swap signposting

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#6520]
## The Chore

Add sign positing for swap UI

These tasks were taken out of https://github.com/vegaprotocol/frontend-monorepo/issues/6464 as the swap UI was not yet merged

## Tasks

- [ ] If the user has no balance of the required asset but they have some of an asset which can be swapped for the required asset using an existing spot market we should display an additional button showing "Swap for asset"
- [ ] If user clicks "Swap for asset" button it should open the simple swap UI in the sidebar and default the received asset appropriately to receive the asset needed for that market (doing this in the sidebar might require #6459 to be complete)
- [ ] Leave the pay asset blank and let the user set it manually

**Comment by JonRay15** [comment]
Look at with sidebar stuff once thats merged to Dev
