### ISSUE TITLE
Retire dev.* environments

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#654]
We have lots of builds happening for lots of different environments. Some of them don't see much use. In particular: environments that point to `devnet` which is (intentionally) relatively unstable.

# Tasks
- [x] Remove dev token site
- [x] Remove dev slimline console if it exists)
- [x] Remove dev trading 
- [x] Remove dev stats (if it exists)

# Exception
- Do not disable dev block explorer. Block explorers are always cool
