### ISSUE TITLE
Simple swap UI snags

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6542]
## The Chore

Random snags from Swap UI

## Tasks

- [ ] If the target market is in auction display the normal blue auction banner including all normal text beneath the Swap button 
- [ ] Ensure the filters on the dropdown only show assets in `STATE_ACTIVE` & `STATE_SUSPENDED` spot markets (currently seems to include cancelled)
- [ ] Once both assets are selected check for the market and if it doesnt exist display the yellow warning banner beneath the swap button saying "Cannot perform swap, no spot market available"
