### ISSUE TITLE
Remove toggle on cross-chain deposits

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6550]
## The Chore

This should just be available by default 

## Tasks

- [ ] Remvoe the toggle from settings ... show by default
- [ ] Remove the experimental feature section from settings completely since ther ewill be none
- [ ] Remove the banner from the cross chain widget warning users
