### ISSUE TITLE
Emblem minor refactor

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#6564]
## The Chore

Emblem's components props are base on HTMLImageAttribute, but most of those attributes are ignored, so the props are a little misleading. Prior to #6525, at least `width` and `height` were used. Now _they're_ ignored, lets just fix the misleading types

# Task
- [x] Remove base HTMLImageAttribute props
- [x] Accept `title`/`alt`/ other important props 
- [x] Ensure they are properly passed through
- [x] Transparent by default until icon has loaded (less jank for dark/light themes)
- [x] Enfore circles

**Comment by JonRay15** [comment]
Circles are now enforced in the work Madalina did ... but the rest needs Ed
