### ISSUE TITLE
Trading sidebar feedback

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6572]
## The Chore

A few things to add

## Tasks

- [ ] When you have clicked on say "Market info" and it expands that view, you should be able to click on "Market info" again to minimise it.  Doing this should just expand the "Trade" view again (which effectivly should be the default).
- [ ] Doesnt look like we've reformatted the market info to match the new styling, including removing the captilisation on the headers  .... see pictures in additional info
- [ ] We should be sorting asset balances so ones you have are at the top ... with no USD conversion we might have to do this with a conversion to quantum and a sort for now 
- [ ] The mini asset view is showing me the asset CODE but when i expand it I am shown the asset NAME ... as youc an see in pictures this made it pretty confusing whether that was actually the same asset.  Mini asset view should be showing just the code and the chain (which it is) ... expanded view probably needs to go across two lines so it can show me code, name, and chain in some combination 
- [ ] The numbers feel a bit big in the asset dropdown.  They're probably fine for the mini asset view ... but I think in the expanded one only the TOTAL should be that large ... the breakdown should be a size smaller. 
- [ ] Rename "Allocation" to "Deployed" and add a % in brackets after the number, ie.. 150 (24%)
- [ ] We're still showing assets with zero balance in the expanded asset view.  We should not do this.  
- [ ] Obviously if you're ON a market which settles in an asset you dont have the mini-asset view should still show this, and if you expand it to show the full breakdown it should still show it and in highlighted form so that users can deposit.

### Market info in sketch

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/467c48f0-9846-4886-a8f3-d728e37b7115)

### Market info on app

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/48978a00-8eff-4a35-bda8-f46e1242d383)

### Mini asset view 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/be14842d-5adb-4459-b626-b2186f426ddd)

### Expanded asset view 

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/42cc82e3-ac48-4eca-b046-04ba1b378346)

### Number size

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/94eaace6-13e9-4e06-b15d-b115885f6465)
