### ISSUE TITLE
Market orders that will put market in auction needs better explanation 

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/frontend-monorepo#6587]
## Story

As a user that puts market orders, there are occasions that makes it so the order will put the market in auction, the UI does nothing to warn you of the fact or what to do after you have made that kind of order and it failed, the error message given in explorer is not self explanatory "non-persistent order trades out of price bounds". 

## Acceptance Criteria

- [ ] UI help in terms of explaining market orders and auction
- [ ] Error message in explorer that is more easily understood 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Images

![Screenshot 2024-06-24 at 10 27 39](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/926436db-7a6b-4ab9-be6e-3cb83b07fb49)
![Screenshot 2024-06-24 at 10 27 29](https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/d18239ed-0f66-4399-ae77-9f5b94c6c050)
