### ISSUE TITLE
Bugs on FCAP trading screen

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6591]
## The Chore

What we need to achieve and who for

## Tasks

- [x] Add the "notional" vs "size" toggle option to the size input, this seems to have been missed
  - [x] If direction = LONG then `size = notional / price`
  - [x] If direction = SHORT then `size = notional / (priceCap - price)`
- [x] Default that toggle to "notional" when viewing an FCAP market
- [x] There is an error on the [previous ticket](https://github.com/vegaprotocol/frontend-monorepo/issues/6418) where we wanted to recognise a fully collaterialised binarary settlement product as a "binary option"... this is wrong:
  - [x] Check there is no product pill for Binary option 
  - [x] Check there is no code to set the product type in the market info to binary option in any circumstance
- [x] I cant verify if the `binarySettlement` or `fullyCollateralised` sections are working in the market info or simply dont appear unless they are `true` because the test markets have them as `false` ... but I think ANY time we have a `cap` section of the market payload we need to be showing all 3 fields with Yes / No 
- [x] We're not showing the margin type switcher at all, which is bad:
  - [x] If `fullyCollateralised` = YES then we should replace the switcher with a pill showing fully collateralised
  - [x] If `fullyCollateralised` = NO then we should just show the normal margin mode switcher
- [x] Check on "expected liquidation" 
  - [x] This should be n/a on a fully collateralised market
  - [x] Should behave as usual otherwise
- [x] Add "Potential return" to the data under the submit button where `potentialReturn` = `size` * `priceCap`

### Logic for generating potential return

```
Given some market that say ... Marco is playing Zverez in Wimbledon ... settles at 100 if Marco wins
- priceCap = 100
- currentPrice = 40

User would say "I want a bet of notional size $200 on Marco" 
- direction = LONG
- notional = $200
- size = notional / price  = $200 / 40 = 5 contracts that would be bought 
- potentialReturn = size * priceCap

User would say "I want a bet of notional size $200 on Zveler" 
- direction = SHORT
- notional = $200
- size =  notional / (priceCap - price) =  $200 / (100 - 40) = 200 /60 = 3.3333 contracts that would be bought .. I think?
- potentialReturn =  size * priceCap = 3.333 x 100 = $333.33 
```

### Original ticket 

- #6418 

### Cap payload

```
"cap": {
"maxPrice": "1000",
"binarySettlement": false,
"fullyCollateralised": false
}
```

###  Polymarket example

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/b81c64b8-f18e-42fe-8508-05dae407a24b)
