### ISSUE TITLE
Basic support for AMM txs

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#6627]
## Tasks

- [x] Show correct labels in TX list
  - [x] Cancel AMM
  - [x] Amend AMM
  - [x] Submit AMM
- [ ] Show TX Details
  - [x] Cancel AMM
    - [x] Method
    - [x] `MarketLink` for Market ID
  - [ ] Submit AMM
    - [ ] commitmentAmount
    - [x] `MarketLink` for Market ID
    - [ ] proposedFee
    - [ ] slippageTolerance
    - [ ] concentratedLiquidityParameters
      - [ ] base
      - [ ] leverageAtLowerBound
      - [ ] leverageAtUpperBound
      - [ ] lowerBound
      - [ ] upperBound
  - [ ] Amend AMM (as above)

**Comment by JonRay15** [comment]
It says "AMM" where it should say "Submit AMM" in the TX list. 

![image](https://github.com/user-attachments/assets/237ae216-f44d-4e64-bbc9-452ced9f7eda)

**Comment by JonRay15** [comment]
Amount looks fishy ... this should be using asset decimals (so this was actually 3k)

![image](https://github.com/user-attachments/assets/084daba3-f441-47ee-95f7-53ac3b182724)

**Comment by JonRay15** [comment]
Bumping back to IN PROG due to feedback above
