### ISSUE TITLE
Explore "Initial Margin mode" on FCAP

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6640]
## The Chore

In my view when people are betting they want to be saying "this is the bet I'm placing" not:

- I want to buy X contracts worth of this bet which i can see equates to Y margin and notional 
- I want to have a position of notional X which equates to size Y and margin Z 

We want to explore a mode whereby we would simply specify the outlay the user is about to make, ie. the Initial margin ... which when long is the same as the notional on a fully collateralised market, but when short it is not that simple. 

We may need Core changes to do this properly unfortunately ... but ticketing it here. 

## Tasks

- [ ] Replace "notional" mode on the on the size toggle with "Outlay" on FCAP products
- [ ] Set the toggle to outlay mode by default
- [ ] When in outlay mode:
  - [ ] LONG: `size` = `worstCaseOutlay` / `price` (with limit order)
  - [ ] SHORT: `size` = `worstCaseOutlay` / `priceCap - price` (with limit order)
- [ ] Change FCAP to CAPF (random addition to this ticket, not really related!)

## Additional details / background info

Thread with some info: https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1720097789068659?thread_ts=1720088638.526389&cid=CAHA5EX0F

**Comment by JonRay15** [comment]
This is now absorbed into #6642
