### ISSUE TITLE
TP / SL shoudl follow new label approach

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6654]
## The Chore

Still showing the label outside the box

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/350cd116-b65a-47ca-948d-40721a99f12b)

Same for icebergs

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/82a6f61f-2810-4add-8287-9a1fc90cdf2d)

## Tasks

- [ ] Adopt the same approach as with price / size
  - [ ] TP / SL to be shown in the same format as new price / size but show side by side as per sketch
  - [ ] Same approach for Icebergs

 NB. there was discussion over whether to use slightly smaller font to ensure it works on small screens.

## Additional details / background info

See Joelle sketch here: https://www.figma.com/design/ywcCZvXdvG28bg0AmCY9mF/Console-v3?node-id=6902-8315&t=sXSlXpv8PvBQqlGj-0

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/68f837b5-03f3-4204-aac3-2691f49b0cf7)

**Comment by JonRay15** [comment]
This all looks great now


![Image](https://github.com/user-attachments/assets/a53525e4-5c82-4b90-aa7c-647138e0b524)
