### ISSUE TITLE
Changes to summary reward card eligbility

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6669]
## The Chore

All these chanegs relate to reward summary cards, ie. where entityScope: entity_scope_individual.

## Tasks

- [ ] If individualScope:team then show "In team" with tick if you're in a team and cross if not....on hover show tooltip saying "Join a team to earn rewards" with a link to the Join Team page
- [ ] If individualScope:noTeam then show "Not in team" with tick if not in a team and cross if you are ... on hover show tooltip saying "You cannot be in a team to earn this reward"
- [ ] If individualScope:NULL then show "All individuals" with tick always and dont show a tooltip
