### ISSUE TITLE
Implement new onboarding flow

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6686]
## The Chore

What we need to achieve and who for

## Tasks

- [ ] Implement the new onboarding flow in the Figma to walk the user through Connect >> Deposit >> Apply code >> Join team .... must cover following scenarios which are outlined in the Figma:
  - [x] Onboarding with a referral code 
  - [x] Onboarding with a team code
  - [x] Onboarding with a referral code and a team code
  - [x] Onboarding with neither
- [x] We will need to store locally whether the user has arrived via a link containign a referral code or a team link or both,  and store those codes against the user so they can be prepopulated in various steps later 
- [ ] We will need to check the users connected wallet to work out where in the onboarding flow they should be dropped
  - [x] If they already have funds they can show "Deposit" step as complete
  - [x] If they already have a referral code applied they can show "Apply referral code" as complete
  - [x] If the already have a team they still can be shown to that page since they may elect to switch teams
- [ ] Should be able to trigger the onboarding page from three places:
  - [x] On the trading show a button in place of buy / sell / connect
  - [ ]  On the portfolio page show a button in place of connect
  - [x] On any other page show a banner offering the ability to trigger
- [ ] The button should be responsive to both the local storage (indicating if the user landed with referral or team codes) and the status of their connected key (indicating if they have funds, or are already part of a referral set or team) 
  - [ ] If a wallet is detected then:
    - [ ] If onboarding is complete (ie. you have deposited, are in a set, and a team) >> Just diplay Connect and follow normal flow
    - [ ] If onboarding is incomplete (ie. you dont have funds, or you have locally stored codes to apply) >> display "Continue onboarding" and send user to the onboarding flow in the relevant step
 - [ ] Both flows need some way for you to dismiss / discard any codes you have landed with since you may already be in a team / in a set and not want to swap and you dont want to be told forever by a banner.  Perhaps an option to "Dismiss" and a warning that says "This will discard your referral code / team link"?

## Additional details / background info

https://www.figma.com/design/Ibo9H9bCPmh4aSASm7qPCF/Reference-UI?node-id=9196-3491&node-type=CANVAS&t=9ToHrJLyw3xC6uOh-0
