### ISSUE TITLE
Live game stats snags

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6694]
## The Chore

Some feedback for minor imporvements

## Tasks

- [ ] When the epoch first starts you get a generic "no scores for this epoch" message. Instead look at the last update on the API, add the `rewards.updateFrequency` to that and count down to that time.
- [x] The sketches included showing the last update time when on live scores view ... can we add this based on the `time` on the API, and include a countdown to when the next update is by doing `time` + `rewards.updateFrequency` on the top right
- [x] Check that the live board works properly for games that do not pay out every epoch; ie. If the game pays out every 2 epochs then when the first epoch ends it should not reset the board since the live board is still relevant
- [x] Add the units to the live score in the column header, these vary based on the reward type 
  - [x] Price taking, price making, relative returns use the `dispatchMetricAssetId` 
  - [x] Average position is currently "Contracts"
  - [x] Returns volatility is technically `dispatchMetricAssetId squared` ... lol ... which we could show ... I guess ... or maybe show "VAR"  or "σ2" seems to be standard finance notation for variance.
  - [x] Staking, LP, market creation, and validator ranking just leave unitless 
- [x] We should include the explainer text from the card in the header somewhere, this should include some explanation of the units and the calculation of the metric.
- [x] I think the spacing on the header could be bigger ... feels a bit cramped and theres loads of room up there
- [x] I do think we need to add the third tab for "Payout structure" if it is a rank strategy game and show the table
- [x] Also remove the table tooltip from the initial card view
- [x] Showing the ranking strategy alongside the eligibility doesnt make sense ... Maybe we need to split this top box into two?  One for "Entry conditions" and one for "Game details"?  
  - [x] Game details would include
    - [x] Rank strategy 
    - [x] Fee cap if applicable
    - [x] The description of the game & the units if needed
    - [x] Next payout; This will need to account for the `transferInterval` on the transfers API, and will mean we need to know when the game last paid out, which can be found by looking at the historic scores on the `games` API to see when we last paid out.
  - [x] Change "Eligibility criiteria" to "Entry conditions" 

## Additional details / background info

![image](https://github.com/user-attachments/assets/296a9dac-61bb-4dd9-9c38-73aad4517150)

**Comment by JonRay15** [comment]
All deployed to mainnet
