### ISSUE TITLE
Display block time auctions

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6699]
## The Chore

There is now long block auctions in Core.  Auction triggers have been updated to include a status for this type of auction.

Console needs to be updated to show this type of auction.

## Tasks

- [x] Update the trading mode to display "Monitoring auction - block time" 
- [x] Update the tooltip for this code to say "This market is in auction due slow block processing, potentially due to an upgrade or network downtime." 
- [x] Update the banner to say "This market is in auction due to slow block processing, but you can still place orders. Time remaining: 1 minute 16 seconds (from 7/17/2024, 3:45:02 PM to 7/17/2024, 3:47:02 PM) [Find out more](https://docs.vega.xyz/testnet/concepts/trading-on-vega/trading-modes#auctions)

**Comment by candida-d** [comment]
> This market is in an auction due to slow block processing.

I can add more detail here but I think this tooltip is meant to be pretty short.

**Comment by JonRay15** [comment]
I have no way of triggering a block auction ... so I am just going to assume this works ... and hope to see it in action at random at some point
