### ISSUE TITLE
Fix IPFS / nx:affected workflow

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#672]
This currently isn't running. Nobody noticed because there's no way in Fleek to *disable* automatic builds, so it builds every time anyway. The net result is that the `deploy-ipfs` script is never used to actually limit our IPFS deploys to only when relevant sites are `nx:affected` - and the only downside of that is a total waste of build minutes. 

# Tasks
- [x] Ask Fleek if there's a way to disable auto deploys
- [ ] When there is, disable auto deploys
- [ ] Fix `ipfs` workflow to run on merges to master, not just pushes
- [ ] Watch the build minute usage reduce (on Fleek)
- [ ] Watch the build minute usage increase (on Github) 

n.b: in case it isn't clear, sites are deploying fine. Just too often. Currently this is only `status`, but #667 will add trading, which will throw more Fleek build minutes in the bin. No milestone yet as everything works, if wastefully.

**Comment by gordsport** [comment]
Hey @pennyandrews 
Please can you provide a little more info on whats required by core/ops and i'll try help unblock

**Comment by edd** [comment]
Sorry I didn't get back to this one. It turns out what I wanted is not possible and won't be supported. The other IPFS tickets cover what we need. I'll close this.
