### ISSUE TITLE
Deal ticket snags

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6720]
## The Chore

Various minor snags on review of the new deal ticket changes.

## Tasks

- [x] Add a tooltip to "TIF" saying "Set the time in force (TIF) of the order"
- [x] Probably that tooltip needs to either explain the TIFs available for that order type (see Hyperliquid example below) or should direct to the docs.
- [x] Do somethiing about tooltip behaviour as they can be hard to get rid of. 
  - [x] Position them off to the side so they don't cover the ticket options
- [x] The clickable area for the post only etc checkboxes is pretty wild ... it extends across the entire row I think
- [x] I dont think the size input is setting the slider ... is that intentional? In my example it is set to 500 which should be about 10%
- [x] The price and size fields on the seconf part of the limit OCO are in the wrong order, they shoud match the top one
- [x] There is no size slider on the bottom part of the OCO on either stop limit or stop market
- [x] The fees & notional are not appearing on stop limit or stop market either in normal or OCO mode.

### Weird TIF text

![image](https://github.com/user-attachments/assets/f11bd14c-ddda-4163-8d2c-e3532732a25c)

### Hyperliquid TIF

![image](https://github.com/user-attachments/assets/23845478-d948-49f5-ae70-2873459d5ca7)

### Slider behaviour

![image](https://github.com/user-attachments/assets/ffbf6449-e9b8-4a80-a40a-49ce9d440201)

### OCO fields

![image](https://github.com/user-attachments/assets/30031e7c-4397-421e-846b-49aba734eb5e)

### Stop fees etc

![image](https://github.com/user-attachments/assets/9dc63917-51a1-4369-914f-639d78e44cb4)

**Comment by JonRay15** [comment]
This is now ALL WORKING
