### ISSUE TITLE
Update average position reward to reflect new Core implementation

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6730]
## The Chore

There is a Core ticket currently scheduled for Suzuka Castle which will change the average position reward type so that instead of simplyl counting number of contracts it will multiply by price first to get the notional.  This is to address the issue that currently if a reward is across multiple markets it would regard a 10000 PEPE position as larger than a 1 BTC position which is clearly wrong. 

https://github.com/vegaprotocol/vega/issues/11459

## Tasks

- [ ] Change the reward details page to use dispatchMetricAssetId as the unit
- [ ] Change the name on the reward card to Average Notional
- [ ] Change the description of the reward to reflect this extra logic
- [ ] Other?
