### ISSUE TITLE
Implement updated Console app map

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6758]
## The Chore

What we need to achieve and who for

## Tasks

- [x] Top level nav should include only
  - [x] Home (via the main icon in the top left - this will be the new landing page which is TBC, put a holding page here for now)
  - [x] Trade - takes you to last traded market, or if new to highest volume (which I think it does now)
  - [ ] Portfolio
  - [x] Pools (the AMM screen ... from here all other parts of AMM can launch)
  - [x] Competitions
  - [ ] More
- [x] Where More includes
  - [x] Markets
  - [x] Fees
  - [ ] Rewards
  - [x] Referrals
  - [x] Governance (external link)
  - [x] Docs (external link)

**Comment by JonRay15** [comment]
All working as expected
