### ISSUE TITLE
Highlight active rewards and games on trading page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6759]
## The Chore

The current active rewards and competitions should be highlighted on the trading screen

## Tasks

- [x] Show a banner showing active rewards and games
- [x] This banner will just be configurable text, no need to look them up from the APIs
- [x] It should be possible to configure multiple messages and there should be a scroll arrow to go to next
- [x] There should be a cross to dismiss the banner
- [x] If dismissed it should disappear and a icon should appear in the main header which when click reopens the banner section

### Sketch

![image](https://github.com/user-attachments/assets/9dd11ea8-e4e6-4064-b416-0be95a787467)

### Figma link

https://www.figma.com/design/Ibo9H9bCPmh4aSASm7qPCF/Reference-UI?node-id=7146-17852&node-type=CANVAS&t=RBBmsyRCs0WNQqLY-0

**Comment by JonRay15** [comment]
There's a snag on this but its ticketed so closing
