### ISSUE TITLE
Lottery distribution strategy

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6760]
## The Chore

What we need to achieve and who for

## Tasks

- [ ] ~Add a column to the reward history table for lottery game type~
- [x] Add a icon to handle lottery type of distribution strategy to be dis[layed where teh pro rata / ranked icon currently is
- [x] Make sure rewards cards and detail page can handle it
- [x] Make sure the game cards and detail page can handle it

**Comment by JonRay15** [comment]
https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1723625912598189?thread_ts=1723401996.974479&cid=CAHA5EX0F

**Comment by JonRay15** [comment]
To make this more consistent with reward cards and to clean up soem leftover UX snags from previous game details work I think we should:

- Remove the distribution strategy text from underneath the asset on the game card
- Put it in the top right as at icon & text to align to reward summary cards
- Add a "Locked for" to the "Game Details" panel so it would say "X epochs", lock period feels like a secondary detail that lives here
- Also amend "Next payout at" to be "Next payout in" and do `payout epoch - current epoch` so instead of showing "82" which is pretty confusing we can also show "X epochs"
- That way its consistent .... "i'm paid in 3 epochs, and its locked for 7 epochs after that"
- Fix the "scored in" bug where I seem to be seeing a blank on a relative return reward

![image](https://github.com/user-attachments/assets/f9129c4b-a258-411f-91c4-f3b075f8ea93)
![image](https://github.com/user-attachments/assets/44b74db1-2191-4ed5-b9a1-9b947d80947f)

**Comment by JonRay15** [comment]
This looks great though
![image](https://github.com/user-attachments/assets/13a68586-385d-4370-bd82-2cf85f58f457)

And so does this 

![image](https://github.com/user-attachments/assets/5ccd3113-0312-4741-b7ea-93fd1c528c52)
