### ISSUE TITLE
Improve navigation to markets from games

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6763]
## The Chore

From the game details page, make it easier to get from the game to the markets you can trade on to participate.

## Tasks

- [x] If you are eligible have a button saying "Trade to play" which when pressed brings up a dropdown of any in scope markets which you can click to trade on ... or a modal that pulls up a set of market cards
- [x] If you are not eligible
  - [x] If you're not in a team have a button for "Sign up" which opens the modal for Create Team / Lone Wolf / Join Team options 
  - [x] If you're in a team but dont have requried VEGA have a button for "Stake Vega" which takes you to Governance site OR ideally could run the TX directly from here
  - [x] If you're in a team, have the VEGA, but need a higher notional show "trade to play" as above

## Additional details / background info

ALL screens above have been created in Figma below

![image](https://github.com/user-attachments/assets/0155abc2-9e7a-40f4-99d2-35b4c0a58b79)

### Figma

https://www.figma.com/design/ywcCZvXdvG28bg0AmCY9mF/Console-v3?node-id=7259-27034&t=3fmNOuPbIo0I3rfz-0
