### ISSUE TITLE
Tweaks to Solo play / lone wolf

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6790]
## The Chore

Want to remove the team related terminology from Solo play

## Tasks

  - [x] Change the options for signup to the three in the sketch in that order
  - [x] When you hit play as individual
    - [x] On the create team screen change "create solo team" to "Create my profile"
    - [x] Instead of Team Name display "Trading alias"
    - [x] Replace "Provide a link so users can learn more about your team" with "Provide a link so users can learn more about you"
    - [x] When you submit the TX ensure it is setting a whitelist with only your key on it

## Additional details / background info

![Image](https://github.com/user-attachments/assets/f3285b92-2968-4c3b-8a0c-94d1463c124a)

**Comment by JonRay15** [comment]
Feedback

- When you already have a referral set and you look to upgrade to a team you get some helpful text 
  - "Note that your existing referees will not be automatically added to your team. Share your team profile to have them join you in competitions. You will still earn commission from their trading even if they do not join."
  - This text doesnt make sense when signing up to play as an individual so dont show it on that screen, on the regular create team it is fine

Other than that this all works well.  Re-opening just for that tiny bit which is petty ... but shrug emoji
