### ISSUE TITLE
Embedded wallet tech debt

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6808]
## The Chore

Random tech debt from the first iteration of the embedded wallet

## Tasks

- [ ] Make the wallet pop up automatically on TX
- [ ] Remove hardcoding of data nodes
- [ ] Solving PoW in thread, may cause delays in browser, and certainly will on mobile
- [ ] Events arent propagated
- [ ] Maybe some other stuff
