### ISSUE TITLE
Update Governance app to handle absence of a vesting contract

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6809]
## The Chore

Since not all governance tokens will have a vesting contract the governance app needs to be able to handle a network that does not have a vesting contract.  Currently we think the entire app falls over without one. 

## Tasks

- [ ] Ensure that the app treats a vestign contract as optional and doesnt fall over
- [ ] That means the ["Supply & Vesting"](https://governance.vega.xyz/token/tranches) page will need to be hidden if no contract is available
- [ ] The wallet sidebar will need to be OK without showing vesting balances / tranches
- [ ] Other?
