### ISSUE TITLE
Show the "From asset" on the deposit form even when in single chain mode

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6843]
## The Chore

When the deposit form detects that we cant use squid (which happens either when squid is down or we are in testnet)....

## Tasks

- [x] Ensure the "from asset" is shown but set it to stay in sync with to To asset that the user sets and disable it
- [x] Ensure that it shows your balance of that asset
- [x] If you hover the select box show a tooltip saying "Swaps currently not supported"

**Comment by JonRay15** [comment]
From asset is being synced with my TO asset as expected, and I am showing the amount available on my key. 

![Image](https://github.com/user-attachments/assets/099bdaec-006a-48f5-9286-048d0a6d1a91)

closing
