### ISSUE TITLE
Show AMM positions in Console

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6854]
## The Chore

Positions table in Console should show any AMM commitments you have open. 

![image](https://github.com/user-attachments/assets/fc1313d4-c06c-4623-ad79-e0e37dcbbfeb)

Currently it does not.

## Tasks

- [ ] When querying the WS for [positions](https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-observe-positions)
  - [ ] Set "include derived parties" to TRUE
  - [ ] Display the positions for those derived parties in the position table
  - [ ] Include some pill to indicate they are AMM in place of the cross / isolated pill

## Additional details / background info

![image](https://github.com/user-attachments/assets/393524ff-a218-4a81-8d28-734ce0590b6a)
