### ISSUE TITLE
Link sharing modal

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6858]
## The Chore

Need the ability to share links easily.

## Tasks

- [ ] Implement the "share" modal shown in the Figma
  - [ ] If the user has a referral code include it
  - [ ] If they do not offer the ability to create one, and in this case trigger the `createReferralCode` TX from the modal
  - [ ] If the user has a team include a tick box offering to include the team
- [ ] The link generated needs to include 
  - [ ] The referral code if present
  - [ ] The team code if included
  - [ ] Both if both included
  - [ ] Neither if neither is available
- [ ] Include a button to dismiss the modal
- [ ] Should be possible to trigger the modal from:
  - [ ] A market, from a "Share" button in the header
  - [ ] The team page, from a "Share" button under the team name
  - [ ] The referral page, from a "Share" button that replaces the share link button on the code tile
  - [ ] From the key selector, from a "Invite friends" option above "Disconnect"
- [ ] The links should still include as a root the URL from the page in which it was generated so the user will land:
  - [ ] Market >> on the market 
  - [ ] Team page >> on the team
  - [ ] Referral page >> Send them to the homepage
  - [ ] If from the selector >> Send them to the homepage

**Comment by JonRay15** [comment]
Feedback 

- Ideally we'd trigger the referral code IN the modal rather than send you off to that page
- I think we probably want to get rid of the "Create Team" option on the referral page now that we have tried to make these feel like seperate steps
- Referral set created = e06b06afebbe86add0fac950df5025fc4dfa762c7fedbe142db19cc5f9092c1c
- Link generated = https://trade.neb.exchange/#/invite?code=e06b06afebbe86add0fac950df5025fc4dfa762c7fedbe142db19cc5f9092c1c
