### ISSUE TITLE
Import temp wallet to Console

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6863]
## The Chore

What we need to achieve and who for

## Tasks

- [x] Ability to use a seed phrase to import a wallet into embedded wallet in Console
- [x] Wallet will only be for current session and will be lost once you disconnect
- [ ] Add ability to export the phrase again at the end for ease of copying

**Comment by JonRay15** [comment]
I am not seeing where I'm meant to be able to do this.  This is the options currently.  So I'm actually seeing embedded TWICE.

Surely we need an option for "import wallet"?

![image](https://github.com/user-attachments/assets/51dac238-c373-4a76-aee5-c91c9c2d40a1)

**Comment by JonRay15** [comment]
Once you import a wallet you dont get the rest of the options you should normally get from an embedded wallet.

![image](https://github.com/user-attachments/assets/fb24fb90-f9d0-480c-9445-66e99a3dbc7b)

Why is this important?  Well because without that I cant open my wallet in order to add more keys, which users doing this will want to do because they - like me - probably are importing a long existing wallet which might have many of them. 

Also without this mode we cannot satisfy the 3rd AC above to be able to easily export my keys again.

**Comment by JonRay15** [comment]
This is still no good ... 

Still no sign of the "Open Wallet" button so I cant do anything useful.

![Image](https://github.com/user-attachments/assets/ba9309cb-6417-4276-9b06-2661292d4838)

This is on FG commit hash 391cf7348ff253e9b6988de7c7da252787b3d1eb

**Comment by JonRay15** [comment]
This now works!
