### ISSUE TITLE
Non-priority embedded wallet snags

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6874]
## The Chore

Follow up work deprioritised from first batch.

## Tasks

- [x] Modals are full screen and not contained to the wallet, which is weird.
- [x] TX queue not behaving
- [x] Possible perf issues in mobile
- [x] No path to persistence of the wallet
- [x] We don't remember if you had a wallet before. This could cause mild heart attacks for less techy users; "why do I need to do this again?", "are my funds lost?" Can we store a map of keys you've connected with before so we can show a slightly more customised message?
