### ISSUE TITLE
For future & perp metadata being used incorrectly

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6896]
## The Chore

What we need to achieve and who for

## Tasks

- [x] Price is currently using SETTLEMENT ASSET and it should be using QUOTE from the metadata
- [x] Size has two potential modes:
  - [ ] Size is fine ... it is using BASE
  - [x] ~Notional it is not right ... it should be using QUOTE again but its using SETTLEMENT~

## Final ACs

On Deal ticket
- [ ] Size unit = "Contracts"
- [ ] Notional unit = Settlement asset

On trade table
- [ ] Price = quote in metadata
- [ ] Notional = Settlement asset

**Comment by JonRay15** [comment]
Think the trade table needs updating too.

Price and notional are still showing settlement asset when I THINK these should be quote?

![Image](https://github.com/user-attachments/assets/820237b9-5ec9-45b3-8305-04649bde78d7)

Fees I assume is fine to stay in settlement as that is what you're actually charged in.

**Comment by barnabee** [comment]
> Size is fine ... it is using BASE
> Notional it is not right ... it should be using QUOTE again but its using SETTLEMENT

I believe this is incorrect and notional is always in terms of the settlement asset.

As I understand the use case triggering this for protocol users is protocol users trying to create a market for, say an FX pair, that settles in a third asset that is neither the base or quote of the pair. For example: a market for CHF/EUR (i.e. Swiss Franc price in Euros) settled in USDT.

The key thing here is that a market like this _is not an FX futures market_ but is more like a CFD. In this case position size is basically how many units of the settlement asset someone risks when the price/quote of the underlying changes by 1.

For example, if I have CHF/EUR settled in USDT then:

* The price is the current number of Euros per Swiss France (e.g. 1.06…) this is in units of "Euros"
* My position size is how many **USDT** I gain/lose each time that price changes by 1 **_not_** how many Swiss Francs (or how many Euros) my position represents
* Therefore my position size is in USDT (technically USDT per unit move in the price of the underlying)
* And my notional is **also** in USDT, because if I have a position of size 1 on CHFEUR entered at a price of 1.06 Euros then I stand to lose 1.06 USDT if it goes to zero

So IMO both notional and size should always be in settlement asset in this case but one is the notional value of the position and the other is the amount of settlement asset risked per unit change in the price of the underlying. 

This means that for this kind of CFD like product on a currency pair, the "base" and "quote" assets _of the currency pair_ don't drive the field labels. It might be sensible to enabled some additional metadata to deal with this, though it can probably be fudged with what's their now if that needs to be a longer term thing.

**Comment by JonRay15** [comment]
Agreed with Barney: For now lets just do:

Size unit = Contracts

(and we will set up some metadata rules later for an info popover here)

Notional unit = Settlement asset

Which means I correct my trade table comments earlier to say 

- Price = QUOTE asset
- Notional = Settlement asset

**Comment by JonRay15** [comment]
Latest screen from Art 

![image](https://github.com/user-attachments/assets/e1f0a926-e2aa-40ee-a13a-93c3d53c7914)

**Comment by JonRay15** [comment]
This looks good
