### ISSUE TITLE
Control network when signing message on "connect with ethereum" mode

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6908]
## The Chore

There are two issues with this mode right now:

1. When we are upgrading the build it is changing the message we're signing (in the latest case "Vega Onboarding" changed to "Onboarding") and this is meaning we generate different keys .... losing any funds the user had deposited previously.
2. The signature is being signed on whichever chain id you happen to be connected to on MM at that time which means that you get a different key if you happen to be on another network at the time

## Tasks

- [x] Ensure the signature is completely deterministic at all times by triggering WAGMI to set it to ethereum mainnet before signing the transaction
- [x] When generating the message we want the format "`chainName` Onboarding" ... this might mean adding a chain name to whatever config file you've been using so we can store a user friendly chain name against the chain ID (or maybe this already exists)
- [x] Once we've made that change NEVER CHANGED THIS AGAIN unless there's very good reason
- [x] In addition to this I suggest we actually add back in the export key option in settings because this would protect early users from something happening if they had that key saved

### Example of AVAX sign

![image](https://github.com/user-attachments/assets/017bd472-54b7-4ac2-9a51-3647249d62da)

**Comment by JonRay15** [comment]
Network switcher kicked in properly 

![image](https://github.com/user-attachments/assets/f3ddba6d-d661-4f65-b624-8e26b0dacc4c)

Onboarding message was updated.

Connection successful.

**Comment by JonRay15** [comment]
Export recovery phrase doesnt work.

![image](https://github.com/user-attachments/assets/60e1bd23-5ede-4e64-8f7b-faae25b95779)

Bumping back to IN PROG for Dex tomorrow morning.

**Comment by JonRay15** [comment]
There is still an open bug on export recovery but its on a diff ticket now ... this works so closing.
