### ISSUE TITLE
Remove create team from the referral page

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6929]
## The Chore

The option to create a team here seems unecssary and complex now that we have worked so hard to make these flows feel as seperate as we can.

![image](https://github.com/user-attachments/assets/7eebaaea-7b8a-4b5e-9016-a3f7d2da5e62)

## Tasks

- [x] Remove the create team button from here
- [x] Ensure that when we send the `createReferralSet` TX we are always setting `isTeam` to no
- [ ] Remove the banner that appears here when you are part of a referral set that is also a team (keep all the referral set stats ... just remove teh top wide panel  since we show that on competitions anyway)

## Additional details / background info

![Image](https://github.com/user-attachments/assets/541ddc18-79d2-4dcd-97dd-ce35db76d4af)
