### ISSUE TITLE
New reward banner impacting status banners

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6945]
## The Chore

The new reward banner in #6891 is now sharing real estate with the original status banner. 

![image](https://github.com/user-attachments/assets/2fcc5329-d923-4230-8e52-f77fe0ea2614)

Here we have a long block auction in the same slot.  If you exit it you cannot get it back without clicking the reward icon which is weird.

I'm also not certain we want status banners swept into the reward scroller cos there could be pretty important info there like a market settling imminently or something. 

## Options

- [ ] Placement
  - [ ] Put all banners back to the top so we dont have to cope with shifting stuff up and down
  - [ ] Have all banners in the new location but chart & order book needs to shift up when dismissed
  - [ ] Have seperate components for the alert banner at the top and the reward banner in the new location
- [ ] How to deal with dismissing / returning them ALL
  - [ ] Dont store the dismiss in local storage so the banner component always comes back
  - [ ] Do store it in local storage but need that icon in the market header to show you have hidden banners .... this could be a reward for rewards but then we also need something for info banners 
  - [ ] If we choose to seperate the components the this coudl be a diff solution for each .... I would say then we fix the reward icon so a click brings them back, but for normal alerts they just always come back on refresh

## Tasks

- [ ]
- [ ]
