### ISSUE TITLE
Add a "undefined game" card

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6962]
## The Chore

The new game cards rely on config being defined to drive them.

I believe we need a fallback card in the event there is a game live on the API that does not have a matching config

## Tasks

- [ ] Build list of expected cards based on transfers API same as today
- [ ] Check for config for each ID and display configured card
- [ ] If there is no config available display a default card where 
  - [ ] Title = "Undefined Game"
  - [ ] Image = Some warning symbol, or the most generic of the stock designs
  - [ ] Description = "Game details to TBD"
