### ISSUE TITLE
Remove onboarding logic from deal ticket

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6966]
## The Chore

TLDR; lets not upset the deal ticket with this onboarding stuff ... its too invasive.  Lets keep the onboarding handled via the banner since then its easier to bypass / dismiss - particularly while we're working thtough bugs.

## Tasks

- [ ] The order button shows GET STARTED until you have more than $10 ... dont do this 
  - [ ] If you have ZERO balance show DEPOSIT
  - [ ] Clicking this button should just launch the in-sidebar deposit form for the asset on that market
  - [ ] The DEPOSIT buttons arent picking up local styling properly currently
