### ISSUE TITLE
Team link onboarding snags

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#6977]
## Summary

Snags found when sharing team links etc 

### Team link ONLY 

I cannot see a way to simply share a team link without sharing a referral code.  We need this since some people might not have or want a referral code OR might be sharing a different team to their code.  I think the obvious place for this is the team profile page where we actually used to have a link to this page but now the share button there generates a referral link.

- [ ] In the team page change the share link modal so it is in reverse, ie. 
  - [ ] Team code
  - [ ] Share link
  - [ ] Also include my referral code (or create one if I dont have one)
- [ ] Once this is done we need to retest the flow where you have a team link that is not a referral code

### Team link & referral link

In this case the first part of the flow should behave exactly like the referral only flow above.  Then you progress to the team part.  If they are properly seperated in this way it shouldnt matter whether we have link where referral and team code are the same or different since they are different operations.

- [ ] I literally cannot get past the referral code part here, if I go to referrals I can see the code got applied AND that I am part of the team. so again we want:
  - [ ] To NOT join the team yet at this point
  - [ ] To be automatically directed forward to the team joining phase which I guess woudl be the team profile page from which I can join

## Tasks

- [ ]
- [ ]
