### ISSUE TITLE
Change the asset activity column order to make it easier to complete withdrawals

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#7000]
## The Chore

There are lots of ppl witdrawing right now ... lets make it simpler and more obvious.

![image](https://github.com/user-attachments/assets/015a22a8-fec7-4ac9-bf90-246644171223)

Also this toast seems to fail if you click "COMPLETE WITHDRAWAL"

![image](https://github.com/user-attachments/assets/ea8b2a9a-685d-4187-b37a-4c5446d7095c)

## Tasks

- [x] Change the column order to be as shown
- [x] The button tp complete withdrawal needs to be clearer
  - [x] It says "Connect" when your metamask is locked ... it doesnt need to ,.... just show "Complete" at **all** times and if you need to connect your MM as part of that then handle that in the WAGMI flow
  - [x] It should be blue so its super obvious
  - [ ] Put the VIEW button behind a kebab menu to get it out of the way
- [x] Simplify the toast so it just sends you to Portolio
- [x] Do more to highlight pending withdrawals ... the current pin / line is too sublte ... maybe highlght the whole row in grey?
