### ISSUE TITLE
Console lite - market list - noticed issues

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/frontend-monorepo#708]
## Task
A few things are still to improve in console lite market list

## ACs
- [x] Active whole row of grid not only a trade button
- [x] Improve the market name renderer - time of expire
- [x] adjust mobile view
- [x] adjust grid view sorting icon
- [x] check the sense of moving the solution to the libs/market-list library
- [x] add pagination (if already given in api)
- [x] adjust data update (`update` and `insert` functions)
- [x] filter linking to trade view by market state
- [x] add row's focus management - tab navigation and enter as trade trigger
