### ISSUE TITLE
Console lite - market list - connect pagination

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/frontend-monorepo#778]
## Task
Although `marketsConnection` query is already exposed,  `makeDataProvider` is still struggling with `totalCount` case, etc. So it's much better wait for final implementation of both data provider and backend endpoint

## ACs
- [ ] connect with marketsConnection query
- [ ] Resolve sorting problem (client or server side ?)
- [ ] Resolve reseting price change from the cell
