### ISSUE TITLE
Paginate rewards lists

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#794]
## User Story

As a Governance dapp user
I want to see a paginated list of all rewards (by epoch)
So that I can browse rewards information without the page taking forever to load / falling over due to the volume of data

## Acceptance Criteria

- I can view the most recent n epoch's rewards and use a common pagination UI pattern to click to view the next n epoch's rewards, and the next
- I understand what number page of data I am currently viewing
- I understand when there is more proposals to view, and when there isn't 

## Tasks

- [ ] Define/design the interaction patterns (utilising common patterns where possible) including consideration of edge cases i.e. navigating 10s-100s pages etc.
- [ ] Implement (utilising existing libraries if at all possible)
- [ ] QA Test (including adherence to design, verify a/c are met and no bugs/defects/regressions have been introduced) 
- [ ] Release

## Design

The designs cover a pagination approach that we can't achieve with the current API so we will implement what is possible and lean on the styles and request anything additional needed from Joëlle

https://www.figma.com/file/X9l0t8TZUF1tU8u0ILV3ws/Governance-%26-Token?node-id=1994%3A10843&t=LkK12CecOUM8x97C-4

Exploration from [the Miro board](https://miro.com/app/board/uXjVPUTU6m4=/?moveToWidget=3458764546161680708&cot=14) (including suggestion of a field + submit button to jump to a specific epoch in bottom left):
![image](https://user-images.githubusercontent.com/1080322/219110519-12bb564e-6384-47a1-ac8b-68d96462ffe1.png)

**Comment by dexturr** [comment]
Realted to #802

**Comment by pennyandrews** [comment]
Might need some additional design for the edge cases i.e. handling loads of pages etc. @joellecharlotte

**Comment by pennyandrews** [comment]
For speed we made a call on the standup today to not make round buttons for the pagination but instead use the square with rounded corners that we have already in the UI toolkit. Sorry @joellecharlotte

**Comment by notbot00** [comment]
blocked by: 
- https://github.com/vegaprotocol/vega/issues/7871 (https://github.com/vegaprotocol/vega/pull/7872)

**Comment by pennyandrews** [comment]
#7872 is part of core version 70.1 which is now deployed to testnet so this ticket should be unblocked now

**Comment by notbot00** [comment]
I'm trying to understand what we're trying to do here exactly, but i have a feeling this is not possible to do with the current state of things.

Here's why.

In both of "total" and "earned by me" reward tabs we query for three things: epoch, available asset types, and the earned rewards. As a result, the frontend received three lists (epochs, assets and rewards). To be able to represent the rewards as we do now (categorised under a certain epoch, and summed up per asset), we do a lot of the heavy lifting on the frontend in terms of parsing all the data we get back from core, and index rewards by epoch, and sum items per asset type. 
We'd be able to request paginated data for the rewards list, but there'd be no guarantee for what that data would look like. For example, we could request for the last 15 rewards, which all are under the same epoch, and they are the same asset, which would result in displaying one epoch table with one row of assets. Imagine the second page we'd request would have 15 rewards all belonging to different epochs. There's no consistent way of displaying the categorised and summed up rewards data we display, because this type of data doesn't exist as such on core. 

In order to be able to move forward with this, we could:

1. task core to create a new data type we could query for with pagination - either something like an assetReward type with the summed rewards for each assets per epoch (this would require the frontend to query epochs before, and send off a)
2. implement new designs, which are representing the data we can actually paginate, which are rewards in one table (not per epoch, and not summed up per asset), with displaying which epoch they belong to and what asset they are representing as e.g. columns
3. leave it as it is, and set a hard limit of how much data we're displaying on the rewards page so we don't break things

**Comment by barnabee** [comment]
4. Governance site team a database/service that takes the raw data node data and serves up the thing you want.

Not every front end page is going to have a perfect data node API. Maybe in this case it can do, but there is definitely another option that can be considered.
