### ISSUE TITLE
Add gas estimate to dapps when about to submit a transaction 

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#798]
## Story

~~As a~~ when I'm about to use a dapp to create an ethereum transaction (or a test that will lead to one, like prepare withdrawal)...
I want to get a sense of the current cost of gas
So that I can decide if it is something I want to do now or later

Note: this story is less pressing now that 
a) gas prices are less high because the network is less busy
b) EIP-1559 is in place (and many wallets support it) therefore there is lower chance of gas price spikes / failed transactions

see https://ethereum.org/en/developers/docs/gas/ for more info

## Acceptance Criteria

- [ ] **must** can see how much in gas the transaction is likely to cost (with some assumptions, see below) in GWEI
- [ ] **should** see how much in gas the transaction is likely to cost (with some assumptions, see below) in ETH
- [ ] **should** see how much in gas the transaction is likely to cost (with some assumptions, see below) in USD
- [ ] **could** I can see the units of gas required to run the transaction in GWEI

### Assumptions

either use the assumptions used by the API we choose to use or,

use the web3 api or,

use
```
tip = 1 GWEI
Base cost: get current `Base fee` from ETH 
gas cost in units of gas
```
i.e. we keep the top as 1 GWEi as this is common in wallets, and do not attempt to adjust for speed

## Tasks

- [x] explore https://docs.ethers.io/v5/api/providers/provider/#Provider-estimateGas and https://ethereum.stackexchange.com/questions/100209/estimate-gas-price-with-ethers-js
- [ ] Explore and sketch where we think this should go
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Sketch

Easy option put it in the confirm in wallet dialogue

competent that goes with the button that submits a transaction

component that can go with button (or anywhere else)

## Additional details / background info

So @candida-d and I were considering adding the gas price to the token front end.

It's a fairly small piece of work from our side, just where do we put it 🤔

Related: https://ethereum.stackexchange.com/questions/60863/estimate-gas-price-not-gas-using-web3

![image](https://user-images.githubusercontent.com/83510148/179513524-5101bc44-0c49-45cd-8d91-64b9955ce089.png)

![image](https://user-images.githubusercontent.com/83510148/179513565-ccfd40ac-98c9-48e9-b39c-672d9ed8e643.png)

Withdrawals are one of the more expensive transactions.

> looking at the ERC20bridge... the withdrawals are using approximately 450k to 500k units of gas, so one could estimate the cost of a withdrawal by doing 500000 x gas_price x eth_usd

https://ethereum.stackexchange.com/questions/27452/how-to-estimate-gas-cost includes options for using truffle and web3
