### ISSUE TITLE
Move away from deprecated APIs and implement resulting changes

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#802]
## Chore 

Some of the APIs on token site are now deprecated which we need to move away from. 

* Stake -> stakeSummary
* Nodes -> paginated API
* Delegations -> Paginated API
* RewardDetails -> Paginated API
* Accounts -> paginated API

**For accounts - quick win is show the top 10 assets then a link to see all that takes you to the party page.**

The impact of these changes should remove / improve summing logic and enable us to handle paginated delegations. (Anything else?)

## Acceptance criteria 

- [ ] We've replaced the list of APIs above with the new API(s) 
- [ ] There is now a way to handle paginated delegations (thanks to the new paginated API) and we've verified it works
- [ ] anything else? E.g. remove / improve summing logic, UI controls for delegations

## Background 

Some of the APIs on token site are now deprecated which we need to move away from. 

Originally from - https://github.com/vegaprotocol/token-frontend/issues/1071

@mattrussell36 could you link to ticket on Data node that adds pagination/filtering to the delegations query

this ticket to implement changes as a result.

 remove/improve summing logic (given API change)
 UI controls for delegations (if/when they exist)
cursor based pagination:

- https://github.com/vegaprotocol/data-node/issues/563

**Comment by ckpringle** [comment]
@dexturr to refine plz (what's the count of deprecated APIs)

**Comment by dexturr** [comment]
@ckpringle There are a total of 5 deprecated APIs used, in 10 queries that need to be fixed 

   * Stake -> stakeSummary
    * Nodes -> paginated API
    * Delegations -> Paginated API
    * rewardDetails -> Paginated API
    * Accounts -> paginated API

**Comment by dexturr** [comment]
Remember to delete old types from the old type generation method
