### ISSUE TITLE
Portfolio: Update Fills tab

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#845]
### Tasks
- [x] Verifying dp formatting outlined in below comment
- [x] Rename 'value' column to 'price'
- [x] Rename 'Filled value' column to 'Notional'. Also check the maths here (when using fractional sizes) it seems to be incorrect
- [x] Add tooltip  (AG Grid) with fee breakdown for makerFee, infrastructureFee and liquidityFee

**Comment by campbellssource** [comment]
Notes about the decimal places on the fills table:
- Size (first number) `Market.positionDecimalPlaces`
- Size (second number) this is the notional value of the fill (size * price) so can have as many decimal places as an asset `asset.decimals`
- Price `Market.decimalPlaces`
- Realised PnL will be the same as Realised PnL (where some was realised, i.e the filled reduced my exposure. `Market.decimalPlaces`
- Fee this can be as many decimal places as an asset so `asset.decimals`
Note [this ticket](https://github.com/vegaprotocol/frontend-monorepo/issues/859) is to check all numbers use the correct decimal places. There will be a separate ticket to potential truncate some decimals.
