### ISSUE TITLE
Fixes and tweaks for order margin calculation

### ISSUE THREAD

**Issue by macqbat** [vegaprotocol/frontend-monorepo#890]
## Task
Fix spotted issues, add possible improvements to the process of calculating initial order margin in console-lite

## ACs

- [x] Fix casting BigNumber balance to bool by use method `isZero` instead in `useMarketPositions`
- [x] Remove some typos and console.logs
- [x] Consider get rid off a call to estimateOrder since it calculates only order's size & price & market risk factor, and it's roughly possible to do it on only market data
