### ISSUE TITLE
[token] New Asset proposals should require validationTimestamp to be specified

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#980]
Background: https://github.com/vegaprotocol/vega/issues/5818

It's not currently enforced by the wallet or the node, but alongside `enactmentTimestamp` and `validationTimestamp`, a `NewAsset` proposal should require a `validationTimestamp`.

# Tasks
- [x] Require a `validationTimestamp` is set on New Asset proposals
- [x] No other proposals type needs a `validationTimestamp`
- [ ] Bonus points/followup: `validationTimestamp` should be a unix timestamp that is in the future and lower than `closingTimestamp`.
